In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
## 1. Setup Paths & Configuration

import sys
import os
from pathlib import Path

# Add source directory to path
current_path = Path.cwd()
base_project_dir = current_path.parent
src_dir = base_project_dir / "src"

if str(src_dir) not in sys.path:
    sys.path.append(str(src_dir))

# Define key directories
dataset_directory = src_dir / "abstractionsshapecoder" / "dataset"
saved_directory = src_dir / "abstractionsshapecoder" / "saved"

# --- AE Model Paths ---
saved_models_L1_AE_dir = saved_directory / "models_L1_AE"
saved_models_L2_AE_dir = saved_directory / "models_L2_AE"
saved_models_L1_AE_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_AE_dir.mkdir(parents=True, exist_ok=True)

# --- PCA Model Paths ---
saved_models_L1_PCA_dir = saved_directory / "models_L1_PCA"
saved_models_L2_PCA_dir = saved_directory / "models_L2_PCA"
saved_models_L1_PCA_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_PCA_dir.mkdir(parents=True, exist_ok=True)

print(f"Base project directory: {base_project_dir}")
print(f"Source directory: {src_dir}")
print(f"L1 AE Models directory: {saved_models_L1_AE_dir}")
print(f"L2 AE Models directory: {saved_models_L2_AE_dir}")
print(f"L1 PCA Models directory: {saved_models_L1_PCA_dir}")
print(f"L2 PCA Models directory: {saved_models_L2_PCA_dir}")

Base project directory: c:\Users\Amogh\abstraction-discovery
Source directory: c:\Users\Amogh\abstraction-discovery\src
L1 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_AE
L2 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_AE
L1 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_PCA
L2 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_PCA

In [3]:
import pickle
from pathlib import Path
from abstractionsshapecoder.debug_utils import debug_info, debug_success, debug_error

def load_processed_datasets():
    """
    Loads all hierarchical datasets (L0, L1-VAE, L1-AE, L2-AE) from the saved directory.
    """
    SAVED_DIR = Path.cwd().parent / "src" / "abstractionsshapecoder" / "saved"
    
    # Define file map: {Variable_Name: Filename}
    dataset_files = {
        "shapes_l0": "all_dsl_shapes.pkl",
        "shapes_l1_vae": "all_abstracted_shapes_L1_VAE.pkl",
        "shapes_l1_ae": "all_abstracted_shapes_L1_AE.pkl",
        "shapes_l2_ae": "all_abstracted_shapes_L2_AE.pkl"
    }
    
    loaded_datasets = {}
    
    for var_name, filename in dataset_files.items():
        file_path = SAVED_DIR / filename
        if file_path.exists():
            debug_info(f"Loading {var_name} from {filename}...")
            with open(file_path, "rb") as f:
                loaded_datasets[var_name] = pickle.load(f)
            debug_success(f"Successfully loaded {len(loaded_datasets[var_name])} shapes into {var_name}.")
        else:
            debug_error(f"Missing file: {filename}. Ensure previous training cells were run.")
            loaded_datasets[var_name] = {}
            
    return loaded_datasets

# Execute the load
datasets = load_processed_datasets()

# Extract into global namespace for easier access in subsequent cells
shapes_l0 = datasets.get("shapes_l0")

[INFO] Loading shapes_l0 from all_dsl_shapes.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l0.
[INFO] Loading shapes_l1_vae from all_abstracted_shapes_L1_VAE.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l1_vae.
[ERROR] Missing file: all_abstracted_shapes_L1_AE.pkl. Ensure previous training cells were run.
[ERROR] Missing file: all_abstracted_shapes_L2_AE.pkl. Ensure previous training cells were run.

In [4]:
shapes_l0["172_0_0"]

{'dsl': <abstractionsshapecoder.dsl_nodes.Union at 0x1082b270e30>,
 'singleton_params': {'Cuboid': [[0.68, 0.09, 0.66],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.68, 0.14, 0.24],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08]],
  'Translate': [[-0.0, -0.17, 0.0],
   [-0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [0.31, -0.51, 0.3],
   [-0.26, 0.27, -0.18],
   [-0.14, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.0, 0.27, -0.25],
   [0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25]]},
 'pair_params': {'Translate(Cuboid)': [[-0.0, -0.17, 0.0, 0.68, 0.09, 0.66],
   [-0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [-0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [-0.26, 0.27, -0.18, 0.08, 0.79, 0.08],
   [-0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.0, 0.74, -0.22, 0.68, 0.14, 0.24],
   [-0.0, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.28, 0.27, -0.25, 0.08, 0.79, 0.08]],
  'Union(Translate)': [[0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25],
   [-0.0, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.14, 0.27, -0.25],
   [-0.26, 0.27, -0.18],
   [0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [-0.31, -0.51, -0.17],
   [-0.0, -0.17, 0.0]]},
 'program_text': 'Union(Move(Cuboid(0.68,0.09,0.66),-0.0,-0.17,0.0),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,0.3),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,0.3),Union(Move(Cuboid(0.08,0.79,0.08),-0.26,0.27,-0.18),Union(Move(Cuboid(0.08,0.79,0.08),-0.14,0.27,-0.25),Union(Move(Cuboid(0.68,0.14,0.24),0.0,0.74,-0.22),Union(Move(Cuboid(0.08,0.79,0.08),-0.0,0.27,-0.25),Union(Move(Cuboid(0.08,0.79,0.08),0.14,0.27,-0.25),Move(Cuboid(0.08,0.79,0.08),0.28,0.27,-0.25)))))))))))'}

In [5]:
from abstractionsshapecoder.dsl_utils import collect_singleton_and_pair_data
from abstractionsshapecoder.debug_utils import debug_info, debug_success

# 1. Isolate the DSL objects from the dictionary
all_l0_dsl_trees = [data['dsl'] for data in shapes_l0.values()]

debug_info(f"Extracting parameters from {len(all_l0_dsl_trees)} L0 shapes...")

# 2. Run the collection utility
# s_data_l0: { 'NodeName': [ [params], [params], ... ] }
# p_data_l0: { 'Parent(Child)': [ [params], [params], ... ] }
s_data_l0, p_data_l0 = collect_singleton_and_pair_data(all_l0_dsl_trees)

debug_success(f"Extraction complete.")
debug_info(f"Unique Singletons found: {len(s_data_l0)}")
debug_info(f"Unique Parent-Child Pairs found: {len(p_data_l0)}")

[INFO] Extracting parameters from 1100 L0 shapes...
[SUCCESS] Extraction complete.
[INFO] Unique Singletons found: 3
[INFO] Unique Parent-Child Pairs found: 5

In [6]:
import pandas as pd

# Create a summary for Singletons
singleton_summary = []
for node_type, param_list in s_data_l0.items():
    singleton_summary.append({
        "Node Type": node_type,
        "Total Occurrences": len(param_list),
        "Param Dimension": len(param_list[0]) if param_list else 0,
        "Example Params": param_list[0] if param_list else []
    })

# Create a summary for Pairs
pair_summary = []
for pair_name, param_list in p_data_l0.items():
    pair_summary.append({
        "Relationship": pair_name,
        "Total Occurrences": len(param_list),
        "Combined Dimension": len(param_list[0]) if param_list else 0
    })

# Convert to DataFrames for easy viewing
df_singletons = pd.DataFrame(singleton_summary).sort_values("Total Occurrences", ascending=False)
df_pairs = pd.DataFrame(pair_summary).sort_values("Total Occurrences", ascending=False)

print("=== L0 SINGLETON CENSUS ===")
display(df_singletons)

print("\n=== L0 PAIR CENSUS ===")
display(df_pairs)

=== L0 SINGLETON CENSUS ===

,Node Type,Total Occurrences,Param Dimension,Example Params
0,Cuboid,10268,3,"[0.68, 0.09, 0.66]"
2,Translate,10268,3,"[-0.0, -0.17, 0.0]"
1,Rotate,3416,4,"[-0.17410813759359595, 0.0, 0.0, 0.98472653890..."

=== L0 PAIR CENSUS ===

        Relationship  Total Occurrences  Combined Dimension
2  Translate(Cuboid)              10268                   6
4   Union(Translate)               8656                   3
0     Rotate(Rotate)               1804                   8
1  Rotate(Translate)               1612                   7
3      Union(Rotate)               1612                   4

In [7]:
import torch

class FloatOperation:
    def __init__(self, func, unary: bool = False):
        self.func = func
        self.unary = unary

LANGUAGE = {
    "binary_ops": {
        "Add": FloatOperation(lambda a, b: a + b),
        "Sub": FloatOperation(lambda a, b: a - b),
        "Mul": FloatOperation(lambda a, b: a * b),
    },
    "unary_ops": {"Neg": FloatOperation(lambda a: -a, unary=True)}
}

def log_best_match(method_name, target_name, expr, diff, tol, min_match):
    """Utility to print how close the best candidate came to success."""
    mean_err = diff.mean().item()
    match_frac = (diff < tol).float().mean().item()
    status = "[SUCCESS]" if match_frac >= min_match else "[FAILED ]"
    
    print(f"    {status} {method_name:10} | Target: {target_name:4} | Best: {expr:20} | "
          f"AvgErr: {mean_err:.4f} | Match: {match_frac*100:5.1f}% (Req: {min_match*100}%)")

def compare_with_tolerance(predicted, target, max_error, min_fraction):
    if not isinstance(predicted, torch.Tensor):
        predicted = torch.tensor(predicted, device=target.device, dtype=target.dtype)
    if predicted.dim() == 0: 
        predicted = predicted.expand_as(target)
    
    diff = torch.abs(predicted - target)
    success = (diff < max_error).float().mean().item() >= min_fraction
    return success, diff

def search_direct_variable(inp, target_name):
    best_diff, best_name = None, None
    for name, values in inp["variables"].items():
        success, diff = compare_with_tolerance(values, inp["target"], inp["tol"], inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success:
            log_best_match("Direct", target_name, name, diff, inp["tol"], inp["min_match"])
            return name
            
    if best_name:
        log_best_match("Direct", target_name, best_name, best_diff, inp["tol"], inp["min_match"])
    return None

def search_constants(inp, target_name):
    best_diff, best_name = None, None
    for name, val in inp["simple_consts"].items():
        # Constants usually use 0.05 tol as per your original code
        success, diff = compare_with_tolerance(val, inp["target"], 0.05, inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success:
            log_best_match("Const", target_name, name, diff, 0.05, inp["min_match"])
            return name
            
    if best_name:
        log_best_match("Const", target_name, best_name, best_diff, 0.05, inp["min_match"])
    return None

def search_binary_operations(inp, target_name):
    var_keys = list(inp["variables"].keys())
    const_keys = list(inp["extended_consts"].keys())
    all_keys = var_keys + const_keys
    
    value_stack = torch.stack(list(inp["variables"].values()) + 
                             [c.expand(len(inp["target"])) for c in inp["extended_consts"].values()])
    
    index_pairs = torch.cartesian_prod(torch.arange(len(inp["variables"])), torch.arange(len(all_keys)))
    
    global_best_fraction = -1.0
    global_best_expr = ""
    global_best_diff = None

    for op_name, op in LANGUAGE["binary_ops"].items():
        results = op.func(value_stack[index_pairs[:, 0]], value_stack[index_pairs[:, 1]])
        diffs = torch.abs(results - inp["target"].unsqueeze(0))
        fractions = (diffs < inp["tol"]).float().mean(dim=1)
        
        # Find best in this specific operation
        best_val, best_idx = torch.max(fractions, dim=0)
        idx = best_idx.item()
        expr = f"{op_name}({all_keys[index_pairs[idx][0]]}, {all_keys[index_pairs[idx][1]]})"
        
        if best_val.item() > global_best_fraction:
            global_best_fraction = best_val.item()
            global_best_expr = expr
            global_best_diff = diffs[idx]

        if best_val.item() >= inp["min_match"]:
            log_best_match("Binary", target_name, expr, diffs[idx], inp["tol"], inp["min_match"])
            return expr

    if global_best_expr:
        log_best_match("Binary", target_name, global_best_expr, global_best_diff, inp["tol"], inp["min_match"])
    return None

def discover_symbolic_rules(df, custom_tol=0.08, custom_min_match=0.85, custom_constants=None):
    rules = {}
    const_dict = {str(round(c, 2)): torch.tensor(c, dtype=torch.float32) for c in (custom_constants or [0.5, 1.0])}

    for target_col in df.columns:
        print(f"--- Searching for target: {target_col} ---")
        input_cols = [p for p in df.columns if p != target_col]
        target_tensor = torch.tensor(df[target_col].values, dtype=torch.float32)
        
        search_space = {
            "target": target_tensor,
            "variables": {inp: torch.tensor(df[inp].values, dtype=torch.float32) for inp in input_cols},
            "simple_consts": const_dict, "extended_consts": const_dict,
            "tol": custom_tol, "min_match": custom_min_match
        }

        found_for_col = False
        for search_fn, name in [(search_direct_variable, "Direct"), 
                                (search_constants, "Const"), 
                                (search_binary_operations, "Binary")]:
            found = search_fn(search_space, target_col)
            if found:
                rules[target_col] = found
                found_for_col = True
                break
        
        if not found_for_col:
            print(f"    [FAILED ] No rule discovered for {target_col}")
            
    return rules

In [8]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY
# ==========================================
raw_cuboids = s_data_l0.get("Cuboid", [])
df_l0 = pd.DataFrame(raw_cuboids, columns=['sw', 'sh', 'sd'])

# Group cuboids into 4 functional types (e.g., Legs, Seats, Backs, Joints)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0['cluster'] = kmeans.fit_predict(df_l0)

cluster_grammars = {}
s_data_l1 = {"Cuboid": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0[df_l0['cluster'] == c_id].drop(columns=['cluster'])
    
    # Auto-harvest potential constants (modes) for this specific cluster
    modes = [float(stats.mode(np.round(subset[col].values, 2), keepdims=True)[0][0]) for col in subset.columns]
    
    # Discover Symbolic Rules (Symmetry or Constants)
    # Using your optimized thresholds: 5% tolerance and 40% minimum match
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=list(set(modes + [0.0, 1.0])), 
        custom_tol=0.05, 
        custom_min_match=0.40
    )
    cluster_grammars[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (COMPRESSION TO L1)
# ==========================================
for _, row in df_l0.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars[c_id]
    
    # Compress: Keep only dimensions that ARE NOT explained by a rule
    latent = [row[v] for v in ['sw', 'sh', 'sd'] if v not in rules]
    
    # Fallback: preserve at least one dimension to keep the instance unique
    if not latent: 
        latent = [row['sw']] 
    
    s_data_l1["Cuboid"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (DECOMPRESSION TO L0)
# ==========================================
reconstructed_rows = []

for node in s_data_l1["Cuboid"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars[c_id]
    
    # Identify which variables are "Free" (Latent)
    latent_vars = [v for v in ['sw', 'sh', 'sd'] if v not in rules]
    if not latent_vars: 
        latent_vars = ['sw']
    
    # Map latent values back to their variable names
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    # Apply rules to fill in the missing/fixed dimensions
    for target, expr in rules.items():
        if expr in recon: 
            # Alias/Symmetry rule (e.g., sd = sw)
            recon[target] = recon[expr]
        else: 
            # Constant rule (e.g., sh = 0.05)
            try:
                recon[target] = float(expr)
            except ValueError:
                recon[target] = 0.05 # Default safety fallback
                
    reconstructed_rows.append([recon.get('sw', 0), recon.get('sh', 0), recon.get('sd', 0)])

# ==========================================
# 4. FINAL PERFORMANCE METRICS
# ==========================================
df_recon = pd.DataFrame(reconstructed_rows, columns=['sw_r', 'sh_r', 'sd_r'])

# Parameter Savings
total_l0_params = len(df_l0) * 3
total_l1_params = sum(len(node["l"]) for node in s_data_l1["Cuboid"])
reduction = (1 - total_l1_params / total_l0_params) * 100

# Error Metric
mse = ((df_l0[['sw', 'sh', 'sd']].values - df_recon.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_params}")
print(f"L1 Parameters: {total_l1_params}")
print(f"Compression:   {reduction:.2f}%")
print(f"Reconstruction MSE: {mse:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: sw ---
    [SUCCESS] Direct     | Target: sw   | Best: sd                   | AvgErr: 0.0378 | Match:  83.9% (Req: 40.0%)
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sd                   | AvgErr: 0.5196 | Match:   0.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.6                  | AvgErr: 0.1200 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Add(sw, 0.6)         | AvgErr: 0.1425 | Match:  19.1% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [SUCCESS] Direct     | Target: sd   | Best: sw                   | AvgErr: 0.0378 | Match:  83.9% (Req: 40.0%)
0        | {'sw': 'sd', 'sd': 'sw'}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sd                   | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sw   | Best: 0.74                 | AvgErr: 0.2384 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: sw   | Best: Add(sd, 0.0)         | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] No rule discovered for sw
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.5935 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.09                 | AvgErr: 0.1886 | Match:  36.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Mul(sd, 0.09)        | AvgErr: 0.1945 | Match:  30.7% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sw                   | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sd   | Best: 0.86                 | AvgErr: 0.1619 | Match:  21.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: sd   | Best: Add(sw, 0.0)         | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] No rule discovered for sd
1        | {}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sh                   | AvgErr: 0.3320 | Match:  13.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sw   | Best: 0.88                 | AvgErr: 0.1651 | Match:  19.5% (Req: 40.0%)
    [FAILED ] Binary     | Target: sw   | Best: Mul(sh, 0.88)        | AvgErr: 0.3433 | Match:  14.8% (Req: 40.0%)
    [FAILED ] No rule discovered for sw
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.3320 | Match:  13.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.77                 | AvgErr: 0.2378 | Match:  17.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Add(sw, 0.11)        | AvgErr: 0.3737 | Match:  13.9% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sh                   | AvgErr: 0.5019 | Match:   8.1% (Req: 40.0%)
    [FAILED ] Const      | Target: sd   | Best: 0.11                 | AvgErr: 0.1196 | Match:  37.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: sd   | Best: Mul(sw, 0.11)        | AvgErr: 0.1259 | Match:  35.0% (Req: 40.0%)
    [FAILED ] No rule discovered for sd
2        | {}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sh                   | AvgErr: 0.2047 | Match:  39.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: sw   | Best: 0.06                 | AvgErr: 0.1847 | Match:  47.4% (Req: 40.0%)
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.2047 | Match:  39.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: sh   | Best: 0.06                 | AvgErr: 0.0750 | Match:  61.8% (Req: 40.0%)
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sh                   | AvgErr: 0.2324 | Match:  26.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: sd   | Best: 0.06                 | AvgErr: 0.2327 | Match:  46.4% (Req: 40.0%)
3        | {'sw': '0.06', 'sh': '0.06', 'sd': '0.06'}
-----------------------------------------------------------------
L0 Parameters: 30804
L1 Parameters: 16568
Compression:   46.21%
Reconstruction MSE: 0.020697

In [9]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY (TRANSLATE)
# ==========================================
raw_translates = s_data_l0.get("Translate", [])
# Translation nodes use tx, ty, tz (X, Y, Z coordinates)
df_l0_t = pd.DataFrame(raw_translates, columns=['tx', 'ty', 'tz'])

# Cluster positions (helps group parts like "Left Legs" vs "Right Legs")
kmeans_t = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0_t['cluster'] = kmeans_t.fit_predict(df_l0_t)

cluster_grammars_t = {}
s_data_l1_t = {"Translate": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0_t[df_l0_t['cluster'] == c_id].drop(columns=['cluster'])
    
    # --- ENHANCED CONSTANT HARVESTING ---
    # We take top 5 frequent positions (tx, ty, or tz) to catch standard offsets
    dynamic_consts = [0.0] # 0 is a critical constant for center-alignment
    for col in subset.columns:
        top_vals = subset[col].round(2).value_counts().head(5).index.tolist()
        dynamic_consts.extend(top_vals)
    dynamic_consts = list(set([x for x in dynamic_consts if not np.isnan(x)]))
    
    # Discover Rules with slightly relaxed tolerance (0.06) to catch near-misses
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=dynamic_consts, 
        custom_tol=0.06, 
        custom_min_match=0.40
    )
    cluster_grammars_t[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (L0 -> L1)
# ==========================================
for _, row in df_l0_t.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars_t[c_id]
    
    # Compress: tx, ty, tz are only latent if they aren't ruled
    latent = [row[v] for v in ['tx', 'ty', 'tz'] if v not in rules]
    
    if not latent: 
        latent = [row['ty']] # Default to vertical position if everything else is fixed
    
    s_data_l1_t["Translate"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (L1 -> L0)
# ==========================================
reconstructed_t = []

for node in s_data_l1_t["Translate"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars_t[c_id]
    
    latent_vars = [v for v in ['tx', 'ty', 'tz'] if v not in rules]
    if not latent_vars: latent_vars = ['ty']
    
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    for target, expr in rules.items():
        if expr in recon: # Alias/Symmetry (e.g. tz = tx)
            recon[target] = recon[expr]
        else: # Constant (e.g. ty = 0.45)
            try:
                recon[target] = float(expr)
            except:
                recon[target] = 0.0
                
    reconstructed_t.append([recon.get('tx', 0), recon.get('ty', 0), recon.get('tz', 0)])

# ==========================================
# 4. METRICS
# ==========================================
df_recon_t = pd.DataFrame(reconstructed_t, columns=['tx_r', 'ty_r', 'tz_r'])

total_l0_t = len(df_l0_t) * 3
total_l1_t = sum(len(node["l"]) for node in s_data_l1_t["Translate"])
reduction_t = (1 - total_l1_t / total_l0_t) * 100
mse_t = ((df_l0_t[['tx', 'ty', 'tz']].values - df_recon_t.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_t}")
print(f"L1 Parameters: {total_l1_t}")
print(f"Compression:   {reduction_t:.2f}%")
print(f"Reconstruction MSE: {mse_t:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.3347 | Match:   8.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: tx   | Best: 0.0                  | AvgErr: 0.1396 | Match:  51.8% (Req: 40.0%)
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tx                   | AvgErr: 0.3775 | Match:   8.0% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: 0.3                  | AvgErr: 0.1419 | Match:  32.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Sub(tx, -0.36)       | AvgErr: 0.2296 | Match:  20.1% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: tx                   | AvgErr: 0.3347 | Match:   8.6% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: -0.27                | AvgErr: 0.1031 | Match:  31.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Add(tx, -0.32)       | AvgErr: 0.1913 | Match:  29.0% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
0        | {'tx': '0.0'}
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: ty                   | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: tx   | Best: -0.4                 | AvgErr: 0.0878 | Match:  33.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tx   | Best: Add(tz, -0.57)       | AvgErr: 0.1799 | Match:  22.8% (Req: 40.0%)
    [FAILED ] No rule discovered for tx
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tx                   | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: -0.44                | AvgErr: 0.2091 | Match:  16.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Add(tx, 0.0)         | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: ty                   | AvgErr: 0.6268 | Match:   7.9% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: 0.34                 | AvgErr: 0.1428 | Match:  27.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Mul(ty, -0.57)       | AvgErr: 0.1599 | Match:  29.2% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
1        | {}
--- Searching for target: tx ---
    [SUCCESS] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.1422 | Match:  45.5% (Req: 40.0%)
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tz                   | AvgErr: 0.4461 | Match:   9.3% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: -0.17                | AvgErr: 0.2001 | Match:  16.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Add(tz, -0.16)       | AvgErr: 0.3384 | Match:  20.1% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [SUCCESS] Direct     | Target: tz   | Best: tx                   | AvgErr: 0.1422 | Match:  45.5% (Req: 40.0%)
2        | {'tx': 'tz', 'tz': 'tx'}
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] Const      | Target: tx   | Best: 0.0                  | AvgErr: 0.2996 | Match:  14.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tx   | Best: Add(tz, 0.0)         | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] No rule discovered for tx
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tz                   | AvgErr: 0.2181 | Match:  14.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: ty   | Best: -0.5                 | AvgErr: 0.0885 | Match:  40.5% (Req: 40.0%)
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: ty                   | AvgErr: 0.2181 | Match:  14.1% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: -0.31                | AvgErr: 0.1005 | Match:  32.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Add(tx, 0.0)         | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
3        | {'ty': '-0.5'}
-----------------------------------------------------------------
L0 Parameters: 30804
L1 Parameters: 19002
Compression:   38.31%
Reconstruction MSE: 0.023101

In [10]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY (ROTATE)
# ==========================================
raw_rotates = s_data_l0.get("Rotate", [])
# Assuming Rotate has 4 parameters: qx, qy, qz, qw
df_l0_r = pd.DataFrame(raw_rotates, columns=['qx', 'qy', 'qz', 'qw'])

# Cluster rotations (groups parts with similar orientations)
kmeans_r = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0_r['cluster'] = kmeans_r.fit_predict(df_l0_r)

cluster_grammars_r = {}
s_data_l1_r = {"Rotate": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0_r[df_l0_r['cluster'] == c_id].drop(columns=['cluster'])
    
    # --- ROTATION SPECIFIC CONSTANTS ---
    # Common rotation values: 0, 1, 0.707 (45/90 deg in quaternions), -1
    dynamic_consts = [0.0, 1.0, -1.0, 0.707, -0.707] 
    for col in subset.columns:
        top_vals = subset[col].round(3).value_counts().head(5).index.tolist()
        dynamic_consts.extend(top_vals)
    dynamic_consts = list(set([x for x in dynamic_consts if not np.isnan(x)]))
    
    # Discover Rules
    # Using 0.06 tol to account for floating point precision in rotations
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=dynamic_consts, 
        custom_tol=0.06, 
        custom_min_match=0.40
    )
    cluster_grammars_r[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (L0 -> L1)
# ==========================================
for _, row in df_l0_r.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars_r[c_id]
    
    # Compress: keep only the components that aren't fixed or aliased
    latent = [row[v] for v in ['qx', 'qy', 'qz', 'qw'] if v not in rules]
    
    # Fallback: if it's a perfect constant rotation, keep qw to represent the instance
    if not latent: 
        latent = [row['qw']] 
    
    s_data_l1_r["Rotate"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (L1 -> L0)
# ==========================================
reconstructed_r = []

for node in s_data_l1_r["Rotate"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars_r[c_id]
    
    latent_vars = [v for v in ['qx', 'qy', 'qz', 'qw'] if v not in rules]
    if not latent_vars: latent_vars = ['qw']
    
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    for target, expr in rules.items():
        if expr in recon:
            recon[target] = recon[expr]
        else:
            try:
                recon[target] = float(expr)
            except:
                # Default for Quaternions is usually (0,0,0,1)
                recon[target] = 1.0 if target == 'qw' else 0.0
                
    reconstructed_r.append([recon.get('qx', 0), recon.get('qy', 0), recon.get('qz', 0), recon.get('qw', 1)])

# ==========================================
# 4. METRICS
# ==========================================
df_recon_r = pd.DataFrame(reconstructed_r, columns=['qx_r', 'qy_r', 'qz_r', 'qw_r'])

total_l0_r = len(df_l0_r) * 4
total_l1_r = sum(len(node["l"]) for node in s_data_l1_r["Rotate"])
reduction_r = (1 - total_l1_r / total_l0_r) * 100
mse_r = ((df_l0_r[['qx', 'qy', 'qz', 'qw']].values - df_recon_r.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_r}")
print(f"L1 Parameters: {total_l1_r}")
print(f"Compression:   {reduction_r:.2f}%")
print(f"Reconstruction MSE: {mse_r:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: qx ---
    [SUCCESS] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.0160 | Match:  94.2% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qx                   | AvgErr: 0.0160 | Match:  94.2% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qx                   | AvgErr: 0.0253 | Match:  88.3% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qx                   | AvgErr: 0.9958 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0034 | Match:  99.6% (Req: 40.0%)
0        | {'qx': 'qy', 'qy': 'qx', 'qz': 'qx', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.0995 | Match:  19.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: -0.09                | AvgErr: 0.0302 | Match:  83.9% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qy                   | AvgErr: 0.9944 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0033 | Match: 100.0% (Req: 40.0%)
1        | {'qx': '-0.09', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.1876 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: 0.14                 | AvgErr: 0.0651 | Match:  64.3% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qx                   | AvgErr: 0.7909 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0214 | Match:  88.8% (Req: 40.0%)
2        | {'qx': '0.14', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.2616 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: -0.19                | AvgErr: 0.0730 | Match:  42.2% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qy                   | AvgErr: 0.9634 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0366 | Match:  76.0% (Req: 40.0%)
3        | {'qx': '-0.19', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
-----------------------------------------------------------------
L0 Parameters: 13664
L1 Parameters: 3416
Compression:   75.00%
Reconstruction MSE: 0.000971

In [11]:
import pandas as pd
import numpy as np

# ==========================================
# 1. AGGREGATE ACTUAL DATA
# ==========================================
def get_report_data(type_name, df_orig, s_data_l1_list, recon_list):
    # Calculate row-wise MSE
    orig_vals = df_orig.drop(columns=['cluster'], errors='ignore').values
    recon_vals = np.array(recon_list)
    row_mse = ((orig_vals - recon_vals)**2).mean(axis=1)
    
    # Prepare strings for display
    return pd.DataFrame({
        'Type': type_name,
        'Original L0': [list(np.round(x, 3)) for x in orig_vals],
        'Latent L1': [node['l'] for node in s_data_l1_list],
        'Reconstructed': [list(np.round(x, 3)) for x in recon_vals],
        'MSE Error': row_mse
    })

# Combine all results
report_cuboid = get_report_data("Cuboid", df_l0, s_data_l1["Cuboid"], reconstructed_rows)
report_trans = get_report_data("Translate", df_l0_t, s_data_l1_t["Translate"], reconstructed_t)
report_rotate = get_report_data("Rotate", df_l0_r, s_data_l1_r["Rotate"], reconstructed_r)

full_report_df = pd.concat([report_cuboid, report_trans, report_rotate]).reset_index(drop=True)

# ==========================================
# 2. FORMATTED REPORT & HEATMAP
# ==========================================
print("=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT ===")

# Summary Statistics Table
summary_stats = pd.DataFrame({
    'Metric': ['Total L0 Params', 'Total L1 Params', 'Compression %', 'Global MSE'],
    'Value': [
        total_l0_params + total_l0_t + total_l0_r,
        total_l1_params + total_l1_t + total_l1_r,
        f"{((1 - (total_l1_params + total_l1_t + total_l1_r) / (total_l0_params + total_l0_t + total_l0_r)) * 100):.2f}%",
        f"{(mse + mse_t + mse_r) / 3:.6f}"
    ]
})
display(summary_stats)

# Styling Function for Error Highlighting
def error_heatmap(val):
    # Normalizing color: 0 error is white, high error is red
    # Adjust 'max_val' based on your typical error range (e.g., 0.1)
    color_intensity = min(int(255 * (val / 0.1)), 255) 
    inv_intensity = 255 - color_intensity
    return f'background-color: rgb(255, {inv_intensity}, {inv_intensity})'

# Display top 20 rows with the most interesting errors
print("\n--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---")
styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)

display(styled_report)

=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT ===

            Metric     Value
0  Total L0 Params     75272
1  Total L1 Params     38986
2    Compression %    48.21%
3       Global MSE  0.014923

--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_139200\1884652687.py:56: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [12]:
import pandas as pd
import numpy as np

# ==========================================
# 1. CLEAN AGGREGATION FUNCTION
# ==========================================
def get_report_data_clean(type_name, df_orig, s_data_l1_list, recon_list):
    # Calculate row-wise MSE
    orig_vals = df_orig.drop(columns=['cluster'], errors='ignore').values
    recon_vals = np.array(recon_list)
    row_mse = ((orig_vals - recon_vals)**2).mean(axis=1)
    
    # helper to force python floats and 2 decimal rounding
    def clean_list(arr):
        return [round(float(x), 2) for x in arr]

    # Prepare strings for display
    return pd.DataFrame({
        'Type': type_name,
        'Original L0': [clean_list(x) for x in orig_vals],
        'Latent L1': [clean_list(node['l']) for node in s_data_l1_list],
        'Reconstructed': [clean_list(x) for x in recon_vals],
        'MSE Error': row_mse
    })

# Combine results with rounding
report_cuboid = get_report_data_clean("Cuboid", df_l0, s_data_l1["Cuboid"], reconstructed_rows)
report_trans = get_report_data_clean("Translate", df_l0_t, s_data_l1_t["Translate"], reconstructed_t)
report_rotate = get_report_data_clean("Rotate", df_l0_r, s_data_l1_r["Rotate"], reconstructed_r)

full_report_df = pd.concat([report_cuboid, report_trans, report_rotate]).reset_index(drop=True)

# Display with Heatmap
print("=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT (ROUNDED) ===")
styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)
display(styled_report)

=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT (ROUNDED) ===

C:\Users\Amogh\AppData\Local\Temp\ipykernel_139200\3563489100.py:35: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [13]:
# Display top 20 rows with the most interesting errors
print("\n--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---")
styled_report = full_report_df.sort_values("MSE Error", ascending=True).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)

styled_report

--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_139200\2999429750.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=True).head(25).style.applymap(

In [14]:
full_report_df

,Type,Original L0,Latent L1,Reconstructed,MSE Error
0,Cuboid,"[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]",0.000000
1,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
2,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
3,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
4,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
...,...,...,...,...,...
23947,Rotate,"[0.0, -0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23948,Rotate,"[0.0, 0.0, -0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100
23949,Rotate,"[0.26, 0.0, 0.0, 0.97]",[0.97],"[0.14, 0.0, 0.0, 1.0]",0.004020
23950,Rotate,"[0.0, 0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23951,Rotate,"[0.0, 0.0, 0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100

In [15]:
p_data_l0.keys()

dict_keys(['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)'])

In [16]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# The relationships found in your p_data_l0
pair_keys = ['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)']

pair_grammars = {}
s_data_l1_pairs = {}

print(f"{'RELATIONSHIP':<20} | {'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 85)

for p_key in pair_keys:
    raw_data = p_data_l0.get(p_key, [])
    if not raw_data:
        continue
        
    # Create column names based on the pair (e.g., p_qx, p_qy... c_tx, c_ty...)
    # We dynamically detect dimension based on the first entry
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    child_dim = len(raw_data[0]) - parent_dim
    
    p_cols = [f'p{i}' for i in range(parent_dim)]
    c_cols = [f'c{i}' for i in range(child_dim)]
    all_cols = p_cols + c_cols
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    
    # 1. Cluster the relationships
    n_clusters = min(3, len(df_pair)) 
    kmeans_p = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    df_pair['cluster'] = kmeans_p.fit_predict(df_pair)
    
    cluster_rules = {}
    s_data_l1_pairs[p_key] = []
    
    for c_id in range(n_clusters):
        subset = df_pair[df_pair['cluster'] == c_id].drop(columns=['cluster'])
        
        # 2. Harvest constants from both parent and child values
        dynamic_consts = [0.0, 0.5, 1.0, -1.0]
        for col in subset.columns:
            top_vals = subset[col].round(2).value_counts().head(3).index.tolist()
            dynamic_consts.extend(top_vals)
        dynamic_consts = list(set(dynamic_consts))
        
        # 3. Discover Rules (Cross-parameter relationships)
        rules = discover_symbolic_rules(
            subset, 
            custom_constants=dynamic_consts, 
            custom_tol=0.07, 
            custom_min_match=0.40
        )
        cluster_rules[c_id] = rules
        print(f"{p_key[:20]:<20} | {c_id:<8} | {rules}")
        
    pair_grammars[p_key] = cluster_rules

RELATIONSHIP         | CLUSTER  | RULES FOUND
-------------------------------------------------------------------------------------
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0311 | Match:  87.1% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.0148 | Match:  97.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0174 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
Rotate(Rotate)       | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': 'p0', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0026 | Match:  99.4% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.1506 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: -0.08                | AvgErr: 0.0707 | Match:  55.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
Rotate(Rotate)       | 1        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '-0.08', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0047 | Match:  97.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.1830 | Match:   1.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.13                 | AvgErr: 0.0660 | Match:  64.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
Rotate(Rotate)       | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '0.13', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1072 | Match:  47.7% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c0                   | AvgErr: 0.5745 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0104 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3664 | Match:  18.7% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.44                 | AvgErr: 0.0875 | Match:  40.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3063 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.26                | AvgErr: 0.2905 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(p1, -0.37)       | AvgErr: 0.3073 | Match:  23.3% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2450 | Match:  15.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.12                 | AvgErr: 0.2308 | Match:  14.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, 0.12)        | AvgErr: 0.2849 | Match:  23.5% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': '0.44'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1078 | Match:  31.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.08                | AvgErr: 0.0664 | Match:  53.8% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c1                   | AvgErr: 0.6753 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0083 | Match:  97.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.1093 | Match:  63.9% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3229 | Match:   9.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.29                 | AvgErr: 0.1464 | Match:  22.9% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c1   | Best: Sub(p2, -0.34)       | AvgErr: 0.1448 | Match:  42.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2652 | Match:   4.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: -0.35                | AvgErr: 0.0878 | Match:  42.3% (Req: 40.0%)
Rotate(Translate)    | 1        | {'p0': '-0.08', 'p1': 'p2', 'p2': 'p1', 'p3': '1.0', 'c0': 'p1', 'c1': 'Sub(p2, -0.34)', 'c2': '-0.35'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1081 | Match:  48.0% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c2                   | AvgErr: 0.9299 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0108 | Match:  94.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c1                   | AvgErr: 0.3280 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: -0.37                | AvgErr: 0.1385 | Match:  28.4% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c0   | Best: Add(p2, -0.44)       | AvgErr: 0.1489 | Match:  46.3% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2769 | Match:  14.9% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.12                | AvgErr: 0.2573 | Match:  10.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, 0.07)        | AvgErr: 0.3493 | Match:  23.4% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2300 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.07                 | AvgErr: 0.2194 | Match:  14.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Sub(p2, -0.12)       | AvgErr: 0.2225 | Match:  22.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': 'Add(p2, -0.44)'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.3687 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.3531 | Match:   4.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p0   | Best: Mul(p2, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p0
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.5051 | Match:   9.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1118 | Match:  41.6% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c0                   | AvgErr: 0.3450 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.11                 | AvgErr: 0.3338 | Match:   1.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Mul(p0, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: c2                   | AvgErr: 0.4043 | Match:  12.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.52                 | AvgErr: 0.1872 | Match:  20.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, -0.51)       | AvgErr: 0.2281 | Match:  31.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
Translate(Cuboid)    | 0        | {'p1': '-0.51', 'c0': 'c2', 'c2': 'c0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.2426 | Match:  33.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1848 | Match:  58.4% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.2411 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: -0.05                | AvgErr: 0.1813 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c0, -0.16)       | AvgErr: 0.1641 | Match:  35.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c1                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.0964 | Match:  45.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: 0.69                 | AvgErr: 0.3358 | Match:  11.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c0   | Best: Sub(c2, p0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c0
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: c1   | Best: 0.08                 | AvgErr: 0.1801 | Match:  42.2% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.83                 | AvgErr: 0.1851 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, c0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Translate(Cuboid)    | 1        | {'p0': '0.0', 'p2': '0.0', 'c1': '0.08'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1203 | Match:  54.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: c2                   | AvgErr: 0.2518 | Match:  13.7% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: 0.28                 | AvgErr: 0.1516 | Match:  29.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c1, 0.5)         | AvgErr: 0.2172 | Match:  32.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3348 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: -0.27                | AvgErr: 0.0893 | Match:  34.2% (Req: 40.0%)
    [SUCCESS] Binary     | Target: p2   | Best: Add(c2, -0.36)       | AvgErr: 0.1245 | Match:  41.3% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.3254 | Match:  11.5% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.06                 | AvgErr: 0.3942 | Match:  41.0% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.4567 | Match:   5.5% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.7                  | AvgErr: 0.2715 | Match:  15.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(c2, 0.7)         | AvgErr: 0.3114 | Match:  27.7% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: 0.06                 | AvgErr: 0.0858 | Match:  57.4% (Req: 40.0%)
Translate(Cuboid)    | 2        | {'p0': '0.0', 'p2': 'Add(c2, -0.36)', 'c0': '0.06', 'c2': '0.06'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0419 | Match:  83.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.9953 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0022 | Match:  99.4% (Req: 40.0%)
Union(Rotate)        | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1654 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.12                | AvgErr: 0.0563 | Match:  67.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.9832 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0168 | Match:  90.9% (Req: 40.0%)
Union(Rotate)        | 1        | {'p0': '-0.12', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1875 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.14                 | AvgErr: 0.0622 | Match:  62.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.7915 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0210 | Match:  90.4% (Req: 40.0%)
Union(Rotate)        | 2        | {'p0': '0.14', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.34                 | AvgErr: 0.0852 | Match:  42.2% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.4912 | Match:  10.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1380 | Match:  40.4% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.3071 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Add(p0, 0.0)         | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
Union(Translate)     | 0        | {'p0': '0.34', 'p1': '-0.51'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3215 | Match:  11.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1339 | Match:  51.7% (Req: 40.0%)

In [17]:
pair_reports = []

for p_key, clusters in pair_grammars.items():
    raw_data = p_data_l0[p_key]
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    p_cols = [f'p{i}' for i in range(parent_dim)]
    c_cols = [f'c{i}' for i in range(len(raw_data[0]) - parent_dim)]
    all_cols = p_cols + c_cols
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    df_pair['cluster'] = KMeans(n_clusters=len(clusters), random_state=42, n_init=10).fit_predict(df_pair)
    
    recon_rows = []
    
    for i, row in df_pair.iterrows():
        c_id = int(row['cluster'])
        rules = clusters[c_id]
        
        # Compression: Only keep columns not ruled
        latent = [row[v] for v in all_cols if v not in rules]
        if not latent: latent = [row[all_cols[0]]]
        
        # Reconstruction logic
        recon = {v: row[v] if v not in rules else None for v in all_cols}
        # (Simplified recon for report mapping)
        for target, expr in rules.items():
            if expr in all_cols: recon[target] = row[expr]
            else: 
                try: recon[target] = float(expr)
                except: recon[target] = 0.0
        
        recon_rows.append([recon[v] for v in all_cols])
        
    # Calculate MSE for this relationship type
    orig_np = df_pair[all_cols].values
    recon_np = np.array(recon_rows)
    mse_p = ((orig_np - recon_np)**2).mean()
    
    pair_reports.append({
        'Relationship': p_key,
        'L0 Params': len(df_pair) * len(all_cols),
        'L1 Params': sum([len([v for v in all_cols if v not in clusters[int(df_pair.iloc[j]['cluster'])]]) for j in range(len(df_pair))]),
        'MSE': mse_p
    })

df_pair_report = pd.DataFrame(pair_reports)

In [18]:
df_pair_report

        Relationship  L0 Params  L1 Params       MSE
0     Rotate(Rotate)      14432          0  0.001285
1  Rotate(Translate)      11284       1934  0.024150
2  Translate(Cuboid)      61608      27816  0.037602
3      Union(Rotate)       6448          0  0.001513
4   Union(Translate)      25968      11240  0.034966

In [19]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# 1. Initialization
pair_keys = ['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)']
pair_grammars = {}
s_data_l1_pairs = {}
pair_reconstructions = {} # This fixes your NameError

print(f"{'RELATIONSHIP':<20} | {'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 85)

# 2. Discovery & Reconstruction Loop
for p_key in pair_keys:
    raw_data = p_data_l0.get(p_key, [])
    if not raw_data: continue
    
    # Setup dimensions
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    child_dim = len(raw_data[0]) - parent_dim
    all_cols = [f'p{i}' for i in range(parent_dim)] + [f'c{i}' for i in range(child_dim)]
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    n_clusters = min(3, len(df_pair)) 
    df_pair['cluster'] = KMeans(n_clusters=n_clusters, random_state=42, n_init=10).fit_predict(df_pair)
    
    cluster_rules = {}
    s_data_l1_pairs[p_key] = []
    recons_for_this_key = []
    
    for c_id in range(n_clusters):
        subset = df_pair[df_pair['cluster'] == c_id].drop(columns=['cluster'])
        
        # Harvest top constants
        dynamic_consts = [0.0, 0.5, 1.0, -1.0]
        for col in subset.columns:
            dynamic_consts.extend(subset[col].round(2).value_counts().head(3).index.tolist())
        
        # Discover Rules
        rules = discover_symbolic_rules(subset, custom_constants=list(set(dynamic_consts)), custom_tol=0.07, custom_min_match=0.40)
        cluster_rules[c_id] = rules
        print(f"{p_key[:20]:<20} | {c_id:<8} | {rules}")

    # 3. Apply Compression and Generate Reconstructions
    for _, row in df_pair.iterrows():
        c_id = int(row['cluster'])
        rules = cluster_rules[c_id]
        
        # L1 Latent
        latent = [row[v] for v in all_cols if v not in rules]
        if not latent: latent = [row[all_cols[0]]]
        s_data_l1_pairs[p_key].append({"c": c_id, "l": [round(x, 4) for x in latent]})
        
        # Reconstruct (Logic for the Report)
        latent_vars = [v for v in all_cols if v not in rules]
        if not latent_vars: latent_vars = [all_cols[0]]
        recon_dict = {var: val for var, val in zip(latent_vars, latent)}
        
        for target, expr in rules.items():
            if expr in recon_dict: recon_dict[target] = recon_dict[expr]
            else:
                try: recon_dict[target] = float(expr)
                except: recon_dict[target] = 0.0
        
        recons_for_this_key.append([recon_dict.get(v, 0.0) for v in all_cols])
    
    pair_reconstructions[p_key] = recons_for_this_key
    pair_grammars[p_key] = cluster_rules

# ==========================================
# 4. FINAL DETAILED REPORT
# ==========================================
pair_report_list = []
for p_key in pair_keys:
    if p_key not in pair_reconstructions: continue
    orig_np = np.array(p_data_l0[p_key])
    recon_np = np.array(pair_reconstructions[p_key])
    row_mse = ((orig_np - recon_np)**2).mean(axis=1)
    
    pair_report_list.append(pd.DataFrame({
        'Relationship': p_key,
        'Original L0': [list(np.round(x, 3)) for x in orig_np],
        'Latent L1': [node['l'] for node in s_data_l1_pairs[p_key]],
        'Reconstructed': [list(np.round(x, 3)) for x in recon_np],
        'MSE Error': row_mse
    }))

full_pair_report_df = pd.concat(pair_report_list).reset_index(drop=True)

def pair_error_heatmap(val):
    intensity = min(int(255 * (val / 0.1)), 255)
    return f'background-color: rgb(255, {255-intensity}, {255-intensity})'

display(full_pair_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    pair_error_heatmap, subset=['MSE Error']
))

RELATIONSHIP         | CLUSTER  | RULES FOUND
-------------------------------------------------------------------------------------
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0311 | Match:  87.1% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.0148 | Match:  97.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0174 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
Rotate(Rotate)       | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': 'p0', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0026 | Match:  99.4% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.1506 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: -0.08                | AvgErr: 0.0707 | Match:  55.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
Rotate(Rotate)       | 1        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '-0.08', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0047 | Match:  97.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.1830 | Match:   1.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.13                 | AvgErr: 0.0660 | Match:  64.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
Rotate(Rotate)       | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '0.13', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1072 | Match:  47.7% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c0                   | AvgErr: 0.5745 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0104 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3664 | Match:  18.7% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.44                 | AvgErr: 0.0875 | Match:  40.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3063 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.26                | AvgErr: 0.2905 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(p1, -0.37)       | AvgErr: 0.3073 | Match:  23.3% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2450 | Match:  15.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.12                 | AvgErr: 0.2308 | Match:  14.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, 0.12)        | AvgErr: 0.2849 | Match:  23.5% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': '0.44'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1078 | Match:  31.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.08                | AvgErr: 0.0664 | Match:  53.8% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c1                   | AvgErr: 0.6753 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0083 | Match:  97.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.1093 | Match:  63.9% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3229 | Match:   9.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.29                 | AvgErr: 0.1464 | Match:  22.9% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c1   | Best: Sub(p2, -0.34)       | AvgErr: 0.1448 | Match:  42.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2652 | Match:   4.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: -0.35                | AvgErr: 0.0878 | Match:  42.3% (Req: 40.0%)
Rotate(Translate)    | 1        | {'p0': '-0.08', 'p1': 'p2', 'p2': 'p1', 'p3': '1.0', 'c0': 'p1', 'c1': 'Sub(p2, -0.34)', 'c2': '-0.35'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1081 | Match:  48.0% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c2                   | AvgErr: 0.9299 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0108 | Match:  94.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c1                   | AvgErr: 0.3280 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: -0.37                | AvgErr: 0.1385 | Match:  28.4% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c0   | Best: Add(p2, -0.44)       | AvgErr: 0.1489 | Match:  46.3% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2769 | Match:  14.9% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.12                | AvgErr: 0.2573 | Match:  10.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, 0.07)        | AvgErr: 0.3493 | Match:  23.4% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2300 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.07                 | AvgErr: 0.2194 | Match:  14.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Sub(p2, -0.12)       | AvgErr: 0.2225 | Match:  22.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': 'Add(p2, -0.44)'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.3687 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.3531 | Match:   4.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p0   | Best: Mul(p2, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p0
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.5051 | Match:   9.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1118 | Match:  41.6% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c0                   | AvgErr: 0.3450 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.11                 | AvgErr: 0.3338 | Match:   1.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Mul(p0, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: c2                   | AvgErr: 0.4043 | Match:  12.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.52                 | AvgErr: 0.1872 | Match:  20.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, -0.51)       | AvgErr: 0.2281 | Match:  31.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
Translate(Cuboid)    | 0        | {'p1': '-0.51', 'c0': 'c2', 'c2': 'c0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.2426 | Match:  33.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1848 | Match:  58.4% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.2411 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: -0.05                | AvgErr: 0.1813 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c0, -0.16)       | AvgErr: 0.1641 | Match:  35.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c1                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.0964 | Match:  45.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: 0.69                 | AvgErr: 0.3358 | Match:  11.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c0   | Best: Sub(c2, p0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c0
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: c1   | Best: 0.08                 | AvgErr: 0.1801 | Match:  42.2% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.83                 | AvgErr: 0.1851 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, c0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Translate(Cuboid)    | 1        | {'p0': '0.0', 'p2': '0.0', 'c1': '0.08'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1203 | Match:  54.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: c2                   | AvgErr: 0.2518 | Match:  13.7% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: 0.28                 | AvgErr: 0.1516 | Match:  29.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c1, 0.5)         | AvgErr: 0.2172 | Match:  32.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3348 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: -0.27                | AvgErr: 0.0893 | Match:  34.2% (Req: 40.0%)
    [SUCCESS] Binary     | Target: p2   | Best: Add(c2, -0.36)       | AvgErr: 0.1245 | Match:  41.3% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.3254 | Match:  11.5% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.06                 | AvgErr: 0.3942 | Match:  41.0% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.4567 | Match:   5.5% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.7                  | AvgErr: 0.2715 | Match:  15.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(c2, 0.7)         | AvgErr: 0.3114 | Match:  27.7% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: 0.06                 | AvgErr: 0.0858 | Match:  57.4% (Req: 40.0%)
Translate(Cuboid)    | 2        | {'p0': '0.0', 'p2': 'Add(c2, -0.36)', 'c0': '0.06', 'c2': '0.06'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0419 | Match:  83.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.9953 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0022 | Match:  99.4% (Req: 40.0%)
Union(Rotate)        | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1654 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.12                | AvgErr: 0.0563 | Match:  67.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.9832 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0168 | Match:  90.9% (Req: 40.0%)
Union(Rotate)        | 1        | {'p0': '-0.12', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1875 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.14                 | AvgErr: 0.0622 | Match:  62.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.7915 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0210 | Match:  90.4% (Req: 40.0%)
Union(Rotate)        | 2        | {'p0': '0.14', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.34                 | AvgErr: 0.0852 | Match:  42.2% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.4912 | Match:  10.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1380 | Match:  40.4% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.3071 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Add(p0, 0.0)         | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
Union(Translate)     | 0        | {'p0': '0.34', 'p1': '-0.51'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3215 | Match:  11.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1339 | Match:  51.7% (Req: 40.0%)

C:\Users\Amogh\AppData\Local\Temp\ipykernel_139200\2689885488.py:96: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(full_pair_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [20]:
# ==========================================
# 2. CLEAN AGGREGATION FOR PAIRS
# ==========================================
pair_report_list_clean = []

def clean_list(arr):
    return [round(float(x), 2) for x in arr]

for p_key in pair_keys:
    if p_key not in pair_reconstructions: continue
    
    orig_np = np.array(p_data_l0[p_key])
    recon_np = np.array(pair_reconstructions[p_key])
    row_mse = ((orig_np - recon_np)**2).mean(axis=1)
    
    pair_report_list_clean.append(pd.DataFrame({
        'Relationship': p_key,
        'Original L0': [clean_list(x) for x in orig_np],
        'Latent L1': [clean_list(node['l']) for node in s_data_l1_pairs[p_key]],
        'Reconstructed': [clean_list(x) for x in recon_np],
        'MSE Error': row_mse
    }))

full_pair_report_clean = pd.concat(pair_report_list_clean).reset_index(drop=True)

print("\n--- TOP PAIR ERROR SAMPLES (ROUNDED) ---")
styled_pair_report = full_pair_report_clean.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    pair_error_heatmap, subset=['MSE Error']
)
display(styled_pair_report)

--- TOP PAIR ERROR SAMPLES (ROUNDED) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_139200\2830648964.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_pair_report = full_pair_report_clean.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [21]:
full_report_df

,Type,Original L0,Latent L1,Reconstructed,MSE Error
0,Cuboid,"[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]",0.000000
1,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
2,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
3,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
4,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
...,...,...,...,...,...
23947,Rotate,"[0.0, -0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23948,Rotate,"[0.0, 0.0, -0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100
23949,Rotate,"[0.26, 0.0, 0.0, 0.97]",[0.97],"[0.14, 0.0, 0.0, 1.0]",0.004020
23950,Rotate,"[0.0, 0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23951,Rotate,"[0.0, 0.0, 0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100

In [23]:
full_pair_report_clean

,Relationship,Original L0,Latent L1,Reconstructed,MSE Error
0,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
1,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]",[0.0],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.250000
2,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
3,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]",[0.0],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.250000
4,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
...,...,...,...,...,...
23947,Union(Translate),"[0.28, -0.61, 0.3]",[0.3],"[0.34, -0.51, 0.3]",0.004533
23948,Union(Translate),"[-0.28, -0.61, 0.3]",[-0.61],"[0.0, -0.61, 0.0]",0.056133
23949,Union(Translate),"[-0.29, -0.6, -0.28]",[-0.6],"[0.0, -0.6, 0.0]",0.054167
23950,Union(Translate),"[-0.0, 0.28, -0.28]","[0.28, -0.28]","[0.0, 0.28, -0.28]",0.000000
23951,Union(Translate),"[0.0, -0.23, 0.08]",[-0.23],"[0.0, -0.23, 0.0]",0.002133