In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
## 1. Setup Paths & Configuration

import sys
import os
from pathlib import Path

# Add source directory to path
current_path = Path.cwd()
base_project_dir = current_path.parent
src_dir = base_project_dir / "src"

if str(src_dir) not in sys.path:
    sys.path.append(str(src_dir))

# Define key directories
dataset_directory = src_dir / "abstractionsshapecoder" / "dataset"
saved_directory = src_dir / "abstractionsshapecoder" / "saved"

# --- AE Model Paths ---
saved_models_L1_AE_dir = saved_directory / "models_L1_AE"
saved_models_L2_AE_dir = saved_directory / "models_L2_AE"
saved_models_L1_AE_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_AE_dir.mkdir(parents=True, exist_ok=True)

# --- PCA Model Paths ---
saved_models_L1_PCA_dir = saved_directory / "models_L1_PCA"
saved_models_L2_PCA_dir = saved_directory / "models_L2_PCA"
saved_models_L1_PCA_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_PCA_dir.mkdir(parents=True, exist_ok=True)

print(f"Base project directory: {base_project_dir}")
print(f"Source directory: {src_dir}")
print(f"L1 AE Models directory: {saved_models_L1_AE_dir}")
print(f"L2 AE Models directory: {saved_models_L2_AE_dir}")
print(f"L1 PCA Models directory: {saved_models_L1_PCA_dir}")
print(f"L2 PCA Models directory: {saved_models_L2_PCA_dir}")

Base project directory: c:\Users\Amogh\abstraction-discovery
Source directory: c:\Users\Amogh\abstraction-discovery\src
L1 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_AE
L2 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_AE
L1 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_PCA
L2 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_PCA

In [4]:
import pickle
from pathlib import Path
from abstractionsshapecoder.debug_utils import debug_info, debug_success, debug_error

def load_processed_datasets():
    """
    Loads all hierarchical datasets (L0, L1-VAE, L1-AE, L2-AE) from the saved directory.
    """
    SAVED_DIR = Path.cwd().parent / "src" / "abstractionsshapecoder" / "saved"
    
    # Define file map: {Variable_Name: Filename}
    dataset_files = {
        "shapes_l0": "all_dsl_shapes.pkl",
        "shapes_l1_vae": "all_abstracted_shapes_L1_VAE.pkl",
        "shapes_l1_ae": "all_abstracted_shapes_L1_AE.pkl",
        "shapes_l2_ae": "all_abstracted_shapes_L2_AE.pkl"
    }
    
    loaded_datasets = {}
    
    for var_name, filename in dataset_files.items():
        file_path = SAVED_DIR / filename
        if file_path.exists():
            debug_info(f"Loading {var_name} from {filename}...")
            with open(file_path, "rb") as f:
                loaded_datasets[var_name] = pickle.load(f)
            debug_success(f"Successfully loaded {len(loaded_datasets[var_name])} shapes into {var_name}.")
        else:
            debug_error(f"Missing file: {filename}. Ensure previous training cells were run.")
            loaded_datasets[var_name] = {}
            
    return loaded_datasets

# Execute the load
datasets = load_processed_datasets()

# Extract into global namespace for easier access in subsequent cells
shapes_l0 = datasets.get("shapes_l0")

[INFO] Loading shapes_l0 from all_dsl_shapes.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l0.
[INFO] Loading shapes_l1_vae from all_abstracted_shapes_L1_VAE.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l1_vae.
[ERROR] Missing file: all_abstracted_shapes_L1_AE.pkl. Ensure previous training cells were run.
[ERROR] Missing file: all_abstracted_shapes_L2_AE.pkl. Ensure previous training cells were run.

In [5]:
shapes_l0["172_0_0"]

{'dsl': <abstractionsshapecoder.dsl_nodes.Union at 0x28a875f07d0>,
 'singleton_params': {'Cuboid': [[0.68, 0.09, 0.66],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.68, 0.14, 0.24],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08]],
  'Translate': [[-0.0, -0.17, 0.0],
   [-0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [0.31, -0.51, 0.3],
   [-0.26, 0.27, -0.18],
   [-0.14, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.0, 0.27, -0.25],
   [0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25]]},
 'pair_params': {'Translate(Cuboid)': [[-0.0, -0.17, 0.0, 0.68, 0.09, 0.66],
   [-0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [-0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [-0.26, 0.27, -0.18, 0.08, 0.79, 0.08],
   [-0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.0, 0.74, -0.22, 0.68, 0.14, 0.24],
   [-0.0, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.28, 0.27, -0.25, 0.08, 0.79, 0.08]],
  'Union(Translate)': [[0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25],
   [-0.0, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.14, 0.27, -0.25],
   [-0.26, 0.27, -0.18],
   [0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [-0.31, -0.51, -0.17],
   [-0.0, -0.17, 0.0]]},
 'program_text': 'Union(Move(Cuboid(0.68,0.09,0.66),-0.0,-0.17,0.0),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,0.3),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,0.3),Union(Move(Cuboid(0.08,0.79,0.08),-0.26,0.27,-0.18),Union(Move(Cuboid(0.08,0.79,0.08),-0.14,0.27,-0.25),Union(Move(Cuboid(0.68,0.14,0.24),0.0,0.74,-0.22),Union(Move(Cuboid(0.08,0.79,0.08),-0.0,0.27,-0.25),Union(Move(Cuboid(0.08,0.79,0.08),0.14,0.27,-0.25),Move(Cuboid(0.08,0.79,0.08),0.28,0.27,-0.25)))))))))))'}

In [6]:
from abstractionsshapecoder.dsl_utils import collect_singleton_and_pair_data
from abstractionsshapecoder.debug_utils import debug_info, debug_success

# 1. Isolate the DSL objects from the dictionary
all_l0_dsl_trees = [data['dsl'] for data in shapes_l0.values()]

debug_info(f"Extracting parameters from {len(all_l0_dsl_trees)} L0 shapes...")

# 2. Run the collection utility
# s_data_l0: { 'NodeName': [ [params], [params], ... ] }
# p_data_l0: { 'Parent(Child)': [ [params], [params], ... ] }
s_data_l0, p_data_l0 = collect_singleton_and_pair_data(all_l0_dsl_trees)

debug_success(f"Extraction complete.")
debug_info(f"Unique Singletons found: {len(s_data_l0)}")
debug_info(f"Unique Parent-Child Pairs found: {len(p_data_l0)}")

[INFO] Extracting parameters from 1100 L0 shapes...
[SUCCESS] Extraction complete.
[INFO] Unique Singletons found: 3
[INFO] Unique Parent-Child Pairs found: 5

In [7]:
import pandas as pd

# Create a summary for Singletons
singleton_summary = []
for node_type, param_list in s_data_l0.items():
    singleton_summary.append({
        "Node Type": node_type,
        "Total Occurrences": len(param_list),
        "Param Dimension": len(param_list[0]) if param_list else 0,
        "Example Params": param_list[0] if param_list else []
    })

# Create a summary for Pairs
pair_summary = []
for pair_name, param_list in p_data_l0.items():
    pair_summary.append({
        "Relationship": pair_name,
        "Total Occurrences": len(param_list),
        "Combined Dimension": len(param_list[0]) if param_list else 0
    })

# Convert to DataFrames for easy viewing
df_singletons = pd.DataFrame(singleton_summary).sort_values("Total Occurrences", ascending=False)
df_pairs = pd.DataFrame(pair_summary).sort_values("Total Occurrences", ascending=False)

print("=== L0 SINGLETON CENSUS ===")
display(df_singletons)

print("\n=== L0 PAIR CENSUS ===")
display(df_pairs)

=== L0 SINGLETON CENSUS ===

,Node Type,Total Occurrences,Param Dimension,Example Params
0,Cuboid,10268,3,"[0.68, 0.09, 0.66]"
2,Translate,10268,3,"[-0.0, -0.17, 0.0]"
1,Rotate,3416,4,"[-0.17410813759359595, 0.0, 0.0, 0.98472653890..."

=== L0 PAIR CENSUS ===

        Relationship  Total Occurrences  Combined Dimension
2  Translate(Cuboid)              10268                   6
4   Union(Translate)               8656                   3
0     Rotate(Rotate)               1804                   8
1  Rotate(Translate)               1612                   7
3      Union(Rotate)               1612                   4

In [49]:
import torch
import pandas as pd
import itertools

# ==============================================================================
# 1. LANGUAGE DEFINITIONS
# ==============================================================================

class FloatOperation:
    def __init__(self, func, unary: bool = False):
        self.func = func
        self.unary = unary

LANGUAGE = {
    "binary_ops": {
        "Add": FloatOperation(lambda a, b: a + b),
        "Sub": FloatOperation(lambda a, b: a - b),
        "Mul": FloatOperation(lambda a, b: a * b),
        "Div": FloatOperation(lambda a, b: torch.div(a, b + 1e-6)),
    },
    "constants": [0.5, 1.0, 2.0, -1.0, 0.35, -0.31, 0.08, 0.05], 
}

UNARY_OPERATIONS = {
    "Neg": FloatOperation(lambda a: -a, unary=True),
    "Inv": FloatOperation(lambda a: torch.div(1.0, a + 1e-6), unary=True)
}

# ==============================================================================
# 2. DEBUG UTILITIES
# ==============================================================================

def log_best_match(method_name, expr, diff, tol, min_match):
    """Prints a debug line showing how close the best candidate came."""
    mean_err = diff.mean().item()
    matches = (diff < tol).float()
    match_frac = matches.mean().item()
    
    status = "❌" if match_frac < min_match else "✅"
    print(f"    [{method_name}] {status} Best: {expr} | Err: {mean_err:.4f} | Match: {match_frac*100:.1f}%")

# ==============================================================================
# 3. MATCHING UTILITIES
# ==============================================================================

def compare_with_tolerance(predicted, target, max_error, min_fraction, name="expr"):
    if not isinstance(predicted, torch.Tensor):
        predicted = torch.tensor(predicted, device=target.device, dtype=target.dtype)
    if predicted.dim() == 0 or (predicted.dim() == 1 and predicted.shape[0] == 1):
        predicted = predicted.expand_as(target)

    diff = torch.abs(predicted - target)
    matches = diff < max_error
    fraction = matches.sum().item() / max(1, len(target))
    
    # Return stats for debugging
    return (fraction >= min_fraction), torch.where(matches)[0].tolist(), diff

def batch_compare(pred_batches, target, max_error, min_fraction, index_pairs, variable_names, op_name):
    results = []
    diffs = torch.abs(pred_batches - target.unsqueeze(0))
    matches = diffs < max_error
    fractions = matches.sum(dim=1).float() / len(target)
    
    # Find the best one in the batch for debugging
    best_idx = torch.argmax(fractions).item()
    best_expr = f"{op_name}({variable_names[index_pairs[best_idx][0]]}, {variable_names[index_pairs[best_idx][1]]})"
    log_best_match("Binary", best_expr, diffs[best_idx], max_error, min_fraction)

    success_indices = torch.where(fractions >= min_fraction)[0]
    for idx in success_indices:
        match_idx_list = torch.where(matches[idx])[0].tolist()
        expr_vars = tuple(variable_names[j] for j in index_pairs[idx])
        results.append((expr_vars, match_idx_list))
    return results

# ==============================================================================
# 4. SEARCH FUNCTIONS
# ==============================================================================

def search_direct_variable(inp, return_indices=False):
    matches = []
    best_diff, best_name = None, ""
    for name, values in inp["variables"].items():
        success, idx, diff = compare_with_tolerance(values, inp["target"], inp["tol"], inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success: matches.append((name, idx) if return_indices else name)
    
    if best_name: log_best_match("Direct", best_name, best_diff, inp["tol"], inp["min_match"])
    return matches

def search_constants(inp, return_indices=False):
    matches = []
    best_diff, best_name = None, ""
    for name, val in inp["simple_consts"].items():
        success, idx, diff = compare_with_tolerance(val, inp["target"], 0.05, inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success: matches.append((name, idx) if return_indices else name)
    
    if best_name: log_best_match("Const", best_name, best_diff, 0.05, inp["min_match"])
    return matches

def search_unary_operations(inp, return_indices=False):
    matches = []
    for op_name, op in inp["unary_ops"].items():
        best_diff, best_var = None, ""
        for var_name, var_value in inp["variables"].items():
            prediction = op.func(var_value)
            success, idx, diff = compare_with_tolerance(prediction, inp["target"], inp["tol"], inp["min_match"])
            if best_diff is None or diff.mean() < best_diff.mean():
                best_diff, best_var = diff, var_name
            if success: matches.append((f"{op_name}({var_name})", idx) if return_indices else f"{op_name}({var_name})")
        if best_var: log_best_match("Unary", f"{op_name}({best_var})", best_diff, inp["tol"], inp["min_match"])
    return matches

def search_binary_operations(inp, return_indices=False):
    matches = []
    var_keys = list(inp["variables"].keys())
    const_keys = list(inp["extended_consts"].keys())
    all_keys = var_keys + const_keys

    var_values = list(inp["variables"].values())
    const_values = [c.expand(len(inp["target"])) for c in inp["extended_consts"].values()]
    value_stack = torch.stack(var_values + const_values)

    index_pairs = torch.cartesian_prod(torch.arange(len(var_values)), torch.arange(len(all_keys)))
    left_sides = value_stack[index_pairs[:, 0]]
    right_sides = value_stack[index_pairs[:, 1]]

    for op_name, op in inp["binary_ops"].items():
        results = op.func(left_sides, right_sides)
        comparisons = batch_compare(results, inp["target"], inp["tol"], inp["min_match"], index_pairs, all_keys, op_name)
        for (a, b), idx in comparisons:
            matches.append((f"{op_name}({a}, {b})", idx) if return_indices else f"{op_name}({a}, {b})")
    return matches

# ==============================================================================
# 5. MAIN DRIVER
# ==============================================================================

def discover_symbolic_rules(df: pd.DataFrame, custom_tol=None, custom_min_match=None, custom_constants=None):
    rules = {}
    param_names = list(df.columns)

    # Use user-provided constants or fall back to the defaults
    search_constants_list = custom_constants if custom_constants is not None else [-1., 0., 1., 0.35, -0.31, 0.08]

    for target_col in param_names:
        input_cols = [p for p in param_names if p != target_col]
        target_tensor = torch.tensor(df[target_col].values, dtype=torch.float32)
        
        # 1. Handle Tolerance
        if custom_tol is not None:
            auto_tol = custom_tol
        else:
            auto_tol = 0.06 if target_tensor.abs().max() < 2.0 else 0.15
        
        # 2. Handle Match Threshold
        min_match = custom_min_match if custom_min_match is not None else 0.85

        # Create the dictionary of constant tensors
        const_dict = {str(c): torch.tensor(c, dtype=torch.float32) for c in search_constants_list}

        search_space = {
            "target": target_tensor,
            "variables": {inp: torch.tensor(df[inp].values, dtype=torch.float32) for inp in input_cols},
            "simple_consts": const_dict,
            "extended_consts": const_dict, # Now using your custom constants for binary ops too
            "binary_ops": LANGUAGE["binary_ops"],
            "unary_ops": UNARY_OPERATIONS,
            "tol": auto_tol,
            "min_match": min_match
        }

        print(f"\n--- Searching: {target_col} | Tol: {auto_tol} | Match: {min_match*100}% | Consts: {search_constants_list} ---")

        search_methods = [
            search_direct_variable,
            search_constants,
            search_unary_operations,
            search_binary_operations
        ]

        found_rule = None
        for method in search_methods:
            matches = method(search_space, return_indices=True)
            if matches:
                expr, _ = matches[0]
                found_rule = expr
                print(f"✅ SUCCESS: {target_col} ≈ {expr}")
                break

        if not found_rule:
            print(f"❌ No rule found for '{target_col}'")
        else:
            rules[target_col] = found_rule

    return rules

In [58]:
s_data_l0["Cuboid"]

[[0.68, 0.09, 0.66],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.68, 0.14, 0.24],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.88, 0.19, 1.01],
 [0.88, 0.85, 0.31],
 [0.15, 0.52, 0.2],
 [0.21, 0.53, 0.19],
 [0.15, 0.52, 0.2],
 [0.21, 0.53, 0.19],
 [0.92, 0.34, 0.92],
 [0.92, 0.79, 0.49],
 [0.12, 0.42, 0.12],
 [0.14, 0.45, 0.13],
 [0.12, 0.42, 0.12],
 [0.14, 0.45, 0.13],
 [0.88, 1.0, 0.1],
 [0.09, 0.52, 0.05],
 [0.07, 0.63, 0.05],
 [0.69, 0.1, 0.03],
 [0.69, 0.11, 0.03],
 [0.09, 0.52, 0.05],
 [0.07, 0.63, 0.05],
 [0.87, 0.16, 0.81],
 [0.09, 0.11, 0.67],
 [0.09, 0.11, 0.67],
 [0.05, 0.04, 0.4],
 [0.06, 0.08, 0.09],
 [0.05, 0.46, 0.12],
 [0.05, 0.04, 0.4],
 [0.06, 0.08, 0.09],
 [0.05, 0.46, 0.12],
 [0.65, 0.84, 0.11],
 [0.65, 0.18, 0.66],
 [0.08, 0.5, 0.43],
 [0.08, 0.52, 0.42],
 [0.08, 0.5, 0.43],
 [0.08, 0.52, 0.42],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.74, 0.16, 0.86],
 [0.74, 0.05, 0.86],
 [0.68, 0.77, 0.11],
 [0.06, 0.02, 0.04],
 [0.06, 0.02, 0.04],
 [0.69, 0.14, 0.69],
 [0.05, 0.79, 0.11],
 [0.03, 0.7, 0.03],
 [0.05, 0.79, 0.11],
 [0.03, 0.7, 0.03],
 [0.04, 0.99, 0.12],
 [0.62, 0.01, 0.1],
 [0.04, 0.99, 0.12],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.96, 0.22, 0.85],
 [1.0, 0.08, 0.1],
 [1.05, 0.05, 0.81],
 [0.99, 0.08, 0.85],
 [0.96, 1.0, 0.55],
 [1.03, 0.06, 0.55],
 [0.04, 0.78, 0.41],
 [0.06, 0.06, 0.46],
 [0.05, 0.72, 0.06],
 [0.04, 0.78, 0.41],
 [0.06, 0.06, 0.46],
 [0.05, 0.72, 0.06],
 [0.89, 0.19, 1.01],
 [0.88, 0.86, 0.31],
 [0.15, 0.52, 0.2],
 [0.2, 0.52, 0.19],
 [0.15, 0.52, 0.2],
 [0.2, 0.52, 0.19],
 [0.92, 0.38, 0.92],
 [0.92, 0.78, 0.47],
 [0.12, 0.42, 0.11],
 [0.12, 0.42, 0.12],
 [0.12, 0.42, 0.11],
 [0.12, 0.42, 0.12],
 [0.68, 0.09, 0.66],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.68, 0.14, 0.24],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.89, 0.18, 0.54],
 [0.95, 0.07, 0.93],
 [0.95, 0.66, 0.5],
 [0.96, 0.1, 0.56],
 [0.07, 0.51, 0.49],
 [0.07, 0.09, 0.43],
 [0.05, 0.1, 0.16],
 [0.1, 0.24, 0.1],
 [0.07, 0.51, 0.49],
 [0.07, 0.09, 0.43],
 [0.05, 0.1, 0.16],
 [0.1, 0.24, 0.1],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.75, 0.15, 0.86],
 [0.74, 0.07, 0.86],
 [0.68, 0.77, 0.11],
 [0.06, 0.03, 0.04],
 [0.06, 0.03, 0.04],
 [0.69, 0.14, 0.69],
 [0.03, 0.79, 0.1],
 [0.03, 0.7, 0.03],
 [0.03, 0.79, 0.1],
 [0.03, 0.7, 0.03],
 [0.03, 1.0, 0.12],
 [0.62, 0.01, 0.1],
 [0.03, 1.0, 0.12],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.65, 0.83, 0.11],
 [0.65, 0.17, 0.66],
 [0.08, 0.51, 0.43],
 [0.08, 0.55, 0.42],
 [0.08, 0.51, 0.43],
 [0.08, 0.55, 0.42],
 [0.68, 0.09, 0.66],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.68, 0.14, 0.24],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.89, 0.18, 1.01],
 [0.88, 0.86, 0.31],
 [0.16, 0.53, 0.2],
 [0.21, 0.51, 0.19],
 [0.16, 0.53, 0.2],
 [0.21, 0.51, 0.19],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.96, 0.22, 0.85],
 [1.0, 0.1, 0.1],
 [1.05, 0.05, 0.81],
 [0.98, 0.09, 0.85],
 [0.92, 0.94, 0.44],
 [0.98, 0.06, 0.47],
 [0.04, 0.9, 0.48],
 [0.06, 0.06, 0.56],
 [0.05, 0.74, 0.06],
 [0.04, 0.9, 0.48],
 [0.06, 0.06, 0.56],
 [0.05, 0.74, 0.06],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.89, 0.18, 0.63],
 [0.95, 0.07, 0.93],
 [0.93, 0.66, 0.42],
 [0.95, 0.1, 0.45],
 [0.08, 0.57, 0.56],
 [0.07, 0.1, 0.38],
 [0.05, 0.14, 0.09],
 [0.1, 0.24, 0.1],
 [0.08, 0.57, 0.56],
 [0.07, 0.1, 0.38],
 [0.05, 0.14, 0.09],
 [0.1, 0.24, 0.1],
 [0.65, 0.84, 0.12],
 [0.66, 0.18, 0.66],
 [0.08, 0.49, 0.43],
 [0.08, 0.53, 0.42],
 [0.08, 0.49, 0.43],
 [0.08, 0.53, 0.42],
 [0.92, 0.36, 0.92],
 [0.92, 0.78, 0.48],
 [0.12, 0.44, 0.12],
 [0.12, 0.42, 0.12],
 [0.12, 0.44, 0.12],
 [0.12, 0.44, 0.12],
 [0.07, 0.62, 0.07],
 [0.07, 0.63, 0.07],
 [0.07, 0.62, 0.07],
 [0.07, 0.63, 0.07],
 [0.74, 0.14, 0.86],
 [0.74, 0.07, 0.86],
 [0.68, 0.77, 0.11],
 [0.06, 0.03, 0.04],
 [0.06, 0.03, 0.04],
 [0.69, 0.14, 0.69],
 [0.03, 0.88, 0.12],
 [0.03, 0.7, 0.03],
 [0.03, 0.88, 0.12],
 [0.03, 0.7, 0.03],
 [0.03, 0.98, 0.1],
 [0.62, 0.01, 0.1],
 [0.03, 0.98, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [1.34, 0.39, 1.31],
 [1.34, 0.5, 0.36],
 [0.29, 0.5, 0.95],
 [0.29, 0.5, 0.95],
 [0.17, 0.14, 0.16],
 [0.17, 0.13, 0.16],
 [0.21, 0.13, 0.16],
 [0.21, 0.13, 0.16],
 [1.62, 0.73, 0.33],
 [0.43, 0.34, 0.62],
 [0.43, 0.34, 0.62],
 [0.2, 0.12, 0.62],
 [0.19, 0.16, 0.62],
 [1.54, 0.44, 0.62],
 [1.36, 0.22, 0.62],
 [0.88, 0.19, 1.01],
 [0.88, 0.85, 0.31],
 [0.15, 0.53, 0.2],
 [0.21, 0.52, 0.19],
 [0.15, 0.53, 0.2],
 [0.21, 0.52, 0.19],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.08, 0.56, 0.08],
 [0.08, 0.55, 0.08],
 [0.89, 0.18, 0.5],
 [0.95, 0.07, 0.93],
 [0.97, 0.66, 0.56],
 [0.97, 0.1, 0.64],
 [0.07, 0.47, 0.4],
 [0.07, 0.09, 0.38],
 [0.05, 0.44, 0.15],
 [0.1, 0.24, 0.1],
 [0.07, 0.47, 0.4],
 [0.07, 0.09, 0.38],
 [0.05, 0.44, 0.15],
 [0.1, 0.24, 0.1],
 [0.78, 0.4, 1.07],
 [0.79, 0.09, 0.71],
 [0.06, 0.03, 0.06],
 [0.08, 0.02, 0.69],
 [0.05, 0.69, 0.03],
 [0.04, 0.05, 0.86],
 [0.04, 0.68, 0.07],
 [0.05, 0.69, 0.03],
 [0.04, 0.05, 0.86],
 [0.04, 0.68, 0.07],
 [0.59, 0.21, 0.59],
 [0.37, 0.14, 0.09],
 [0.38, 0.06, 0.06],
 [0.45, 0.83, 0.09],
 [0.09, 0.59, 0.11],
 [0.12, 0.07, 0.39],
 [0.09, 0.6, 0.12],
 [0.09, 0.59, 0.11],
 [0.12, 0.07, 0.39],
 [0.09, 0.6, 0.12],
 [0.08, 0.7, 0.09],
 [0.08, 0.13, 0.09],
 [0.08, 0.7, 0.09],
 [0.08, 0.13, 0.09],
 [1.03, 0.2, 1.18],
 [0.93, 1.01, 0.32],
 [0.15, 0.99, 1.34],
 [0.14, 0.99, 1.34],
 [0.14, 0.1, 0.09],
 [0.14, 0.1, 0.09],
 [0.14, 0.1, 0.09],
 [0.14, 0.1, 0.09],
 [1.22, 0.13, 1.14],
 [0.93, 1.01, 0.32],
 [0.15, 0.93, 1.34],
 [0.15, 0.93, 1.34],
 [1.03, 0.2, 1.18],
 [0.14, 0.09, 1.23],
 [0.14, 0.09, 1.23],
 [0.08, 0.55, 0.08],
 [0.08, 0.49, 0.08],
 [0.08, 0.52, 0.08],
 [0.08, 0.49, 0.08],
 [0.92, 0.24, 0.93],
 [0.93, 0.09, 0.94],
 [0.67, 0.69, 0.17],
 [0.81, 0.82, 0.12],
 [0.1, 0.07, 0.04],
 [0.1, 0.07, 0.04],
 [0.11, 0.11, 0.83],
 [0.09, 0.61, 0.11],
 [0.11, 0.11, 0.83],
 [0.09, 0.61, 0.11],
 [0.77, 0.14, 0.73],
 [0.11, 0.6, 0.11],
 [0.11, 0.6, 0.11],
 [0.11, 0.6, 0.11],
 [0.11, 0.6, 0.11],
 [0.05, 0.7, 0.05],
 [0.83, 0.17, 0.29],
 [0.05, 0.7, 0.05],
 [0.05, 0.7, 0.05],
 [0.05, 0.7, 0.05],
 [0.05, 0.7, 0.05],
 [0.05, 0.7, 0.05],
 [0.7, 0.24, 0.72],
 [0.7, 1.0, 0.16],
 [0.12, 0.59, 0.15],
 [0.12, 0.58, 0.12],
 [0.12, 0.59, 0.15],
 [0.12, 0.58, 0.12],
 [0.68, 0.09, 0.66],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.68, 0.14, 0.24],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.18, 0.43, 0.96],
 [0.18, 0.43, 0.96],
 [0.33, 0.02, 0.32],
 [0.17, 0.02, 0.16],
 [0.33, 0.02, 0.32],
 [0.17, 0.02, 0.16],
 [1.04, 0.14, 0.95],
 [1.33, 0.43, 1.33],
 [1.04, 0.41, 0.19],
 [1.33, 0.43, 0.43],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.1, 0.42, 0.13],
 [0.15, 0.49, 0.13],
 [0.96, 0.22, 0.85],
 [1.0, 0.11, 0.1],
 [1.05, 0.05, 0.81],
 [0.98, 0.1, 0.85],
 [0.92, 0.94, 0.45],
 [1.0, 0.06, 0.47],
 [0.04, 0.91, 0.48],
 [0.06, 0.06, 0.53],
 [0.05, 0.74, 0.06],
 [0.04, 0.91, 0.48],
 [0.06, 0.06, 0.53],
 [0.05, 0.74, 0.06],
 [0.74, 0.22, 0.75],
 [0.08, 0.51, 0.07],
 [0.08, 0.6, 0.07],
 [0.08, 0.51, 0.07],
 [0.08, 0.6, 0.07],
 [0.94, 0.79, 0.29],
 [0.77, 0.06, 0.28],
 [0.08, 0.46, 0.65],
 [0.07, 0.44, 0.05],
 [0.08, 0.46, 0.79],
 [0.07, 0.42, 0.05],
 [0.85, 0.09, 0.85],
 [0.1, 0.59, 0.1],
 [0.09, 0.58, 0.09],
 [0.1, 0.59, 0.1],
 [0.09, 0.58, 0.09],
 [0.07, 0.76, 0.07],
 [0.89, 0.09, 0.05],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.07, 0.76, 0.07],
 [0.7, 0.17, 0.56],
 [0.7, 1.23, 0.16],
 [0.12, 0.62, 0.14],
 [0.12, 0.59, 0.12],
 [0.12, 0.58, 0.15],
 [0.12, 0.59, 0.12],
 [0.18, 0.52, 0.86],
 [0.18, 0.52, 0.86],
 [0.33, 0.02, 0.32],
 [0.17, 0.02, 0.16],
 [0.33, 0.02, 0.32],
 [0.17, 0.02, 0.16],
 [1.04, 0.19, 0.86],
 [1.33, 0.4, 0.86],
 [1.04, 0.41, 0.19],
 [1.33, 0.86, 0.47],
 [0.56, 0.12, 1.0],
 [0.56, 0.92, 0.11],
 [0.07, 0.57, 0.11],
 [0.07, 0.54, 0.11],
 [0.07, 0.57, 0.11],
 [0.07, 0.54, 0.11],
 [0.85, 0.09, 0.85],
 [0.08, 0.58, 0.08],
 [0.08, 0.58, 0.07],
 [0.08, 0.58, 0.08],
 [0.08, 0.58, 0.07],
 [0.07, 0.75, 0.07],
 [0.11, 0.78, 0.04],
 [0.07, 0.73, 0.04],
 [0.89, 0.09, 0.05],
 [0.07, 0.75, 0.07],
 [0.07, 0.75, 0.07],
 [0.07, 0.75, 0.07],
 [0.07, 0.73, 0.04],
 [0.07, 0.73, 0.04],
 [0.07, 0.73, 0.04],
 [0.56, 0.11, 0.89],
 [0.56, 1.04, 0.11],
 [0.07, 0.57, 0.11],
 [0.07, 0.56, 0.11],
 [0.07, 0.57, 0.11],
 [0.07, 0.56, 0.11],
 [0.76, 0.05, 0.76],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.76, 0.22, 0.27],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.75, 0.15, 0.83],
 [0.8, 0.79, 0.16],
 [0.1, 0.63, 0.1],
 [0.1, 0.63, 0.1],
 [0.1, 0.63, 0.1],
 [0.1, 0.63, 0.1],
 [0.89, 0.1, 0.87],
 [0.89, 0.97, 0.09],
 [0.04, 0.52, 0.06],
 [0.04, 0.05, 0.7],
 [0.06, 0.04, 0.7],
 [0.04, 0.52, 0.05],
 [0.04, 0.52, 0.06],
 [0.04, 0.05, 0.7],
 [0.06, 0.04, 0.7],
 [0.04, 0.52, 0.05],
 [0.68, 0.09, 0.66],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.06, 0.6, 0.06],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.68, 0.14, 0.24],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.08, 0.79, 0.08],
 [0.76, 0.05, 0.76],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.08, 0.5, 0.08],
 [0.76, 0.22, 0.27],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.06, 0.88, 0.06],
 [0.75, 0.13, 0.83],
 [0.8, 0.8, 0.16],
 [0.1, 0.66, 0.1],
 [0.1, 0.65, 0.1],
 [0.1, 0.66, 0.1],
 [0.1, 0.65, 0.1],
 [0.65, 0.17, 0.66],
 [0.65, 0.84, 0.11],
 [0.07, 0.5, 0.43],
 [0.08, 0.52, 0.42],
 [0.07, 0.5, 0.43],
 [0.08, 0.52, 0.42],
 [0.06, 0.71, 0.05],
 [0.06, 0.72, 0.05],
 [0.06, 0.71, 0.05],
 [0.06, 0.72, 0.05],
 [0.74, 0.06, 0.63],
 [0.8, 0.08, 0.65],
 [0.67, 0.45, 0.03],
 [0.08, 0.73, 0.06],
 [0.08, 0.73, 0.06],
 [0.92, 0.36, 0.92],
 [0.92, 0.77, 0.48],
 [0.12, 0.44, 0.12],
 [0.12, 0.42, 0.12],
 [0.12, 0.44, 0.12],
 [0.12, 0.42, 0.12],
 [0.62, 1.06, 0.11],
 [0.65, 0.04, 0.01],
 [0.62, 0.13, 0.73],
 [0.69, 0.19, 0.06],
 [0.08, 0.02, 0.9],
 [0.08, 0.21, 0.03],
 [0.08, 0.37, 0.03],
 [0.08, 0.02, 0.9],
 [0.08, 0.21, 0.03],
 [0.08, 0.37, 0.03],
 [0.08, 0.38, 0.05],
 [0.08, 0.07, 0.94],
 [0.08, 0.4, 0.05],
 [0.08, 0.38, 0.05],
 [0.08, 0.07, 0.94],
 [0.08, 0.4, 0.05],
 [0.69, 0.1, 0.61],
 [0.38, 0.05, 0.04],
 [0.4, 0.05, 0.04],
 [0.52, 0.24, 0.04],
 [0.65, 0.63, 0.05],
 [0.06, 0.31, 0.05],
 [0.06, 0.31, 0.05],
 [0.09, 0.98, 0.08],
 [0.05, 0.05, 0.25],
 [0.09, 0.98, 0.08],
 [0.09, 0.98, 0.08],
 [0.05, 0.05, 0.25],
 [0.09, 0.98, 0.08],
 [0.98, 0.34, 0.9],
 [0.33, 0.54, 0.28],
 [0.32, 0.44, 0.22],
 [0.31, 0.41, 0.19],
 [0.28, 0.28, 0.11],
 [0.32, 0.44, 0.22],
 [0.98, 0.81, 0.23],
 [0.71, 1.37, 0.24],
 [0.72, 0.22, 0.7],
 [0.92, 0.78, 0.28],
 [0.09, 0.46, 0.72],
 [0.09, 0.46, 0.72],
 [0.12, 0.51, 0.07],
 [0.12, 0.96, 0.07],
 [0.12, 0.51, 0.07],
 [0.12, 0.96, 0.07],
 [0.83, 0.16, 0.85],
 [0.08, 0.66, 0.11],
 [0.08, 0.65, 0.09],
 [0.08, 0.58, 0.09],
 [0.08, 0.65, 0.09],
 [0.86, 0.2, 0.26],
 [0.07, 0.4, 0.09],
 [0.07, 0.64, 0.09],
 [0.1, 0.11, 0.68],
 [0.07, 0.57, 0.12],
 [0.1, 0.11, 0.62],
 [0.07, 0.52, 0.11],
 [0.74, 0.05, 0.82],
 [0.74, 0.88, 0.09],
 [0.74, 0.56, 0.94],
 [0.05, 0.12, 0.05],
 [0.05, 0.12, 0.05],
 [0.05, 0.12, 0.05],
 [0.05, 0.12, 0.05],
 [0.8, 0.15, 0.83],
 [0.89, 0.88, 0.4],
 [0.06, 0.63, 0.08],
 [0.06, 0.61, 0.06],
 [0.06, 0.63, 0.08],
 [0.06, 0.61, 0.06],
 [0.79, 0.18, 0.79],
 [0.09, 0.63, 0.09],
 [0.09, 0.61, 0.09],
 [0.09, 0.63, 0.09],
 [0.09, 0.61, 0.09],
 [0.09, 0.62, 0.07],
 [0.09, 0.29, 0.07],
 [0.09, 0.13, 0.07],
 [0.61, 0.12, 0.07],
 [0.79, 0.08, 0.08],
 [0.67, 0.15, 0.07],
 [0.09, 0.62, 0.07],
 [0.09, 0.29, 0.07],
 [0.09, 0.29, 0.07],
 [0.09, 0.13, 0.07],
 [0.09, 0.13, 0.07],
 [0.71, 1.17, 0.28],
 [0.15, 1.14, 0.96],
 [0.15, 1.14, 0.96],
 [0.08, 0.1, 0.08],
 [0.08, 0.1, 0.08],
 [0.08, 0.1, 0.08],
 [0.08, 0.1, 0.08],
 [1.01, 0.18, 0.86],
 [1.01, 0.23, 0.82],
 [1.04, 0.59, 0.23],
 [0.08, 0.13, 0.1],
 [0.08, 0.13, 0.1],
 [0.08, 0.13, 0.1],
 [0.08, 0.13, 0.1],
 [1.04, 0.18, 1.33],
 [1.04, 0.37, 1.32],
 [0.1, 0.79, 1.32],
 [0.1, 0.05, 1.32],
 [0.1, 0.79, 1.32],
 [0.1, 0.05, 1.32],
 [0.11, 0.47, 1.09],
 [0.11, 0.47, 1.09],
 [0.09, 0.17, 0.1],
 [0.09, 0.17, 0.09],
 [0.09, 0.17, 0.1],
 [0.09, 0.17, 0.09],
 [0.97, 0.15, 1.0],
 [1.14, 0.08, 1.17],
 [1.15, 0.23, 1.19],
 [1.13, 0.47, 0.12],
 [1.13, 0.47, 0.12],
 [0.97, 0.14, 0.97],
 [0.11, 0.71, 0.11],
 [0.11, 0.71, 0.11],
 [0.11, 0.71, 0.11],
 [0.11, 0.71, 0.11],
 [0.53, 0.32, 0.07],
 [0.12, 0.91, 0.11],
 [0.12, 0.91, 0.11],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.07, 0.64, 0.07],
 [0.74, 0.13, 0.86],
 [0.74, 0.07, 0.86],
 [0.68, 0.77, 0.11],
 [0.06, 0.02, 0.04],
 [0.06, 0.02, 0.04],
 [0.69, 0.14, 0.69],
 [0.03, 0.81, 0.11],
 [0.03, 0.7, 0.03],
 [0.03, 0.81, 0.11],
 [0.03, 0.7, 0.03],
 [0.03, 0.99, 0.11],
 [0.62, 0.01, 0.1],
 [0.03, 0.99, 0.11],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.08, 0.75],
 [0.1, 0.71, 0.09],
 [0.1, 0.71, 0.09],
 [0.1, 0.71, 0.09],
 [0.1, 0.71, 0.09],
 [0.69, 0.22, 0.47],
 [0.05, 0.46, 0.05],
 [0.05, 0.46, 0.05],
 [0.05, 0.46, 0.05],
 [0.05, 0.46, 0.05],
 [0.05, 0.46, 0.05],
 [0.68, 0.22, 0.67],
 [0.67, 0.96, 0.24],
 [0.21, 0.23, 0.44],
 [0.21, 0.23, 0.44],
 [0.2, 0.66, 0.12],
 [0.14, 0.66, 0.16],
 [0.2, 0.66, 0.12],
 [0.14, 0.66, 0.16],
 [1.54, 0.53, 0.32],
 [0.39, 0.35, 0.88],
 [0.39, 0.35, 0.88],
 [0.08, 0.22, 0.04],
 [0.08, 0.21, 0.04],
 [0.08, 0.22, 0.04],
 [0.08, 0.21, 0.04],
 [1.58, 0.19, 0.87],
 [1.54, 0.09, 0.87],
 [1.42, 0.18, 0.46],
 [0.94, 1.01, 0.32],
 [0.16, 0.46, 0.95],
 [0.16, 0.46, 0.95],
 [0.12, 0.12, 0.13],
 [0.12, 0.12, 0.13],
 [0.12, 0.12, 0.13],
 [0.12, 0.12, 0.13],
 [0.89, 0.17, 0.69],
 [1.15, 0.24, 0.97],
 [0.65, 0.14, 0.64],
 [0.65, 1.08, 0.11],
 [0.08, 0.55, 0.07],
 [0.08, 0.54, 0.07],
 [0.08, 0.55, 0.07],
 [0.08, 0.54, 0.07],
 [0.69, 0.09, 0.8],
 [0.1, 0.8, 0.08],
 [0.09, 0.8, 0.09],
 [0.1, 0.8, 0.08],
 [0.09, 0.8, 0.09],
 [0.11, 0.64, 0.06],
 [0.1, 0.74, 0.06],
 [0.69, 0.06, 0.08],
 [0.64, 0.1, 0.06],
 [0.11, 0.64, 0.06],
 [0.11, 0.64, 0.06],
 [0.11, 0.64, 0.06],
 [0.82, 0.18, 0.82],
 [0.1, 0.66, 0.1],
 [0.1, 0.65, 0.11],
 [0.1, 0.66, 0.1],
 [0.1, 0.65, 0.11],
 [0.82, 0.39, 0.14],
 [0.1, 0.34, 0.1],
 [0.1, 0.34, 0.1],
 [0.78, 0.17, 0.96],
 [0.78, 0.7, 0.14],
 [0.13, 0.55, 0.12],
 [0.09, 0.54, 0.12],
 [0.13, 0.55, 0.12],
 [0.09, 0.54, 0.12],
 [1.3, 0.86, 0.3],
 [0.26, 0.28, 0.99],
 [0.26, 0.28, 0.99],
 [0.09, 0.06, 0.05],
 [0.09, 0.08, 0.05],
 [0.09, 0.06, 0.05],
 [0.09, 0.08, 0.05],
 [0.82, 0.14, 0.93],
 [1.27, 0.55, 1.2],
 [0.53, 0.23, 0.66],
 [0.53, 0.77, 0.2],
 [0.53, 0.24, 0.45],
 [0.08, 0.62, 0.19],
 [0.08, 0.61, 0.08],
 [0.53, 0.61, 0.09],
 [0.08, 0.62, 0.19],
 [0.66, 0.07, 0.62],
 [0.11, 0.66, 0.07],
 [0.11, 0.66, 0.07],
 [0.11, 0.66, 0.07],
 [0.11, 0.66, 0.07],
 [0.84, 0.16, 0.2],
 [0.06, 0.8, 0.05],
 [0.06, 0.8, 0.05],
 [0.06, 0.8, 0.05],
 [0.06, 0.8, 0.05],
 [0.06, 0.8, 0.05],
 [0.06, 0.8, 0.05],
 [0.78, 0.15, 0.82],
 [0.61, 0.81, 0.13],
 [0.08, 0.64, 0.07],
 [0.07, 0.62, 0.08],
 [0.08, 0.64, 0.07],
 [0.07, 0.62, 0.08],
 [0.69, 0.14, 0.69],
 [0.03, 0.79, 0.1],
 [0.03, 0.7, 0.03],
 [0.03, 0.79, 0.1],
 [0.03, 0.7, 0.03],
 [0.03, 1.0, 0.12],
 [0.62, 0.01, 0.1],
 [0.03, 1.0, 0.12],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.62, 0.01, 0.1],
 [0.87, 0.53, 0.8],
 [0.21, 0.87, 1.15],
 [0.21, 0.87, 1.15],
 [1.31, 0.91, 0.21],
 [1.27, 1.43, 0.04],
 [1.3, 1.44, 0.02],
 [0.92, 0.35, 0.15],
 [0.73, 0.09, 0.05],
 [0.87, 0.08, 0.69],
 [0.01, 0.01, 0.11],
 [0.72, 0.45, 0.03],
 [0.1, 0.78, 0.07],
 [0.1, 0.78, 0.07],
 [0.07, 0.77, 0.07],
 [0.05, 0.06, 0.59],
 [0.07, 0.77, 0.07],
 [0.07, 0.77, 0.07],
 [0.05, 0.06, 0.59],
 [0.07, 0.77, 0.07],
 [0.52, 0.12, 0.6],
 [0.54, 1.06, 0.24],
 [0.17, 0.19, 0.59],
 [0.17, 0.19, 0.59],
 [0.13, 0.54, 0.19],
 [0.12, 0.53, 0.17],
 [0.13, 0.54, 0.19],
 [0.12, 0.53, 0.17],
 [0.65, 0.64, 0.08],
 [0.73, 0.01, 0.49],
 [0.62, 0.85, 0.15],
 [0.81, 0.81, 0.93],
 [0.81, 0.56, 0.86],
 [1.1, 1.17, 0.3],
 [0.19, 0.91, 0.88],
 [0.19, 0.91, 0.88],
 [0.14, 0.12, 0.14],
 [0.14, 0.13, 0.14],
 [0.14, 0.12, 0.14],
 [0.14, 0.13, 0.14],
 [0.61, 0.09, 0.62],
 [0.61, 0.85, 0.1],
 [0.11, 0.83, 0.09],
 [0.11, 0.79, 0.09],
 [0.11, 0.83, 0.09],
 [0.11, 0.79, 0.09],
 [0.07, 0.28, 0.07],
 [0.08, 0.12, 0.05],
 [0.07, 0.28, 0.07],
 [0.08, 0.12, 0.05],
 [0.81, 0.1, 1.06],
 [0.81, 0.32, 1.14],
 [0.17, 0.77, 0.07],
 [0.86, 0.76, 0.1],
 [0.1, 0.84, 1.51],
 [0.1, 0.43, 1.57],
 [0.1, 0.84, 1.51],
 [0.1, 0.43, 1.57],
 [0.17, 0.77, 0.07],
 [0.17, 0.77, 0.07],
 [0.17, 0.77, 0.07],
 [0.17, 0.77, 0.07],
 [1.1, 0.38, 1.27],
 [1.1, 0.32, 0.38],
 [0.09, 0.49, 0.08],
 [0.09, 0.49, 0.08],
 [0.09, 0.06, 1.04],
 [0.09, 0.5, 0.06],
 [0.09, 0.06, 0.89],
 [0.09, 0.5, 0.08],
 [0.09, 0.5, 0.07],
 [0.09, 0.06, 0.89],
 [0.09, 0.5, 0.07],
 [0.09, 0.5, 0.07],
 [0.09, 0.06, 0.89],
 [0.09, 0.5, 0.07],
 [0.94, 0.12, 0.8],
 [0.73, 0.14, 0.73],
 [0.63, 0.95, 0.63],
 [0.8, 0.41, 0.23],
 [0.26, 0.2, 0.07],
 [1.19, 1.06, 0.07],
 [0.17, 0.63, 1.03],
 [0.17, 0.63, 1.03],
 [0.05, 0.24, 0.03],
 [0.05, 0.24, 0.03],
 [0.05, 0.24, 0.03],
 [0.05, 0.24, 0.03],
 [0.99, 0.4, 1.06],
 [0.73, 0.25, 0.3],
 [0.7, 0.13, 0.78],
 [0.67, 0.84, 0.09],
 [0.06, 0.75, 0.16],
 [0.06, 0.75, 0.16],
 [0.06, 0.75, 0.16],
 [0.06, 0.75, 0.16],
 [0.15, 0.05, 0.86],
 [0.07, 0.37, 0.06],
 [0.07, 0.37, 0.06],
 [0.15, 0.05, 0.86],
 [0.07, 0.37, 0.06],
 [0.07, 0.37, 0.06],
 [1.07, 0.33, 0.85],
 [1.07, 0.49, 0.16],
 [0.16, 0.23, 0.72],
 [0.16, 0.23, 0.72],
 [0.46, 0.08, 0.09],
 [0.11, 0.09, 0.33],
 [0.13, 0.08, 0.27],
 [0.52, 0.08, 0.13],
 [0.12, 0.63, 0.14],
 [0.91, 0.08, 0.7],
 [0.04, 0.73, 0.04],
 [0.04, 0.73, 0.04],
 [0.04, 0.73, 0.04],
 [0.04, 0.73, 0.04],
 [0.9, 0.38, 0.02],
 [0.04, 0.43, 0.08],
 [0.05, 0.42, 0.05],
 [0.82, 0.04, 0.03],
 [0.58, 0.24, 0.82],
 [0.57, 0.99, 0.32],
 [0.06, 0.46, 0.05],
 [0.05, 0.48, 0.04],
 [0.28, 0.7, 0.12],
 [0.06, 0.46, 0.05],
 [0.06, 0.05, 0.36],
 [0.08, 0.35, 0.04],
 [0.9, 0.83, 0.98],
 [0.13, 0.46, 1.16],
 [0.13, 0.46, 1.16],
 [0.08, 0.4, 0.12],
 [0.05, 0.44, 0.12],
 [0.07, 0.56, 0.15],
 [0.08, 0.4, 0.12],
 [0.9, 0.24, 1.06],
 [0.82, 0.04, 0.02],
 [0.74, 0.03, 0.12],
 [0.05, 0.64, 0.08],
 [0.05, 0.68, 0.07],
 [0.05, 0.64, 0.08],
 [0.05, 0.68, 0.07],
 [0.8, 0.1, 0.84],
 [0.05, 0.1, 0.74],
 [0.7, 0.1, 0.04],
 [0.7, 0.07, 0.04],
 [0.05, 0.1, 0.86],
 [0.05, 0.93, 0.13],
 [0.05, 0.83, 0.12],
 [0.7, 0.04, 0.07],
 [0.7, 0.05, 0.07],
 [0.7, 0.04, 0.07],
 [0.7, 0.04, 0.07],
 [0.7, 0.26, 0.69],
 [0.69, 1.0, 0.2],
 [0.11, 0.56, 0.2],
 [0.11, 0.56, 0.18],
 [0.11, 0.56, 0.2],
 [0.11, 0.56, 0.18],
 [0.81, 0.1, 0.7],
 [0.65, 0.09, 0.07],
 [0.65, 0.09, 0.07],
 [0.69, 0.38, 0.13],
 [0.09, 0.31, 0.08],
 [0.1, 0.36, 0.08],
 [0.81, 0.11, 0.12],
 [0.81, 0.11, 0.12],
 [0.09, 0.31, 0.08],
 [0.1, 0.36, 0.08],
 [0.1, 0.63, 0.09],
 [0.06, 0.09, 0.56],
 [0.1, 0.63, 0.09],

In [59]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# --- STEP A: Clustering ---
raw_cuboids = s_data_l0.get("Cuboid", [])
df_l0 = pd.DataFrame(raw_cuboids, columns=['sw', 'sh', 'sd'])
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0['cluster'] = kmeans.fit_predict(df_l0)

# --- STEP B: Harvest Magic Constants ---
def get_magic_constants(subset):
    # Find the most frequent rounded values (Modes)
    sw_mode = stats.mode(np.round(subset['sw'].values, 2), keepdims=True)[0][0]
    sh_mode = stats.mode(np.round(subset['sh'].values, 2), keepdims=True)[0][0]
    sd_mode = stats.mode(np.round(subset['sd'].values, 2), keepdims=True)[0][0]
    return {'sw': sw_mode, 'sh': sh_mode, 'sd': sd_mode}

# --- STEP C: Compress to L1 ---
s_data_l1 = {"Cuboid": []}
cluster_profiles = {}

for c_id in range(4):
    subset = df_l0[df_l0['cluster'] == c_id]
    cluster_profiles[c_id] = get_magic_constants(subset)

for i, row in df_l0.iterrows():
    c_id = int(row['cluster'])
    
    # 3D -> 1D/2D Compression Logic based on your Discovered Grammar
    if c_id == 0: # Leg: 1D (Thickness)
        latent = [(row['sw'] + row['sd']) / 2]
    elif c_id == 1: # Seat: 1D (Size)
        latent = [(row['sw'] + row['sd']) / 2]
    elif c_id == 2: # Panel: 2D (Width, Height)
        latent = [row['sw'], row['sh']]
    else: # Joint: 1D (Uniform Scale)
        latent = [(row['sw'] + row['sh'] + row['sd']) / 3]
        
    s_data_l1["Cuboid"].append({
        "cluster": c_id,
        "latent": [round(x, 4) for x in latent]
    })

print(f"Successfully created s_data_l1 with {len(s_data_l1['Cuboid'])} compressed nodes.")

Successfully created s_data_l1 with 10268 compressed nodes.

In [60]:
s_data_l1

{'Cuboid': [{'cluster': 1, 'latent': [np.float64(0.67)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.3533)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.945)]},
  {'cluster': 2, 'latent': [np.float64(0.88), np.float64(0.85)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 1, 'latent': [np.float64(0.92)]},
  {'cluster': 2, 'latent': [np.float64(0.92), np.float64(0.79)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.135)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.135)]},
  {'cluster': 2, 'latent': [np.float64(0.88), np.float64(1.0)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 3, 'latent': [np.float64(0.2733)]},
  {'cluster': 3, 'latent': [np.float64(0.2767)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 1, 'latent': [np.float64(0.84)]},
  {'cluster': 3, 'latent': [np.float64(0.29)]},
  {'cluster': 3, 'latent': [np.float64(0.29)]},
  {'cluster': 3, 'latent': [np.float64(0.1633)]},
  {'cluster': 3, 'latent': [np.float64(0.0767)]},
  {'cluster': 0, 'latent': [np.float64(0.085)]},
  {'cluster': 3, 'latent': [np.float64(0.1633)]},
  {'cluster': 3, 'latent': [np.float64(0.0767)]},
  {'cluster': 0, 'latent': [np.float64(0.085)]},
  {'cluster': 2, 'latent': [np.float64(0.65), np.float64(0.84)]},
  {'cluster': 1, 'latent': [np.float64(0.655)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 1, 'latent': [np.float64(0.8)]},
  {'cluster': 1, 'latent': [np.float64(0.8)]},
  {'cluster': 2, 'latent': [np.float64(0.68), np.float64(0.77)]},
  {'cluster': 3, 'latent': [np.float64(0.04)]},
  {'cluster': 3, 'latent': [np.float64(0.04)]},
  {'cluster': 1, 'latent': [np.float64(0.69)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 1, 'latent': [np.float64(0.905)]},
  {'cluster': 2, 'latent': [np.float64(1.0), np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.93)]},
  {'cluster': 1, 'latent': [np.float64(0.92)]},
  {'cluster': 2, 'latent': [np.float64(0.96), np.float64(1.0)]},
  {'cluster': 1, 'latent': [np.float64(0.79)]},
  {'cluster': 0, 'latent': [np.float64(0.225)]},
  {'cluster': 3, 'latent': [np.float64(0.1933)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 0, 'latent': [np.float64(0.225)]},
  {'cluster': 3, 'latent': [np.float64(0.1933)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 1, 'latent': [np.float64(0.95)]},
  {'cluster': 2, 'latent': [np.float64(0.88), np.float64(0.86)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.195)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.195)]},
  {'cluster': 1, 'latent': [np.float64(0.92)]},
  {'cluster': 2, 'latent': [np.float64(0.92), np.float64(0.78)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 1, 'latent': [np.float64(0.67)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.3533)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.715)]},
  {'cluster': 1, 'latent': [np.float64(0.94)]},
  {'cluster': 2, 'latent': [np.float64(0.95), np.float64(0.66)]},
  {'cluster': 1, 'latent': [np.float64(0.76)]},
  {'cluster': 0, 'latent': [np.float64(0.28)]},
  {'cluster': 3, 'latent': [np.float64(0.1967)]},
  {'cluster': 3, 'latent': [np.float64(0.1033)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 0, 'latent': [np.float64(0.28)]},
  {'cluster': 3, 'latent': [np.float64(0.1967)]},
  {'cluster': 3, 'latent': [np.float64(0.1033)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 1, 'latent': [np.float64(0.805)]},
  {'cluster': 1, 'latent': [np.float64(0.8)]},
  {'cluster': 2, 'latent': [np.float64(0.68), np.float64(0.77)]},
  {'cluster': 3, 'latent': [np.float64(0.0433)]},
  {'cluster': 3, 'latent': [np.float64(0.0433)]},
  {'cluster': 1, 'latent': [np.float64(0.69)]},
  {'cluster': 0, 'latent': [np.float64(0.065)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.065)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 2, 'latent': [np.float64(0.65), np.float64(0.83)]},
  {'cluster': 1, 'latent': [np.float64(0.655)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 1, 'latent': [np.float64(0.67)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.3533)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.95)]},
  {'cluster': 2, 'latent': [np.float64(0.88), np.float64(0.86)]},
  {'cluster': 0, 'latent': [np.float64(0.18)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 0, 'latent': [np.float64(0.18)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 1, 'latent': [np.float64(0.905)]},
  {'cluster': 2, 'latent': [np.float64(1.0), np.float64(0.1)]},
  {'cluster': 1, 'latent': [np.float64(0.93)]},
  {'cluster': 1, 'latent': [np.float64(0.915)]},
  {'cluster': 2, 'latent': [np.float64(0.92), np.float64(0.94)]},
  {'cluster': 1, 'latent': [np.float64(0.725)]},
  {'cluster': 0, 'latent': [np.float64(0.26)]},
  {'cluster': 3, 'latent': [np.float64(0.2267)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 0, 'latent': [np.float64(0.26)]},
  {'cluster': 3, 'latent': [np.float64(0.2267)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.76)]},
  {'cluster': 1, 'latent': [np.float64(0.94)]},
  {'cluster': 2, 'latent': [np.float64(0.93), np.float64(0.66)]},
  {'cluster': 1, 'latent': [np.float64(0.7)]},
  {'cluster': 0, 'latent': [np.float64(0.32)]},
  {'cluster': 3, 'latent': [np.float64(0.1833)]},
  {'cluster': 3, 'latent': [np.float64(0.0933)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 0, 'latent': [np.float64(0.32)]},
  {'cluster': 3, 'latent': [np.float64(0.1833)]},
  {'cluster': 3, 'latent': [np.float64(0.0933)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 2, 'latent': [np.float64(0.65), np.float64(0.84)]},
  {'cluster': 1, 'latent': [np.float64(0.66)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 0, 'latent': [np.float64(0.255)]},
  {'cluster': 0, 'latent': [np.float64(0.25)]},
  {'cluster': 1, 'latent': [np.float64(0.92)]},
  {'cluster': 2, 'latent': [np.float64(0.92), np.float64(0.78)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 0, 'latent': [np.float64(0.07)]},
  {'cluster': 1, 'latent': [np.float64(0.8)]},
  {'cluster': 1, 'latent': [np.float64(0.8)]},
  {'cluster': 2, 'latent': [np.float64(0.68), np.float64(0.77)]},
  {'cluster': 3, 'latent': [np.float64(0.0433)]},
  {'cluster': 3, 'latent': [np.float64(0.0433)]},
  {'cluster': 1, 'latent': [np.float64(0.69)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 0, 'latent': [np.float64(0.03)]},
  {'cluster': 0, 'latent': [np.float64(0.065)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 0, 'latent': [np.float64(0.065)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 3, 'latent': [np.float64(0.2433)]},
  {'cluster': 1, 'latent': [np.float64(1.325)]},
  {'cluster': 2, 'latent': [np.float64(1.34), np.float64(0.5)]},
  {'cluster': 1, 'latent': [np.float64(0.62)]},
  {'cluster': 1, 'latent': [np.float64(0.62)]},
  {'cluster': 3, 'latent': [np.float64(0.1567)]},
  {'cluster': 3, 'latent': [np.float64(0.1533)]},
  {'cluster': 3, 'latent': [np.float64(0.1667)]},
  {'cluster': 3, 'latent': [np.float64(0.1667)]},
  {'cluster': 2, 'latent': [np.float64(1.62), np.float64(0.73)]},
  {'cluster': 1, 'latent': [np.float64(0.525)]},
  {'cluster': 1, 'latent': [np.float64(0.525)]},
  {'cluster': 3, 'latent': [np.float64(0.3133)]},
  {'cluster': 3, 'latent': [np.float64(0.3233)]},
  {'cluster': 2, 'latent': [np.float64(1.54), np.float64(0.44)]},
  {'cluster': 1, 'latent': [np.float64(0.99)]},
  {'cluster': 1, 'latent': [np.float64(0.945)]},
  {'cluster': 2, 'latent': [np.float64(0.88), np.float64(0.85)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 0, 'latent': [np.float64(0.175)]},
  {'cluster': 0, 'latent': [np.float64(0.2)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.695)]},
  {'cluster': 1, 'latent': [np.float64(0.94)]},
  {'cluster': 2, 'latent': [np.float64(0.97), np.float64(0.66)]},
  {'cluster': 1, 'latent': [np.float64(0.805)]},
  {'cluster': 0, 'latent': [np.float64(0.235)]},
  {'cluster': 3, 'latent': [np.float64(0.18)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 0, 'latent': [np.float64(0.235)]},
  {'cluster': 3, 'latent': [np.float64(0.18)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 3, 'latent': [np.float64(0.1467)]},
  {'cluster': 1, 'latent': [np.float64(0.925)]},
  {'cluster': 1, 'latent': [np.float64(0.75)]},
  {'cluster': 3, 'latent': [np.float64(0.05)]},
  {'cluster': 3, 'latent': [np.float64(0.2633)]},
  {'cluster': 0, 'latent': [np.float64(0.04)]},
  {'cluster': 3, 'latent': [np.float64(0.3167)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 0, 'latent': [np.float64(0.04)]},
  {'cluster': 3, 'latent': [np.float64(0.3167)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 1, 'latent': [np.float64(0.59)]},
  {'cluster': 3, 'latent': [np.float64(0.2)]},
  {'cluster': 3, 'latent': [np.float64(0.1667)]},
  {'cluster': 0, 'latent': [np.float64(0.27)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 3, 'latent': [np.float64(0.1933)]},
  {'cluster': 0, 'latent': [np.float64(0.105)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 3, 'latent': [np.float64(0.1933)]},
  {'cluster': 0, 'latent': [np.float64(0.105)]},
  {'cluster': 0, 'latent': [np.float64(0.085)]},
  {'cluster': 3, 'latent': [np.float64(0.1)]},
  {'cluster': 0, 'latent': [np.float64(0.085)]},
  {'cluster': 3, 'latent': [np.float64(0.1)]},
  {'cluster': 1, 'latent': [np.float64(1.105)]},
  {'cluster': 2, 'latent': [np.float64(0.93), np.float64(1.01)]},
  {'cluster': 1, 'latent': [np.float64(0.745)]},
  {'cluster': 1, 'latent': [np.float64(0.74)]},
  {'cluster': 3, 'latent': [np.float64(0.11)]},
  {'cluster': 3, 'latent': [np.float64(0.11)]},
  {'cluster': 3, 'latent': [np.float64(0.11)]},
  {'cluster': 3, 'latent': [np.float64(0.11)]},
  {'cluster': 1, 'latent': [np.float64(1.18)]},
  {'cluster': 2, 'latent': [np.float64(0.93), np.float64(1.01)]},
  {'cluster': 1, 'latent': [np.float64(0.745)]},
  {'cluster': 1, 'latent': [np.float64(0.745)]},
  {'cluster': 1, 'latent': [np.float64(1.105)]},
  {'cluster': 1, 'latent': [np.float64(0.685)]},
  {'cluster': 1, 'latent': [np.float64(0.685)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.925)]},
  {'cluster': 1, 'latent': [np.float64(0.935)]},
  {'cluster': 2, 'latent': [np.float64(0.67), np.float64(0.69)]},
  {'cluster': 2, 'latent': [np.float64(0.81), np.float64(0.82)]},
  {'cluster': 3, 'latent': [np.float64(0.07)]},
  {'cluster': 3, 'latent': [np.float64(0.07)]},
  {'cluster': 3, 'latent': [np.float64(0.35)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 3, 'latent': [np.float64(0.35)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 1, 'latent': [np.float64(0.75)]},
  {'cluster': 0, 'latent': [np.float64(0.11)]},
  {'cluster': 0, 'latent': [np.float64(0.11)]},
  {'cluster': 0, 'latent': [np.float64(0.11)]},
  {'cluster': 0, 'latent': [np.float64(0.11)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 2, 'latent': [np.float64(0.83), np.float64(0.17)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 0, 'latent': [np.float64(0.05)]},
  {'cluster': 1, 'latent': [np.float64(0.71)]},
  {'cluster': 2, 'latent': [np.float64(0.7), np.float64(1.0)]},
  {'cluster': 0, 'latent': [np.float64(0.135)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 0, 'latent': [np.float64(0.135)]},
  {'cluster': 0, 'latent': [np.float64(0.12)]},
  {'cluster': 1, 'latent': [np.float64(0.67)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 3, 'latent': [np.float64(0.3533)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 0, 'latent': [np.float64(0.08)]},
  {'cluster': 1, 'latent': [np.float64(0.57)]},
  {'cluster': 1, 'latent': [np.float64(0.57)]},
  {'cluster': 3, 'latent': [np.float64(0.2233)]},
  {'cluster': 3, 'latent': [np.float64(0.1167)]},
  {'cluster': 3, 'latent': [np.float64(0.2233)]},
  {'cluster': 3, 'latent': [np.float64(0.1167)]},
  {'cluster': 1, 'latent': [np.float64(0.995)]},
  {'cluster': 1, 'latent': [np.float64(1.33)]},
  {'cluster': 2, 'latent': [np.float64(1.04), np.float64(0.41)]},
  {'cluster': 2, 'latent': [np.float64(1.33), np.float64(0.43)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 0, 'latent': [np.float64(0.115)]},
  {'cluster': 0, 'latent': [np.float64(0.14)]},
  {'cluster': 1, 'latent': [np.float64(0.905)]},
  {'cluster': 2, 'latent': [np.float64(1.0), np.float64(0.11)]},
  {'cluster': 1, 'latent': [np.float64(0.93)]},
  {'cluster': 1, 'latent': [np.float64(0.915)]},
  {'cluster': 2, 'latent': [np.float64(0.92), np.float64(0.94)]},
  {'cluster': 1, 'latent': [np.float64(0.735)]},
  {'cluster': 0, 'latent': [np.float64(0.26)]},
  {'cluster': 3, 'latent': [np.float64(0.2167)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 0, 'latent': [np.float64(0.26)]},
  {'cluster': 3, 'latent': [np.float64(0.2167)]},
  {'cluster': 0, 'latent': [np.float64(0.055)]},
  {'cluster': 1, 'latent': [np.float64(0.745)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 0, 'latent': [np.float64(0.075)]},
  {'cluster': 2, 'latent': [np.float64(0.94), np.float64(0.79)]},
  {'cluster': 3, 'latent': [np.float64(0.37)]},
  {'cluster': 3, 'latent': [np.float64(0.3967)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 3, 'latent': [np.float64(0.4433)]},
  {'cluster': 0, 'latent': [np.float64(0.06)]},
  {'cluster': 1, 'latent': [np.float64(0.85)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},
  {'cluster': 0, 'latent': [np.float64(0.09)]},
  {'cluster': 0, 'latent': [np.float64(0.1)]},

In [61]:
# --- STEP D: Decompress L1 back to L0 ---
reconstructed_l0 = []

for node in s_data_l1["Cuboid"]:
    c_id = node["cluster"]
    latent = node["latent"]
    profile = cluster_profiles[c_id]
    
    # Reconstruct 3D vectors based on the Symbolic Grammar
    if c_id == 0: # Leg: sw=latent, sd=latent, sh=constant
        recon = [latent[0], profile['sh'], latent[0]]
    elif c_id == 1: # Seat: sw=latent, sd=latent, sh=constant
        recon = [latent[0], profile['sh'], latent[0]]
    elif c_id == 2: # Panel: sw=latent[0], sh=latent[1], sd=constant
        recon = [latent[0], latent[1], profile['sd']]
    else: # Joint: sw=sh=sd=latent
        recon = [latent[0], latent[0], latent[0]]
    
    reconstructed_l0.append(recon)

# --- STEP E: Compare Output ---
df_recon = pd.DataFrame(reconstructed_l0, columns=['sw_rec', 'sh_rec', 'sd_rec'])
comparison = pd.concat([df_l0[['sw', 'sh', 'sd']], df_recon], axis=1)

print("\n=== ROUND-TRIP COMPARISON (First 5 Nodes) ===")
print(comparison.head(5).round(3))

# Calculate Accuracy (MSE)
mse = ((df_l0[['sw', 'sh', 'sd']].values - df_recon.values)**2).mean()
print(f"\nReconstruction MSE: {mse:.6f}")
print("Note: A low MSE means the Symbolic Grammar effectively captured the design intent!")

=== ROUND-TRIP COMPARISON (First 5 Nodes) ===
     sw    sh    sd  sw_rec  sh_rec  sd_rec
0  0.68  0.09  0.66    0.67    0.09    0.67
1  0.06  0.60  0.06    0.06    0.60    0.06
2  0.06  0.60  0.06    0.06    0.60    0.06
3  0.06  0.60  0.06    0.06    0.60    0.06
4  0.06  0.60  0.06    0.06    0.60    0.06

Reconstruction MSE: 0.027541
Note: A low MSE means the Symbolic Grammar effectively captured the design intent!

In [65]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# --- 1. PREP & CLUSTER ---
raw_cuboids = s_data_l0.get("Cuboid", [])
df_l0 = pd.DataFrame(raw_cuboids, columns=['sw', 'sh', 'sd'])
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0['cluster'] = kmeans.fit_predict(df_l0)

# --- 2. HARVEST CONSTANTS ---
cluster_profiles = {}
for c_id in range(4):
    subset = df_l0[df_l0['cluster'] == c_id]
    if not subset.empty:
        cluster_profiles[c_id] = {
            'sh': float(stats.mode(np.round(subset['sh'].values, 2), keepdims=True)[0][0]),
            'sd': float(stats.mode(np.round(subset['sd'].values, 2), keepdims=True)[0][0])
        }

# --- 3. COMPRESS & PRINT ALL NODES ---
s_data_l1 = {"Cuboid": []}

print(f"{'IDX':<4} | {'TYPE':<8} | {'ORIGINAL (L0)':<20} | {'COMPRESSED (L1)':<15} | {'RECONSTRUCTED'}")
print("-" * 85)

for i, row in df_l0.iterrows():
    c_id = int(row['cluster'])
    sw, sh, sd = row['sw'], row['sh'], row['sd']
    
    # Apply Grammar Logic to get Latent Code
    if c_id in [0, 1]: # Leg/Seat (3D -> 1D)
        latent = [round((sw + sd) / 2, 4)]
        recon = [latent[0], cluster_profiles[c_id]['sh'], latent[0]]
        type_label = "Leg/Seat"
    elif c_id == 2:    # Panel (3D -> 2D)
        latent = [round(sw, 4), round(sh, 4)]
        recon = [latent[0], latent[1], cluster_profiles[c_id]['sd']]
        type_label = "Panel"
    else:              # Joint (3D -> 1D)
        latent = [round((sw + sh + sd) / 3, 4)]
        recon = [latent[0], latent[0], latent[0]]
        type_label = "Joint"

    # Save to the new L1 structure with consistent keys
    s_data_l1["Cuboid"].append({"c": c_id, "l": latent})

    # Print the row for inspection
    orig_str = f"[{sw:.2f}, {sh:.2f}, {sd:.2f}]"
    lat_str = str(latent)
    recon_str = f"[{recon[0]:.2f}, {recon[1]:.2f}, {recon[2]:.2f}]"
    print(f"{i:<4} | {type_label:<8} | {orig_str:<20} | {lat_str:<15} | {recon_str}")

# Final Metric
print("-" * 85)
print(f"Total Nodes Processed: {len(s_data_l1['Cuboid'])}")

IDX  | TYPE     | ORIGINAL (L0)        | COMPRESSED (L1) | RECONSTRUCTED
-------------------------------------------------------------------------------------
0    | Leg/Seat | [0.68, 0.09, 0.66]   | [np.float64(0.67)] | [0.67, 0.09, 0.67]
1    | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
2    | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
3    | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
4    | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
5    | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
6    | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
7    | Joint    | [0.68, 0.14, 0.24]   | [np.float64(0.3533)] | [0.35, 0.35, 0.35]
8    | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
9    | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
10   | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
11   | Leg/Seat | [0.88, 0.19, 1.01]   | [np.float64(0.945)] | [0.94, 0.09, 0.94]
12   | Panel    | [0.88, 0.85, 0.31]   | [np.float64(0.88), np.float64(0.85)] | [0.88, 0.85, 0.11]
13   | Leg/Seat | [0.15, 0.52, 0.20]   | [np.float64(0.175)] | [0.17, 0.60, 0.17]
14   | Leg/Seat | [0.21, 0.53, 0.19]   | [np.float64(0.2)] | [0.20, 0.60, 0.20]
15   | Leg/Seat | [0.15, 0.52, 0.20]   | [np.float64(0.175)] | [0.17, 0.60, 0.17]
16   | Leg/Seat | [0.21, 0.53, 0.19]   | [np.float64(0.2)] | [0.20, 0.60, 0.20]
17   | Leg/Seat | [0.92, 0.34, 0.92]   | [np.float64(0.92)] | [0.92, 0.09, 0.92]
18   | Panel    | [0.92, 0.79, 0.49]   | [np.float64(0.92), np.float64(0.79)] | [0.92, 0.79, 0.11]
19   | Leg/Seat | [0.12, 0.42, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
20   | Leg/Seat | [0.14, 0.45, 0.13]   | [np.float64(0.135)] | [0.14, 0.60, 0.14]
21   | Leg/Seat | [0.12, 0.42, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
22   | Leg/Seat | [0.14, 0.45, 0.13]   | [np.float64(0.135)] | [0.14, 0.60, 0.14]
23   | Panel    | [0.88, 1.00, 0.10]   | [np.float64(0.88), np.float64(1.0)] | [0.88, 1.00, 0.11]
24   | Leg/Seat | [0.09, 0.52, 0.05]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
25   | Leg/Seat | [0.07, 0.63, 0.05]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
26   | Joint    | [0.69, 0.10, 0.03]   | [np.float64(0.2733)] | [0.27, 0.27, 0.27]
27   | Joint    | [0.69, 0.11, 0.03]   | [np.float64(0.2767)] | [0.28, 0.28, 0.28]
28   | Leg/Seat | [0.09, 0.52, 0.05]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
29   | Leg/Seat | [0.07, 0.63, 0.05]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
30   | Leg/Seat | [0.87, 0.16, 0.81]   | [np.float64(0.84)] | [0.84, 0.09, 0.84]
31   | Joint    | [0.09, 0.11, 0.67]   | [np.float64(0.29)] | [0.29, 0.29, 0.29]
32   | Joint    | [0.09, 0.11, 0.67]   | [np.float64(0.29)] | [0.29, 0.29, 0.29]
33   | Joint    | [0.05, 0.04, 0.40]   | [np.float64(0.1633)] | [0.16, 0.16, 0.16]
34   | Joint    | [0.06, 0.08, 0.09]   | [np.float64(0.0767)] | [0.08, 0.08, 0.08]
35   | Leg/Seat | [0.05, 0.46, 0.12]   | [np.float64(0.085)] | [0.09, 0.60, 0.09]
36   | Joint    | [0.05, 0.04, 0.40]   | [np.float64(0.1633)] | [0.16, 0.16, 0.16]
37   | Joint    | [0.06, 0.08, 0.09]   | [np.float64(0.0767)] | [0.08, 0.08, 0.08]
38   | Leg/Seat | [0.05, 0.46, 0.12]   | [np.float64(0.085)] | [0.09, 0.60, 0.09]
39   | Panel    | [0.65, 0.84, 0.11]   | [np.float64(0.65), np.float64(0.84)] | [0.65, 0.84, 0.11]
40   | Leg/Seat | [0.65, 0.18, 0.66]   | [np.float64(0.655)] | [0.66, 0.09, 0.66]
41   | Leg/Seat | [0.08, 0.50, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
42   | Leg/Seat | [0.08, 0.52, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
43   | Leg/Seat | [0.08, 0.50, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
44   | Leg/Seat | [0.08, 0.52, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
45   | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
46   | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
47   | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
48   | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
49   | Leg/Seat | [0.74, 0.16, 0.86]   | [np.float64(0.8)] | [0.80, 0.09, 0.80]
50   | Leg/Seat | [0.74, 0.05, 0.86]   | [np.float64(0.8)] | [0.80, 0.09, 0.80]
51   | Panel    | [0.68, 0.77, 0.11]   | [np.float64(0.68), np.float64(0.77)] | [0.68, 0.77, 0.11]
52   | Joint    | [0.06, 0.02, 0.04]   | [np.float64(0.04)] | [0.04, 0.04, 0.04]
53   | Joint    | [0.06, 0.02, 0.04]   | [np.float64(0.04)] | [0.04, 0.04, 0.04]
54   | Leg/Seat | [0.69, 0.14, 0.69]   | [np.float64(0.69)] | [0.69, 0.09, 0.69]
55   | Leg/Seat | [0.05, 0.79, 0.11]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
56   | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
57   | Leg/Seat | [0.05, 0.79, 0.11]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
58   | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
59   | Leg/Seat | [0.04, 0.99, 0.12]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
60   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
61   | Leg/Seat | [0.04, 0.99, 0.12]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
62   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
63   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
64   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
65   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
66   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
67   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
68   | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
69   | Leg/Seat | [0.10, 0.42, 0.13]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
70   | Leg/Seat | [0.15, 0.49, 0.13]   | [np.float64(0.14)] | [0.14, 0.60, 0.14]
71   | Leg/Seat | [0.10, 0.42, 0.13]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
72   | Leg/Seat | [0.15, 0.49, 0.13]   | [np.float64(0.14)] | [0.14, 0.60, 0.14]
73   | Leg/Seat | [0.96, 0.22, 0.85]   | [np.float64(0.905)] | [0.91, 0.09, 0.91]
74   | Panel    | [1.00, 0.08, 0.10]   | [np.float64(1.0), np.float64(0.08)] | [1.00, 0.08, 0.11]
75   | Leg/Seat | [1.05, 0.05, 0.81]   | [np.float64(0.93)] | [0.93, 0.09, 0.93]
76   | Leg/Seat | [0.99, 0.08, 0.85]   | [np.float64(0.92)] | [0.92, 0.09, 0.92]
77   | Panel    | [0.96, 1.00, 0.55]   | [np.float64(0.96), np.float64(1.0)] | [0.96, 1.00, 0.11]
78   | Leg/Seat | [1.03, 0.06, 0.55]   | [np.float64(0.79)] | [0.79, 0.09, 0.79]
79   | Leg/Seat | [0.04, 0.78, 0.41]   | [np.float64(0.225)] | [0.23, 0.60, 0.23]
80   | Joint    | [0.06, 0.06, 0.46]   | [np.float64(0.1933)] | [0.19, 0.19, 0.19]
81   | Leg/Seat | [0.05, 0.72, 0.06]   | [np.float64(0.055)] | [0.06, 0.60, 0.06]
82   | Leg/Seat | [0.04, 0.78, 0.41]   | [np.float64(0.225)] | [0.23, 0.60, 0.23]
83   | Joint    | [0.06, 0.06, 0.46]   | [np.float64(0.1933)] | [0.19, 0.19, 0.19]
84   | Leg/Seat | [0.05, 0.72, 0.06]   | [np.float64(0.055)] | [0.06, 0.60, 0.06]
85   | Leg/Seat | [0.89, 0.19, 1.01]   | [np.float64(0.95)] | [0.95, 0.09, 0.95]
86   | Panel    | [0.88, 0.86, 0.31]   | [np.float64(0.88), np.float64(0.86)] | [0.88, 0.86, 0.11]
87   | Leg/Seat | [0.15, 0.52, 0.20]   | [np.float64(0.175)] | [0.17, 0.60, 0.17]
88   | Leg/Seat | [0.20, 0.52, 0.19]   | [np.float64(0.195)] | [0.20, 0.60, 0.20]
89   | Leg/Seat | [0.15, 0.52, 0.20]   | [np.float64(0.175)] | [0.17, 0.60, 0.17]
90   | Leg/Seat | [0.20, 0.52, 0.19]   | [np.float64(0.195)] | [0.20, 0.60, 0.20]
91   | Leg/Seat | [0.92, 0.38, 0.92]   | [np.float64(0.92)] | [0.92, 0.09, 0.92]
92   | Panel    | [0.92, 0.78, 0.47]   | [np.float64(0.92), np.float64(0.78)] | [0.92, 0.78, 0.11]
93   | Leg/Seat | [0.12, 0.42, 0.11]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
94   | Leg/Seat | [0.12, 0.42, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
95   | Leg/Seat | [0.12, 0.42, 0.11]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
96   | Leg/Seat | [0.12, 0.42, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
97   | Leg/Seat | [0.68, 0.09, 0.66]   | [np.float64(0.67)] | [0.67, 0.09, 0.67]
98   | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
99   | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
100  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
101  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
102  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
103  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
104  | Joint    | [0.68, 0.14, 0.24]   | [np.float64(0.3533)] | [0.35, 0.35, 0.35]
105  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
106  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
107  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
108  | Leg/Seat | [0.08, 0.56, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
109  | Leg/Seat | [0.08, 0.55, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
110  | Leg/Seat | [0.08, 0.56, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
111  | Leg/Seat | [0.08, 0.55, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
112  | Leg/Seat | [0.89, 0.18, 0.54]   | [np.float64(0.715)] | [0.71, 0.09, 0.71]
113  | Leg/Seat | [0.95, 0.07, 0.93]   | [np.float64(0.94)] | [0.94, 0.09, 0.94]
114  | Panel    | [0.95, 0.66, 0.50]   | [np.float64(0.95), np.float64(0.66)] | [0.95, 0.66, 0.11]
115  | Leg/Seat | [0.96, 0.10, 0.56]   | [np.float64(0.76)] | [0.76, 0.09, 0.76]
116  | Leg/Seat | [0.07, 0.51, 0.49]   | [np.float64(0.28)] | [0.28, 0.60, 0.28]
117  | Joint    | [0.07, 0.09, 0.43]   | [np.float64(0.1967)] | [0.20, 0.20, 0.20]
118  | Joint    | [0.05, 0.10, 0.16]   | [np.float64(0.1033)] | [0.10, 0.10, 0.10]
119  | Joint    | [0.10, 0.24, 0.10]   | [np.float64(0.1467)] | [0.15, 0.15, 0.15]
120  | Leg/Seat | [0.07, 0.51, 0.49]   | [np.float64(0.28)] | [0.28, 0.60, 0.28]
121  | Joint    | [0.07, 0.09, 0.43]   | [np.float64(0.1967)] | [0.20, 0.20, 0.20]
122  | Joint    | [0.05, 0.10, 0.16]   | [np.float64(0.1033)] | [0.10, 0.10, 0.10]
123  | Joint    | [0.10, 0.24, 0.10]   | [np.float64(0.1467)] | [0.15, 0.15, 0.15]
124  | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
125  | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
126  | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
127  | Leg/Seat | [0.07, 0.64, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
128  | Leg/Seat | [0.75, 0.15, 0.86]   | [np.float64(0.805)] | [0.81, 0.09, 0.81]
129  | Leg/Seat | [0.74, 0.07, 0.86]   | [np.float64(0.8)] | [0.80, 0.09, 0.80]
130  | Panel    | [0.68, 0.77, 0.11]   | [np.float64(0.68), np.float64(0.77)] | [0.68, 0.77, 0.11]
131  | Joint    | [0.06, 0.03, 0.04]   | [np.float64(0.0433)] | [0.04, 0.04, 0.04]
132  | Joint    | [0.06, 0.03, 0.04]   | [np.float64(0.0433)] | [0.04, 0.04, 0.04]
133  | Leg/Seat | [0.69, 0.14, 0.69]   | [np.float64(0.69)] | [0.69, 0.09, 0.69]
134  | Leg/Seat | [0.03, 0.79, 0.10]   | [np.float64(0.065)] | [0.07, 0.60, 0.07]
135  | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
136  | Leg/Seat | [0.03, 0.79, 0.10]   | [np.float64(0.065)] | [0.07, 0.60, 0.07]
137  | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
138  | Leg/Seat | [0.03, 1.00, 0.12]   | [np.float64(0.075)] | [0.07, 0.60, 0.07]
139  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
140  | Leg/Seat | [0.03, 1.00, 0.12]   | [np.float64(0.075)] | [0.07, 0.60, 0.07]
141  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
142  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
143  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
144  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
145  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
146  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
147  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
148  | Panel    | [0.65, 0.83, 0.11]   | [np.float64(0.65), np.float64(0.83)] | [0.65, 0.83, 0.11]
149  | Leg/Seat | [0.65, 0.17, 0.66]   | [np.float64(0.655)] | [0.66, 0.09, 0.66]
150  | Leg/Seat | [0.08, 0.51, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
151  | Leg/Seat | [0.08, 0.55, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
152  | Leg/Seat | [0.08, 0.51, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
153  | Leg/Seat | [0.08, 0.55, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
154  | Leg/Seat | [0.68, 0.09, 0.66]   | [np.float64(0.67)] | [0.67, 0.09, 0.67]
155  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
156  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
157  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
158  | Leg/Seat | [0.06, 0.60, 0.06]   | [np.float64(0.06)] | [0.06, 0.60, 0.06]
159  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
160  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
161  | Joint    | [0.68, 0.14, 0.24]   | [np.float64(0.3533)] | [0.35, 0.35, 0.35]
162  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
163  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
164  | Leg/Seat | [0.08, 0.79, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
165  | Leg/Seat | [0.89, 0.18, 1.01]   | [np.float64(0.95)] | [0.95, 0.09, 0.95]
166  | Panel    | [0.88, 0.86, 0.31]   | [np.float64(0.88), np.float64(0.86)] | [0.88, 0.86, 0.11]
167  | Leg/Seat | [0.16, 0.53, 0.20]   | [np.float64(0.18)] | [0.18, 0.60, 0.18]
168  | Leg/Seat | [0.21, 0.51, 0.19]   | [np.float64(0.2)] | [0.20, 0.60, 0.20]
169  | Leg/Seat | [0.16, 0.53, 0.20]   | [np.float64(0.18)] | [0.18, 0.60, 0.18]
170  | Leg/Seat | [0.21, 0.51, 0.19]   | [np.float64(0.2)] | [0.20, 0.60, 0.20]
171  | Leg/Seat | [0.10, 0.42, 0.13]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
172  | Leg/Seat | [0.15, 0.49, 0.13]   | [np.float64(0.14)] | [0.14, 0.60, 0.14]
173  | Leg/Seat | [0.10, 0.42, 0.13]   | [np.float64(0.115)] | [0.12, 0.60, 0.12]
174  | Leg/Seat | [0.15, 0.49, 0.13]   | [np.float64(0.14)] | [0.14, 0.60, 0.14]
175  | Leg/Seat | [0.96, 0.22, 0.85]   | [np.float64(0.905)] | [0.91, 0.09, 0.91]
176  | Panel    | [1.00, 0.10, 0.10]   | [np.float64(1.0), np.float64(0.1)] | [1.00, 0.10, 0.11]
177  | Leg/Seat | [1.05, 0.05, 0.81]   | [np.float64(0.93)] | [0.93, 0.09, 0.93]
178  | Leg/Seat | [0.98, 0.09, 0.85]   | [np.float64(0.915)] | [0.92, 0.09, 0.92]
179  | Panel    | [0.92, 0.94, 0.44]   | [np.float64(0.92), np.float64(0.94)] | [0.92, 0.94, 0.11]
180  | Leg/Seat | [0.98, 0.06, 0.47]   | [np.float64(0.725)] | [0.72, 0.09, 0.72]
181  | Leg/Seat | [0.04, 0.90, 0.48]   | [np.float64(0.26)] | [0.26, 0.60, 0.26]
182  | Joint    | [0.06, 0.06, 0.56]   | [np.float64(0.2267)] | [0.23, 0.23, 0.23]
183  | Leg/Seat | [0.05, 0.74, 0.06]   | [np.float64(0.055)] | [0.06, 0.60, 0.06]
184  | Leg/Seat | [0.04, 0.90, 0.48]   | [np.float64(0.26)] | [0.26, 0.60, 0.26]
185  | Joint    | [0.06, 0.06, 0.56]   | [np.float64(0.2267)] | [0.23, 0.23, 0.23]
186  | Leg/Seat | [0.05, 0.74, 0.06]   | [np.float64(0.055)] | [0.06, 0.60, 0.06]
187  | Leg/Seat | [0.08, 0.56, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
188  | Leg/Seat | [0.08, 0.55, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
189  | Leg/Seat | [0.08, 0.56, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
190  | Leg/Seat | [0.08, 0.55, 0.08]   | [np.float64(0.08)] | [0.08, 0.60, 0.08]
191  | Leg/Seat | [0.89, 0.18, 0.63]   | [np.float64(0.76)] | [0.76, 0.09, 0.76]
192  | Leg/Seat | [0.95, 0.07, 0.93]   | [np.float64(0.94)] | [0.94, 0.09, 0.94]
193  | Panel    | [0.93, 0.66, 0.42]   | [np.float64(0.93), np.float64(0.66)] | [0.93, 0.66, 0.11]
194  | Leg/Seat | [0.95, 0.10, 0.45]   | [np.float64(0.7)] | [0.70, 0.09, 0.70]
195  | Leg/Seat | [0.08, 0.57, 0.56]   | [np.float64(0.32)] | [0.32, 0.60, 0.32]
196  | Joint    | [0.07, 0.10, 0.38]   | [np.float64(0.1833)] | [0.18, 0.18, 0.18]
197  | Joint    | [0.05, 0.14, 0.09]   | [np.float64(0.0933)] | [0.09, 0.09, 0.09]
198  | Joint    | [0.10, 0.24, 0.10]   | [np.float64(0.1467)] | [0.15, 0.15, 0.15]
199  | Leg/Seat | [0.08, 0.57, 0.56]   | [np.float64(0.32)] | [0.32, 0.60, 0.32]
200  | Joint    | [0.07, 0.10, 0.38]   | [np.float64(0.1833)] | [0.18, 0.18, 0.18]
201  | Joint    | [0.05, 0.14, 0.09]   | [np.float64(0.0933)] | [0.09, 0.09, 0.09]
202  | Joint    | [0.10, 0.24, 0.10]   | [np.float64(0.1467)] | [0.15, 0.15, 0.15]
203  | Panel    | [0.65, 0.84, 0.12]   | [np.float64(0.65), np.float64(0.84)] | [0.65, 0.84, 0.11]
204  | Leg/Seat | [0.66, 0.18, 0.66]   | [np.float64(0.66)] | [0.66, 0.09, 0.66]
205  | Leg/Seat | [0.08, 0.49, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
206  | Leg/Seat | [0.08, 0.53, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
207  | Leg/Seat | [0.08, 0.49, 0.43]   | [np.float64(0.255)] | [0.26, 0.60, 0.26]
208  | Leg/Seat | [0.08, 0.53, 0.42]   | [np.float64(0.25)] | [0.25, 0.60, 0.25]
209  | Leg/Seat | [0.92, 0.36, 0.92]   | [np.float64(0.92)] | [0.92, 0.09, 0.92]
210  | Panel    | [0.92, 0.78, 0.48]   | [np.float64(0.92), np.float64(0.78)] | [0.92, 0.78, 0.11]
211  | Leg/Seat | [0.12, 0.44, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
212  | Leg/Seat | [0.12, 0.42, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
213  | Leg/Seat | [0.12, 0.44, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
214  | Leg/Seat | [0.12, 0.44, 0.12]   | [np.float64(0.12)] | [0.12, 0.60, 0.12]
215  | Leg/Seat | [0.07, 0.62, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
216  | Leg/Seat | [0.07, 0.63, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
217  | Leg/Seat | [0.07, 0.62, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
218  | Leg/Seat | [0.07, 0.63, 0.07]   | [np.float64(0.07)] | [0.07, 0.60, 0.07]
219  | Leg/Seat | [0.74, 0.14, 0.86]   | [np.float64(0.8)] | [0.80, 0.09, 0.80]
220  | Leg/Seat | [0.74, 0.07, 0.86]   | [np.float64(0.8)] | [0.80, 0.09, 0.80]
221  | Panel    | [0.68, 0.77, 0.11]   | [np.float64(0.68), np.float64(0.77)] | [0.68, 0.77, 0.11]
222  | Joint    | [0.06, 0.03, 0.04]   | [np.float64(0.0433)] | [0.04, 0.04, 0.04]
223  | Joint    | [0.06, 0.03, 0.04]   | [np.float64(0.0433)] | [0.04, 0.04, 0.04]
224  | Leg/Seat | [0.69, 0.14, 0.69]   | [np.float64(0.69)] | [0.69, 0.09, 0.69]
225  | Leg/Seat | [0.03, 0.88, 0.12]   | [np.float64(0.075)] | [0.07, 0.60, 0.07]
226  | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
227  | Leg/Seat | [0.03, 0.88, 0.12]   | [np.float64(0.075)] | [0.07, 0.60, 0.07]
228  | Leg/Seat | [0.03, 0.70, 0.03]   | [np.float64(0.03)] | [0.03, 0.60, 0.03]
229  | Leg/Seat | [0.03, 0.98, 0.10]   | [np.float64(0.065)] | [0.07, 0.60, 0.07]
230  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
231  | Leg/Seat | [0.03, 0.98, 0.10]   | [np.float64(0.065)] | [0.07, 0.60, 0.07]
232  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
233  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
234  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
235  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
236  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
237  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]
238  | Joint    | [0.62, 0.01, 0.10]   | [np.float64(0.2433)] | [0.24, 0.24, 0.24]

In [67]:
class SymbolicPartProgram:
    def __init__(self, cluster_id, grammar_rules):
        self.cluster_id = cluster_id
        self.rules = grammar_rules
        self.target_vars = ['sw', 'sh', 'sd']
        
        # 1. Identify which variables are actually "Free" (Latent)
        # A variable is latent if it has no rule OR if the rules are circular
        self.latent_vars = []
        for v in self.target_vars:
            if v not in self.rules:
                self.latent_vars.append(v)
        
        # If the grammar is circular (sw=sd, sd=sw), we must pick one to be latent
        if not self.latent_vars:
            # Default to the first variable in alphabetical order if all are ruled
            self.latent_vars = [min(self.rules.keys())]

    def compress(self, l0_row):
        return [l0_row[v] for v in self.latent_vars]

    def decompress(self, latent_code):
        # Start with latent values
        recon = {var: val for var, val in zip(self.latent_vars, latent_code)}
        
        # We iterate multiple times to resolve dependencies (Simple fixed-point iteration)
        for _ in range(3): 
            for var in self.target_vars:
                if var in recon: continue # Already solved
                if var not in self.rules: continue # No rule to apply
                
                rule = self.rules[var]
                
                # Case 1: Constant (e.g., '0.6')
                try:
                    recon[var] = float(rule)
                    continue
                except ValueError:
                    pass
                
                # Case 2: Direct Alias (e.g., 'sd')
                if rule in recon:
                    recon[var] = recon[rule]
                    continue
                
                # Case 3: Binary Operation (e.g., 'Add(sd, 0.5)')
                if 'Add' in str(rule):
                    parts = rule.split('(')[1].split(')')[0].split(', ')
                    a_name, b_val = parts[0], float(parts[1])
                    if a_name in recon:
                        recon[var] = recon[a_name] + b_val
        
        # Final safety check: if something didn't resolve, use a default 0.05
        return [recon.get(v, 0.05) for v in ['sw', 'sh', 'sd']]

# --- RE-RUN THE AUTO-PIPELINE ---
part_library = {c_id: SymbolicPartProgram(c_id, rules) for c_id, rules in final_grammar.items()}
s_data_l1 = {"Cuboid": []}
reconstructed_l0 = []

for i, row in df_l0.iterrows():
    c_id = int(row['cluster'])
    prog = part_library[c_id]
    
    latent = prog.compress(row)
    s_data_l1["Cuboid"].append({"c": c_id, "l": latent})
    
    recon = prog.decompress(latent)
    reconstructed_l0.append(recon)

print("✅ Automated Abstraction Successful!")

✅ Automated Abstraction Successful!

In [68]:
reconstructed_l0

[[np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.05, 0.05, np.float64(0.24)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(1.01), 0.09, np.float64(1.01)],
 [0.61, np.float64(0.85), 0.11],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.92), 0.09, np.float64(0.92)],
 [0.61, np.float64(0.79), 0.11],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [0.61, np.float64(1.0), 0.11],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [0.05, 0.05, np.float64(0.03)],
 [0.05, 0.05, np.float64(0.03)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.81), 0.09, np.float64(0.81)],
 [0.05, 0.05, np.float64(0.67)],
 [0.05, 0.05, np.float64(0.67)],
 [0.05, 0.05, np.float64(0.4)],
 [0.05, 0.05, np.float64(0.09)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.05, 0.05, np.float64(0.4)],
 [0.05, 0.05, np.float64(0.09)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.61, np.float64(0.84), 0.11],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [0.61, np.float64(0.77), 0.11],
 [0.05, 0.05, np.float64(0.04)],
 [0.05, 0.05, np.float64(0.04)],
 [np.float64(0.69), 0.09, np.float64(0.69)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(0.08), 0.11],
 [np.float64(0.81), 0.09, np.float64(0.81)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(1.0), 0.11],
 [np.float64(0.55), 0.09, np.float64(0.55)],
 [np.float64(0.41), 0.6, np.float64(0.41)],
 [0.05, 0.05, np.float64(0.46)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.41), 0.6, np.float64(0.41)],
 [0.05, 0.05, np.float64(0.46)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(1.01), 0.09, np.float64(1.01)],
 [0.61, np.float64(0.86), 0.11],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.92), 0.09, np.float64(0.92)],
 [0.61, np.float64(0.78), 0.11],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.05, 0.05, np.float64(0.24)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.54), 0.09, np.float64(0.54)],
 [np.float64(0.93), 0.09, np.float64(0.93)],
 [0.61, np.float64(0.66), 0.11],
 [np.float64(0.56), 0.09, np.float64(0.56)],
 [np.float64(0.49), 0.6, np.float64(0.49)],
 [0.05, 0.05, np.float64(0.43)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.49), 0.6, np.float64(0.49)],
 [0.05, 0.05, np.float64(0.43)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [0.61, np.float64(0.77), 0.11],
 [0.05, 0.05, np.float64(0.04)],
 [0.05, 0.05, np.float64(0.04)],
 [np.float64(0.69), 0.09, np.float64(0.69)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.61, np.float64(0.83), 0.11],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.05, 0.05, np.float64(0.24)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(1.01), 0.09, np.float64(1.01)],
 [0.61, np.float64(0.86), 0.11],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(0.1), 0.11],
 [np.float64(0.81), 0.09, np.float64(0.81)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(0.94), 0.11],
 [np.float64(0.47), 0.09, np.float64(0.47)],
 [np.float64(0.48), 0.6, np.float64(0.48)],
 [0.05, 0.05, np.float64(0.56)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.48), 0.6, np.float64(0.48)],
 [0.05, 0.05, np.float64(0.56)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.63), 0.09, np.float64(0.63)],
 [np.float64(0.93), 0.09, np.float64(0.93)],
 [0.61, np.float64(0.66), 0.11],
 [np.float64(0.45), 0.09, np.float64(0.45)],
 [np.float64(0.56), 0.6, np.float64(0.56)],
 [0.05, 0.05, np.float64(0.38)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.56), 0.6, np.float64(0.56)],
 [0.05, 0.05, np.float64(0.38)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.1)],
 [0.61, np.float64(0.84), 0.11],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.43), 0.6, np.float64(0.43)],
 [np.float64(0.42), 0.6, np.float64(0.42)],
 [np.float64(0.92), 0.09, np.float64(0.92)],
 [0.61, np.float64(0.78), 0.11],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [0.61, np.float64(0.77), 0.11],
 [0.05, 0.05, np.float64(0.04)],
 [0.05, 0.05, np.float64(0.04)],
 [np.float64(0.69), 0.09, np.float64(0.69)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(1.31), 0.09, np.float64(1.31)],
 [0.61, np.float64(0.5), 0.11],
 [np.float64(0.95), 0.09, np.float64(0.95)],
 [np.float64(0.95), 0.09, np.float64(0.95)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.16)],
 [0.61, np.float64(0.73), 0.11],
 [np.float64(0.62), 0.09, np.float64(0.62)],
 [np.float64(0.62), 0.09, np.float64(0.62)],
 [0.05, 0.05, np.float64(0.62)],
 [0.05, 0.05, np.float64(0.62)],
 [0.61, np.float64(0.44), 0.11],
 [np.float64(0.62), 0.09, np.float64(0.62)],
 [np.float64(1.01), 0.09, np.float64(1.01)],
 [0.61, np.float64(0.85), 0.11],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.2), 0.6, np.float64(0.2)],
 [np.float64(0.19), 0.6, np.float64(0.19)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.5), 0.09, np.float64(0.5)],
 [np.float64(0.93), 0.09, np.float64(0.93)],
 [0.61, np.float64(0.66), 0.11],
 [np.float64(0.64), 0.09, np.float64(0.64)],
 [np.float64(0.4), 0.6, np.float64(0.4)],
 [0.05, 0.05, np.float64(0.38)],
 [np.float64(0.15), 0.6, np.float64(0.15)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(0.4), 0.6, np.float64(0.4)],
 [0.05, 0.05, np.float64(0.38)],
 [np.float64(0.15), 0.6, np.float64(0.15)],
 [0.05, 0.05, np.float64(0.1)],
 [np.float64(1.07), 0.09, np.float64(1.07)],
 [np.float64(0.71), 0.09, np.float64(0.71)],
 [0.05, 0.05, np.float64(0.06)],
 [0.05, 0.05, np.float64(0.69)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [0.05, 0.05, np.float64(0.86)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.03), 0.6, np.float64(0.03)],
 [0.05, 0.05, np.float64(0.86)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.59), 0.09, np.float64(0.59)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.06)],
 [np.float64(0.09), 0.6, np.float64(0.09)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [0.05, 0.05, np.float64(0.39)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [0.05, 0.05, np.float64(0.39)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.09), 0.6, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.09)],
 [np.float64(0.09), 0.6, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.09)],
 [np.float64(1.18), 0.09, np.float64(1.18)],
 [0.61, np.float64(1.01), 0.11],
 [np.float64(1.34), 0.09, np.float64(1.34)],
 [np.float64(1.34), 0.09, np.float64(1.34)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.09)],
 [0.05, 0.05, np.float64(0.09)],
 [np.float64(1.14), 0.09, np.float64(1.14)],
 [0.61, np.float64(1.01), 0.11],
 [np.float64(1.34), 0.09, np.float64(1.34)],
 [np.float64(1.34), 0.09, np.float64(1.34)],
 [np.float64(1.18), 0.09, np.float64(1.18)],
 [np.float64(1.23), 0.09, np.float64(1.23)],
 [np.float64(1.23), 0.09, np.float64(1.23)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.93), 0.09, np.float64(0.93)],
 [np.float64(0.94), 0.09, np.float64(0.94)],
 [0.61, np.float64(0.69), 0.11],
 [0.61, np.float64(0.82), 0.11],
 [0.05, 0.05, np.float64(0.04)],
 [0.05, 0.05, np.float64(0.04)],
 [0.05, 0.05, np.float64(0.83)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [0.05, 0.05, np.float64(0.83)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.73), 0.09, np.float64(0.73)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [0.61, np.float64(0.17), 0.11],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.72), 0.09, np.float64(0.72)],
 [0.61, np.float64(1.0), 0.11],
 [np.float64(0.15), 0.6, np.float64(0.15)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.15), 0.6, np.float64(0.15)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.05, 0.05, np.float64(0.24)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.96), 0.09, np.float64(0.96)],
 [np.float64(0.96), 0.09, np.float64(0.96)],
 [0.05, 0.05, np.float64(0.32)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.32)],
 [0.05, 0.05, np.float64(0.16)],
 [np.float64(0.95), 0.09, np.float64(0.95)],
 [np.float64(1.33), 0.09, np.float64(1.33)],
 [0.61, np.float64(0.41), 0.11],
 [0.61, np.float64(0.43), 0.11],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.13), 0.6, np.float64(0.13)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(0.11), 0.11],
 [np.float64(0.81), 0.09, np.float64(0.81)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [0.61, np.float64(0.94), 0.11],
 [np.float64(0.47), 0.09, np.float64(0.47)],
 [np.float64(0.48), 0.6, np.float64(0.48)],
 [0.05, 0.05, np.float64(0.53)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.48), 0.6, np.float64(0.48)],
 [0.05, 0.05, np.float64(0.53)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.75), 0.09, np.float64(0.75)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [0.61, np.float64(0.79), 0.11],
 [0.05, 0.05, np.float64(0.28)],
 [0.05, 0.05, np.float64(0.65)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [0.05, 0.05, np.float64(0.79)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.09), 0.6, np.float64(0.09)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.09), 0.6, np.float64(0.09)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [0.61, np.float64(0.09), 0.11],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.56), 0.09, np.float64(0.56)],
 [0.61, np.float64(1.23), 0.11],
 [np.float64(0.14), 0.6, np.float64(0.14)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.15), 0.6, np.float64(0.15)],
 [np.float64(0.12), 0.6, np.float64(0.12)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [0.05, 0.05, np.float64(0.32)],
 [0.05, 0.05, np.float64(0.16)],
 [0.05, 0.05, np.float64(0.32)],
 [0.05, 0.05, np.float64(0.16)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [np.float64(0.86), 0.09, np.float64(0.86)],
 [0.61, np.float64(0.41), 0.11],
 [0.61, np.float64(0.86), 0.11],
 [np.float64(1.0), 0.09, np.float64(1.0)],
 [0.61, np.float64(0.92), 0.11],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.85), 0.09, np.float64(0.85)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.04), 0.6, np.float64(0.04)],
 [np.float64(0.04), 0.6, np.float64(0.04)],
 [0.61, np.float64(0.09), 0.11],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.07), 0.6, np.float64(0.07)],
 [np.float64(0.04), 0.6, np.float64(0.04)],
 [np.float64(0.04), 0.6, np.float64(0.04)],
 [np.float64(0.04), 0.6, np.float64(0.04)],
 [np.float64(0.89), 0.09, np.float64(0.89)],
 [0.61, np.float64(1.04), 0.11],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.11), 0.6, np.float64(0.11)],
 [np.float64(0.76), 0.09, np.float64(0.76)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.61, np.float64(0.22), 0.11],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.83), 0.09, np.float64(0.83)],
 [0.61, np.float64(0.79), 0.11],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.1), 0.6, np.float64(0.1)],
 [np.float64(0.87), 0.09, np.float64(0.87)],
 [0.61, np.float64(0.97), 0.11],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [0.05, 0.05, np.float64(0.7)],
 [0.05, 0.05, np.float64(0.7)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [0.05, 0.05, np.float64(0.7)],
 [0.05, 0.05, np.float64(0.7)],
 [np.float64(0.05), 0.6, np.float64(0.05)],
 [np.float64(0.66), 0.09, np.float64(0.66)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.06), 0.6, np.float64(0.06)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [0.05, 0.05, np.float64(0.24)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],
 [np.float64(0.08), 0.6, np.float64(0.08)],

In [69]:
import pandas as pd

# Create a summary dataframe for clear comparison
summary_data = []

for i in range(len(df_l0)):
    # Original L0
    orig = df_l0.iloc[i]
    
    # Compressed L1 (from our automated s_data_l1)
    l1_node = s_data_l1["Cuboid"][i]
    
    # Reconstructed L0
    recon = reconstructed_l0[i]
    
    summary_data.append({
        "ID": i,
        "Cluster": l1_node["c"],
        "Original [sw, sh, sd]": [round(orig['sw'], 3), round(orig['sh'], 3), round(orig['sd'], 3)],
        "Latent Code": l1_node["l"],
        "Reconstructed": [round(recon[0], 3), round(recon[1], 3), round(recon[2], 3)],
        "Dimensions Saved": 3 - len(l1_node["l"])
    })

df_summary = pd.DataFrame(summary_data)

# Display a slice of the table covering different clusters
print(f"{'IDX':<5} | {'TYPE':<10} | {'ORIGINAL':<22} | {'LATENT':<12} | {'RECONSTRUCTED'}")
print("-" * 85)
# Show a representative sample (first few nodes)
for idx, row in df_summary.head(15).iterrows():
    c_id = row['Cluster']
    type_map = {0: "Leg", 1: "Seat", 2: "Back", 3: "Joint"}
    label = type_map.get(c_id, f"C_{c_id}")
    
    print(f"{row['ID']:<5} | {label:<10} | {str(row['Original [sw, sh, sd]']):<22} | {str(row['Latent Code']):<12} | {str(row['Reconstructed'])}")

# Final Stats
total_params_l0 = len(df_l0) * 3
total_params_l1 = sum(len(node["l"]) for node in s_data_l1["Cuboid"])
compression_ratio = (1 - (total_params_l1 / total_params_l0)) * 100

print("-" * 85)
print(f"Total Parameters L0: {total_params_l0}")
print(f"Total Parameters L1: {total_params_l1}")
print(f"Overall Parameter Reduction: {compression_ratio:.2f}%")

IDX   | TYPE       | ORIGINAL               | LATENT       | RECONSTRUCTED
-------------------------------------------------------------------------------------
0     | Seat       | [np.float64(0.68), np.float64(0.09), np.float64(0.66)] | [np.float64(0.66)] | [np.float64(0.66), 0.09, np.float64(0.66)]
1     | Leg        | [np.float64(0.06), np.float64(0.6), np.float64(0.06)] | [np.float64(0.06)] | [np.float64(0.06), 0.6, np.float64(0.06)]
2     | Leg        | [np.float64(0.06), np.float64(0.6), np.float64(0.06)] | [np.float64(0.06)] | [np.float64(0.06), 0.6, np.float64(0.06)]
3     | Leg        | [np.float64(0.06), np.float64(0.6), np.float64(0.06)] | [np.float64(0.06)] | [np.float64(0.06), 0.6, np.float64(0.06)]
4     | Leg        | [np.float64(0.06), np.float64(0.6), np.float64(0.06)] | [np.float64(0.06)] | [np.float64(0.06), 0.6, np.float64(0.06)]
5     | Leg        | [np.float64(0.08), np.float64(0.79), np.float64(0.08)] | [np.float64(0.08)] | [np.float64(0.08), 0.6, np.float64(0.08)]
6     | Leg        | [np.float64(0.08), np.float64(0.79), np.float64(0.08)] | [np.float64(0.08)] | [np.float64(0.08), 0.6, np.float64(0.08)]
7     | Joint      | [np.float64(0.68), np.float64(0.14), np.float64(0.24)] | [np.float64(0.24)] | [0.05, 0.05, np.float64(0.24)]
8     | Leg        | [np.float64(0.08), np.float64(0.79), np.float64(0.08)] | [np.float64(0.08)] | [np.float64(0.08), 0.6, np.float64(0.08)]
9     | Leg        | [np.float64(0.08), np.float64(0.79), np.float64(0.08)] | [np.float64(0.08)] | [np.float64(0.08), 0.6, np.float64(0.08)]
10    | Leg        | [np.float64(0.08), np.float64(0.79), np.float64(0.08)] | [np.float64(0.08)] | [np.float64(0.08), 0.6, np.float64(0.08)]
11    | Seat       | [np.float64(0.88), np.float64(0.19), np.float64(1.01)] | [np.float64(1.01)] | [np.float64(1.01), 0.09, np.float64(1.01)]
12    | Back       | [np.float64(0.88), np.float64(0.85), np.float64(0.31)] | [np.float64(0.85)] | [0.61, np.float64(0.85), 0.11]
13    | Leg        | [np.float64(0.15), np.float64(0.52), np.float64(0.2)] | [np.float64(0.2)] | [np.float64(0.2), 0.6, np.float64(0.2)]
14    | Leg        | [np.float64(0.21), np.float64(0.53), np.float64(0.19)] | [np.float64(0.19)] | [np.float64(0.19), 0.6, np.float64(0.19)]
-------------------------------------------------------------------------------------
Total Parameters L0: 30804
Total Parameters L1: 10268
Overall Parameter Reduction: 66.67%