In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
## 1. Setup Paths & Configuration

import sys
import os
from pathlib import Path

# Add source directory to path
current_path = Path.cwd()
base_project_dir = current_path.parent
src_dir = base_project_dir / "src"

if str(src_dir) not in sys.path:
    sys.path.append(str(src_dir))

# Define key directories
dataset_directory = src_dir / "abstractionsshapecoder" / "dataset"
saved_directory = src_dir / "abstractionsshapecoder" / "saved"

# --- AE Model Paths ---
saved_models_L1_AE_dir = saved_directory / "models_L1_AE"
saved_models_L2_AE_dir = saved_directory / "models_L2_AE"
saved_models_L1_AE_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_AE_dir.mkdir(parents=True, exist_ok=True)

# --- PCA Model Paths ---
saved_models_L1_PCA_dir = saved_directory / "models_L1_PCA"
saved_models_L2_PCA_dir = saved_directory / "models_L2_PCA"
saved_models_L1_PCA_dir.mkdir(parents=True, exist_ok=True)
saved_models_L2_PCA_dir.mkdir(parents=True, exist_ok=True)

print(f"Base project directory: {base_project_dir}")
print(f"Source directory: {src_dir}")
print(f"L1 AE Models directory: {saved_models_L1_AE_dir}")
print(f"L2 AE Models directory: {saved_models_L2_AE_dir}")
print(f"L1 PCA Models directory: {saved_models_L1_PCA_dir}")
print(f"L2 PCA Models directory: {saved_models_L2_PCA_dir}")

Base project directory: c:\Users\Amogh\abstraction-discovery
Source directory: c:\Users\Amogh\abstraction-discovery\src
L1 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_AE
L2 AE Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_AE
L1 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L1_PCA
L2 PCA Models directory: c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\models_L2_PCA

In [4]:
import pickle
from pathlib import Path
from abstractionsshapecoder.debug_utils import debug_info, debug_success, debug_error

def load_processed_datasets():
    """
    Loads all hierarchical datasets (L0, L1-VAE, L1-AE, L2-AE) from the saved directory.
    """
    SAVED_DIR = Path.cwd().parent / "src" / "abstractionsshapecoder" / "saved"
    
    # Define file map: {Variable_Name: Filename}
    dataset_files = {
        "shapes_l0": "all_dsl_shapes.pkl",
        "shapes_l1_vae": "all_abstracted_shapes_L1_VAE.pkl",
        "shapes_l1_ae": "all_abstracted_shapes_L1_AE.pkl",
        "shapes_l2_ae": "all_abstracted_shapes_L2_AE.pkl"
    }
    
    loaded_datasets = {}
    
    for var_name, filename in dataset_files.items():
        file_path = SAVED_DIR / filename
        if file_path.exists():
            debug_info(f"Loading {var_name} from {filename}...")
            with open(file_path, "rb") as f:
                loaded_datasets[var_name] = pickle.load(f)
            debug_success(f"Successfully loaded {len(loaded_datasets[var_name])} shapes into {var_name}.")
        else:
            debug_error(f"Missing file: {filename}. Ensure previous training cells were run.")
            loaded_datasets[var_name] = {}
            
    return loaded_datasets

# Execute the load
datasets = load_processed_datasets()

# Extract into global namespace for easier access in subsequent cells
shapes_l0 = datasets.get("shapes_l0")

[INFO] Loading shapes_l0 from all_dsl_shapes.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l0.
[INFO] Loading shapes_l1_vae from all_abstracted_shapes_L1_VAE.pkl...
[SUCCESS] Successfully loaded 1100 shapes into shapes_l1_vae.
[ERROR] Missing file: all_abstracted_shapes_L1_AE.pkl. Ensure previous training cells were run.
[ERROR] Missing file: all_abstracted_shapes_L2_AE.pkl. Ensure previous training cells were run.

In [5]:
shapes_l0["172_0_0"]

{'dsl': <abstractionsshapecoder.dsl_nodes.Union at 0x219f40ee900>,
 'singleton_params': {'Cuboid': [[0.68, 0.09, 0.66],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.68, 0.14, 0.24],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08]],
  'Translate': [[-0.0, -0.17, 0.0],
   [-0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [0.31, -0.51, 0.3],
   [-0.26, 0.27, -0.18],
   [-0.14, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.0, 0.27, -0.25],
   [0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25]]},
 'pair_params': {'Translate(Cuboid)': [[-0.0, -0.17, 0.0, 0.68, 0.09, 0.66],
   [-0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [-0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [-0.26, 0.27, -0.18, 0.08, 0.79, 0.08],
   [-0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.0, 0.74, -0.22, 0.68, 0.14, 0.24],
   [-0.0, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.28, 0.27, -0.25, 0.08, 0.79, 0.08]],
  'Union(Translate)': [[0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25],
   [-0.0, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.14, 0.27, -0.25],
   [-0.26, 0.27, -0.18],
   [0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [-0.31, -0.51, -0.17],
   [-0.0, -0.17, 0.0]]},
 'program_text': 'Union(Move(Cuboid(0.68,0.09,0.66),-0.0,-0.17,0.0),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),-0.31,-0.51,0.3),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,-0.17),Union(Move(Cuboid(0.06,0.6,0.06),0.31,-0.51,0.3),Union(Move(Cuboid(0.08,0.79,0.08),-0.26,0.27,-0.18),Union(Move(Cuboid(0.08,0.79,0.08),-0.14,0.27,-0.25),Union(Move(Cuboid(0.68,0.14,0.24),0.0,0.74,-0.22),Union(Move(Cuboid(0.08,0.79,0.08),-0.0,0.27,-0.25),Union(Move(Cuboid(0.08,0.79,0.08),0.14,0.27,-0.25),Move(Cuboid(0.08,0.79,0.08),0.28,0.27,-0.25)))))))))))'}

In [ ]:
shapes_l0["172_0_0"]["dsl"]

In [8]:
print(shapes_l0["172_0_0"]["dsl"])

Union(
    Translate(vec=[-0.000, -0.170, 0.000])
        Cuboid(size=[0.680, 0.090, 0.660]),
    Union(
        Translate(vec=[-0.310, -0.510, -0.170])
            Cuboid(size=[0.060, 0.600, 0.060]),
        Union(
            Translate(vec=[-0.310, -0.510, 0.300])
                Cuboid(size=[0.060, 0.600, 0.060]),
            Union(
                Translate(vec=[0.310, -0.510, -0.170])
                    Cuboid(size=[0.060, 0.600, 0.060]),
                Union(
                    Translate(vec=[0.310, -0.510, 0.300])
                        Cuboid(size=[0.060, 0.600, 0.060]),
                    Union(
                        Translate(vec=[-0.260, 0.270, -0.180])
                            Cuboid(size=[0.080, 0.790, 0.080]),
                        Union(
                            Translate(vec=[-0.140, 0.270, -0.250])
                                Cuboid(size=[0.080, 0.790, 0.080]),
                            Union(
                                Translate(vec=[0.000, 0.740, -0.220])
                                    Cuboid(size=[0.680, 0.140, 0.240]),
                                Union(
                                    Translate(vec=[-0.000, 0.270, -0.250])
                                        Cuboid(size=[0.080, 0.790, 0.080]),
                                    Union(
                                        Translate(vec=[0.140, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080]),
                                        Translate(vec=[0.280, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080])
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)

In [11]:
import numpy as np
from abstractionsshapecoder.dsl_nodes import Union, Translate, Rotate, Cuboid

class DSLRefactorer:
    def __init__(self, threshold=0.01):
        self.threshold = threshold

    def is_near(self, a, b):
        """Helper to handle the 'abs:0.01' logic."""
        return np.all(np.abs(np.array(a) - np.array(b)) <= self.threshold)

    def refactor(self, node):
        """Main recursive entry point."""
        
        # 1. Recurse down first (Bottom-up transformation)
        if isinstance(node, Union):
            node.left = self.refactor(node.left)
            node.right = self.refactor(node.right)
        elif isinstance(node, (Translate, Rotate)):
            node.child = self.refactor(node.child)

        # 2. Apply "Simplification" Rules
        
        # RULE: s3dl_zero_mov -> Remove translations of [0,0,0]
        if isinstance(node, Translate):
            if self.is_near(node.vector, [0, 0, 0]):
                return node.child

        # RULE: s3dl_move_comb -> Combine nested translations
        if isinstance(node, Translate) and isinstance(node.child, Translate):
            new_vec = node.vector + node.child.vector
            return Translate(node.child.child, new_vec)

        # RULE: s3dl_move_over_union_fwd -> Factoring out common moves
        if isinstance(node, Union):
            if isinstance(node.left, Translate) and isinstance(node.right, Translate):
                if self.is_near(node.left.vector, node.right.vector):
                    new_inner_union = Union(node.left.child, node.right.child)
                    return Translate(new_inner_union, node.left.vector)

        # RULE: s3dl_sym_x_def -> Symmetry Detection (X-axis)
        # Looking for Union(Translate(X), Translate(-X)) where children match
        if isinstance(node, Union):
            res = self._check_symmetry(node)
            if res: return res

        return node

    def _check_symmetry(self, node):
        """Detects if two branches are mirrored across an axis."""
        L, R = node.left, node.right
        if isinstance(L, Translate) and isinstance(R, Translate):
            # Check if sizes of children (Cuboids) match
            if isinstance(L.child, Cuboid) and isinstance(R.child, Cuboid):
                if self.is_near(L.child.size, R.child.size):
                    # Check X-Symmetry: Y,Z are same, X is inverted
                    mirrored_x = np.array([-R.vector[0], R.vector[1], R.vector[2]])
                    if self.is_near(L.vector, mirrored_x):
                        # Note: You need a SymRef class in dsl_nodes to return this!
                        # For now, we'll return a marked object or the original
                        print(f"DEBUG: Found X-Symmetry at {L.vector}")
        return None

# --- Usage ---
refactorer = DSLRefactorer(threshold=0.01)

# Apply to your specific shape
original_dsl = shapes_l0["172_0_0"]["dsl"]
optimized_dsl = refactorer.refactor(original_dsl)

print(optimized_dsl)

Union(
    Translate(vec=[-0.000, -0.170, 0.000])
        Cuboid(size=[0.680, 0.090, 0.660]),
    Union(
        Translate(vec=[-0.310, -0.510, -0.170])
            Cuboid(size=[0.060, 0.600, 0.060]),
        Union(
            Translate(vec=[-0.310, -0.510, 0.300])
                Cuboid(size=[0.060, 0.600, 0.060]),
            Union(
                Translate(vec=[0.310, -0.510, -0.170])
                    Cuboid(size=[0.060, 0.600, 0.060]),
                Union(
                    Translate(vec=[0.310, -0.510, 0.300])
                        Cuboid(size=[0.060, 0.600, 0.060]),
                    Union(
                        Translate(vec=[-0.260, 0.270, -0.180])
                            Cuboid(size=[0.080, 0.790, 0.080]),
                        Union(
                            Translate(vec=[-0.140, 0.270, -0.250])
                                Cuboid(size=[0.080, 0.790, 0.080]),
                            Union(
                                Translate(vec=[0.000, 0.740, -0.220])
                                    Cuboid(size=[0.680, 0.140, 0.240]),
                                Union(
                                    Translate(vec=[-0.000, 0.270, -0.250])
                                        Cuboid(size=[0.080, 0.790, 0.080]),
                                    Union(
                                        Translate(vec=[0.140, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080]),
                                        Translate(vec=[0.280, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080])
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)

In [13]:
import numpy as np
import copy
from abstractionsshapecoder.dsl_nodes import Union, Translate, Cuboid

class ShapeOptimizer:
    def __init__(self, threshold=0.01):
        self.threshold = threshold

    def is_near(self, a, b):
        return np.all(np.abs(np.array(a) - np.array(b)) <= self.threshold)

    def flatten_unions(self, node):
        """Turns nested Union(A, Union(B, C)) into [A, B, C]."""
        if isinstance(node, Union):
            return self.flatten_unions(node.left) + self.flatten_unions(node.right)
        return [node]

    def rebuild_union(self, nodes):
        """Turns [A, B, C] back into Union(A, Union(B, C))."""
        if not nodes: return None
        if len(nodes) == 1: return nodes[0]
        return Union(nodes[0], self.rebuild_union(nodes[1:]))

    def optimize_node(self, node):
        """Applies local simplifications (Move+Move, ZeroMove)."""
        if isinstance(node, Translate):
            node.child = self.optimize_node(node.child)
            # Combine Move(Move)
            if isinstance(node.child, Translate):
                return Translate(node.child.child, node.vector + node.child.vector)
            # Remove Zero Move
            if self.is_near(node.vector, [0, 0, 0]):
                return node.child
        return node

    def find_symmetries(self, parts):
        """
        Scans a flat list of parts and replaces symmetric pairs with a single part.
        Note: This assumes you define a SymRef class in your dsl_nodes.py.
        """
        optimized = []
        used_indices = set()

        for i in range(len(parts)):
            if i in used_indices: continue
            
            found_match = False
            for j in range(i + 1, len(parts)):
                if j in used_indices: continue
                
                p1, p2 = parts[i], parts[j]
                
                # Simple X-Symmetry check for Translate(Cuboid)
                if isinstance(p1, Translate) and isinstance(p2, Translate):
                    if isinstance(p1.child, Cuboid) and isinstance(p2.child, Cuboid):
                        if self.is_near(p1.child.size, p2.child.size):
                            mirrored_vec = np.array([-p2.vector[0], p2.vector[1], p2.vector[2]])
                            if self.is_near(p1.vector, mirrored_vec):
                                # Found X-Symmetry! 
                                # We keep p1 and treat it as a representative
                                optimized.append(p1) # In a real refactor, wrap in SymRef(p1, "AX")
                                used_indices.add(i)
                                used_indices.add(j)
                                found_match = True
                                break
            
            if not found_match:
                optimized.append(parts[i])
                used_indices.add(i)
                
        return optimized

    def run(self, root_node):
        # 1. Simplify individual branches (Move+Move)
        root_node = self.optimize_node(root_node)
        
        # 2. Flatten the whole thing to find global patterns
        parts = self.flatten_unions(root_node)
        
        # 3. Apply Symmetry Detection
        parts = self.find_symmetries(parts)
        
        # 4. Rebuild the tree
        return self.rebuild_union(parts)

# --- EXECUTION ---
optimizer = ShapeOptimizer()
results = {}

for shape_id, data in shapes_l0.items():
    original_dsl = data["dsl"]
    try:
        # We work on a deepcopy to avoid mutating your original dataset
        optimized = optimizer.run(copy.deepcopy(original_dsl))
        results[shape_id] = optimized
        
        # Check if it actually got smaller
        orig_count = len(optimizer.flatten_unions(original_dsl))
        opt_count = len(optimizer.flatten_unions(optimized))
        
        if opt_count < orig_count:
            print(f"✅ Refactored {shape_id}: {orig_count} parts -> {opt_count} parts")
    except Exception as e:
        print(f"❌ Failed on {shape_id}: {e}")

✅ Refactored 172_0_0: 11 parts -> 8 parts
✅ Refactored 173_0_1: 6 parts -> 4 parts
✅ Refactored 182_0_4: 6 parts -> 5 parts
✅ Refactored 186_0_5: 9 parts -> 7 parts
✅ Refactored 187_0_6: 15 parts -> 13 parts
✅ Refactored 197_0_7: 16 parts -> 14 parts
✅ Refactored 272_0_9: 6 parts -> 5 parts
✅ Refactored 278_0_10: 11 parts -> 8 parts
✅ Refactored 280_0_11: 16 parts -> 15 parts
✅ Refactored 285_0_12: 9 parts -> 7 parts
✅ Refactored 286_0_13: 15 parts -> 14 parts
✅ Refactored 314_0_15: 11 parts -> 8 parts
✅ Refactored 315_0_16: 6 parts -> 4 parts
✅ Refactored 328_0_17: 16 parts -> 14 parts
✅ Refactored 340_0_19: 6 parts -> 5 parts
✅ Refactored 341_0_20: 6 parts -> 5 parts
✅ Refactored 347_0_21: 9 parts -> 7 parts
✅ Refactored 456_0_23: 8 parts -> 7 parts
✅ Refactored 470_0_24: 7 parts -> 6 parts
✅ Refactored 515_0_27: 10 parts -> 9 parts
✅ Refactored 518_0_29: 8 parts -> 7 parts
✅ Refactored 523_0_30: 7 parts -> 5 parts
✅ Refactored 526_0_31: 14 parts -> 12 parts
✅ Refactored 543_0_33: 6 parts -> 4 parts
✅ Refactored 545_0_34: 11 parts -> 8 parts
✅ Refactored 547_0_35: 10 parts -> 7 parts
✅ Refactored 550_0_36: 16 parts -> 14 parts
✅ Refactored 555_0_39: 6 parts -> 5 parts
✅ Refactored 557_0_40: 10 parts -> 9 parts
✅ Refactored 561_0_41: 6 parts -> 5 parts
✅ Refactored 671_0_43: 6 parts -> 4 parts
✅ Refactored 682_0_44: 11 parts -> 7 parts
✅ Refactored 698_0_46: 10 parts -> 6 parts
✅ Refactored 699_0_47: 11 parts -> 8 parts
✅ Refactored 701_0_48: 11 parts -> 7 parts
✅ Refactored 724_0_50: 6 parts -> 4 parts
✅ Refactored 725_0_51: 9 parts -> 6 parts
✅ Refactored 732_0_52: 6 parts -> 4 parts
✅ Refactored 737_0_53: 16 parts -> 15 parts
✅ Refactored 739_0_54: 13 parts -> 12 parts
✅ Refactored 746_0_56: 8 parts -> 6 parts
✅ Refactored 748_0_57: 12 parts -> 11 parts
✅ Refactored 750_0_58: 7 parts -> 5 parts
✅ Refactored 752_0_59: 6 parts -> 5 parts
✅ Refactored 754_0_60: 16 parts -> 11 parts
✅ Refactored 756_0_61: 9 parts -> 6 parts
✅ Refactored 760_0_62: 11 parts -> 7 parts
✅ Refactored 763_0_63: 11 parts -> 9 parts
✅ Refactored 772_0_65: 9 parts -> 7 parts
✅ Refactored 1282_0_68: 8 parts -> 6 parts
✅ Refactored 1287_0_69: 10 parts -> 9 parts
✅ Refactored 1293_0_70: 9 parts -> 6 parts
✅ Refactored 1295_0_71: 6 parts -> 4 parts
✅ Refactored 1299_0_73: 8 parts -> 7 parts
✅ Refactored 1301_0_74: 6 parts -> 4 parts
✅ Refactored 1314_0_77: 12 parts -> 9 parts
✅ Refactored 1316_0_78: 6 parts -> 4 parts
✅ Refactored 1319_0_79: 15 parts -> 14 parts
✅ Refactored 1331_0_81: 12 parts -> 11 parts
✅ Refactored 1333_0_82: 8 parts -> 7 parts
✅ Refactored 1355_0_84: 8 parts -> 6 parts
✅ Refactored 1359_0_85: 6 parts -> 4 parts
✅ Refactored 1368_0_87: 14 parts -> 10 parts
✅ Refactored 1374_0_89: 9 parts -> 7 parts
✅ Refactored 1377_0_90: 12 parts -> 10 parts
✅ Refactored 1382_0_92: 9 parts -> 7 parts
✅ Refactored 1400_0_94: 10 parts -> 9 parts
✅ Refactored 1403_0_95: 15 parts -> 14 parts
✅ Refactored 1409_0_96: 6 parts -> 4 parts
✅ Refactored 1425_0_97: 16 parts -> 15 parts
✅ Refactored 1441_0_100: 6 parts -> 4 parts
✅ Refactored 1472_0_102: 10 parts -> 9 parts
✅ Refactored 2121_0_106: 11 parts -> 8 parts
✅ Refactored 2132_0_107: 8 parts -> 7 parts
✅ Refactored 2136_0_108: 14 parts -> 12 parts
✅ Refactored 2194_0_110: 9 parts -> 8 parts
✅ Refactored 2198_0_111: 6 parts -> 4 parts
✅ Refactored 2203_0_112: 9 parts -> 6 parts
✅ Refactored 2214_0_113: 12 parts -> 8 parts
✅ Refactored 2217_0_114: 6 parts -> 4 parts
✅ Refactored 2221_0_116: 6 parts -> 5 parts
✅ Refactored 2223_0_117: 10 parts -> 7 parts
✅ Refactored 2225_0_118: 6 parts -> 5 parts
✅ Refactored 2227_0_119: 5 parts -> 4 parts
✅ Refactored 2233_0_120: 13 parts -> 11 parts
✅ Refactored 2236_0_123: 7 parts -> 5 parts
✅ Refactored 2239_0_124: 12 parts -> 7 parts
✅ Refactored 2240_0_125: 14 parts -> 11 parts
✅ Refactored 2241_0_126: 6 parts -> 4 parts
✅ Refactored 2248_0_128: 10 parts -> 9 parts
✅ Refactored 2249_0_129: 11 parts -> 7 parts
✅ Refactored 2252_0_130: 11 parts -> 7 parts
✅ Refactored 2253_0_131: 5 parts -> 4 parts
✅ Refactored 2255_0_132: 16 parts -> 14 parts
✅ Refactored 2262_0_135: 8 parts -> 6 parts
✅ Refactored 2263_0_136: 10 parts -> 7 parts
✅ Refactored 2266_0_137: 6 parts -> 4 parts
✅ Refactored 2269_0_138: 7 parts -> 5 parts
✅ Refactored 2270_0_139: 6 parts -> 5 parts
✅ Refactored 2271_0_140: 6 parts -> 5 parts
✅ Refactored 2276_0_141: 9 parts -> 6 parts
✅ Refactored 2277_0_142: 16 parts -> 15 parts
✅ Refactored 2281_0_144: 9 parts -> 6 parts
✅ Refactored 2283_0_145: 9 parts -> 6 parts
✅ Refactored 2287_0_147: 12 parts -> 9 parts
✅ Refactored 2291_0_148: 6 parts -> 5 parts
✅ Refactored 2293_0_149: 12 parts -> 11 parts
✅ Refactored 2294_0_150: 9 parts -> 7 parts
✅ Refactored 2295_0_151: 7 parts -> 5 parts
✅ Refactored 2302_0_153: 9 parts -> 7 parts
✅ Refactored 2304_0_154: 14 parts -> 11 parts
✅ Refactored 2306_0_155: 9 parts -> 6 parts
✅ Refactored 2307_0_156: 13 parts -> 11 parts
✅ Refactored 2309_0_158: 6 parts -> 4 parts
✅ Refactored 2315_0_161: 14 parts -> 10 parts
✅ Refactored 2316_0_162: 4 parts -> 3 parts
✅ Refactored 2318_0_163: 12 parts -> 11 parts
✅ Refactored 2328_0_167: 11 parts -> 8 parts
✅ Refactored 2330_0_168: 6 parts -> 4 parts
✅ Refactored 2332_0_169: 6 parts -> 5 parts
✅ Refactored 2333_0_170: 9 parts -> 8 parts
✅ Refactored 2334_0_171: 12 parts -> 11 parts
✅ Refactored 2341_0_174: 8 parts -> 6 parts
✅ Refactored 2342_0_175: 6 parts -> 5 parts
✅ Refactored 2344_0_177: 6 parts -> 4 parts
✅ Refactored 2345_0_178: 12 parts -> 10 parts
✅ Refactored 2346_0_179: 16 parts -> 11 parts
✅ Refactored 2350_0_180: 10 parts -> 8 parts
✅ Refactored 2351_0_181: 6 parts -> 4 parts
✅ Refactored 2352_0_182: 7 parts -> 6 parts
✅ Refactored 2354_0_183: 9 parts -> 7 parts
✅ Refactored 2355_0_184: 7 parts -> 6 parts
✅ Refactored 2360_0_186: 6 parts -> 5 parts
✅ Refactored 2365_0_187: 13 parts -> 10 parts
✅ Refactored 2369_0_189: 6 parts -> 4 parts
✅ Refactored 2370_0_190: 6 parts -> 4 parts
✅ Refactored 2371_0_191: 9 parts -> 6 parts
✅ Refactored 2373_0_192: 11 parts -> 7 parts
✅ Refactored 2374_0_193: 8 parts -> 7 parts
✅ Refactored 2376_0_194: 11 parts -> 8 parts
✅ Refactored 2379_0_196: 10 parts -> 8 parts
✅ Refactored 2382_0_197: 9 parts -> 7 parts
✅ Refactored 2384_0_199: 15 parts -> 11 parts
✅ Refactored 2396_0_202: 8 parts -> 7 parts
✅ Refactored 2399_0_204: 5 parts -> 3 parts
✅ Refactored 2406_0_207: 6 parts -> 5 parts
✅ Refactored 2410_0_209: 12 parts -> 9 parts
✅ Refactored 2412_0_210: 6 parts -> 4 parts
✅ Refactored 2416_0_211: 16 parts -> 15 parts
✅ Refactored 2423_0_214: 12 parts -> 11 parts
✅ Refactored 2424_0_215: 7 parts -> 5 parts
✅ Refactored 2429_0_216: 11 parts -> 9 parts
✅ Refactored 2435_0_219: 10 parts -> 9 parts
✅ Refactored 2436_0_220: 6 parts -> 5 parts
✅ Refactored 2437_0_221: 12 parts -> 7 parts
✅ Refactored 2439_0_222: 6 parts -> 4 parts
✅ Refactored 2446_0_225: 11 parts -> 9 parts
✅ Refactored 2447_0_226: 11 parts -> 8 parts
✅ Refactored 2448_0_227: 13 parts -> 9 parts
✅ Refactored 2449_0_228: 15 parts -> 14 parts
✅ Refactored 2454_0_229: 6 parts -> 4 parts
✅ Refactored 2457_0_230: 8 parts -> 7 parts
✅ Refactored 2458_0_231: 11 parts -> 8 parts
✅ Refactored 2464_0_234: 9 parts -> 8 parts
✅ Refactored 2466_0_235: 10 parts -> 8 parts
✅ Refactored 2470_0_237: 9 parts -> 8 parts
✅ Refactored 2476_0_239: 4 parts -> 3 parts
✅ Refactored 2478_0_240: 4 parts -> 3 parts
✅ Refactored 2479_0_241: 13 parts -> 11 parts
✅ Refactored 2483_0_243: 10 parts -> 9 parts
✅ Refactored 2493_0_246: 7 parts -> 6 parts
✅ Refactored 2495_0_248: 12 parts -> 10 parts
✅ Refactored 2497_0_249: 16 parts -> 12 parts
✅ Refactored 2502_0_251: 13 parts -> 12 parts
✅ Refactored 2503_0_252: 11 parts -> 9 parts
✅ Refactored 2505_0_253: 6 parts -> 4 parts
✅ Refactored 2506_0_254: 14 parts -> 12 parts
✅ Refactored 2508_0_255: 15 parts -> 14 parts
✅ Refactored 2511_0_257: 9 parts -> 7 parts
✅ Refactored 2516_0_259: 7 parts -> 6 parts
✅ Refactored 2524_0_262: 10 parts -> 9 parts
✅ Refactored 2529_0_263: 5 parts -> 4 parts
✅ Refactored 2535_0_266: 13 parts -> 12 parts
✅ Refactored 2539_0_267: 6 parts -> 4 parts
✅ Refactored 2542_0_269: 6 parts -> 4 parts
✅ Refactored 2544_0_270: 6 parts -> 5 parts
✅ Refactored 2545_0_271: 6 parts -> 4 parts
✅ Refactored 2546_0_272: 7 parts -> 6 parts
✅ Refactored 2558_0_273: 14 parts -> 10 parts
✅ Refactored 2562_0_274: 9 parts -> 8 parts
✅ Refactored 2567_0_276: 13 parts -> 11 parts
✅ Refactored 2570_0_278: 6 parts -> 4 parts
✅ Refactored 2574_0_280: 6 parts -> 4 parts
✅ Refactored 2582_0_284: 9 parts -> 7 parts
✅ Refactored 2584_0_285: 4 parts -> 3 parts
✅ Refactored 2585_0_286: 6 parts -> 4 parts
✅ Refactored 2586_0_287: 15 parts -> 14 parts
✅ Refactored 2592_0_291: 6 parts -> 4 parts
✅ Refactored 2598_0_294: 9 parts -> 7 parts
✅ Refactored 2602_0_296: 11 parts -> 9 parts
✅ Refactored 2605_0_297: 15 parts -> 10 parts
✅ Refactored 2607_0_298: 10 parts -> 7 parts
✅ Refactored 2611_0_299: 10 parts -> 7 parts
✅ Refactored 2612_0_300: 6 parts -> 4 parts
✅ Refactored 2614_0_301: 9 parts -> 6 parts
✅ Refactored 2620_0_302: 10 parts -> 9 parts
✅ Refactored 2623_0_303: 10 parts -> 7 parts
✅ Refactored 2631_0_306: 16 parts -> 15 parts
✅ Refactored 2636_0_307: 4 parts -> 3 parts
✅ Refactored 2637_0_308: 6 parts -> 4 parts
✅ Refactored 2645_0_310: 7 parts -> 6 parts
✅ Refactored 2647_0_311: 9 parts -> 7 parts
✅ Refactored 2648_0_312: 12 parts -> 10 parts
✅ Refactored 2650_0_313: 8 parts -> 7 parts
✅ Refactored 2653_0_314: 15 parts -> 10 parts
✅ Refactored 2655_0_315: 6 parts -> 5 parts
✅ Refactored 2656_0_316: 8 parts -> 6 parts
✅ Refactored 2663_0_317: 11 parts -> 9 parts
✅ Refactored 2666_0_319: 12 parts -> 11 parts
✅ Refactored 2673_0_320: 16 parts -> 12 parts
✅ Refactored 2681_0_323: 7 parts -> 5 parts
✅ Refactored 2684_0_324: 12 parts -> 11 parts
✅ Refactored 2687_0_325: 8 parts -> 7 parts
✅ Refactored 2691_0_327: 9 parts -> 7 parts
✅ Refactored 2692_0_328: 6 parts -> 4 parts
✅ Refactored 2694_0_329: 9 parts -> 6 parts
✅ Refactored 2700_0_330: 4 parts -> 3 parts
✅ Refactored 2707_0_333: 8 parts -> 7 parts
✅ Refactored 2710_0_335: 4 parts -> 3 parts
✅ Refactored 2711_0_336: 7 parts -> 6 parts
✅ Refactored 2712_0_337: 10 parts -> 6 parts
✅ Refactored 2723_0_339: 6 parts -> 4 parts
✅ Refactored 2728_0_340: 13 parts -> 10 parts
✅ Refactored 2731_0_341: 15 parts -> 11 parts
✅ Refactored 2741_0_343: 8 parts -> 7 parts
✅ Refactored 2746_0_344: 11 parts -> 7 parts
✅ Refactored 2750_0_345: 7 parts -> 5 parts
✅ Refactored 2752_0_346: 6 parts -> 5 parts
✅ Refactored 2755_0_348: 10 parts -> 7 parts
✅ Refactored 2759_0_350: 14 parts -> 11 parts
✅ Refactored 2764_0_351: 9 parts -> 6 parts
✅ Refactored 2769_0_352: 8 parts -> 5 parts
✅ Refactored 2770_0_353: 6 parts -> 4 parts
✅ Refactored 2772_0_354: 6 parts -> 5 parts
✅ Refactored 2773_0_355: 5 parts -> 4 parts
✅ Refactored 2774_0_356: 12 parts -> 9 parts
✅ Refactored 2785_0_359: 10 parts -> 8 parts
✅ Refactored 2786_0_360: 10 parts -> 7 parts
✅ Refactored 2788_0_361: 13 parts -> 12 parts
✅ Refactored 2789_0_362: 14 parts -> 11 parts
✅ Refactored 2790_0_363: 6 parts -> 4 parts
✅ Refactored 2797_0_365: 6 parts -> 5 parts
✅ Refactored 2799_0_366: 6 parts -> 5 parts
✅ Refactored 2804_0_369: 6 parts -> 4 parts
✅ Refactored 2810_0_371: 16 parts -> 12 parts
✅ Refactored 2815_0_374: 6 parts -> 5 parts
✅ Refactored 2817_0_375: 11 parts -> 10 parts
✅ Refactored 2820_0_376: 15 parts -> 13 parts
✅ Refactored 2827_0_377: 14 parts -> 13 parts
✅ Refactored 2828_0_378: 9 parts -> 7 parts
✅ Refactored 2830_0_379: 8 parts -> 5 parts
✅ Refactored 2832_0_380: 9 parts -> 6 parts
✅ Refactored 2834_0_381: 12 parts -> 10 parts
✅ Refactored 2847_0_383: 16 parts -> 13 parts
✅ Refactored 2855_0_385: 11 parts -> 10 parts
✅ Refactored 2864_0_386: 10 parts -> 8 parts
✅ Refactored 2867_0_389: 6 parts -> 5 parts
✅ Refactored 2868_0_390: 6 parts -> 4 parts
✅ Refactored 2869_0_391: 14 parts -> 11 parts
✅ Refactored 2878_0_394: 8 parts -> 6 parts
✅ Refactored 2882_0_396: 13 parts -> 12 parts
✅ Refactored 2885_0_397: 7 parts -> 5 parts
✅ Refactored 2886_0_398: 9 parts -> 8 parts
✅ Refactored 2893_0_399: 11 parts -> 10 parts
✅ Refactored 2896_0_400: 5 parts -> 4 parts
✅ Refactored 2898_0_401: 7 parts -> 5 parts
✅ Refactored 2900_0_402: 12 parts -> 11 parts
✅ Refactored 2903_0_403: 10 parts -> 8 parts
✅ Refactored 2904_0_404: 6 parts -> 5 parts
✅ Refactored 2906_0_405: 16 parts -> 12 parts
✅ Refactored 2908_0_406: 12 parts -> 10 parts
✅ Refactored 2913_0_408: 14 parts -> 9 parts
✅ Refactored 2930_0_411: 11 parts -> 9 parts
✅ Refactored 2943_0_413: 10 parts -> 7 parts
✅ Refactored 2946_0_414: 12 parts -> 11 parts
✅ Refactored 2947_0_415: 14 parts -> 13 parts
✅ Refactored 2948_0_416: 9 parts -> 8 parts
✅ Refactored 2957_0_421: 6 parts -> 4 parts
✅ Refactored 2959_0_423: 11 parts -> 9 parts
✅ Refactored 2960_0_424: 10 parts -> 6 parts
✅ Refactored 2975_0_428: 10 parts -> 8 parts
✅ Refactored 2980_0_429: 13 parts -> 9 parts
✅ Refactored 2993_0_432: 4 parts -> 3 parts
✅ Refactored 3005_0_436: 15 parts -> 13 parts
✅ Refactored 3006_0_437: 11 parts -> 10 parts
✅ Refactored 3007_0_438: 9 parts -> 8 parts
✅ Refactored 3009_0_439: 16 parts -> 12 parts
✅ Refactored 3013_0_440: 10 parts -> 7 parts
✅ Refactored 3015_0_441: 9 parts -> 6 parts
✅ Refactored 3026_0_443: 12 parts -> 10 parts
✅ Refactored 3032_0_445: 9 parts -> 7 parts
✅ Refactored 3033_0_446: 12 parts -> 9 parts
✅ Refactored 3035_0_447: 5 parts -> 4 parts
✅ Refactored 3037_0_448: 8 parts -> 6 parts
✅ Refactored 3043_0_449: 12 parts -> 8 parts
✅ Refactored 3045_0_450: 11 parts -> 9 parts
✅ Refactored 3054_0_452: 11 parts -> 10 parts
✅ Refactored 3068_0_454: 11 parts -> 8 parts
✅ Refactored 3074_0_456: 10 parts -> 8 parts
✅ Refactored 3078_0_457: 9 parts -> 6 parts
✅ Refactored 3081_0_459: 6 parts -> 4 parts
✅ Refactored 3094_0_460: 6 parts -> 4 parts
✅ Refactored 3105_0_463: 6 parts -> 4 parts
✅ Refactored 3107_0_465: 8 parts -> 7 parts
✅ Refactored 3109_0_466: 6 parts -> 4 parts
✅ Refactored 3113_0_468: 14 parts -> 10 parts
✅ Refactored 3123_0_470: 9 parts -> 6 parts
✅ Refactored 3124_0_471: 8 parts -> 7 parts
✅ Refactored 3128_0_473: 14 parts -> 10 parts
✅ Refactored 3131_0_474: 8 parts -> 6 parts
✅ Refactored 3146_0_478: 9 parts -> 8 parts
✅ Refactored 3150_0_480: 9 parts -> 7 parts
✅ Refactored 3157_0_481: 8 parts -> 6 parts
✅ Refactored 3159_0_482: 6 parts -> 4 parts
✅ Refactored 3163_0_484: 12 parts -> 11 parts
✅ Refactored 3174_0_485: 6 parts -> 4 parts
✅ Refactored 3187_0_487: 10 parts -> 9 parts
✅ Refactored 3198_0_491: 13 parts -> 10 parts
✅ Refactored 3199_0_492: 15 parts -> 13 parts
✅ Refactored 3207_0_493: 8 parts -> 5 parts
✅ Refactored 3214_0_496: 8 parts -> 7 parts
✅ Refactored 3215_0_497: 6 parts -> 5 parts
✅ Refactored 3217_0_498: 6 parts -> 5 parts
✅ Refactored 3224_0_500: 6 parts -> 5 parts
✅ Refactored 3227_0_502: 6 parts -> 5 parts
✅ Refactored 3233_0_504: 6 parts -> 5 parts
✅ Refactored 3236_0_505: 12 parts -> 10 parts
✅ Refactored 3251_0_509: 6 parts -> 4 parts
✅ Refactored 3253_0_510: 11 parts -> 7 parts
✅ Refactored 3257_0_512: 7 parts -> 6 parts
✅ Refactored 3269_0_516: 11 parts -> 9 parts
✅ Refactored 3271_0_517: 10 parts -> 7 parts
✅ Refactored 3272_0_518: 8 parts -> 7 parts
✅ Refactored 3274_0_519: 9 parts -> 7 parts
✅ Refactored 3277_0_520: 8 parts -> 6 parts
✅ Refactored 3278_0_521: 8 parts -> 5 parts
✅ Refactored 3280_0_522: 13 parts -> 11 parts
✅ Refactored 3281_0_523: 10 parts -> 8 parts
✅ Refactored 3288_0_525: 15 parts -> 14 parts
✅ Refactored 3293_0_526: 10 parts -> 8 parts
✅ Refactored 3301_0_528: 14 parts -> 13 parts
✅ Refactored 3302_0_529: 16 parts -> 13 parts
✅ Refactored 3305_0_530: 11 parts -> 10 parts
✅ Refactored 3309_0_531: 10 parts -> 7 parts
✅ Refactored 3318_0_534: 6 parts -> 4 parts
✅ Refactored 3321_0_537: 15 parts -> 14 parts
✅ Refactored 3322_0_538: 16 parts -> 14 parts
✅ Refactored 3323_0_539: 6 parts -> 4 parts
✅ Refactored 3324_0_540: 7 parts -> 5 parts
✅ Refactored 3328_0_541: 12 parts -> 10 parts
✅ Refactored 3330_0_542: 10 parts -> 9 parts
✅ Refactored 3331_0_543: 12 parts -> 9 parts
✅ Refactored 3336_0_544: 10 parts -> 9 parts
✅ Refactored 3340_0_545: 14 parts -> 11 parts
✅ Refactored 3344_0_546: 11 parts -> 10 parts
✅ Refactored 3347_0_547: 13 parts -> 9 parts
✅ Refactored 3353_0_551: 11 parts -> 9 parts
✅ Refactored 3361_0_554: 7 parts -> 5 parts
✅ Refactored 3364_0_555: 6 parts -> 5 parts
✅ Refactored 3375_0_558: 6 parts -> 4 parts
✅ Refactored 3377_0_559: 14 parts -> 10 parts
✅ Refactored 3384_0_561: 6 parts -> 5 parts
✅ Refactored 3402_0_562: 8 parts -> 5 parts
✅ Refactored 34924_0_564: 6 parts -> 4 parts
✅ Refactored 34925_0_565: 11 parts -> 8 parts
✅ Refactored 34926_0_566: 16 parts -> 15 parts
✅ Refactored 34998_0_567: 6 parts -> 4 parts
✅ Refactored 35014_0_568: 11 parts -> 8 parts
✅ Refactored 35062_0_569: 15 parts -> 13 parts
✅ Refactored 35064_0_570: 9 parts -> 7 parts
✅ Refactored 35070_0_572: 6 parts -> 5 parts
✅ Refactored 35072_0_574: 6 parts -> 4 parts
✅ Refactored 35082_0_576: 10 parts -> 8 parts
✅ Refactored 35096_0_578: 6 parts -> 4 parts
✅ Refactored 35097_0_579: 6 parts -> 4 parts
✅ Refactored 35100_0_581: 16 parts -> 13 parts
✅ Refactored 35104_0_585: 6 parts -> 4 parts
✅ Refactored 35111_0_587: 16 parts -> 12 parts
✅ Refactored 35119_0_589: 11 parts -> 8 parts
✅ Refactored 35121_0_590: 9 parts -> 7 parts
✅ Refactored 35123_0_591: 15 parts -> 13 parts
✅ Refactored 35131_0_592: 11 parts -> 8 parts
✅ Refactored 35142_0_593: 9 parts -> 7 parts
✅ Refactored 35144_0_594: 14 parts -> 12 parts
✅ Refactored 35146_0_596: 9 parts -> 7 parts
✅ Refactored 35153_0_597: 11 parts -> 8 parts
✅ Refactored 35178_0_598: 11 parts -> 8 parts
✅ Refactored 35180_0_599: 12 parts -> 11 parts
✅ Refactored 35184_0_600: 12 parts -> 10 parts
✅ Refactored 35189_0_604: 11 parts -> 8 parts
✅ Refactored 35197_0_607: 15 parts -> 13 parts
✅ Refactored 35200_0_608: 6 parts -> 4 parts
✅ Refactored 35203_0_610: 15 parts -> 13 parts
✅ Refactored 35204_0_611: 6 parts -> 4 parts
✅ Refactored 35205_0_612: 9 parts -> 7 parts
✅ Refactored 35213_0_613: 15 parts -> 13 parts
✅ Refactored 35222_0_615: 6 parts -> 4 parts
✅ Refactored 35223_0_616: 16 parts -> 12 parts
✅ Refactored 35233_0_617: 16 parts -> 12 parts
✅ Refactored 35234_0_618: 6 parts -> 5 parts
✅ Refactored 35236_0_620: 6 parts -> 4 parts
✅ Refactored 35238_0_621: 6 parts -> 4 parts
✅ Refactored 35245_0_623: 11 parts -> 8 parts
✅ Refactored 35270_0_625: 16 parts -> 14 parts
✅ Refactored 35273_0_626: 6 parts -> 5 parts
✅ Refactored 35274_0_627: 9 parts -> 7 parts
✅ Refactored 35319_0_629: 15 parts -> 13 parts
✅ Refactored 35326_0_630: 8 parts -> 7 parts
✅ Refactored 35331_0_631: 14 parts -> 12 parts
✅ Refactored 35333_0_632: 16 parts -> 13 parts
✅ Refactored 35376_0_633: 11 parts -> 8 parts
✅ Refactored 35392_0_634: 11 parts -> 8 parts
✅ Refactored 35393_0_635: 12 parts -> 9 parts
✅ Refactored 35401_0_637: 10 parts -> 8 parts
✅ Refactored 35407_0_638: 11 parts -> 8 parts
✅ Refactored 35423_0_639: 11 parts -> 8 parts
✅ Refactored 35424_0_640: 6 parts -> 4 parts
✅ Refactored 35439_0_641: 10 parts -> 7 parts
✅ Refactored 35440_0_642: 11 parts -> 8 parts
✅ Refactored 35441_0_643: 15 parts -> 13 parts
✅ Refactored 35445_0_644: 15 parts -> 13 parts
✅ Refactored 35447_0_645: 9 parts -> 7 parts
✅ Refactored 35448_0_646: 10 parts -> 8 parts
✅ Refactored 35455_0_647: 9 parts -> 7 parts
✅ Refactored 35464_0_648: 15 parts -> 13 parts
✅ Refactored 35471_0_649: 11 parts -> 9 parts
✅ Refactored 35477_0_650: 11 parts -> 8 parts
✅ Refactored 35481_0_651: 9 parts -> 7 parts
✅ Refactored 35482_0_652: 10 parts -> 8 parts
✅ Refactored 35486_0_653: 6 parts -> 4 parts
✅ Refactored 35498_0_655: 6 parts -> 4 parts
✅ Refactored 35499_0_656: 16 parts -> 14 parts
✅ Refactored 35500_0_657: 6 parts -> 5 parts
✅ Refactored 35505_0_658: 15 parts -> 13 parts
✅ Refactored 35511_0_662: 10 parts -> 9 parts
✅ Refactored 35515_0_664: 6 parts -> 4 parts
✅ Refactored 35517_0_666: 6 parts -> 4 parts
✅ Refactored 35519_0_668: 6 parts -> 4 parts

In [22]:
import numpy as np
import copy
import logging
from abstractionsshapecoder.dsl_nodes import Union, Translate, Cuboid

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger("ShapeOptimizer")

class ShapeOptimizer:
    def __init__(self, threshold=0.01):
        self.threshold = threshold

    def is_near(self, a, b):
        try:
            return np.all(np.abs(np.array(a) - np.array(b)) <= self.threshold)
        except (TypeError, ValueError) as e:
            logger.error(f"Vector comparison failed: {e}")
            return False

    def flatten_unions(self, node):
        """Turns nested Union(A, Union(B, C)) into [A, B, C]."""
        if isinstance(node, Union):
            return self.flatten_unions(node.left) + self.flatten_unions(node.right)
        return [node] if node is not None else []

    def rebuild_union(self, nodes):
        """Turns [A, B, C] back into Union(A, Union(B, C))."""
        if not nodes: 
            return None
        if len(nodes) == 1: 
            return nodes[0]
        return Union(nodes[0], self.rebuild_union(nodes[1:]))

    def apply_optimization_rules(self, node):
        """
        Logic for specific node-level simplifications. 
        Separate this to easily add new rules like Rotation or Scaling.
        """
        if not isinstance(node, Translate):
            return node

        child = self.optimize_node(node.child) # Recurse first
        
        # Rule 1: Combine nested Translates
        if isinstance(child, Translate):
            logger.debug("Rule Applied: Combined nested translations.")
            combined_vector = np.array(node.vector) + np.array(child.vector)
            return Translate(child.child, combined_vector.tolist())

        # Rule 2: Remove Identity (Zero) Move
        if self.is_near(node.vector, [0, 0, 0]):
            logger.debug("Rule Applied: Removed zero-translation.")
            return child

        # Re-assign optimized child if no rules triggered a return
        node.child = child
        return node

    def optimize_node(self, node):
        """Entry point for recursive node optimization."""
        if node is None:
            return None
        return self.apply_optimization_rules(node)

    def find_symmetries(self, parts):
        """Scans a flat list and replaces symmetric pairs."""
        optimized = []
        used_indices = set()

        for i in range(len(parts)):
            if i in used_indices: 
                continue
            
            found_match = False
            p1 = parts[i]

            for j in range(i + 1, len(parts)):
                if j in used_indices: 
                    continue
                
                p2 = parts[j]
                
                # Check for X-Symmetry between Translate(Cuboid) structures
                if (isinstance(p1, Translate) and isinstance(p2, Translate) and
                    isinstance(p1.child, Cuboid) and isinstance(p2.child, Cuboid)):
                    
                    if self.is_near(p1.child.size, p2.child.size):
                        mirrored_vec = np.array([-p2.vector[0], p2.vector[1], p2.vector[2]])
                        
                        if self.is_near(p1.vector, mirrored_vec):
                            logger.info(f"Symmetry Found: Mirror pair at {p1.vector} and {p2.vector}")
                            # Keep p1 as representative
                            optimized.append(p1) 
                            used_indices.add(i)
                            used_indices.add(j)
                            found_match = True
                            break
            
            if not found_match:
                optimized.append(p1)
                used_indices.add(i)
                
        return optimized

    def run(self, root_node):
        if root_node is None:
            logger.warning("Optimization called on None node.")
            return None

        # 1. Simplify individual branches (Move+Move, etc.)
        root_node = self.optimize_node(root_node)
        
        # 2. Flatten for global pattern recognition
        parts = self.flatten_unions(root_node)
        
        # 3. Apply Symmetry Detection
        original_count = len(parts)
        parts = self.find_symmetries(parts)
        
        if len(parts) < original_count:
            logger.info(f"Symmetry reduction: {original_count} -> {len(parts)} parts.")
        
        # 4. Rebuild the tree
        return self.rebuild_union(parts)

# --- EXECUTION ---
optimizer = ShapeOptimizer()
results = {}

# Example loop with improved error handling
for shape_id, data in shapes_l0.items():
    try:
        original_dsl = data.get("dsl")
        if original_dsl is None:
            continue

        optimized = optimizer.run(copy.deepcopy(original_dsl))
        results[shape_id] = optimized
        
        orig_count = len(optimizer.flatten_unions(original_dsl))
        opt_count = len(optimizer.flatten_unions(optimized))
        
        if opt_count < orig_count:
            print(f"✅ {shape_id}: Reduced from {orig_count} to {opt_count} nodes.")
            
    except Exception as e:
        logger.error(f"Critical failure on {shape_id}: {e}", exc_info=True)

INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.51 -0.4 ] and [ 0.37 -0.51 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.41] and [ 0.34 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48 -0.29] and [ 0.28 -0.48 -0.29]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.52 -0.33] and [ 0.3  -0.52 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.56  0.32] and [ 0.3  -0.56  0.32]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.22] and [ 0.31 -0.49 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.51  0.44] and [ 0.49 -0.51  0.44]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57  0.4 ] and [ 0.4  -0.57  0.4 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.42  0.45] and [ 0.44 -0.42  0.45]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.42 -0.25] and [ 0.31  0.42 -0.25]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.51 -0.41] and [ 0.36 -0.51 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.41] and [ 0.34 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48 -0.23] and [ 0.31 -0.48 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.51  0.43] and [ 0.49 -0.51  0.43]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.5  -0.29] and [ 0.28 -0.5  -0.29]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.4 ] and [ 0.4  -0.56 -0.4 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.52  0.27  0.18] and [0.52 0.27 0.18]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.69  0.16  0.  ] and [ 0.69  0.16 -0.  ]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.35  0.54] and [ 0.35 -0.35  0.54]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55 -0.49] and [ 0.54 -0.55 -0.49]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.53  0.03  0.04] and [0.53 0.03 0.04]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.45 -0.  ] and [ 0.54 -0.45 -0.  ]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.61  0.42] and [ 0.41 -0.61  0.42]
INFO: Symmetry Found: Mirror pair at [-0.42  0.26  0.03] and [0.42 0.26 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61 -0.29] and [ 0.29 -0.61 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.3 ] and [ 0.29 -0.61  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.58  0.16  0.19] and [0.58 0.16 0.19]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.22] and [ 0.31 -0.49 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.43] and [ 0.49 -0.52  0.43]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.59  0.3 ] and [ 0.3  -0.59  0.3 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.5   0.44] and [ 0.24 -0.5   0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.43] and [ 0.24 -0.52 -0.43]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.51  0.45] and [ 0.24 -0.51  0.45]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.54 -0.32] and [ 0.42 -0.54 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.78  0.04] and [ 0.42 -0.78  0.04]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.26 -0.  ] and [ 0.42 -0.26 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.54  0.42] and [ 0.42 -0.54  0.42]
INFO: Symmetry reduction: 10 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.49 -0.28] and [ 0.28 -0.49 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.49  0.3 ] and [ 0.28 -0.49  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.36 -0.29] and [ 0.37 -0.36 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.36  0.34] and [ 0.37 -0.36  0.34]
INFO: Symmetry Found: Mirror pair at [-0.36  0.35 -0.33] and [ 0.36  0.35 -0.33]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.4 ] and [ 0.4  -0.56 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.55  0.4 ] and [ 0.4  -0.55  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.57  0.23] and [ 0.37 -0.57  0.23]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.33  0.31 -0.28] and [ 0.33  0.31 -0.28]
INFO: Symmetry reduction: 13 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.41 -0.25] and [ 0.38 -0.41 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.18  0.48] and [ 0.42 -0.18  0.48]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.45 -0.34  0.42] and [ 0.45 -0.34  0.42]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.72 -0.39] and [ 0.35 -0.72 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.72  0.5 ] and [ 0.35 -0.72  0.5 ]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48 -0.13] and [ 0.28 -0.48 -0.13]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.47 -0.35] and [ 0.34 -0.47 -0.35]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.46  0.36] and [ 0.34 -0.46  0.36]
INFO: Symmetry Found: Mirror pair at [-0.35  0.4  -0.36] and [ 0.35  0.4  -0.36]
INFO: Symmetry Found: Mirror pair at [-0.18  0.24 -0.36] and [ 0.18  0.24 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.18  0.57 -0.35] and [ 0.18  0.57 -0.35]
INFO: Symmetry reduction: 16 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.43  0.05 -0.09] and [ 0.43  0.05 -0.09]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.59 -0.45] and [ 0.44 -0.59 -0.45]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.59  0.33] and [ 0.44 -0.59  0.33]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.56 -0.57 -0.55] and [ 0.56 -0.57 -0.55]
INFO: Symmetry Found: Mirror pair at [-0.56 -0.57  0.54] and [ 0.56 -0.57  0.54]
INFO: Symmetry Found: Mirror pair at [-0.57 -0.1   0.  ] and [ 0.57 -0.1   0.  ]
INFO: Symmetry Found: Mirror pair at [-0.57  0.32  0.  ] and [0.57 0.32 0.  ]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.43 -0.46] and [ 0.53 -0.43 -0.46]
INFO: Symmetry Found: Mirror pair at [-0.53 -0.43  0.62] and [ 0.53 -0.43  0.62]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.24  0.08  0.12] and [0.24 0.08 0.12]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.58 -0.28] and [ 0.23 -0.58 -0.28]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.7   0.16 -0.  ] and [ 0.7   0.16 -0.  ]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.5  -0.12  0.06] and [ 0.5  -0.12  0.06]
INFO: Symmetry Found: Mirror pair at [-0.5  -0.62 -0.33] and [ 0.5  -0.62 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.5  -0.62  0.48] and [ 0.5  -0.62  0.48]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61 -0.28] and [ 0.29 -0.61 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.6   0.29] and [ 0.29 -0.6   0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.36  0.22 -0.34] and [ 0.36  0.22 -0.34]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.44 -0.42] and [ 0.33 -0.44 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.43  0.42] and [ 0.34 -0.43  0.42]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.3   0.29 -0.19] and [ 0.3   0.29 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.18  0.29 -0.19] and [ 0.18  0.29 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.06  0.29 -0.19] and [ 0.06  0.29 -0.19]
INFO: Symmetry reduction: 12 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.47 -0.27] and [ 0.27 -0.47 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.46  0.47] and [ 0.35 -0.46  0.47]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.41 -0.25] and [ 0.31  0.41 -0.25]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.38 -0.33] and [ 0.4   0.38 -0.33]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.26  0.05  0.1 ] and [0.26 0.05 0.1 ]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.06  0.17] and [ 0.46 -0.06  0.17]
INFO: Symmetry Found: Mirror pair at [-0.5  -0.59  0.51] and [ 0.5  -0.59  0.51]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.47 -0.25] and [ 0.25 -0.47 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.45  0.27] and [ 0.25 -0.45  0.27]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.18 -0.58] and [ 0.59  0.18 -0.58]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.32 -0.6 ] and [ 0.59 -0.32 -0.6 ]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.53 -0.12] and [ 0.59 -0.53 -0.12]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.32  0.38] and [ 0.59 -0.32  0.38]
INFO: Symmetry reduction: 14 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.58 -0.53 -0.45] and [ 0.58 -0.53 -0.45]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.53  0.57] and [ 0.58 -0.53  0.57]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.46 -0.2 ] and [ 0.3  -0.46 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.46  0.35] and [ 0.3  -0.46  0.35]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.25 -0.32] and [ 0.43 -0.25 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.25  0.32] and [ 0.43 -0.25  0.32]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.43  0.    0.  ] and [0.43 0.   0.  ]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.44  0.43] and [ 0.38 -0.44  0.43]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.62 -0.25] and [ 0.29 -0.62 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.62  0.26] and [ 0.29 -0.62  0.26]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.36  0.11 -0.31] and [ 0.36  0.11 -0.31]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.49 -0.39] and [ 0.39 -0.49 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.47  0.4 ] and [ 0.36 -0.47  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.55  0.18  0.05] and [0.55 0.18 0.05]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.35 -0.41] and [ 0.38 -0.35 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.7   0.02] and [ 0.38 -0.7   0.02]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.35  0.44] and [ 0.38 -0.35  0.44]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55 -0.49] and [ 0.54 -0.55 -0.49]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.61  0.42] and [ 0.41 -0.61  0.42]
INFO: Symmetry Found: Mirror pair at [-0.42  0.26  0.03] and [0.42 0.26 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.52  0.12 -0.05] and [ 0.52  0.12 -0.05]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61 -0.28] and [ 0.29 -0.61 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.31] and [ 0.29 -0.61  0.31]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.58 -0.05  0.  ] and [ 0.58 -0.05  0.  ]
INFO: Symmetry Found: Mirror pair at [-0.5  -0.49 -0.5 ] and [ 0.5  -0.49 -0.5 ]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.49  0.58] and [ 0.58 -0.49  0.58]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.38 -0.38] and [ 0.38 -0.38 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.77 -0.38] and [ 0.38 -0.77 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.37  0.38] and [ 0.38 -0.37  0.38]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.76  0.38] and [ 0.38 -0.76  0.38]
INFO: Symmetry reduction: 12 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.58 -0.29] and [ 0.27 -0.58 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.58  0.29] and [ 0.28 -0.58  0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.09 -0.06] and [ 0.42 -0.09 -0.06]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.42 -0.24] and [ 0.23 -0.42 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.54 -0.01] and [ 0.24 -0.54 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.23 -0.42  0.23] and [ 0.23 -0.42  0.23]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.44] and [ 0.24 -0.52 -0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.35] and [ 0.44 -0.52 -0.35]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.52 -0.18] and [ 0.25 -0.52 -0.18]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.52  0.33] and [ 0.25 -0.52  0.33]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.56 -0.36] and [ 0.36 -0.56 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.55  0.37] and [ 0.37 -0.55  0.37]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.39 -0.33] and [ 0.39 -0.39 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.4   0.38] and [ 0.38 -0.4   0.38]
INFO: Symmetry Found: Mirror pair at [-0.38  0.41 -0.01] and [ 0.38  0.41 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.38  0.16 -0.33] and [ 0.38  0.16 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.37  0.25  0.37] and [0.37 0.25 0.37]
INFO: Symmetry reduction: 12 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.46 -0.32 -0.36] and [ 0.46 -0.32 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.46 -0.64  0.01] and [ 0.46 -0.64  0.01]
INFO: Symmetry Found: Mirror pair at [-0.46 -0.36  0.41] and [ 0.46 -0.36  0.41]
INFO: Symmetry reduction: 14 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.61 -0.27] and [ 0.25 -0.61 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.3 ] and [ 0.29 -0.61  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.27  0.04] and [ 0.42 -0.27  0.04]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.64 -0.07  0.03] and [ 0.64 -0.07  0.03]
INFO: Symmetry Found: Mirror pair at [-0.52 -0.46 -0.43] and [ 0.52 -0.46 -0.43]
INFO: Symmetry Found: Mirror pair at [-0.52 -0.39  0.03] and [ 0.52 -0.39  0.03]
INFO: Symmetry Found: Mirror pair at [-0.52 -0.46  0.51] and [ 0.52 -0.46  0.51]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.49  0.19 -0.02] and [ 0.49  0.19 -0.02]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.   -0.09] and [ 0.31  0.   -0.09]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.03  0.52] and [ 0.31 -0.03  0.52]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.67 -0.47] and [ 0.46 -0.67 -0.47]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.66  0.47] and [ 0.46 -0.66  0.47]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.57 -0.39] and [ 0.39 -0.57 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.57  0.4 ] and [ 0.39 -0.57  0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.39  0.04  0.39] and [0.39 0.04 0.39]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.38 -0.17] and [ 0.32 -0.38 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.38  0.33] and [ 0.32 -0.38  0.33]
INFO: Symmetry reduction: 6 -> 4 parts.

✅ 172_0_0: Reduced from 11 to 8 nodes.
✅ 173_0_1: Reduced from 6 to 4 nodes.
✅ 182_0_4: Reduced from 6 to 5 nodes.
✅ 186_0_5: Reduced from 9 to 7 nodes.
✅ 187_0_6: Reduced from 15 to 13 nodes.
✅ 197_0_7: Reduced from 16 to 14 nodes.
✅ 272_0_9: Reduced from 6 to 5 nodes.
✅ 278_0_10: Reduced from 11 to 8 nodes.
✅ 280_0_11: Reduced from 16 to 15 nodes.
✅ 285_0_12: Reduced from 9 to 7 nodes.
✅ 286_0_13: Reduced from 15 to 14 nodes.
✅ 314_0_15: Reduced from 11 to 8 nodes.
✅ 315_0_16: Reduced from 6 to 4 nodes.
✅ 328_0_17: Reduced from 16 to 14 nodes.
✅ 340_0_19: Reduced from 6 to 5 nodes.
✅ 341_0_20: Reduced from 6 to 5 nodes.
✅ 347_0_21: Reduced from 9 to 7 nodes.
✅ 456_0_23: Reduced from 8 to 7 nodes.
✅ 470_0_24: Reduced from 7 to 6 nodes.
✅ 515_0_27: Reduced from 10 to 9 nodes.
✅ 518_0_29: Reduced from 8 to 7 nodes.
✅ 523_0_30: Reduced from 7 to 5 nodes.
✅ 526_0_31: Reduced from 14 to 12 nodes.
✅ 543_0_33: Reduced from 6 to 4 nodes.
✅ 545_0_34: Reduced from 11 to 8 nodes.
✅ 547_0_35: Reduced from 10 to 7 nodes.
✅ 550_0_36: Reduced from 16 to 14 nodes.
✅ 555_0_39: Reduced from 6 to 5 nodes.
✅ 557_0_40: Reduced from 10 to 9 nodes.
✅ 561_0_41: Reduced from 6 to 5 nodes.
✅ 671_0_43: Reduced from 6 to 4 nodes.
✅ 682_0_44: Reduced from 11 to 7 nodes.
✅ 698_0_46: Reduced from 10 to 6 nodes.
✅ 699_0_47: Reduced from 11 to 8 nodes.
✅ 701_0_48: Reduced from 11 to 7 nodes.
✅ 724_0_50: Reduced from 6 to 4 nodes.
✅ 725_0_51: Reduced from 9 to 6 nodes.
✅ 732_0_52: Reduced from 6 to 4 nodes.
✅ 737_0_53: Reduced from 16 to 15 nodes.
✅ 739_0_54: Reduced from 13 to 12 nodes.
✅ 746_0_56: Reduced from 8 to 6 nodes.
✅ 748_0_57: Reduced from 12 to 11 nodes.
✅ 750_0_58: Reduced from 7 to 5 nodes.
✅ 752_0_59: Reduced from 6 to 5 nodes.
✅ 754_0_60: Reduced from 16 to 11 nodes.
✅ 756_0_61: Reduced from 9 to 6 nodes.
✅ 760_0_62: Reduced from 11 to 7 nodes.
✅ 763_0_63: Reduced from 11 to 9 nodes.
✅ 772_0_65: Reduced from 9 to 7 nodes.
✅ 1282_0_68: Reduced from 8 to 6 nodes.
✅ 1287_0_69: Reduced from 10 to 9 nodes.
✅ 1293_0_70: Reduced from 9 to 6 nodes.
✅ 1295_0_71: Reduced from 6 to 4 nodes.
✅ 1299_0_73: Reduced from 8 to 7 nodes.
✅ 1301_0_74: Reduced from 6 to 4 nodes.
✅ 1314_0_77: Reduced from 12 to 9 nodes.
✅ 1316_0_78: Reduced from 6 to 4 nodes.
✅ 1319_0_79: Reduced from 15 to 14 nodes.
✅ 1331_0_81: Reduced from 12 to 11 nodes.
✅ 1333_0_82: Reduced from 8 to 7 nodes.
✅ 1355_0_84: Reduced from 8 to 6 nodes.
✅ 1359_0_85: Reduced from 6 to 4 nodes.
✅ 1368_0_87: Reduced from 14 to 10 nodes.
✅ 1374_0_89: Reduced from 9 to 7 nodes.
✅ 1377_0_90: Reduced from 12 to 10 nodes.
✅ 1382_0_92: Reduced from 9 to 7 nodes.
✅ 1400_0_94: Reduced from 10 to 9 nodes.
✅ 1403_0_95: Reduced from 15 to 14 nodes.
✅ 1409_0_96: Reduced from 6 to 4 nodes.
✅ 1425_0_97: Reduced from 16 to 15 nodes.
✅ 1441_0_100: Reduced from 6 to 4 nodes.
✅ 1472_0_102: Reduced from 10 to 9 nodes.
✅ 2121_0_106: Reduced from 11 to 8 nodes.
✅ 2132_0_107: Reduced from 8 to 7 nodes.
✅ 2136_0_108: Reduced from 14 to 12 nodes.
✅ 2194_0_110: Reduced from 9 to 8 nodes.
✅ 2198_0_111: Reduced from 6 to 4 nodes.
✅ 2203_0_112: Reduced from 9 to 6 nodes.
✅ 2214_0_113: Reduced from 12 to 8 nodes.
✅ 2217_0_114: Reduced from 6 to 4 nodes.
✅ 2221_0_116: Reduced from 6 to 5 nodes.
✅ 2223_0_117: Reduced from 10 to 7 nodes.
✅ 2225_0_118: Reduced from 6 to 5 nodes.
✅ 2227_0_119: Reduced from 5 to 4 nodes.
✅ 2233_0_120: Reduced from 13 to 11 nodes.
✅ 2236_0_123: Reduced from 7 to 5 nodes.
✅ 2239_0_124: Reduced from 12 to 7 nodes.
✅ 2240_0_125: Reduced from 14 to 11 nodes.
✅ 2241_0_126: Reduced from 6 to 4 nodes.
✅ 2248_0_128: Reduced from 10 to 9 nodes.
✅ 2249_0_129: Reduced from 11 to 7 nodes.
✅ 2252_0_130: Reduced from 11 to 7 nodes.
✅ 2253_0_131: Reduced from 5 to 4 nodes.
✅ 2255_0_132: Reduced from 16 to 14 nodes.
✅ 2262_0_135: Reduced from 8 to 6 nodes.
✅ 2263_0_136: Reduced from 10 to 7 nodes.
✅ 2266_0_137: Reduced from 6 to 4 nodes.
✅ 2269_0_138: Reduced from 7 to 5 nodes.
✅ 2270_0_139: Reduced from 6 to 5 nodes.
✅ 2271_0_140: Reduced from 6 to 5 nodes.
✅ 2276_0_141: Reduced from 9 to 6 nodes.
✅ 2277_0_142: Reduced from 16 to 15 nodes.
✅ 2281_0_144: Reduced from 9 to 6 nodes.
✅ 2283_0_145: Reduced from 9 to 6 nodes.
✅ 2287_0_147: Reduced from 12 to 9 nodes.
✅ 2291_0_148: Reduced from 6 to 5 nodes.
✅ 2293_0_149: Reduced from 12 to 11 nodes.
✅ 2294_0_150: Reduced from 9 to 7 nodes.
✅ 2295_0_151: Reduced from 7 to 5 nodes.
✅ 2302_0_153: Reduced from 9 to 7 nodes.
✅ 2304_0_154: Reduced from 14 to 11 nodes.
✅ 2306_0_155: Reduced from 9 to 6 nodes.
✅ 2307_0_156: Reduced from 13 to 11 nodes.
✅ 2309_0_158: Reduced from 6 to 4 nodes.
✅ 2315_0_161: Reduced from 14 to 10 nodes.
✅ 2316_0_162: Reduced from 4 to 3 nodes.
✅ 2318_0_163: Reduced from 12 to 11 nodes.
✅ 2328_0_167: Reduced from 11 to 8 nodes.
✅ 2330_0_168: Reduced from 6 to 4 nodes.
✅ 2332_0_169: Reduced from 6 to 5 nodes.
✅ 2333_0_170: Reduced from 9 to 8 nodes.
✅ 2334_0_171: Reduced from 12 to 11 nodes.
✅ 2341_0_174: Reduced from 8 to 6 nodes.
✅ 2342_0_175: Reduced from 6 to 5 nodes.
✅ 2344_0_177: Reduced from 6 to 4 nodes.

INFO: Symmetry Found: Mirror pair at [-0.41 -0.56  0.72] and [ 0.41 -0.56  0.72]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.5  -0.4  -0.42] and [ 0.5  -0.4  -0.42]
INFO: Symmetry Found: Mirror pair at [-0.5  -0.4   0.48] and [ 0.5  -0.4   0.48]
INFO: Symmetry Found: Mirror pair at [-0.5   0.37  0.03] and [0.5  0.37 0.03]
INFO: Symmetry Found: Mirror pair at [-0.5   0.15 -0.41] and [ 0.5   0.15 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.5   0.18  0.47] and [0.5  0.18 0.47]
INFO: Symmetry reduction: 16 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.16  0.05] and [ 0.36 -0.16  0.05]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.44  0.46] and [ 0.35 -0.44  0.46]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.59 -0.28] and [ 0.29 -0.59 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.59  0.28] and [ 0.29 -0.59  0.28]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.4   0.41] and [ 0.41 -0.4   0.41]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.49  0.33] and [ 0.33 -0.49  0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.49 -0.3 ] and [ 0.25 -0.49 -0.3 ]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.63  0.11  0.01] and [0.63 0.11 0.01]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.41  0.41] and [ 0.33 -0.41  0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.35 -0.41] and [ 0.34 -0.35 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.31  0.46] and [ 0.37 -0.31  0.46]
INFO: Symmetry Found: Mirror pair at [-0.35  0.04  0.07] and [0.35 0.04 0.07]
INFO: Symmetry reduction: 13 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.42 -0.26] and [ 0.27 -0.42 -0.26]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.42  0.27] and [ 0.27 -0.42  0.27]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.46 -0.32] and [ 0.34 -0.46 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.49  0.36] and [ 0.34 -0.49  0.36]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42  0.31  0.48] and [0.42 0.31 0.48]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.63 -0.42] and [ 0.46 -0.63 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.63  0.44] and [ 0.46 -0.63  0.44]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.28  0.41 -0.29] and [ 0.28  0.41 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.45 -0.29] and [ 0.29 -0.45 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.79 -0.  ] and [ 0.29 -0.79 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.45  0.28] and [ 0.29 -0.45  0.28]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.48  0.35] and [ 0.41 -0.48  0.35]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.49 -0.23] and [ 0.23 -0.49 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.23 -0.47  0.23] and [ 0.23 -0.47  0.23]
INFO: Symmetry Found: Mirror pair at [-0.3   0.45 -0.3 ] and [ 0.3   0.45 -0.3 ]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.36  0.31 -0.4 ] and [ 0.36  0.31 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.12  0.31 -0.4 ] and [ 0.12  0.31 -0.4 ]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.08  0.04] and [ 0.53 -0.08  0.04]
INFO: Symmetry Found: Mirror pair at [-0.53  0.37  0.04] and [0.53 0.37 0.04]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.05  0.03] and [ 0.34 -0.05  0.03]
INFO: Symmetry Found: Mirror pair at [-0.34  0.4  -0.37] and [ 0.34  0.4  -0.37]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.43  0.4 ] and [ 0.34 -0.43  0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.8   0.01] and [ 0.34 -0.8   0.01]
INFO: Symmetry reduction: 15 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.22 -0.5  -0.39] and [ 0.22 -0.5  -0.39]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.51 -0.59 -0.53] and [ 0.51 -0.59 -0.53]
INFO: Symmetry Found: Mirror pair at [-0.51 -0.59  0.54] and [ 0.51 -0.59  0.54]
INFO: Symmetry reduction: 5 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.31  0.03] and [ 0.47 -0.31  0.03]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.51 -0.4 ] and [ 0.37 -0.51 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.47  0.4 ] and [ 0.36 -0.47  0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.18  0.01] and [ 0.37 -0.18  0.01]
INFO: Symmetry reduction: 12 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.52 -0.3 ] and [ 0.31 -0.52 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.52  0.3 ] and [ 0.31 -0.52  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.17  0.09] and [ 0.3  -0.17  0.09]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.74  0.  ] and [ 0.39 -0.74  0.  ]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.7  -0.38] and [ 0.33 -0.7  -0.38]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.7   0.48] and [ 0.34 -0.7   0.48]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.6  -0.16 -0.02] and [ 0.6  -0.16 -0.02]
INFO: Symmetry Found: Mirror pair at [-0.6   0.26  0.01] and [0.6  0.26 0.01]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.34  0.62] and [ 0.47 -0.34  0.62]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.44 -0.36] and [ 0.36 -0.44 -0.36]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.32 -0.33] and [ 0.4  -0.32 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.33  0.44] and [ 0.4  -0.33  0.44]
INFO: Symmetry Found: Mirror pair at [-0.4   0.1  -0.01] and [ 0.4   0.1  -0.01]
INFO: Symmetry Found: Mirror pair at [-0.4   0.56 -0.34] and [ 0.4   0.56 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.4   0.28 -0.28] and [ 0.4   0.28 -0.28]
INFO: Symmetry reduction: 12 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.42 -0.3 ] and [ 0.36 -0.42 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.43  0.35] and [ 0.36 -0.43  0.35]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.5  -0.17] and [ 0.3  -0.5  -0.17]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.5   0.27] and [ 0.3  -0.5   0.27]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.54 -0.44] and [ 0.47 -0.54 -0.44]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.53  0.5 ] and [ 0.47 -0.53  0.5 ]
INFO: Symmetry Found: Mirror pair at [-0.46  0.18 -0.21] and [ 0.46  0.18 -0.21]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.39 -0.32] and [ 0.4   0.39 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.36 -0.33] and [ 0.4  -0.36 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.73  0.02] and [ 0.41 -0.73  0.02]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.36  0.33] and [ 0.4  -0.36  0.33]
INFO: Symmetry reduction: 13 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.48 -0.32  0.51] and [ 0.48 -0.32  0.51]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.31 -0.37] and [ 0.42 -0.31 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.31  0.33] and [ 0.42 -0.31  0.33]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.54  0.01 -0.04] and [ 0.54  0.01 -0.04]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.58  0.13 -0.  ] and [ 0.58  0.13 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.68 -0.53 -0.54] and [ 0.68 -0.53 -0.54]
INFO: Symmetry Found: Mirror pair at [-0.68 -0.53  0.53] and [ 0.68 -0.53  0.53]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.48  0.49] and [ 0.34 -0.48  0.49]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.48 -0.42] and [ 0.41 -0.48 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.46  0.15  0.45] and [0.47 0.15 0.45]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.41  0.04  0.01] and [0.41 0.04 0.01]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.03  0.13] and [ 0.44 -0.03  0.13]
INFO: Symmetry reduction: 4 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.03  0.1 ] and [ 0.43 -0.03  0.1 ]
INFO: Symmetry reduction: 4 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.16  0.2  -0.36] and [ 0.16  0.2  -0.36]
INFO: Symmetry Found: Mirror pair at [-0.05  0.2  -0.36] and [ 0.06  0.2  -0.36]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.56 -0.5  -0.51] and [ 0.56 -0.5  -0.51]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.29  0.05 -0.2 ] and [ 0.29  0.05 -0.2 ]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.48 -0.23] and [ 0.33 -0.48 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.48  0.34] and [ 0.33 -0.48  0.34]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.44  0.43 -0.42] and [ 0.44  0.43 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.69  0.03] and [ 0.42 -0.69  0.03]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.41 -0.38] and [ 0.42 -0.41 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.41  0.44] and [ 0.42 -0.41  0.44]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.33  0.39 -0.32] and [ 0.33  0.39 -0.32]
INFO: Symmetry reduction: 13 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.22 -0.31] and [ 0.41  0.22 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.2   0.22 -0.31] and [ 0.21  0.22 -0.31]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.51 -0.36] and [ 0.36 -0.51 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.51  0.36] and [ 0.36 -0.51  0.36]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.41 -0.39] and [ 0.47 -0.41 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.13  0.03] and [ 0.47 -0.13  0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.2   0.  ] and [ 0.25 -0.2   0.  ]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.43 -0.34] and [ 0.34 -0.43 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.43  0.4 ] and [ 0.34 -0.43  0.4 ]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.36 -0.29] and [ 0.29 -0.36 -0.29]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.49  0.13  0.11] and [0.49 0.13 0.11]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.09 -0.02] and [ 0.4   0.09 -0.02]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.26  0.4  -0.31] and [ 0.26  0.4  -0.31]
INFO: Symmetry reduction: 13 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.67 -0.34] and [ 0.31 -0.67 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.67  0.32] and [ 0.31 -0.67  0.32]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.45 -0.37] and [ 0.36 -0.45 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.45  0.4 ] and [ 0.36 -0.45  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.05 -0.33] and [ 0.28 -0.05 -0.33]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.56 -0.28] and [ 0.28 -0.56 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.55  0.28] and [ 0.28 -0.55  0.28]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.49  0.12 -0.01] and [ 0.49  0.12 -0.01]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.3   0.41 -0.4 ] and [ 0.3   0.41 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.54 -0.4 ] and [ 0.33 -0.54 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.59  0.01] and [ 0.32 -0.59  0.01]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.54  0.41] and [ 0.33 -0.54  0.41]
INFO: Symmetry reduction: 14 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.51 -0.14 -0.01] and [ 0.51 -0.14 -0.01]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.42  0.3  -0.32] and [ 0.42  0.3  -0.32]
INFO: Symmetry Found: Mirror pair at [-0.15  0.3  -0.42] and [ 0.15  0.3  -0.42]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.26 -0.61 -0.28] and [ 0.26 -0.61 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.63  0.28] and [ 0.25 -0.63  0.28]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47 -0.33] and [ 0.29 -0.47 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47  0.45] and [ 0.29 -0.47  0.45]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.36 -0.24] and [ 0.25 -0.36 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.36  0.34] and [ 0.25 -0.36  0.34]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.56 -0.21 -0.03] and [ 0.56 -0.21 -0.03]
INFO: Symmetry reduction: 4 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.37 -0.31] and [ 0.42 -0.37 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.36  0.31] and [ 0.42 -0.36  0.31]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42  0.35  0.01] and [0.42 0.35 0.01]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.49 -0.41] and [ 0.28 -0.49 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.5   0.39] and [ 0.3  -0.5   0.39]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.64  0.01  0.03] and [0.64 0.01 0.03]
INFO: Symmetry Found: Mirror pair at [-0.64 -0.49  0.45] and [ 0.64 -0.49  0.45]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.23  0.37 -0.16] and [ 0.24  0.37 -0.16]
INFO: Symmetry Found: Mirror pair at [-0.11  0.37 -0.16] and [ 0.12  0.37 -0.16]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.46 -0.39] and [ 0.36 -0.46 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.45  0.34] and [ 0.36 -0.45  0.34]
INFO: Symmetry Found: Mirror pair at [-0.36  0.33 -0.39] and [ 0.36  0.33 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.16 -0.01] and [ 0.44 -0.16 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.19 -0.03] and [ 0.39 -0.19 -0.03]
INFO: Symmetry reduction: 15 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.29 -0.33] and [ 0.3  -0.29 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.47  0.05] and [ 0.3  -0.47  0.05]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.29  0.31] and [ 0.3  -0.29  0.31]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.42 -0.33] and [ 0.32 -0.42 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.13 -0.  ] and [ 0.38 -0.13 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.42  0.34] and [ 0.32 -0.42  0.34]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.42 -0.3 ] and [ 0.3  -0.42 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.41  0.3 ] and [ 0.3  -0.41  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.59 -0.09  0.  ] and [ 0.59 -0.09  0.  ]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.53 -0.49] and [ 0.59 -0.53 -0.49]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.53  0.51] and [ 0.59 -0.53  0.51]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.6   0.58] and [ 0.53 -0.6   0.58]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.37 -0.33] and [ 0.36 -0.37 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.22  0.01] and [ 0.36 -0.22  0.01]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.37  0.36] and [ 0.36 -0.37  0.36]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.24  0.01] and [ 0.4  -0.24  0.01]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.55 -0.23 -0.12] and [ 0.55 -0.23 -0.12]
INFO: Symmetry reduction: 4 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.47 -0.22] and [ 0.31 -0.47 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.48  0.24] and [ 0.3  -0.48  0.24]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.46  0.34] and [ 0.32 -0.46  0.34]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.3  -0.27] and [ 0.25 -0.3  -0.27]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.3   0.3 ] and [ 0.25 -0.3   0.3 ]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.38  0.18 -0.07] and [ 0.38  0.18 -0.07]
INFO: Symmetry Found: Mirror pair at [-0.36  0.15 -0.33] and [ 0.36  0.15 -0.33]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.37  0.35 -0.34] and [ 0.37  0.35 -0.34]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.47  0.22 -0.09] and [ 0.47  0.22 -0.09]
INFO: Symmetry Found: Mirror pair at [-0.47  0.01  0.45] and [0.47 0.01 0.45]
INFO: Symmetry Found: Mirror pair at [-0.46 -0.19 -0.61] and [ 0.46 -0.19 -0.61]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.56  0.03] and [ 0.47 -0.56  0.03]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.32  0.67] and [ 0.47 -0.32  0.67]
INFO: Symmetry reduction: 15 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.48  0.41] and [ 0.32 -0.48  0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.48  0.06  0.14] and [0.48 0.06 0.14]
INFO: Symmetry Found: Mirror pair at [-0.52 -0.56  0.49] and [ 0.52 -0.56  0.49]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.49 -0.19] and [ 0.27 -0.49 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.49  0.28] and [ 0.27 -0.49  0.28]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.07  0.14 -0.24] and [ 0.07  0.14 -0.24]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.43  0.44] and [ 0.44 -0.43  0.44]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.04  0.12] and [ 0.42 -0.04  0.12]
INFO: Symmetry Found: Mirror pair at [-0.42  0.33  0.07] and [0.42 0.33 0.07]
INFO: Symmetry Found: Mirror pair at [-0.42  0.13  0.44] and [0.42 0.13 0.44]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.54 -0.31] and [ 0.32 -0.54 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.54  0.32] and [ 0.32 -0.54  0.32]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.5   0.45] and [ 0.35 -0.5   0.45]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.58  0.6 ] and [ 0.43 -0.58  0.6 ]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.58 -0.08  0.03] and [ 0.58 -0.08  0.03]
INFO: Symmetry Found: Mirror pair at [-0.58  0.31  0.05] and [0.58 0.31 0.05]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.36 -0.34] and [ 0.33 -0.36 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.36  0.35] and [ 0.33 -0.36  0.35]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.63 -0.06 -0.01] and [ 0.63 -0.06 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.59 -0.59 -0.48] and [ 0.59 -0.59 -0.48]

✅ 2345_0_178: Reduced from 12 to 10 nodes.
✅ 2346_0_179: Reduced from 16 to 11 nodes.
✅ 2350_0_180: Reduced from 10 to 8 nodes.
✅ 2351_0_181: Reduced from 6 to 4 nodes.
✅ 2352_0_182: Reduced from 7 to 6 nodes.
✅ 2354_0_183: Reduced from 9 to 7 nodes.
✅ 2355_0_184: Reduced from 7 to 6 nodes.
✅ 2360_0_186: Reduced from 6 to 5 nodes.
✅ 2365_0_187: Reduced from 13 to 10 nodes.
✅ 2369_0_189: Reduced from 6 to 4 nodes.
✅ 2370_0_190: Reduced from 6 to 4 nodes.
✅ 2371_0_191: Reduced from 9 to 6 nodes.
✅ 2373_0_192: Reduced from 11 to 7 nodes.
✅ 2374_0_193: Reduced from 8 to 7 nodes.
✅ 2376_0_194: Reduced from 11 to 8 nodes.
✅ 2379_0_196: Reduced from 10 to 8 nodes.
✅ 2382_0_197: Reduced from 9 to 7 nodes.
✅ 2384_0_199: Reduced from 15 to 11 nodes.
✅ 2396_0_202: Reduced from 8 to 7 nodes.
✅ 2399_0_204: Reduced from 5 to 3 nodes.
✅ 2406_0_207: Reduced from 6 to 5 nodes.
✅ 2410_0_209: Reduced from 12 to 9 nodes.
✅ 2412_0_210: Reduced from 6 to 4 nodes.
✅ 2416_0_211: Reduced from 16 to 15 nodes.
✅ 2423_0_214: Reduced from 12 to 11 nodes.
✅ 2424_0_215: Reduced from 7 to 5 nodes.
✅ 2429_0_216: Reduced from 11 to 9 nodes.
✅ 2435_0_219: Reduced from 10 to 9 nodes.
✅ 2436_0_220: Reduced from 6 to 5 nodes.
✅ 2437_0_221: Reduced from 12 to 7 nodes.
✅ 2439_0_222: Reduced from 6 to 4 nodes.
✅ 2446_0_225: Reduced from 11 to 9 nodes.
✅ 2447_0_226: Reduced from 11 to 8 nodes.
✅ 2448_0_227: Reduced from 13 to 9 nodes.
✅ 2449_0_228: Reduced from 15 to 14 nodes.
✅ 2454_0_229: Reduced from 6 to 4 nodes.
✅ 2457_0_230: Reduced from 8 to 7 nodes.
✅ 2458_0_231: Reduced from 11 to 8 nodes.
✅ 2464_0_234: Reduced from 9 to 8 nodes.
✅ 2466_0_235: Reduced from 10 to 8 nodes.
✅ 2470_0_237: Reduced from 9 to 8 nodes.
✅ 2476_0_239: Reduced from 4 to 3 nodes.
✅ 2478_0_240: Reduced from 4 to 3 nodes.
✅ 2479_0_241: Reduced from 13 to 11 nodes.
✅ 2483_0_243: Reduced from 10 to 9 nodes.
✅ 2493_0_246: Reduced from 7 to 6 nodes.
✅ 2495_0_248: Reduced from 12 to 10 nodes.
✅ 2497_0_249: Reduced from 16 to 12 nodes.
✅ 2502_0_251: Reduced from 13 to 12 nodes.
✅ 2503_0_252: Reduced from 11 to 9 nodes.
✅ 2505_0_253: Reduced from 6 to 4 nodes.
✅ 2506_0_254: Reduced from 14 to 12 nodes.
✅ 2508_0_255: Reduced from 15 to 14 nodes.
✅ 2511_0_257: Reduced from 9 to 7 nodes.
✅ 2516_0_259: Reduced from 7 to 6 nodes.
✅ 2524_0_262: Reduced from 10 to 9 nodes.
✅ 2529_0_263: Reduced from 5 to 4 nodes.
✅ 2535_0_266: Reduced from 13 to 12 nodes.
✅ 2539_0_267: Reduced from 6 to 4 nodes.
✅ 2542_0_269: Reduced from 6 to 4 nodes.
✅ 2544_0_270: Reduced from 6 to 5 nodes.
✅ 2545_0_271: Reduced from 6 to 4 nodes.
✅ 2546_0_272: Reduced from 7 to 6 nodes.
✅ 2558_0_273: Reduced from 14 to 10 nodes.
✅ 2562_0_274: Reduced from 9 to 8 nodes.
✅ 2567_0_276: Reduced from 13 to 11 nodes.
✅ 2570_0_278: Reduced from 6 to 4 nodes.
✅ 2574_0_280: Reduced from 6 to 4 nodes.
✅ 2582_0_284: Reduced from 9 to 7 nodes.
✅ 2584_0_285: Reduced from 4 to 3 nodes.
✅ 2585_0_286: Reduced from 6 to 4 nodes.
✅ 2586_0_287: Reduced from 15 to 14 nodes.
✅ 2592_0_291: Reduced from 6 to 4 nodes.
✅ 2598_0_294: Reduced from 9 to 7 nodes.
✅ 2602_0_296: Reduced from 11 to 9 nodes.
✅ 2605_0_297: Reduced from 15 to 10 nodes.
✅ 2607_0_298: Reduced from 10 to 7 nodes.
✅ 2611_0_299: Reduced from 10 to 7 nodes.
✅ 2612_0_300: Reduced from 6 to 4 nodes.
✅ 2614_0_301: Reduced from 9 to 6 nodes.
✅ 2620_0_302: Reduced from 10 to 9 nodes.
✅ 2623_0_303: Reduced from 10 to 7 nodes.
✅ 2631_0_306: Reduced from 16 to 15 nodes.
✅ 2636_0_307: Reduced from 4 to 3 nodes.
✅ 2637_0_308: Reduced from 6 to 4 nodes.
✅ 2645_0_310: Reduced from 7 to 6 nodes.
✅ 2647_0_311: Reduced from 9 to 7 nodes.
✅ 2648_0_312: Reduced from 12 to 10 nodes.
✅ 2650_0_313: Reduced from 8 to 7 nodes.
✅ 2653_0_314: Reduced from 15 to 10 nodes.
✅ 2655_0_315: Reduced from 6 to 5 nodes.
✅ 2656_0_316: Reduced from 8 to 6 nodes.
✅ 2663_0_317: Reduced from 11 to 9 nodes.
✅ 2666_0_319: Reduced from 12 to 11 nodes.
✅ 2673_0_320: Reduced from 16 to 12 nodes.
✅ 2681_0_323: Reduced from 7 to 5 nodes.
✅ 2684_0_324: Reduced from 12 to 11 nodes.
✅ 2687_0_325: Reduced from 8 to 7 nodes.
✅ 2691_0_327: Reduced from 9 to 7 nodes.
✅ 2692_0_328: Reduced from 6 to 4 nodes.
✅ 2694_0_329: Reduced from 9 to 6 nodes.
✅ 2700_0_330: Reduced from 4 to 3 nodes.
✅ 2707_0_333: Reduced from 8 to 7 nodes.
✅ 2710_0_335: Reduced from 4 to 3 nodes.
✅ 2711_0_336: Reduced from 7 to 6 nodes.
✅ 2712_0_337: Reduced from 10 to 6 nodes.
✅ 2723_0_339: Reduced from 6 to 4 nodes.
✅ 2728_0_340: Reduced from 13 to 10 nodes.
✅ 2731_0_341: Reduced from 15 to 11 nodes.
✅ 2741_0_343: Reduced from 8 to 7 nodes.
✅ 2746_0_344: Reduced from 11 to 7 nodes.
✅ 2750_0_345: Reduced from 7 to 5 nodes.
✅ 2752_0_346: Reduced from 6 to 5 nodes.
✅ 2755_0_348: Reduced from 10 to 7 nodes.
✅ 2759_0_350: Reduced from 14 to 11 nodes.
✅ 2764_0_351: Reduced from 9 to 6 nodes.
✅ 2769_0_352: Reduced from 8 to 5 nodes.
✅ 2770_0_353: Reduced from 6 to 4 nodes.
✅ 2772_0_354: Reduced from 6 to 5 nodes.
✅ 2773_0_355: Reduced from 5 to 4 nodes.
✅ 2774_0_356: Reduced from 12 to 9 nodes.
✅ 2785_0_359: Reduced from 10 to 8 nodes.
✅ 2786_0_360: Reduced from 10 to 7 nodes.
✅ 2788_0_361: Reduced from 13 to 12 nodes.
✅ 2789_0_362: Reduced from 14 to 11 nodes.
✅ 2790_0_363: Reduced from 6 to 4 nodes.
✅ 2797_0_365: Reduced from 6 to 5 nodes.
✅ 2799_0_366: Reduced from 6 to 5 nodes.
✅ 2804_0_369: Reduced from 6 to 4 nodes.
✅ 2810_0_371: Reduced from 16 to 12 nodes.
✅ 2815_0_374: Reduced from 6 to 5 nodes.
✅ 2817_0_375: Reduced from 11 to 10 nodes.
✅ 2820_0_376: Reduced from 15 to 13 nodes.
✅ 2827_0_377: Reduced from 14 to 13 nodes.
✅ 2828_0_378: Reduced from 9 to 7 nodes.
✅ 2830_0_379: Reduced from 8 to 5 nodes.

INFO: Symmetry Found: Mirror pair at [-0.44 -0.67 -0.05] and [ 0.44 -0.67 -0.05]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.17  0.32 -0.21] and [ 0.17  0.32 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.06  0.32 -0.21] and [ 0.06  0.32 -0.21]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.58  0.42] and [ 0.4  -0.58  0.42]
INFO: Symmetry Found: Mirror pair at [-0.46  0.27 -0.  ] and [ 0.46  0.27 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.41  0.27  0.04] and [0.41 0.27 0.04]
INFO: Symmetry reduction: 16 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.28  0.33 -0.21] and [ 0.29  0.33 -0.21]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.27  0.49 -0.22] and [ 0.27  0.49 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.09  0.49 -0.22] and [ 0.09  0.49 -0.22]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.31  0.23] and [ 0.34 -0.31  0.23]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.59 -0.37] and [ 0.36 -0.59 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.6   0.37] and [ 0.36 -0.6   0.37]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.46  0.31] and [ 0.28 -0.46  0.31]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.16 -0.02] and [ 0.29 -0.16 -0.02]
INFO: Symmetry Found: Mirror pair at [-0.3   0.28 -0.35] and [ 0.3   0.28 -0.35]
INFO: Symmetry reduction: 14 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48 -0.18] and [ 0.31 -0.48 -0.18]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.48  0.21] and [ 0.32 -0.48  0.21]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.29  0.42 -0.32] and [ 0.29  0.42 -0.32]
INFO: Symmetry reduction: 13 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.42 -0.34] and [ 0.35 -0.42 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.42  0.34] and [ 0.35 -0.42  0.34]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.45 -0.43  0.47] and [ 0.45 -0.43  0.47]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.17  0.28 -0.29] and [ 0.18  0.28 -0.29]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.53  0.1  -0.  ] and [ 0.53  0.1  -0.  ]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.43 -0.31] and [ 0.38 -0.43 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.42  0.38] and [ 0.38 -0.42  0.38]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.5  -0.42  0.47] and [ 0.5  -0.42  0.47]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.5  -0.45] and [ 0.53 -0.5  -0.45]
INFO: Symmetry Found: Mirror pair at [-0.53 -0.5   0.55] and [ 0.53 -0.5   0.55]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.5  -0.13] and [ 0.34 -0.5  -0.13]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.06  0.03] and [ 0.34 -0.06  0.03]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.42 -0.36] and [ 0.34 -0.42 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.03] and [ 0.34 -0.51  0.03]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.42  0.42] and [ 0.34 -0.42  0.42]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.43 -0.32] and [ 0.4  -0.43 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.41 -0.42  0.43] and [ 0.4  -0.42  0.43]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.63 -0.38 -0.51] and [ 0.63 -0.38 -0.51]
INFO: Symmetry Found: Mirror pair at [-0.64 -0.3   0.51] and [ 0.64 -0.3   0.51]
INFO: Symmetry Found: Mirror pair at [-0.64  0.17  0.03] and [0.64 0.17 0.03]
INFO: Symmetry Found: Mirror pair at [-0.64 -0.04 -0.51] and [ 0.64 -0.04 -0.51]
INFO: Symmetry Found: Mirror pair at [-0.65 -0.    0.51] and [ 0.65 -0.    0.51]
INFO: Symmetry reduction: 14 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.48 -0.19] and [ 0.3  -0.48 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.48  0.41] and [ 0.3  -0.48  0.41]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.5  -0.11] and [ 0.23 -0.5  -0.11]
INFO: Symmetry Found: Mirror pair at [-0.23 -0.5   0.26] and [ 0.23 -0.5   0.26]
INFO: Symmetry Found: Mirror pair at [-0.21  0.38 -0.16] and [ 0.2   0.38 -0.16]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.7   0.03] and [ 0.43 -0.7   0.03]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.51  0.34] and [ 0.32 -0.51  0.34]
INFO: Symmetry reduction: 14 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.33  0.44 -0.34] and [ 0.33  0.44 -0.34]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.53 -0.24] and [ 0.23 -0.53 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.22 -0.53  0.23] and [ 0.22 -0.53  0.23]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.45  0.45] and [ 0.37 -0.45  0.45]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.77 -0.  ] and [ 0.37 -0.77 -0.  ]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.58 -0.2 ] and [ 0.34 -0.58 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.58  0.3 ] and [ 0.34 -0.58  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.26  0.24 -0.22] and [ 0.26  0.24 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.09  0.24 -0.22] and [ 0.08  0.24 -0.22]
INFO: Symmetry reduction: 10 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.42  0.46] and [ 0.38 -0.42  0.46]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.75  0.03] and [ 0.43 -0.75  0.03]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.08  0.  ] and [0.59 0.08 0.  ]
INFO: Symmetry Found: Mirror pair at [-0.57 -0.44 -0.53] and [ 0.57 -0.44 -0.53]
INFO: Symmetry Found: Mirror pair at [-0.57 -0.44  0.51] and [ 0.57 -0.44  0.51]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.37 -0.01] and [ 0.58 -0.37 -0.01]
INFO: Symmetry reduction: 13 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.55  0.16  0.17] and [0.55 0.16 0.17]
INFO: Symmetry reduction: 4 -> 3 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.32  0.42] and [ 0.3  -0.32  0.42]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.65  0.4 ] and [ 0.3  -0.65  0.4 ]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.48 -0.39] and [ 0.4  -0.48 -0.39]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.38  0.41] and [ 0.41 -0.38  0.41]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.39  0.45] and [ 0.34 -0.39  0.45]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.15  0.07] and [ 0.33 -0.15  0.07]
INFO: Symmetry Found: Mirror pair at [-0.37  0.26 -0.02] and [ 0.37  0.26 -0.02]
INFO: Symmetry Found: Mirror pair at [-0.37  0.02  0.04] and [0.37 0.02 0.04]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52 -0.28] and [ 0.49 -0.52 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.48 -0.72 -0.  ] and [ 0.48 -0.72 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.28] and [ 0.49 -0.52  0.28]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.45 -0.1   0.06] and [ 0.45 -0.1   0.06]
INFO: Symmetry Found: Mirror pair at [-0.45 -0.6  -0.38] and [ 0.45 -0.6  -0.38]
INFO: Symmetry Found: Mirror pair at [-0.45 -0.6   0.41] and [ 0.45 -0.6   0.41]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.3   0.06  0.09] and [0.3  0.06 0.09]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.06  0.28] and [ 0.29 -0.06  0.28]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.5   0.33] and [ 0.33 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.28] and [ 0.25 -0.5  -0.28]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.48  0.29 -0.  ] and [ 0.48  0.29 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.5   0.07 -0.46] and [ 0.5   0.07 -0.46]
INFO: Symmetry Found: Mirror pair at [-0.49  0.21  0.52] and [0.49 0.21 0.52]
INFO: Symmetry reduction: 12 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.35  0.1  -0.45] and [ 0.35  0.1  -0.45]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.45  0.23  0.22] and [0.45 0.23 0.22]
INFO: Symmetry Found: Mirror pair at [-0.45 -0.36  0.46] and [ 0.45 -0.36  0.46]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.65 -0.39 -0.57] and [ 0.65 -0.39 -0.57]
INFO: Symmetry Found: Mirror pair at [-0.64  0.33 -0.05] and [ 0.64  0.33 -0.05]
INFO: Symmetry Found: Mirror pair at [-0.64  0.   -0.58] and [ 0.64  0.   -0.58]
INFO: Symmetry Found: Mirror pair at [-0.64  0.02  0.51] and [0.64 0.02 0.51]
INFO: Symmetry reduction: 12 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.43 -0.21] and [ 0.33 -0.43 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.33 -0.43  0.34] and [ 0.33 -0.43  0.34]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.67  0.38] and [ 0.46 -0.67  0.38]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.4  -0.34] and [ 0.37 -0.4  -0.34]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.38  0.41] and [ 0.38 -0.38  0.41]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.73  0.42] and [ 0.39 -0.73  0.42]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.47  0.23 -0.03] and [ 0.47  0.23 -0.03]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.59 -0.38] and [ 0.43 -0.59 -0.38]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.33 -0.3 ] and [ 0.25 -0.33 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.28  0.01] and [ 0.25 -0.28  0.01]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.33  0.3 ] and [ 0.25 -0.33  0.3 ]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.21 -0.48 -0.22] and [ 0.2  -0.48 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.21 -0.47  0.22] and [ 0.2  -0.47  0.22]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.18 -0.55 -0.18] and [ 0.18 -0.55 -0.18]
INFO: Symmetry Found: Mirror pair at [-0.19 -0.55  0.19] and [ 0.19 -0.55  0.19]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.54 -0.25] and [ 0.25 -0.54 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.53  0.28] and [ 0.25 -0.53  0.28]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.32 -0.29] and [ 0.43 -0.32 -0.29]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.64 -0.2 ] and [ 0.23 -0.64 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.22 -0.64  0.22] and [ 0.22 -0.64  0.22]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.45 -0.19  0.08] and [ 0.45 -0.19  0.08]
INFO: Symmetry Found: Mirror pair at [-0.45  0.21  0.1 ] and [0.45 0.21 0.1 ]
INFO: Symmetry Found: Mirror pair at [-0.46  0.01 -0.28] and [ 0.46  0.01 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.46  0.01  0.48] and [0.46 0.01 0.48]
INFO: Symmetry reduction: 14 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.57 -0.42] and [ 0.37 -0.57 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.57  0.42] and [ 0.36 -0.57  0.42]
INFO: Symmetry Found: Mirror pair at [-0.15  0.13 -0.38] and [ 0.15  0.13 -0.38]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.47 -0.02  0.08] and [ 0.47 -0.02  0.08]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.49  0.01  0.11] and [0.49 0.01 0.11]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.48 -0.61] and [ 0.58 -0.48 -0.61]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.48  0.56] and [ 0.58 -0.48  0.56]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.36 -0.02] and [ 0.58 -0.36 -0.02]
INFO: Symmetry reduction: 14 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.35 -0.31] and [ 0.37 -0.35 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.34  0.4 ] and [ 0.37 -0.34  0.4 ]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.6   0.49] and [ 0.43 -0.6   0.49]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.63 -0.23] and [ 0.24 -0.63 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.63  0.24] and [ 0.24 -0.63  0.24]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.46 -0.25] and [ 0.33 -0.46 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.46  0.4 ] and [ 0.34 -0.46  0.4 ]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.39 -0.38] and [ 0.38 -0.39 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.39  0.39] and [ 0.38 -0.39  0.39]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.37  0.24 -0.22] and [ 0.37  0.24 -0.22]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.48 -0.25] and [ 0.32 -0.48 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48  0.39] and [ 0.31 -0.48  0.39]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.05 -0.3 ] and [ 0.38 -0.05 -0.3 ]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.18  0.37 -0.37] and [ 0.18  0.37 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.32  0.4  -0.33] and [ 0.32  0.4  -0.33]
INFO: Symmetry Found: Mirror pair at [-0.06  0.37 -0.37] and [ 0.06  0.37 -0.37]
INFO: Symmetry reduction: 13 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.36 -0.26] and [ 0.36 -0.36 -0.26]
INFO: Symmetry Found: Mirror pair at [-0.41 -0.34  0.4 ] and [ 0.41 -0.34  0.4 ]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34  0.12  0.03] and [0.34 0.12 0.03]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.38 -0.28] and [ 0.34 -0.38 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.38  0.34] and [ 0.34 -0.38  0.34]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.04 -0.04] and [ 0.33 -0.04 -0.04]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.57  0.28] and [ 0.28 -0.57  0.28]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.53  0.32  0.15] and [0.53 0.32 0.15]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.49  0.32] and [ 0.32 -0.49  0.32]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.49 -0.13 -0.04] and [ 0.49 -0.13 -0.04]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.28 -0.04] and [ 0.53 -0.28 -0.04]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.2   0.17 -0.29] and [ 0.2   0.17 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.07  0.17 -0.29] and [ 0.07  0.17 -0.29]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.5  -0.29] and [ 0.24 -0.5  -0.29]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.5   0.44] and [ 0.31 -0.5   0.44]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.52 -0.27] and [ 0.28 -0.52 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.52  0.33] and [ 0.28 -0.52  0.33]
INFO: Symmetry Found: Mirror pair at [-0.3   0.28 -0.28] and [ 0.3   0.28 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.15  0.28 -0.28] and [ 0.15  0.28 -0.28]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.51  0.21  0.  ] and [0.51 0.21 0.  ]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.22  0.09] and [ 0.41 -0.22  0.09]
INFO: Symmetry Found: Mirror pair at [-0.41 -0.08 -0.33] and [ 0.41 -0.08 -0.33]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.31 -0.42] and [ 0.39 -0.31 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.63 -0.  ] and [ 0.4  -0.63 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.31  0.45] and [ 0.39 -0.31  0.45]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.49 -0.56  0.26] and [ 0.49 -0.56  0.26]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.46 -0.32] and [ 0.25 -0.46 -0.32]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.46  0.34] and [ 0.37 -0.46  0.34]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.22 -0.36 -0.23] and [ 0.22 -0.36 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.36  0.35] and [ 0.35 -0.36  0.35]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.49 -0.27] and [ 0.28 -0.49 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.76  0.08] and [ 0.29 -0.76  0.08]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.49  0.4 ] and [ 0.28 -0.49  0.4 ]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.38 -0.27] and [ 0.39 -0.38 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.37  0.39] and [ 0.39 -0.37  0.39]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.47 -0.39] and [ 0.44 -0.47 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.47  0.33] and [ 0.44 -0.47  0.33]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.18  0.4   0.02] and [0.18 0.4  0.02]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.28 -0.  ] and [ 0.36 -0.28 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.65  0.  ] and [ 0.36 -0.65  0.  ]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.13 -0.3 ] and [ 0.27 -0.13 -0.3 ]
INFO: Symmetry reduction: 14 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.42 -0.31] and [ 0.3  -0.42 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.63 -0.01] and [ 0.32 -0.63 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.42  0.29] and [ 0.3  -0.42  0.29]
INFO: Symmetry reduction: 16 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.11  0.4  -0.24] and [ 0.1   0.4  -0.24]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.53 -0.09  0.01] and [ 0.53 -0.09  0.01]
INFO: Symmetry Found: Mirror pair at [-0.53 -0.57 -0.52] and [ 0.53 -0.57 -0.52]
INFO: Symmetry Found: Mirror pair at [-0.53 -0.57  0.6 ] and [ 0.53 -0.57  0.6 ]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.46 -0.47 -0.41] and [ 0.46 -0.47 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.46 -0.47  0.43] and [ 0.46 -0.47  0.43]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.3  -0.35] and [ 0.31  0.3  -0.35]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.55 -0.34] and [ 0.35 -0.55 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.55  0.36] and [ 0.35 -0.55  0.36]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.53 -0.41] and [ 0.4  -0.53 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.52  0.41] and [ 0.37 -0.52  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.27 -0.56 -0.27] and [ 0.27 -0.56 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.56  0.27] and [ 0.27 -0.56  0.27]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.59 -0.46] and [ 0.38 -0.59 -0.46]
INFO: Symmetry Found: Mirror pair at [-0.47 -0.56  0.45] and [ 0.46 -0.56  0.45]

✅ 2832_0_380: Reduced from 9 to 6 nodes.
✅ 2834_0_381: Reduced from 12 to 10 nodes.
✅ 2847_0_383: Reduced from 16 to 13 nodes.
✅ 2855_0_385: Reduced from 11 to 10 nodes.
✅ 2864_0_386: Reduced from 10 to 8 nodes.
✅ 2867_0_389: Reduced from 6 to 5 nodes.
✅ 2868_0_390: Reduced from 6 to 4 nodes.
✅ 2869_0_391: Reduced from 14 to 11 nodes.
✅ 2878_0_394: Reduced from 8 to 6 nodes.
✅ 2882_0_396: Reduced from 13 to 12 nodes.
✅ 2885_0_397: Reduced from 7 to 5 nodes.
✅ 2886_0_398: Reduced from 9 to 8 nodes.
✅ 2893_0_399: Reduced from 11 to 10 nodes.
✅ 2896_0_400: Reduced from 5 to 4 nodes.
✅ 2898_0_401: Reduced from 7 to 5 nodes.
✅ 2900_0_402: Reduced from 12 to 11 nodes.
✅ 2903_0_403: Reduced from 10 to 8 nodes.
✅ 2904_0_404: Reduced from 6 to 5 nodes.
✅ 2906_0_405: Reduced from 16 to 12 nodes.
✅ 2908_0_406: Reduced from 12 to 10 nodes.
✅ 2913_0_408: Reduced from 14 to 9 nodes.
✅ 2930_0_411: Reduced from 11 to 9 nodes.
✅ 2943_0_413: Reduced from 10 to 7 nodes.
✅ 2946_0_414: Reduced from 12 to 11 nodes.
✅ 2947_0_415: Reduced from 14 to 13 nodes.
✅ 2948_0_416: Reduced from 9 to 8 nodes.
✅ 2957_0_421: Reduced from 6 to 4 nodes.
✅ 2959_0_423: Reduced from 11 to 9 nodes.
✅ 2960_0_424: Reduced from 10 to 6 nodes.
✅ 2975_0_428: Reduced from 10 to 8 nodes.
✅ 2980_0_429: Reduced from 13 to 9 nodes.
✅ 2993_0_432: Reduced from 4 to 3 nodes.
✅ 3005_0_436: Reduced from 15 to 13 nodes.
✅ 3006_0_437: Reduced from 11 to 10 nodes.
✅ 3007_0_438: Reduced from 9 to 8 nodes.
✅ 3009_0_439: Reduced from 16 to 12 nodes.
✅ 3013_0_440: Reduced from 10 to 7 nodes.
✅ 3015_0_441: Reduced from 9 to 6 nodes.
✅ 3026_0_443: Reduced from 12 to 10 nodes.
✅ 3032_0_445: Reduced from 9 to 7 nodes.
✅ 3033_0_446: Reduced from 12 to 9 nodes.
✅ 3035_0_447: Reduced from 5 to 4 nodes.
✅ 3037_0_448: Reduced from 8 to 6 nodes.
✅ 3043_0_449: Reduced from 12 to 8 nodes.
✅ 3045_0_450: Reduced from 11 to 9 nodes.
✅ 3054_0_452: Reduced from 11 to 10 nodes.
✅ 3068_0_454: Reduced from 11 to 8 nodes.
✅ 3074_0_456: Reduced from 10 to 8 nodes.
✅ 3078_0_457: Reduced from 9 to 6 nodes.
✅ 3081_0_459: Reduced from 6 to 4 nodes.
✅ 3094_0_460: Reduced from 6 to 4 nodes.
✅ 3105_0_463: Reduced from 6 to 4 nodes.
✅ 3107_0_465: Reduced from 8 to 7 nodes.
✅ 3109_0_466: Reduced from 6 to 4 nodes.
✅ 3113_0_468: Reduced from 14 to 10 nodes.
✅ 3123_0_470: Reduced from 9 to 6 nodes.
✅ 3124_0_471: Reduced from 8 to 7 nodes.
✅ 3128_0_473: Reduced from 14 to 10 nodes.
✅ 3131_0_474: Reduced from 8 to 6 nodes.
✅ 3146_0_478: Reduced from 9 to 8 nodes.
✅ 3150_0_480: Reduced from 9 to 7 nodes.
✅ 3157_0_481: Reduced from 8 to 6 nodes.
✅ 3159_0_482: Reduced from 6 to 4 nodes.
✅ 3163_0_484: Reduced from 12 to 11 nodes.
✅ 3174_0_485: Reduced from 6 to 4 nodes.
✅ 3187_0_487: Reduced from 10 to 9 nodes.
✅ 3198_0_491: Reduced from 13 to 10 nodes.
✅ 3199_0_492: Reduced from 15 to 13 nodes.
✅ 3207_0_493: Reduced from 8 to 5 nodes.
✅ 3214_0_496: Reduced from 8 to 7 nodes.
✅ 3215_0_497: Reduced from 6 to 5 nodes.
✅ 3217_0_498: Reduced from 6 to 5 nodes.
✅ 3224_0_500: Reduced from 6 to 5 nodes.
✅ 3227_0_502: Reduced from 6 to 5 nodes.
✅ 3233_0_504: Reduced from 6 to 5 nodes.
✅ 3236_0_505: Reduced from 12 to 10 nodes.
✅ 3251_0_509: Reduced from 6 to 4 nodes.
✅ 3253_0_510: Reduced from 11 to 7 nodes.
✅ 3257_0_512: Reduced from 7 to 6 nodes.
✅ 3269_0_516: Reduced from 11 to 9 nodes.
✅ 3271_0_517: Reduced from 10 to 7 nodes.
✅ 3272_0_518: Reduced from 8 to 7 nodes.
✅ 3274_0_519: Reduced from 9 to 7 nodes.
✅ 3277_0_520: Reduced from 8 to 6 nodes.
✅ 3278_0_521: Reduced from 8 to 5 nodes.
✅ 3280_0_522: Reduced from 13 to 11 nodes.
✅ 3281_0_523: Reduced from 10 to 8 nodes.
✅ 3288_0_525: Reduced from 15 to 14 nodes.
✅ 3293_0_526: Reduced from 10 to 8 nodes.
✅ 3301_0_528: Reduced from 14 to 13 nodes.
✅ 3302_0_529: Reduced from 16 to 13 nodes.
✅ 3305_0_530: Reduced from 11 to 10 nodes.
✅ 3309_0_531: Reduced from 10 to 7 nodes.
✅ 3318_0_534: Reduced from 6 to 4 nodes.
✅ 3321_0_537: Reduced from 15 to 14 nodes.
✅ 3322_0_538: Reduced from 16 to 14 nodes.
✅ 3323_0_539: Reduced from 6 to 4 nodes.
✅ 3324_0_540: Reduced from 7 to 5 nodes.
✅ 3328_0_541: Reduced from 12 to 10 nodes.
✅ 3330_0_542: Reduced from 10 to 9 nodes.
✅ 3331_0_543: Reduced from 12 to 9 nodes.
✅ 3336_0_544: Reduced from 10 to 9 nodes.
✅ 3340_0_545: Reduced from 14 to 11 nodes.
✅ 3344_0_546: Reduced from 11 to 10 nodes.
✅ 3347_0_547: Reduced from 13 to 9 nodes.
✅ 3353_0_551: Reduced from 11 to 9 nodes.
✅ 3361_0_554: Reduced from 7 to 5 nodes.
✅ 3364_0_555: Reduced from 6 to 5 nodes.
✅ 3375_0_558: Reduced from 6 to 4 nodes.
✅ 3377_0_559: Reduced from 14 to 10 nodes.
✅ 3384_0_561: Reduced from 6 to 5 nodes.
✅ 3402_0_562: Reduced from 8 to 5 nodes.
✅ 34924_0_564: Reduced from 6 to 4 nodes.
✅ 34925_0_565: Reduced from 11 to 8 nodes.
✅ 34926_0_566: Reduced from 16 to 15 nodes.
✅ 34998_0_567: Reduced from 6 to 4 nodes.
✅ 35014_0_568: Reduced from 11 to 8 nodes.
✅ 35062_0_569: Reduced from 15 to 13 nodes.
✅ 35064_0_570: Reduced from 9 to 7 nodes.
✅ 35070_0_572: Reduced from 6 to 5 nodes.
✅ 35072_0_574: Reduced from 6 to 4 nodes.
✅ 35082_0_576: Reduced from 10 to 8 nodes.
✅ 35096_0_578: Reduced from 6 to 4 nodes.
✅ 35097_0_579: Reduced from 6 to 4 nodes.
✅ 35100_0_581: Reduced from 16 to 13 nodes.
✅ 35104_0_585: Reduced from 6 to 4 nodes.
✅ 35111_0_587: Reduced from 16 to 12 nodes.

INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.32  0.52] and [ 0.43 -0.32  0.52]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.71 -0.04] and [ 0.43 -0.71 -0.04]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.5  -0.22] and [ 0.31 -0.5  -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.53  0.44] and [ 0.49 -0.53  0.44]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.33] and [ 0.34 -0.51  0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.51 -0.29] and [ 0.25 -0.51 -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.1   0.17] and [ 0.35 -0.1   0.17]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.15  0.07] and [ 0.71 -0.15  0.07]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.49 -0.29] and [ 0.25 -0.49 -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.47  0.37] and [ 0.39 -0.47  0.37]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.49 -0.38] and [ 0.38 -0.49 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.46  0.35] and [ 0.4  -0.46  0.35]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48 -0.22] and [ 0.31 -0.48 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.51  0.44] and [ 0.49 -0.51  0.44]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57 -0.4 ] and [ 0.4  -0.57 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56  0.41] and [ 0.4  -0.56  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.21] and [ 0.31 -0.49 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.45] and [ 0.49 -0.52  0.45]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.5  -0.29] and [ 0.29 -0.5  -0.29]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48  0.29] and [ 0.28 -0.48  0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.33] and [ 0.34 -0.51  0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.51 -0.29] and [ 0.25 -0.51 -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.71 -0.37 -0.27] and [ 0.71 -0.37 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.71  0.17  0.07] and [0.71 0.17 0.07]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.51 -0.4 ] and [ 0.37 -0.51 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.51  0.41] and [ 0.35 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.42  0.45] and [ 0.44 -0.42  0.45]
INFO: Symmetry Found: Mirror pair at [-0.44  0.2   0.2 ] and [0.44 0.2  0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.45  0.42  0.21] and [0.45 0.42 0.21]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.03  0.45] and [ 0.44 -0.03  0.45]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.42  0.46] and [ 0.44 -0.42  0.46]
INFO: Symmetry Found: Mirror pair at [-0.44  0.21  0.18] and [0.44 0.21 0.18]
INFO: Symmetry Found: Mirror pair at [-0.45  0.42  0.2 ] and [0.45 0.42 0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.04  0.46] and [ 0.44 -0.04  0.46]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.41] and [ 0.34 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.51 -0.4 ] and [ 0.37 -0.51 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.41] and [ 0.34 -0.5   0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.5  -0.4 ] and [ 0.36 -0.5  -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.41] and [ 0.34 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.43  0.45] and [ 0.44 -0.43  0.45]
INFO: Symmetry Found: Mirror pair at [-0.44  0.17  0.16] and [0.44 0.17 0.16]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.55  0.41] and [ 0.41 -0.55  0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.71  0.03] and [ 0.37 -0.71  0.03]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.36  0.45] and [ 0.36 -0.36  0.45]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.57  0.32] and [ 0.31 -0.57  0.32]
INFO: Symmetry Found: Mirror pair at [-0.31  0.42 -0.26] and [ 0.31  0.42 -0.26]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55 -0.52] and [ 0.54 -0.55 -0.52]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.43  0.26  0.05] and [0.43 0.26 0.05]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.06  0.43] and [ 0.42 -0.06  0.43]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.44  0.2   0.19] and [0.44 0.2  0.19]
INFO: Symmetry Found: Mirror pair at [-0.45  0.42  0.2 ] and [0.45 0.42 0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.45 -0.03  0.45] and [ 0.45 -0.03  0.45]
INFO: Symmetry reduction: 16 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.54 -0.17] and [ 0.31 -0.54 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.54  0.3 ] and [ 0.31 -0.54  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 12 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.6  -0.28] and [ 0.28 -0.6  -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.31] and [ 0.28 -0.61  0.31]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.58 -0.05  0.22] and [ 0.58 -0.05  0.22]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.49  0.58] and [ 0.58 -0.49  0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.21] and [ 0.31 -0.49 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.45] and [ 0.49 -0.52  0.45]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.5  -0.2 ] and [ 0.31 -0.5  -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.53  0.46] and [ 0.49 -0.53  0.46]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.22] and [ 0.31 -0.49 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.44] and [ 0.49 -0.52  0.44]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.53  0.33] and [ 0.34 -0.53  0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.52 -0.29] and [ 0.25 -0.52 -0.29]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.5  -0.38] and [ 0.38 -0.5  -0.38]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.47  0.33] and [ 0.4  -0.47  0.33]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.51 -0.4 ] and [ 0.37 -0.51 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.52  0.42] and [ 0.34 -0.52  0.42]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57 -0.4 ] and [ 0.4  -0.57 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56  0.4 ] and [ 0.4  -0.56  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.44  0.06  0.14] and [0.44 0.06 0.14]
INFO: Symmetry Found: Mirror pair at [-0.45  0.18 -0.41] and [ 0.45  0.18 -0.41]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.54  0.4 ] and [ 0.4  -0.54  0.4 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.71 -0.38 -0.28] and [ 0.71 -0.38 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.71  0.17  0.08] and [0.71 0.17 0.08]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.62  0.06  0.11] and [0.62 0.06 0.11]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.55 -0.4 ] and [ 0.4  -0.55 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.41 -0.55  0.39] and [ 0.41 -0.55  0.39]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47 -0.28] and [ 0.29 -0.47 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48  0.29] and [ 0.29 -0.48  0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57 -0.41] and [ 0.4  -0.57 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56  0.4 ] and [ 0.4  -0.56  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57 -0.41] and [ 0.4  -0.57 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57  0.4 ] and [ 0.4  -0.57  0.41]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.52 -0.33] and [ 0.31 -0.52 -0.33]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.48  0.3 ] and [ 0.28 -0.48  0.3 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.45 -0.28] and [ 0.28 -0.45 -0.28]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.51 -0.44] and [ 0.23 -0.51 -0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.52  0.34] and [ 0.43 -0.52  0.34]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.02  0.12] and [ 0.35 -0.02  0.12]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.71  0.02] and [ 0.35 -0.71  0.02]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.35  0.45] and [ 0.34 -0.35  0.45]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.6   0.01  0.14] and [0.6  0.01 0.14]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.2  -0.08] and [ 0.58 -0.2  -0.08]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.4   0.32] and [ 0.58 -0.4   0.32]
INFO: Symmetry reduction: 15 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.22] and [ 0.31 -0.49 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.44] and [ 0.49 -0.52  0.44]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.62  0.43] and [ 0.41 -0.62  0.43]
INFO: Symmetry Found: Mirror pair at [-0.42  0.25  0.03] and [0.42 0.25 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.49 -0.37] and [ 0.39 -0.49 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.47  0.35] and [ 0.39 -0.47  0.35]
INFO: Symmetry Found: Mirror pair at [-0.44  0.02  0.21] and [0.44 0.02 0.21]
INFO: Symmetry reduction: 16 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.4 ] and [ 0.4  -0.56 -0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.54  0.4 ] and [ 0.4  -0.54  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.33] and [ 0.34 -0.51  0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.51 -0.29] and [ 0.25 -0.51 -0.29]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48 -0.28] and [ 0.28 -0.48 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47  0.29] and [ 0.29 -0.47  0.29]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57  0.43] and [ 0.4  -0.57  0.43]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.52 -0.33] and [ 0.31 -0.52 -0.33]
INFO: Symmetry reduction: 15 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48 -0.28] and [ 0.28 -0.48 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48  0.29] and [ 0.28 -0.48  0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.09  0.05] and [0.41 0.09 0.05]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.49 -0.29] and [ 0.28 -0.49 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.48  0.3 ] and [ 0.29 -0.48  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.71 -0.04  0.34] and [ 0.71 -0.04  0.34]
INFO: Symmetry Found: Mirror pair at [-0.7  -0.14  0.07] and [ 0.7  -0.14  0.07]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.55 -0.23] and [ 0.25 -0.55 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.73 -0.  ] and [ 0.24 -0.73 -0.  ]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.55  0.23] and [ 0.25 -0.55  0.23]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.47 -0.39] and [ 0.37 -0.47 -0.39]
INFO: Symmetry reduction: 13 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.    0.04] and [ 0.54 -0.    0.04]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55 -0.52] and [ 0.54 -0.55 -0.52]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55  0.52] and [ 0.54 -0.55  0.52]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.    0.04] and [ 0.54 -0.    0.04]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.54 -0.53] and [ 0.54 -0.54 -0.53]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.55  0.52] and [ 0.54 -0.55  0.52]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.61  0.42] and [ 0.41 -0.61  0.42]
INFO: Symmetry Found: Mirror pair at [-0.42  0.26  0.03] and [0.42 0.26 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.71  0.16  0.07] and [0.71 0.16 0.07]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.02  0.34] and [ 0.71 -0.02  0.34]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.71  0.05] and [ 0.36 -0.71  0.05]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.35  0.47] and [ 0.34 -0.35  0.47]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.71  0.06] and [ 0.37 -0.71  0.06]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.36  0.46] and [ 0.35 -0.36  0.46]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.53 -0.24] and [ 0.25 -0.53 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.55  0.24] and [ 0.25 -0.55  0.24]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.57 -0.41] and [ 0.41 -0.57 -0.41]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.57  0.4 ] and [ 0.4  -0.57  0.41]

✅ 35119_0_589: Reduced from 11 to 8 nodes.
✅ 35121_0_590: Reduced from 9 to 7 nodes.
✅ 35123_0_591: Reduced from 15 to 13 nodes.
✅ 35131_0_592: Reduced from 11 to 8 nodes.
✅ 35142_0_593: Reduced from 9 to 7 nodes.
✅ 35144_0_594: Reduced from 14 to 12 nodes.
✅ 35146_0_596: Reduced from 9 to 7 nodes.
✅ 35153_0_597: Reduced from 11 to 8 nodes.
✅ 35178_0_598: Reduced from 11 to 8 nodes.
✅ 35180_0_599: Reduced from 12 to 11 nodes.
✅ 35184_0_600: Reduced from 12 to 10 nodes.
✅ 35189_0_604: Reduced from 11 to 8 nodes.
✅ 35197_0_607: Reduced from 15 to 13 nodes.
✅ 35200_0_608: Reduced from 6 to 4 nodes.
✅ 35203_0_610: Reduced from 15 to 13 nodes.
✅ 35204_0_611: Reduced from 6 to 4 nodes.
✅ 35205_0_612: Reduced from 9 to 7 nodes.
✅ 35213_0_613: Reduced from 15 to 13 nodes.
✅ 35222_0_615: Reduced from 6 to 4 nodes.
✅ 35223_0_616: Reduced from 16 to 12 nodes.
✅ 35233_0_617: Reduced from 16 to 12 nodes.
✅ 35234_0_618: Reduced from 6 to 5 nodes.
✅ 35236_0_620: Reduced from 6 to 4 nodes.
✅ 35238_0_621: Reduced from 6 to 4 nodes.
✅ 35245_0_623: Reduced from 11 to 8 nodes.
✅ 35270_0_625: Reduced from 16 to 14 nodes.
✅ 35273_0_626: Reduced from 6 to 5 nodes.
✅ 35274_0_627: Reduced from 9 to 7 nodes.
✅ 35319_0_629: Reduced from 15 to 13 nodes.
✅ 35326_0_630: Reduced from 8 to 7 nodes.
✅ 35331_0_631: Reduced from 14 to 12 nodes.
✅ 35333_0_632: Reduced from 16 to 13 nodes.
✅ 35376_0_633: Reduced from 11 to 8 nodes.
✅ 35392_0_634: Reduced from 11 to 8 nodes.
✅ 35393_0_635: Reduced from 12 to 9 nodes.
✅ 35401_0_637: Reduced from 10 to 8 nodes.
✅ 35407_0_638: Reduced from 11 to 8 nodes.
✅ 35423_0_639: Reduced from 11 to 8 nodes.
✅ 35424_0_640: Reduced from 6 to 4 nodes.
✅ 35439_0_641: Reduced from 10 to 7 nodes.
✅ 35440_0_642: Reduced from 11 to 8 nodes.
✅ 35441_0_643: Reduced from 15 to 13 nodes.
✅ 35445_0_644: Reduced from 15 to 13 nodes.
✅ 35447_0_645: Reduced from 9 to 7 nodes.
✅ 35448_0_646: Reduced from 10 to 8 nodes.
✅ 35455_0_647: Reduced from 9 to 7 nodes.
✅ 35464_0_648: Reduced from 15 to 13 nodes.
✅ 35471_0_649: Reduced from 11 to 9 nodes.
✅ 35477_0_650: Reduced from 11 to 8 nodes.
✅ 35481_0_651: Reduced from 9 to 7 nodes.
✅ 35482_0_652: Reduced from 10 to 8 nodes.
✅ 35486_0_653: Reduced from 6 to 4 nodes.
✅ 35498_0_655: Reduced from 6 to 4 nodes.
✅ 35499_0_656: Reduced from 16 to 14 nodes.
✅ 35500_0_657: Reduced from 6 to 5 nodes.
✅ 35505_0_658: Reduced from 15 to 13 nodes.
✅ 35511_0_662: Reduced from 10 to 9 nodes.
✅ 35515_0_664: Reduced from 6 to 4 nodes.
✅ 35517_0_666: Reduced from 6 to 4 nodes.
✅ 35519_0_668: Reduced from 6 to 4 nodes.
✅ 35526_0_671: Reduced from 8 to 6 nodes.
✅ 35527_0_672: Reduced from 9 to 7 nodes.
✅ 35531_0_674: Reduced from 6 to 4 nodes.
✅ 35532_0_675: Reduced from 15 to 14 nodes.
✅ 35533_0_676: Reduced from 6 to 5 nodes.
✅ 35551_0_678: Reduced from 6 to 5 nodes.
✅ 35553_0_679: Reduced from 6 to 5 nodes.
✅ 35554_0_680: Reduced from 6 to 4 nodes.
✅ 35561_0_682: Reduced from 11 to 8 nodes.
✅ 35583_0_685: Reduced from 15 to 12 nodes.
✅ 35584_0_686: Reduced from 15 to 13 nodes.
✅ 35589_0_689: Reduced from 9 to 7 nodes.
✅ 35606_0_692: Reduced from 14 to 12 nodes.
✅ 35607_0_693: Reduced from 16 to 13 nodes.
✅ 35608_0_694: Reduced from 6 to 4 nodes.
✅ 35609_0_695: Reduced from 11 to 7 nodes.
✅ 35621_0_697: Reduced from 9 to 7 nodes.
✅ 35624_0_698: Reduced from 7 to 5 nodes.
✅ 35633_0_699: Reduced from 6 to 5 nodes.
✅ 35635_0_700: Reduced from 15 to 14 nodes.
✅ 35642_0_702: Reduced from 6 to 4 nodes.
✅ 35650_0_704: Reduced from 11 to 10 nodes.
✅ 35670_0_708: Reduced from 6 to 4 nodes.
✅ 35672_0_709: Reduced from 14 to 12 nodes.
✅ 35731_0_711: Reduced from 9 to 6 nodes.
✅ 35738_0_713: Reduced from 13 to 12 nodes.
✅ 35759_0_718: Reduced from 8 to 5 nodes.
✅ 35761_0_719: Reduced from 8 to 5 nodes.
✅ 35765_0_720: Reduced from 14 to 12 nodes.
✅ 35772_0_722: Reduced from 14 to 12 nodes.
✅ 35776_0_723: Reduced from 11 to 10 nodes.
✅ 35780_0_725: Reduced from 11 to 10 nodes.
✅ 35785_0_726: Reduced from 11 to 9 nodes.
✅ 35786_0_727: Reduced from 9 to 7 nodes.
✅ 35788_0_728: Reduced from 6 to 4 nodes.
✅ 35793_0_729: Reduced from 15 to 14 nodes.
✅ 35795_0_731: Reduced from 6 to 4 nodes.
✅ 35802_0_732: Reduced from 6 to 5 nodes.
✅ 35803_0_733: Reduced from 6 to 4 nodes.
✅ 35804_0_734: Reduced from 6 to 5 nodes.
✅ 35806_0_735: Reduced from 11 to 10 nodes.
✅ 35809_0_736: Reduced from 10 to 7 nodes.
✅ 35811_0_737: Reduced from 8 to 7 nodes.
✅ 35814_0_739: Reduced from 14 to 12 nodes.
✅ 35816_0_740: Reduced from 6 to 5 nodes.
✅ 35820_0_741: Reduced from 8 to 7 nodes.
✅ 35822_0_742: Reduced from 13 to 10 nodes.
✅ 35837_0_744: Reduced from 8 to 6 nodes.
✅ 35858_0_748: Reduced from 15 to 13 nodes.
✅ 35861_0_749: Reduced from 8 to 6 nodes.
✅ 35871_0_752: Reduced from 13 to 12 nodes.
✅ 35875_0_753: Reduced from 14 to 11 nodes.
✅ 35881_0_757: Reduced from 11 to 8 nodes.
✅ 35883_0_758: Reduced from 8 to 5 nodes.
✅ 35902_0_762: Reduced from 11 to 10 nodes.
✅ 35905_0_763: Reduced from 15 to 12 nodes.
✅ 35909_0_764: Reduced from 9 to 6 nodes.
✅ 35910_0_765: Reduced from 14 to 11 nodes.
✅ 35919_0_769: Reduced from 8 to 7 nodes.
✅ 35923_0_771: Reduced from 6 to 4 nodes.
✅ 35925_0_772: Reduced from 8 to 7 nodes.
✅ 35932_0_774: Reduced from 6 to 5 nodes.
✅ 35939_0_775: Reduced from 10 to 9 nodes.
✅ 35946_0_776: Reduced from 6 to 4 nodes.
✅ 35959_0_778: Reduced from 10 to 7 nodes.
✅ 35960_0_779: Reduced from 12 to 10 nodes.

INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61 -0.28] and [ 0.29 -0.61 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.3 ] and [ 0.29 -0.61  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.56 -0.05  0.23] and [ 0.56 -0.05  0.23]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.55 -0.24] and [ 0.25 -0.55 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.23 -0.72 -0.01] and [ 0.23 -0.72 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.55  0.24] and [ 0.25 -0.55  0.24]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.77  0.24] and [ 0.32 -0.77  0.24]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.41 -0.19] and [ 0.32 -0.41 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.41  0.33] and [ 0.32 -0.41  0.33]
INFO: Symmetry Found: Mirror pair at [-0.27  0.37 -0.2 ] and [ 0.27  0.37 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.37 -0.2 ] and [ 0.14  0.37 -0.2 ]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.51  0.41] and [ 0.34 -0.51  0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.37 -0.38] and [ 0.23 -0.37 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.39  0.41  0.2 ] and [0.39 0.41 0.2 ]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.54 -0.49] and [ 0.54 -0.54 -0.49]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.54  0.55] and [ 0.54 -0.54  0.55]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.44  0.26  0.15] and [0.44 0.26 0.15]
INFO: Symmetry Found: Mirror pair at [-0.44  0.47  0.15] and [0.44 0.47 0.15]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.02  0.45] and [ 0.43 -0.02  0.45]
INFO: Symmetry reduction: 16 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.61  0.42] and [ 0.41 -0.61  0.42]
INFO: Symmetry Found: Mirror pair at [-0.42  0.26  0.03] and [0.42 0.26 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.53  0.31] and [ 0.33 -0.53  0.31]
INFO: Symmetry Found: Mirror pair at [-0.14  0.57 -0.31] and [ 0.15  0.57 -0.31]
INFO: Symmetry reduction: 13 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.21] and [ 0.31 -0.49 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.45] and [ 0.49 -0.52  0.45]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.73  0.01] and [ 0.23 -0.73  0.01]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.62 -0.29] and [ 0.3  -0.62 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.62  0.3 ] and [ 0.3  -0.62  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.53 -0.44] and [ 0.24 -0.53 -0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.18  0.22] and [0.59 0.18 0.22]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.3   0.28 -0.36] and [ 0.3   0.28 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.2   0.28 -0.36] and [ 0.2   0.28 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.1   0.28 -0.36] and [ 0.1   0.28 -0.36]
INFO: Symmetry reduction: 15 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.58  0.15  0.23] and [0.58 0.15 0.23]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.39 -0.41] and [ 0.39 -0.39 -0.41]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.59 -0.29] and [ 0.3  -0.59 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.3 -0.6  0.3] and [ 0.3 -0.6  0.3]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.5  -0.21] and [ 0.31 -0.5  -0.21]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.53  0.45] and [ 0.49 -0.53  0.45]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.57  0.16  0.22] and [0.57 0.16 0.22]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.44] and [ 0.24 -0.52 -0.44]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.51  0.44] and [ 0.24 -0.51  0.44]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.6  -0.29] and [ 0.28 -0.6  -0.29]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.32] and [ 0.44 -0.52 -0.32]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.45 -0.36] and [ 0.36 -0.45 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.44  0.37] and [ 0.36 -0.44  0.37]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.61  0.21  0.16] and [0.61 0.21 0.16]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.44] and [ 0.24 -0.52 -0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.55 -0.29] and [ 0.43 -0.55 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.78  0.11] and [ 0.43 -0.78  0.11]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.55  0.41] and [ 0.43 -0.55  0.41]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.47 -0.38] and [ 0.39 -0.47 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.46  0.42] and [ 0.4  -0.46  0.42]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.16  0.2 ] and [0.59 0.16 0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.37 -0.42 -0.38] and [ 0.37 -0.42 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.37 -0.42  0.37] and [ 0.37 -0.42  0.37]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.49 -0.21] and [ 0.31 -0.49 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.52  0.45] and [ 0.49 -0.52  0.45]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.43] and [ 0.24 -0.52 -0.43]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.69 -0.35] and [ 0.3  -0.69 -0.35]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.69  0.37] and [ 0.29 -0.69  0.37]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.51  0.45] and [ 0.25 -0.51  0.45]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.45 -0.36] and [ 0.36 -0.45 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.44  0.36] and [ 0.36 -0.44  0.36]
INFO: Symmetry Found: Mirror pair at [-0.41  0.31 -0.36] and [ 0.41  0.31 -0.36]
INFO: Symmetry reduction: 15 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61 -0.28] and [ 0.29 -0.61 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.61  0.3 ] and [ 0.29 -0.61  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.51  0.24 -0.36] and [ 0.51  0.24 -0.36]
INFO: Symmetry reduction: 14 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.16  0.21] and [0.59 0.16 0.21]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.41 -0.39] and [ 0.35 -0.41 -0.39]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.5   0.45] and [ 0.24 -0.5   0.45]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.44  0.1   0.13] and [0.44 0.1  0.13]
INFO: Symmetry Found: Mirror pair at [-0.48 -0.65 -0.47] and [ 0.48 -0.65 -0.47]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.52  0.02  0.  ] and [0.52 0.02 0.  ]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.45 -0.27] and [ 0.31  0.45 -0.27]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.71  0.04] and [ 0.38 -0.71  0.04]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.36  0.47] and [ 0.39 -0.36  0.47]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51 -0.17] and [ 0.31 -0.51 -0.17]
INFO: Symmetry Found: Mirror pair at [-0.31 -0.51  0.3 ] and [ 0.31 -0.51  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.27 -0.25] and [ 0.14  0.27 -0.25]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.53 -0.44] and [ 0.24 -0.53 -0.44]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52  0.45] and [ 0.24 -0.52  0.45]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.71 -0.22 -0.25] and [ 0.71 -0.22 -0.25]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.33  0.4 ] and [ 0.71 -0.33  0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.71  0.16  0.07] and [0.71 0.16 0.07]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.01  0.34] and [ 0.71 -0.01  0.34]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.15  0.07] and [ 0.71 -0.15  0.07]
INFO: Symmetry reduction: 14 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry Found: Mirror pair at [-0.17  0.03 -0.36] and [ 0.17  0.03 -0.36]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.32] and [ 0.44 -0.52 -0.32]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.73  0.  ] and [ 0.24 -0.73  0.  ]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.54  0.28  0.02] and [0.54 0.28 0.02]
INFO: Symmetry Found: Mirror pair at [-0.51 -0.06  0.01] and [ 0.51 -0.06  0.01]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48 -0.23] and [ 0.31 -0.48 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.51  0.43] and [ 0.49 -0.51  0.43]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.54  0.    0.04] and [ 0.54 -0.    0.04]
INFO: Symmetry Found: Mirror pair at [-0.54 -0.54 -0.52] and [ 0.54 -0.54 -0.52]
INFO: Symmetry Found: Mirror pair at [-0.53 -0.55  0.52] and [ 0.53 -0.55  0.52]
INFO: Symmetry reduction: 8 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.44 -0.36] and [ 0.36 -0.44 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.36 -0.44  0.36] and [ 0.36 -0.44  0.36]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.49 -0.37] and [ 0.39 -0.49 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.46  0.38] and [ 0.4  -0.46  0.38]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.56 -0.41] and [ 0.39 -0.56 -0.41]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.15  0.12] and [0.4  0.15 0.12]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.54 -0.26] and [ 0.28 -0.54 -0.26]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.54  0.37] and [ 0.28 -0.54  0.37]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.44] and [ 0.24 -0.52 -0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.49  0.08  0.  ] and [0.49 0.08 0.  ]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.59 -0.42] and [ 0.49 -0.59 -0.42]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.59  0.45] and [ 0.49 -0.59  0.45]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.48  0.29] and [ 0.29 -0.48  0.29]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.47 -0.28] and [ 0.29 -0.47 -0.28]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.4 ] and [ 0.4  -0.56 -0.4 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.58  0.15  0.22] and [0.58 0.15 0.22]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.48 -0.29] and [ 0.29 -0.48 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.49  0.3 ] and [ 0.29 -0.49  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.3   0.04] and [ 0.42 -0.3   0.04]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.01  0.11] and [ 0.34 -0.01  0.11]
INFO: Symmetry Found: Mirror pair at [-0.34  0.38 -0.31] and [ 0.35  0.38 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.4   0.48 -0.03] and [ 0.4   0.48 -0.03]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.4   0.48] and [ 0.34 -0.4   0.48]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.48 -0.22] and [ 0.31 -0.48 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.49 -0.51  0.44] and [ 0.49 -0.51  0.44]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.5   0.33] and [ 0.34 -0.5   0.33]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.5  -0.29] and [ 0.25 -0.5  -0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.43 -0.52 -0.33] and [ 0.43 -0.52 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.77  0.04] and [ 0.43 -0.77  0.04]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.52  0.42] and [ 0.43 -0.52  0.42]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.52 -0.44] and [ 0.23 -0.52 -0.44]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.51  0.44] and [ 0.23 -0.51  0.44]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34  0.09  0.7 ] and [0.35 0.09 0.7 ]
INFO: Symmetry reduction: 14 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.71  0.16  0.07] and [0.71 0.16 0.07]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.    0.34] and [ 0.71 -0.01  0.34]
INFO: Symmetry Found: Mirror pair at [-0.71 -0.22 -0.25] and [ 0.71 -0.22 -0.25]

✅ 35962_0_780: Reduced from 6 to 4 nodes.
✅ 35969_0_782: Reduced from 6 to 4 nodes.
✅ 35970_0_783: Reduced from 10 to 9 nodes.
✅ 35979_0_784: Reduced from 11 to 8 nodes.
✅ 35996_0_787: Reduced from 9 to 6 nodes.
✅ 36002_0_789: Reduced from 8 to 7 nodes.
✅ 36008_0_792: Reduced from 11 to 7 nodes.
✅ 36009_0_793: Reduced from 6 to 5 nodes.
✅ 36015_0_795: Reduced from 13 to 11 nodes.
✅ 36027_0_796: Reduced from 11 to 8 nodes.
✅ 36032_0_797: Reduced from 8 to 6 nodes.
✅ 36034_0_798: Reduced from 16 to 13 nodes.
✅ 36042_0_801: Reduced from 14 to 12 nodes.
✅ 36043_0_802: Reduced from 13 to 11 nodes.
✅ 36055_0_804: Reduced from 15 to 13 nodes.
✅ 36066_0_808: Reduced from 9 to 8 nodes.
✅ 36069_0_809: Reduced from 6 to 4 nodes.
✅ 36070_0_810: Reduced from 6 to 5 nodes.
✅ 36071_0_811: Reduced from 7 to 6 nodes.
✅ 36078_0_812: Reduced from 10 to 7 nodes.
✅ 36081_0_813: Reduced from 10 to 8 nodes.
✅ 36083_0_814: Reduced from 15 to 12 nodes.
✅ 36092_0_815: Reduced from 10 to 7 nodes.
✅ 36098_0_816: Reduced from 9 to 8 nodes.
✅ 36110_0_818: Reduced from 6 to 4 nodes.
✅ 36113_0_819: Reduced from 15 to 13 nodes.
✅ 36114_0_820: Reduced from 10 to 7 nodes.
✅ 36115_0_821: Reduced from 6 to 4 nodes.
✅ 36116_0_822: Reduced from 6 to 5 nodes.
✅ 36117_0_823: Reduced from 11 to 8 nodes.
✅ 36119_0_824: Reduced from 6 to 5 nodes.
✅ 36129_0_825: Reduced from 15 to 13 nodes.
✅ 36130_0_826: Reduced from 9 to 8 nodes.
✅ 36131_0_827: Reduced from 6 to 5 nodes.
✅ 36132_0_828: Reduced from 6 to 5 nodes.
✅ 36136_0_829: Reduced from 8 to 5 nodes.
✅ 36138_0_830: Reduced from 7 to 5 nodes.
✅ 36142_0_832: Reduced from 11 to 8 nodes.
✅ 36144_0_833: Reduced from 10 to 7 nodes.
✅ 36145_0_834: Reduced from 11 to 7 nodes.
✅ 36166_0_840: Reduced from 11 to 8 nodes.
✅ 36175_0_842: Reduced from 6 to 4 nodes.
✅ 36177_0_843: Reduced from 15 to 13 nodes.
✅ 36179_0_844: Reduced from 6 to 5 nodes.
✅ 36188_0_847: Reduced from 6 to 5 nodes.
✅ 36196_0_849: Reduced from 6 to 4 nodes.
✅ 36199_0_850: Reduced from 6 to 5 nodes.
✅ 36201_0_852: Reduced from 15 to 12 nodes.
✅ 36202_0_853: Reduced from 6 to 4 nodes.
✅ 36203_0_854: Reduced from 14 to 13 nodes.
✅ 36209_0_855: Reduced from 11 to 7 nodes.
✅ 36212_0_857: Reduced from 10 to 7 nodes.
✅ 36213_0_858: Reduced from 11 to 10 nodes.
✅ 36217_0_859: Reduced from 6 to 5 nodes.
✅ 36220_0_861: Reduced from 8 to 6 nodes.
✅ 36225_0_862: Reduced from 9 to 8 nodes.
✅ 36228_0_863: Reduced from 10 to 9 nodes.
✅ 36229_0_864: Reduced from 10 to 8 nodes.
✅ 36236_0_867: Reduced from 11 to 8 nodes.
✅ 36239_0_868: Reduced from 6 to 4 nodes.
✅ 36245_0_870: Reduced from 14 to 9 nodes.
✅ 36248_0_872: Reduced from 10 to 7 nodes.
✅ 36249_0_873: Reduced from 6 to 5 nodes.
✅ 36251_0_874: Reduced from 9 to 8 nodes.
✅ 36256_0_876: Reduced from 10 to 8 nodes.
✅ 36258_0_878: Reduced from 12 to 10 nodes.
✅ 36267_0_879: Reduced from 14 to 12 nodes.
✅ 36269_0_880: Reduced from 8 to 5 nodes.
✅ 36277_0_882: Reduced from 15 to 13 nodes.
✅ 36284_0_884: Reduced from 12 to 10 nodes.
✅ 36291_0_885: Reduced from 6 to 5 nodes.
✅ 36292_0_886: Reduced from 9 to 8 nodes.
✅ 36293_0_887: Reduced from 11 to 9 nodes.
✅ 36308_0_892: Reduced from 6 to 5 nodes.
✅ 36309_0_893: Reduced from 9 to 6 nodes.
✅ 36315_0_897: Reduced from 6 to 4 nodes.
✅ 36316_0_898: Reduced from 6 to 5 nodes.
✅ 36323_0_900: Reduced from 6 to 5 nodes.
✅ 36325_0_901: Reduced from 10 to 8 nodes.
✅ 36332_0_904: Reduced from 6 to 4 nodes.
✅ 36336_0_906: Reduced from 10 to 9 nodes.
✅ 36343_0_908: Reduced from 16 to 12 nodes.
✅ 36347_0_909: Reduced from 11 to 7 nodes.
✅ 36353_0_912: Reduced from 15 to 13 nodes.
✅ 36374_0_915: Reduced from 10 to 8 nodes.
✅ 36379_0_916: Reduced from 11 to 7 nodes.
✅ 36381_0_917: Reduced from 9 to 6 nodes.
✅ 36385_0_918: Reduced from 11 to 7 nodes.
✅ 36402_0_921: Reduced from 11 to 7 nodes.
✅ 36407_0_923: Reduced from 11 to 7 nodes.
✅ 36410_0_924: Reduced from 11 to 7 nodes.
✅ 36414_0_925: Reduced from 6 to 4 nodes.
✅ 36420_0_927: Reduced from 14 to 13 nodes.
✅ 36428_0_928: Reduced from 14 to 11 nodes.
✅ 36431_0_929: Reduced from 8 to 6 nodes.
✅ 36432_0_930: Reduced from 11 to 10 nodes.
✅ 36433_0_931: Reduced from 8 to 6 nodes.
✅ 36439_0_935: Reduced from 9 to 7 nodes.
✅ 36442_0_937: Reduced from 10 to 8 nodes.
✅ 36444_0_938: Reduced from 11 to 8 nodes.
✅ 36455_0_939: Reduced from 10 to 8 nodes.
✅ 36462_0_941: Reduced from 6 to 4 nodes.
✅ 36466_0_942: Reduced from 10 to 7 nodes.
✅ 36468_0_943: Reduced from 6 to 4 nodes.
✅ 36481_0_947: Reduced from 8 to 7 nodes.
✅ 36491_0_948: Reduced from 5 to 4 nodes.
✅ 36495_0_951: Reduced from 11 to 7 nodes.
✅ 36496_0_952: Reduced from 5 to 4 nodes.
✅ 36499_0_953: Reduced from 15 to 12 nodes.
✅ 36502_0_954: Reduced from 12 to 10 nodes.
✅ 36514_0_956: Reduced from 15 to 14 nodes.
✅ 36520_0_959: Reduced from 8 to 6 nodes.
✅ 36522_0_960: Reduced from 6 to 4 nodes.
✅ 36525_0_961: Reduced from 16 to 13 nodes.
✅ 36530_0_963: Reduced from 8 to 6 nodes.
✅ 36535_0_965: Reduced from 6 to 5 nodes.
✅ 36537_0_966: Reduced from 4 to 3 nodes.
✅ 36538_0_967: Reduced from 12 to 10 nodes.
✅ 36540_0_968: Reduced from 10 to 7 nodes.
✅ 36545_0_969: Reduced from 6 to 4 nodes.
✅ 36547_0_970: Reduced from 8 to 6 nodes.
✅ 36554_0_972: Reduced from 6 to 5 nodes.
✅ 36556_0_973: Reduced from 12 to 11 nodes.
✅ 36557_0_974: Reduced from 12 to 11 nodes.
✅ 36560_0_975: Reduced from 6 to 4 nodes.
✅ 36561_0_976: Reduced from 16 to 12 nodes.
✅ 36564_0_977: Reduced from 11 to 7 nodes.

INFO: Symmetry Found: Mirror pair at [-0.35 -0.41 -0.37] and [ 0.35 -0.41 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.44  0.36] and [ 0.35 -0.44  0.36]
INFO: Symmetry reduction: 16 -> 14 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.39] and [ 0.4  -0.56 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56  0.4 ] and [ 0.4  -0.56  0.4 ]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.57 -0.05  0.21] and [ 0.57 -0.05  0.21]
INFO: Symmetry Found: Mirror pair at [-0.5 -0.5 -0.5] and [ 0.5 -0.5 -0.5]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.5   0.58] and [ 0.58 -0.5   0.58]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.14  0.22 -0.24] and [ 0.14  0.22 -0.24]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.2   0.06] and [ 0.4  -0.2   0.06]
INFO: Symmetry reduction: 16 -> 15 parts.
INFO: Symmetry Found: Mirror pair at [-0.38  0.3   0.1 ] and [0.38 0.3  0.1 ]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.56 -0.43] and [ 0.4  -0.56 -0.43]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.53 -0.23] and [ 0.3  -0.53 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.54  0.25] and [ 0.29 -0.54  0.25]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31 -0.45 -0.23] and [ 0.31 -0.45 -0.23]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.45  0.39] and [ 0.3  -0.45  0.39]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.52 -0.27] and [ 0.28 -0.52 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.28  0.28 -0.33] and [ 0.28  0.28 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.14  0.28 -0.33] and [ 0.14  0.28 -0.33]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.57 -0.39] and [ 0.29 -0.57 -0.39]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.56  0.4 ] and [ 0.29 -0.56  0.4 ]
INFO: Symmetry Found: Mirror pair at [-0.3   0.29  0.09] and [0.3  0.29 0.09]
INFO: Symmetry Found: Mirror pair at [-0.3   0.12  0.4 ] and [0.3  0.12 0.4 ]
INFO: Symmetry reduction: 10 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47 -0.28] and [ 0.28 -0.47 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.48  0.29] and [ 0.27 -0.48  0.29]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.6  -0.49 -0.58] and [ 0.6  -0.49 -0.58]
INFO: Symmetry Found: Mirror pair at [-0.6  -0.49  0.58] and [ 0.6  -0.49  0.58]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.37  0.34  0.11] and [0.37 0.34 0.11]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.54  0.4 ] and [ 0.41 -0.54  0.4 ]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.26 -0.49 -0.26] and [ 0.26 -0.49 -0.26]
INFO: Symmetry Found: Mirror pair at [-0.26 -0.49  0.26] and [ 0.26 -0.49  0.26]
INFO: Symmetry Found: Mirror pair at [-0.3   0.38 -0.2 ] and [ 0.3   0.38 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.15  0.38 -0.2 ] and [ 0.15  0.38 -0.2 ]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.72  0.  ] and [ 0.23 -0.72  0.  ]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.43  0.45] and [ 0.32 -0.43  0.45]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.56 -0.36] and [ 0.32 -0.56 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.56  0.36] and [ 0.32 -0.56  0.36]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.44  0.31] and [ 0.29 -0.44  0.31]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.39 -0.25  0.02] and [ 0.39 -0.25  0.02]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28  0.26 -0.2 ] and [ 0.28  0.26 -0.2 ]
INFO: Symmetry Found: Mirror pair at [-0.14  0.26 -0.2 ] and [ 0.14  0.26 -0.2 ]
INFO: Symmetry reduction: 15 -> 13 parts.
INFO: Symmetry Found: Mirror pair at [-0.62  0.06  0.16] and [0.62 0.06 0.16]
INFO: Symmetry reduction: 9 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.45 -0.3 ] and [ 0.23 -0.45 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.45  0.42] and [ 0.3  -0.45  0.42]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.31  0.35 -0.3 ] and [ 0.31  0.35 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.11  0.35 -0.3 ] and [ 0.1   0.35 -0.3 ]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.42 -0.26] and [ 0.23 -0.42 -0.26]
INFO: Symmetry Found: Mirror pair at [-0.23 -0.42  0.3 ] and [ 0.23 -0.42  0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.25  0.3  -0.24] and [ 0.25  0.3  -0.24]
INFO: Symmetry reduction: 11 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.51  0.44] and [ 0.24 -0.51  0.44]
INFO: Symmetry reduction: 6 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.14  0.4  -0.3 ] and [ 0.14  0.4  -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.29  0.43 -0.31] and [ 0.29  0.43 -0.31]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.43 -0.27] and [ 0.27 -0.43 -0.27]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.18  0.01] and [ 0.28 -0.18  0.01]
INFO: Symmetry Found: Mirror pair at [-0.27 -0.43  0.28] and [ 0.27 -0.43  0.28]
INFO: Symmetry reduction: 15 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.44 -0.52 -0.34] and [ 0.44 -0.52 -0.34]
INFO: Symmetry Found: Mirror pair at [-0.43 -0.52  0.34] and [ 0.43 -0.52  0.34]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.71  0.01] and [ 0.36 -0.71  0.01]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.36  0.46] and [ 0.34 -0.36  0.46]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.45  0.12  0.18] and [0.45 0.12 0.18]
INFO: Symmetry Found: Mirror pair at [-0.45  0.12 -0.09] and [ 0.45  0.12 -0.09]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.62 -0.36] and [ 0.4  -0.62 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.62  0.37] and [ 0.39 -0.62  0.37]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.34  0.4 ] and [ 0.29 -0.34  0.4 ]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.49 -0.29] and [ 0.25 -0.49 -0.29]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.49  0.2 ] and [ 0.25 -0.49  0.2 ]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.56 -0.24] and [ 0.25 -0.56 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.56  0.24] and [ 0.25 -0.56  0.24]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.41 -0.61  0.42] and [ 0.41 -0.61  0.42]
INFO: Symmetry Found: Mirror pair at [-0.42  0.26  0.03] and [0.42 0.26 0.03]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.54 -0.54 -0.52] and [ 0.54 -0.54 -0.52]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.43  0.26  0.05] and [0.43 0.26 0.05]
INFO: Symmetry Found: Mirror pair at [-0.42 -0.06  0.43] and [ 0.42 -0.06  0.43]
INFO: Symmetry reduction: 14 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.63 -0.07  0.  ] and [ 0.63 -0.07  0.  ]
INFO: Symmetry Found: Mirror pair at [-0.67 -0.48 -0.38] and [ 0.67 -0.48 -0.38]
INFO: Symmetry reduction: 11 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.24 -0.6  -0.23] and [ 0.24 -0.6  -0.23]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.56  0.31] and [ 0.25 -0.56  0.31]
INFO: Symmetry reduction: 7 -> 5 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57 -0.21] and [ 0.34 -0.57 -0.21]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.57  0.34] and [ 0.34 -0.57  0.34]
INFO: Symmetry Found: Mirror pair at [-0.32  0.16 -0.22] and [ 0.32  0.16 -0.22]
INFO: Symmetry Found: Mirror pair at [-0.16  0.16 -0.22] and [ 0.16  0.16 -0.22]
INFO: Symmetry reduction: 11 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.46 -0.28] and [ 0.28 -0.46 -0.28]
INFO: Symmetry reduction: 7 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48 -0.28] and [ 0.28 -0.48 -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.48  0.29] and [ 0.28 -0.48  0.29]
INFO: Symmetry reduction: 10 -> 8 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.32 -0.27] and [ 0.41 -0.32 -0.27]
INFO: Symmetry reduction: 12 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.59  0.02  0.13] and [0.59 0.02 0.13]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.22  0.31] and [ 0.58 -0.22  0.31]
INFO: Symmetry Found: Mirror pair at [-0.56 -0.42 -0.09] and [ 0.56 -0.42 -0.09]
INFO: Symmetry reduction: 14 -> 11 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.26  0.06] and [ 0.32 -0.26  0.06]
INFO: Symmetry Found: Mirror pair at [-0.32  0.25 -0.24] and [ 0.32  0.25 -0.24]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.41 -0.3 ] and [ 0.29 -0.41 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.41  0.47] and [ 0.29 -0.41  0.47]
INFO: Symmetry Found: Mirror pair at [-0.11  0.26 -0.39] and [ 0.12  0.26 -0.39]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.23 -0.5  -0.22] and [ 0.23 -0.5  -0.22]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.5   0.31] and [ 0.28 -0.5   0.31]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.42 -0.3  -0.32] and [ 0.42 -0.3  -0.32]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.5  -0.27] and [ 0.28 -0.5  -0.27]
INFO: Symmetry Found: Mirror pair at [-0.29 -0.5   0.27] and [ 0.28 -0.5   0.27]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.6  -0.42 -0.46] and [ 0.6  -0.42 -0.46]
INFO: Symmetry reduction: 11 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.35 -0.36  0.44] and [ 0.35 -0.36  0.44]
INFO: Symmetry Found: Mirror pair at [-0.35 -0.72  0.01] and [ 0.35 -0.72  0.01]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.4   0.16 -0.01] and [ 0.4   0.16 -0.01]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.42 -0.35] and [ 0.38 -0.42 -0.35]
INFO: Symmetry Found: Mirror pair at [-0.38 -0.39  0.42] and [ 0.38 -0.39  0.42]
INFO: Symmetry Found: Mirror pair at [-0.39 -0.75  0.43] and [ 0.39 -0.75  0.43]
INFO: Symmetry reduction: 13 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.49 -0.3 ] and [ 0.25 -0.49 -0.3 ]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.53 -0.28] and [ 0.28 -0.53 -0.28]
INFO: Symmetry reduction: 8 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.36 -0.6  -0.35] and [ 0.36 -0.6  -0.35]
INFO: Symmetry Found: Mirror pair at [-0.51 -0.6   0.41] and [ 0.51 -0.6   0.41]
INFO: Symmetry reduction: 9 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.25 -0.79 -0.24] and [ 0.25 -0.79 -0.24]
INFO: Symmetry Found: Mirror pair at [-0.24 -0.73  0.  ] and [ 0.23 -0.73  0.  ]
INFO: Symmetry Found: Mirror pair at [-0.25 -0.79  0.24] and [ 0.25 -0.79  0.24]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.38 -0.55 -0.38] and [ 0.38 -0.55 -0.38]
INFO: Symmetry Found: Mirror pair at [-0.4   0.25 -0.37] and [ 0.4   0.25 -0.37]
INFO: Symmetry Found: Mirror pair at [-0.13  0.25 -0.37] and [ 0.13  0.25 -0.37]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.32 -0.43 -0.36] and [ 0.32 -0.43 -0.36]
INFO: Symmetry Found: Mirror pair at [-0.32 -0.42  0.36] and [ 0.32 -0.42  0.36]
INFO: Symmetry Found: Mirror pair at [-0.15  0.29 -0.36] and [ 0.15  0.29 -0.36]
INFO: Symmetry reduction: 10 -> 7 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.62 -0.33] and [ 0.34 -0.62 -0.33]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.63  0.34] and [ 0.34 -0.63  0.34]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47 -0.19] and [ 0.29 -0.47 -0.19]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.47  0.33] and [ 0.29 -0.47  0.33]
INFO: Symmetry reduction: 12 -> 10 parts.
INFO: Symmetry Found: Mirror pair at [-0.4  -0.41 -0.41] and [ 0.4  -0.41 -0.41]
INFO: Symmetry reduction: 10 -> 9 parts.
INFO: Symmetry Found: Mirror pair at [-0.58  0.02  0.14] and [0.58 0.02 0.14]
INFO: Symmetry Found: Mirror pair at [-0.56 -0.23 -0.08] and [ 0.56 -0.23 -0.08]
INFO: Symmetry Found: Mirror pair at [-0.52 -0.4  -0.07] and [ 0.52 -0.4  -0.07]
INFO: Symmetry Found: Mirror pair at [-0.58 -0.44  0.32] and [ 0.58 -0.44  0.32]
INFO: Symmetry reduction: 16 -> 12 parts.
INFO: Symmetry Found: Mirror pair at [-0.3  -0.6  -0.28] and [ 0.3  -0.6  -0.28]
INFO: Symmetry Found: Mirror pair at [-0.3  -0.63  0.31] and [ 0.3  -0.63  0.31]
INFO: Symmetry reduction: 6 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.34 -0.53 -0.3 ] and [ 0.34 -0.53 -0.3 ]
INFO: Symmetry Found: Mirror pair at [-0.34 -0.52  0.31] and [ 0.34 -0.52  0.31]
INFO: Symmetry Found: Mirror pair at [-0.33  0.19 -0.3 ] and [ 0.33  0.19 -0.3 ]
INFO: Symmetry reduction: 9 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.33 -0.61 -0.46] and [ 0.33 -0.61 -0.46]
INFO: Symmetry Found: Mirror pair at [-0.44 -0.61  0.47] and [ 0.44 -0.61  0.47]
INFO: Symmetry reduction: 8 -> 6 parts.
INFO: Symmetry Found: Mirror pair at [-0.5   0.08  0.3 ] and [0.5  0.08 0.3 ]
INFO: Symmetry reduction: 5 -> 4 parts.
INFO: Symmetry Found: Mirror pair at [-0.29 -0.6  -0.28] and [ 0.29 -0.6  -0.28]
INFO: Symmetry Found: Mirror pair at [-0.28 -0.61  0.3 ] and [ 0.28 -0.61  0.3 ]
INFO: Symmetry reduction: 6 -> 4 parts.

✅ 36584_0_981: Reduced from 16 to 14 nodes.
✅ 36606_0_987: Reduced from 6 to 4 nodes.
✅ 36611_0_989: Reduced from 10 to 7 nodes.
✅ 36612_0_990: Reduced from 11 to 10 nodes.
✅ 36613_0_991: Reduced from 16 to 15 nodes.
✅ 36621_0_993: Reduced from 10 to 9 nodes.
✅ 36627_0_994: Reduced from 6 to 5 nodes.
✅ 36630_0_995: Reduced from 6 to 4 nodes.
✅ 36638_0_997: Reduced from 6 to 4 nodes.
✅ 36641_0_998: Reduced from 11 to 8 nodes.
✅ 36646_0_1002: Reduced from 10 to 6 nodes.
✅ 36653_0_1005: Reduced from 6 to 4 nodes.
✅ 36655_0_1006: Reduced from 10 to 8 nodes.
✅ 36656_0_1007: Reduced from 8 to 7 nodes.
✅ 36672_0_1013: Reduced from 6 to 5 nodes.
✅ 36676_0_1015: Reduced from 11 to 7 nodes.
✅ 36680_0_1016: Reduced from 10 to 9 nodes.
✅ 36686_0_1018: Reduced from 6 to 5 nodes.
✅ 36697_0_1023: Reduced from 6 to 4 nodes.
✅ 36702_0_1024: Reduced from 10 to 9 nodes.
✅ 36703_0_1025: Reduced from 5 to 4 nodes.
✅ 36704_0_1026: Reduced from 15 to 13 nodes.
✅ 36714_0_1028: Reduced from 9 to 8 nodes.
✅ 36716_0_1029: Reduced from 6 to 4 nodes.
✅ 36720_0_1031: Reduced from 10 to 8 nodes.
✅ 36723_0_1033: Reduced from 11 to 8 nodes.
✅ 36734_0_1037: Reduced from 6 to 5 nodes.
✅ 36738_0_1038: Reduced from 15 to 10 nodes.
✅ 36739_0_1039: Reduced from 6 to 4 nodes.
✅ 36740_0_1040: Reduced from 9 to 7 nodes.
✅ 36743_0_1042: Reduced from 9 to 7 nodes.
✅ 36749_0_1043: Reduced from 8 to 6 nodes.
✅ 36750_0_1044: Reduced from 7 to 6 nodes.
✅ 36754_0_1046: Reduced from 11 to 9 nodes.
✅ 36760_0_1047: Reduced from 9 to 7 nodes.
✅ 36766_0_1048: Reduced from 14 to 12 nodes.
✅ 36768_0_1049: Reduced from 8 to 7 nodes.
✅ 36771_0_1050: Reduced from 14 to 12 nodes.
✅ 36772_0_1051: Reduced from 11 to 9 nodes.
✅ 36782_0_1055: Reduced from 7 to 5 nodes.
✅ 36787_0_1058: Reduced from 11 to 7 nodes.
✅ 36792_0_1059: Reduced from 7 to 6 nodes.
✅ 36795_0_1060: Reduced from 10 to 8 nodes.
✅ 36803_0_1061: Reduced from 12 to 11 nodes.
✅ 36804_0_1062: Reduced from 14 to 11 nodes.
✅ 36807_0_1063: Reduced from 12 to 10 nodes.
✅ 36809_0_1064: Reduced from 10 to 7 nodes.
✅ 36811_0_1065: Reduced from 6 to 4 nodes.
✅ 36812_0_1066: Reduced from 10 to 9 nodes.
✅ 36814_0_1068: Reduced from 8 to 6 nodes.
✅ 36815_0_1069: Reduced from 11 to 10 nodes.
✅ 36821_0_1070: Reduced from 8 to 6 nodes.
✅ 36824_0_1071: Reduced from 13 to 9 nodes.
✅ 36830_0_1073: Reduced from 8 to 7 nodes.
✅ 36837_0_1074: Reduced from 8 to 7 nodes.
✅ 36838_0_1075: Reduced from 9 to 7 nodes.
✅ 36842_0_1078: Reduced from 9 to 6 nodes.
✅ 36849_0_1080: Reduced from 10 to 7 nodes.
✅ 36854_0_1083: Reduced from 10 to 7 nodes.
✅ 36858_0_1084: Reduced from 6 to 4 nodes.
✅ 36881_0_1090: Reduced from 12 to 10 nodes.
✅ 36889_0_1092: Reduced from 10 to 9 nodes.
✅ 36897_0_1093: Reduced from 16 to 12 nodes.
✅ 36904_0_1095: Reduced from 6 to 4 nodes.
✅ 36913_0_1096: Reduced from 9 to 6 nodes.
✅ 36914_0_1097: Reduced from 8 to 6 nodes.
✅ 36919_0_1098: Reduced from 5 to 4 nodes.
✅ 36927_0_1099: Reduced from 6 to 4 nodes.

In [23]:
## Nice

In [27]:
class SymRef:
    """Mirror symmetry (Reflection) across an axis."""
    def __init__(self, child, axis='AX'):
        self.child = child
        self.axis = axis  # 'AX', 'AY', or 'AZ'

class SymTrans:
    """Translational symmetry (Repetition)."""
    def __init__(self, child, axis, count, distance):
        self.child = child
        self.axis = axis      # 'AX', 'AY', or 'AZ'
        self.count = count    # Integer: number of repetitions
        self.distance = distance  # Float: spacing between repetitions

In [28]:
import numpy as np
import copy
import logging
from abstractionsshapecoder.dsl_nodes import Union, Translate, Cuboid, Rotate

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger("ShapeOptimizer")

class ShapeOptimizer:
    def __init__(self, threshold=0.01):
        self.threshold = threshold

    def is_near(self, a, b):
        """Helper for scalar comparison (abs:0.01)."""
        return abs(float(a) - float(b)) <= self.threshold

    def is_near_vec(self, v1, v2):
        """Helper for vector comparison."""
        return np.all(np.abs(np.array(v1) - np.array(v2)) <= self.threshold)

    def is_zero(self, val):
        """Rule: zero_add or zero_mov check."""
        if isinstance(val, (list, np.ndarray)):
            return np.all(np.abs(np.array(val)) <= self.threshold)
        return abs(float(val)) <= self.threshold

    def apply_optimization_rules(self, node):
        """
        Implements SEM_3DL_REWRITES logic at the individual node level.
        """
        if node is None: return None

        # --- RULE: s3dl_move_comb & s3dl_zero_mov ---
        if isinstance(node, Translate):
            node.child = self.optimize_node(node.child)
            
            # Combine Move(Move) -> Move(Add(a,x))
            if isinstance(node.child, Translate):
                logger.debug("Rule: s3dl_move_comb applied.")
                new_vec = (np.array(node.vector) + np.array(node.child.vector)).tolist()
                return Translate(node.child.child, new_vec)
            
            # Remove No-op Move
            if self.is_zero(node.vector):
                logger.debug("Rule: s3dl_zero_mov applied.")
                return node.child

        # --- RULE: s3dl_rot_comb & s3dl_zero_rot ---
        if isinstance(node, Rotate):
            node.child = self.optimize_node(node.child)
            
            # Combine Rotate(Rotate) if axis is same
            if isinstance(node.child, Rotate) and node.axis == node.child.axis:
                logger.debug("Rule: s3dl_rot_comb applied.")
                return Rotate(node.child.child, node.axis, node.angle + node.child.angle)
            
            # Remove No-op Rotate
            if self.is_zero(node.angle):
                logger.debug("Rule: s3dl_zero_rot applied.")
                return node.child

        # --- RULE: s3dl_rot_over_move ---
        # (Move (Rotate X A v) a b c) -> (Rotate (Move X a b c) A v)
        if isinstance(node, Translate) and isinstance(node.child, Rotate):
            logger.debug("Rule: s3dl_rot_over_move applied.")
            rot_node = node.child
            inner_move = Translate(rot_node.child, node.vector)
            return Rotate(inner_move, rot_node.axis, rot_node.angle)

        # --- RULE: s3dl_union_over_sym ---
        # (SymRef (Union X Y) A) -> (Union (SymRef X A) (SymRef Y A))
        if isinstance(node, SymRef) and isinstance(node.child, Union):
            logger.debug("Rule: s3dl_union_over_sym applied.")
            left_sym = SymRef(node.child.left, node.axis)
            right_sym = SymRef(node.child.right, node.axis)
            return Union(left_sym, right_sym)

        return node

    def find_symmetries(self, parts):
        optimized = []
        used_indices = set()

        for i in range(len(parts)):
            if i in used_indices: continue
            p1 = parts[i]
            
            # --- 1. Translational Symmetry (SymTrans) ---
            # Look for 3+ items with equal spacing along an axis
            for axis_idx, axis_name in enumerate(['AX', 'AY', 'AZ']):
                sequence = [i]
                if not isinstance(p1, Translate): continue
                
                # Find all potential matches in this axis
                for j in range(i + 1, len(parts)):
                    if j in used_indices: continue
                    p2 = parts[j]
                    if isinstance(p2, Translate) and self.is_near_node_geometry(p1.child, p2.child):
                        # Check if it aligns on the current axis but matches others
                        diff = np.array(p1.vector) - np.array(p2.vector)
                        other_axes = [0, 1, 2]
                        other_axes.remove(axis_idx)
                        
                        # Must be aligned on other axes
                        if all(abs(diff[ax]) < self.threshold for ax in other_axes):
                            sequence.append(j)
                
                if len(sequence) >= 3:
                    # Sort by the active axis to find consistent distance
                    sequence.sort(key=lambda idx: parts[idx].vector[axis_idx])
                    vecs = [np.array(parts[idx].vector)[axis_idx] for idx in sequence]
                    dist = vecs[1] - vecs[0]
                    
                    # Verify spacing is consistent
                    is_consistent = all(self.is_near(vecs[k+1] - vecs[k], dist) for k in range(len(vecs)-1))
                    
                    if is_consistent:
                        logger.info(f"Rule: SymTrans detected ({len(sequence)} parts, axis {axis_name})")
                        # Representative is the first item
                        optimized.append(SymTrans(parts[sequence[0]], axis_name, len(sequence), dist))
                        used_indices.update(sequence)
                        break

            if i in used_indices: continue

            # --- 2. Mirror Symmetry (SymRef) ---
            found_mirror = False
            for j in range(i + 1, len(parts)):
                if j in used_indices: continue
                p2 = parts[j]
                
                if isinstance(p1, Translate) and isinstance(p2, Translate):
                    v1, v2 = np.array(p1.vector), np.array(p2.vector)
                    for axis_name, idx in [('AX', 0), ('AY', 1), ('AZ', 2)]:
                        mirrored_v2 = v2.copy()
                        mirrored_v2[idx] = -mirrored_v2[idx]
                        
                        if self.is_near_vec(v1, mirrored_v2) and self.is_near_node_geometry(p1.child, p2.child):
                            optimized.append(SymRef(p1, axis_name))
                            used_indices.add(i); used_indices.add(j)
                            found_mirror = True
                            break
                    if found_mirror: break
            
            if not found_mirror:
                optimized.append(p1)
                used_indices.add(i)
                
        return optimized

    def is_near_node_geometry(self, n1, n2):
        """Checks if two nodes are identical in shape/size (for symmetry)."""
        if type(n1) != type(n2): return False
        if isinstance(n1, Cuboid):
            return self.is_near_vec(n1.size, n2.size)
        # Add more geometry checks (Sphere, Cylinder) here
        return False

    def flatten_unions(self, node):
        if isinstance(node, Union):
            return self.flatten_unions(node.left) + self.flatten_unions(node.right)
        return [node] if node is not None else []

    def rebuild_union(self, nodes):
        if not nodes: return None
        if len(nodes) == 1: return nodes[0]
        # s3dl_union_over ensures we build a consistent tree
        return Union(nodes[0], self.rebuild_union(nodes[1:]))

    def optimize_node(self, node):
        return self.apply_optimization_rules(node)

    def run(self, root_node):
        if root_node is None: return None

        # 1. Deep apply local rules (combining moves, rotations, etc.)
        root_node = self.optimize_node(root_node)
        
        # 2. Flatten for global structural rules
        parts = self.flatten_unions(root_node)
        
        # 3. Apply Symmetry and Factoring
        parts = self.find_symmetries(parts)
        
        # 4. Final rebuild
        return self.rebuild_union(parts)

# --- EXECUTION ---
optimizer = ShapeOptimizer()
results = {}

# Example loop with improved error handling
for shape_id, data in shapes_l0.items():
    try:
        original_dsl = data.get("dsl")
        if original_dsl is None:
            continue

        optimized = optimizer.run(copy.deepcopy(original_dsl))
        results[shape_id] = optimized
        
        orig_count = len(optimizer.flatten_unions(original_dsl))
        opt_count = len(optimizer.flatten_unions(optimized))
        
        if opt_count < orig_count:
            print(f"✅ {shape_id}: Reduced from {orig_count} to {opt_count} nodes.")
            
    except Exception as e:
        logger.error(f"Critical failure on {shape_id}: {e}", exc_info=True)

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (9 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)

✅ 172_0_0: Reduced from 11 to 6 nodes.
✅ 173_0_1: Reduced from 6 to 4 nodes.
✅ 182_0_4: Reduced from 6 to 5 nodes.
✅ 186_0_5: Reduced from 9 to 7 nodes.
✅ 187_0_6: Reduced from 15 to 8 nodes.
✅ 197_0_7: Reduced from 16 to 14 nodes.
✅ 272_0_9: Reduced from 6 to 5 nodes.
✅ 278_0_10: Reduced from 11 to 6 nodes.
✅ 280_0_11: Reduced from 16 to 15 nodes.
✅ 285_0_12: Reduced from 9 to 7 nodes.
✅ 286_0_13: Reduced from 15 to 11 nodes.
✅ 314_0_15: Reduced from 11 to 6 nodes.
✅ 315_0_16: Reduced from 6 to 4 nodes.
✅ 328_0_17: Reduced from 16 to 14 nodes.
✅ 340_0_19: Reduced from 6 to 5 nodes.
✅ 341_0_20: Reduced from 6 to 5 nodes.
✅ 347_0_21: Reduced from 9 to 7 nodes.
✅ 349_0_22: Reduced from 15 to 12 nodes.
✅ 456_0_23: Reduced from 8 to 6 nodes.
✅ 470_0_24: Reduced from 7 to 6 nodes.
✅ 515_0_27: Reduced from 10 to 9 nodes.
✅ 518_0_29: Reduced from 8 to 7 nodes.
✅ 523_0_30: Reduced from 7 to 5 nodes.
✅ 526_0_31: Reduced from 14 to 12 nodes.
✅ 539_0_32: Reduced from 12 to 7 nodes.
✅ 543_0_33: Reduced from 6 to 4 nodes.
✅ 545_0_34: Reduced from 11 to 6 nodes.
✅ 547_0_35: Reduced from 10 to 7 nodes.
✅ 550_0_36: Reduced from 16 to 14 nodes.
✅ 554_0_38: Reduced from 15 to 7 nodes.
✅ 555_0_39: Reduced from 6 to 5 nodes.
✅ 557_0_40: Reduced from 10 to 9 nodes.
✅ 561_0_41: Reduced from 6 to 5 nodes.
✅ 574_0_42: Reduced from 15 to 9 nodes.
✅ 671_0_43: Reduced from 6 to 4 nodes.
✅ 682_0_44: Reduced from 11 to 5 nodes.
✅ 698_0_46: Reduced from 10 to 6 nodes.
✅ 699_0_47: Reduced from 11 to 6 nodes.
✅ 701_0_48: Reduced from 11 to 5 nodes.
✅ 724_0_50: Reduced from 6 to 4 nodes.
✅ 725_0_51: Reduced from 9 to 6 nodes.
✅ 732_0_52: Reduced from 6 to 4 nodes.
✅ 737_0_53: Reduced from 16 to 15 nodes.
✅ 739_0_54: Reduced from 13 to 12 nodes.
✅ 746_0_56: Reduced from 8 to 6 nodes.
✅ 748_0_57: Reduced from 12 to 11 nodes.
✅ 750_0_58: Reduced from 7 to 5 nodes.
✅ 752_0_59: Reduced from 6 to 5 nodes.
✅ 754_0_60: Reduced from 16 to 9 nodes.
✅ 756_0_61: Reduced from 9 to 6 nodes.
✅ 760_0_62: Reduced from 11 to 7 nodes.
✅ 763_0_63: Reduced from 11 to 9 nodes.
✅ 772_0_65: Reduced from 9 to 7 nodes.
✅ 776_0_66: Reduced from 15 to 8 nodes.
✅ 1282_0_68: Reduced from 8 to 6 nodes.
✅ 1287_0_69: Reduced from 10 to 9 nodes.
✅ 1293_0_70: Reduced from 9 to 6 nodes.
✅ 1295_0_71: Reduced from 6 to 4 nodes.
✅ 1299_0_73: Reduced from 8 to 7 nodes.
✅ 1301_0_74: Reduced from 6 to 4 nodes.
✅ 1314_0_77: Reduced from 12 to 7 nodes.
✅ 1316_0_78: Reduced from 6 to 4 nodes.
✅ 1319_0_79: Reduced from 15 to 11 nodes.
✅ 1331_0_81: Reduced from 12 to 9 nodes.
✅ 1333_0_82: Reduced from 8 to 7 nodes.
✅ 1355_0_84: Reduced from 8 to 6 nodes.
✅ 1359_0_85: Reduced from 6 to 4 nodes.
✅ 1368_0_87: Reduced from 14 to 10 nodes.
✅ 1374_0_89: Reduced from 9 to 7 nodes.
✅ 1377_0_90: Reduced from 12 to 10 nodes.
✅ 1382_0_92: Reduced from 9 to 7 nodes.
✅ 1400_0_94: Reduced from 10 to 9 nodes.
✅ 1403_0_95: Reduced from 15 to 14 nodes.
✅ 1409_0_96: Reduced from 6 to 4 nodes.
✅ 1425_0_97: Reduced from 16 to 15 nodes.
✅ 1441_0_100: Reduced from 6 to 4 nodes.
✅ 1463_0_101: Reduced from 10 to 7 nodes.
✅ 1472_0_102: Reduced from 10 to 9 nodes.
✅ 2121_0_106: Reduced from 11 to 8 nodes.
✅ 2132_0_107: Reduced from 8 to 7 nodes.
✅ 2136_0_108: Reduced from 14 to 12 nodes.
✅ 2184_0_109: Reduced from 12 to 7 nodes.
✅ 2194_0_110: Reduced from 9 to 8 nodes.
✅ 2198_0_111: Reduced from 6 to 4 nodes.
✅ 2203_0_112: Reduced from 9 to 6 nodes.
✅ 2214_0_113: Reduced from 12 to 8 nodes.
✅ 2217_0_114: Reduced from 6 to 4 nodes.
✅ 2221_0_116: Reduced from 6 to 5 nodes.
✅ 2223_0_117: Reduced from 10 to 6 nodes.
✅ 2225_0_118: Reduced from 6 to 5 nodes.
✅ 2227_0_119: Reduced from 5 to 4 nodes.
✅ 2233_0_120: Reduced from 13 to 9 nodes.
✅ 2234_0_121: Reduced from 14 to 13 nodes.
✅ 2236_0_123: Reduced from 7 to 5 nodes.
✅ 2239_0_124: Reduced from 12 to 7 nodes.
✅ 2240_0_125: Reduced from 14 to 11 nodes.
✅ 2241_0_126: Reduced from 6 to 4 nodes.
✅ 2248_0_128: Reduced from 10 to 9 nodes.
✅ 2249_0_129: Reduced from 11 to 5 nodes.
✅ 2252_0_130: Reduced from 11 to 7 nodes.
✅ 2253_0_131: Reduced from 5 to 4 nodes.
✅ 2255_0_132: Reduced from 16 to 14 nodes.
✅ 2262_0_135: Reduced from 8 to 6 nodes.
✅ 2263_0_136: Reduced from 10 to 7 nodes.
✅ 2266_0_137: Reduced from 6 to 4 nodes.
✅ 2269_0_138: Reduced from 7 to 5 nodes.
✅ 2270_0_139: Reduced from 6 to 5 nodes.
✅ 2271_0_140: Reduced from 6 to 5 nodes.
✅ 2276_0_141: Reduced from 9 to 6 nodes.
✅ 2277_0_142: Reduced from 16 to 15 nodes.
✅ 2281_0_144: Reduced from 9 to 6 nodes.
✅ 2283_0_145: Reduced from 9 to 6 nodes.
✅ 2287_0_147: Reduced from 12 to 9 nodes.
✅ 2291_0_148: Reduced from 6 to 5 nodes.
✅ 2293_0_149: Reduced from 12 to 11 nodes.
✅ 2294_0_150: Reduced from 9 to 7 nodes.
✅ 2295_0_151: Reduced from 7 to 5 nodes.
✅ 2302_0_153: Reduced from 9 to 5 nodes.
✅ 2304_0_154: Reduced from 14 to 11 nodes.
✅ 2306_0_155: Reduced from 9 to 6 nodes.
✅ 2307_0_156: Reduced from 13 to 5 nodes.
✅ 2309_0_158: Reduced from 6 to 4 nodes.
✅ 2315_0_161: Reduced from 14 to 10 nodes.
✅ 2316_0_162: Reduced from 4 to 3 nodes.
✅ 2318_0_163: Reduced from 12 to 11 nodes.
✅ 2328_0_167: Reduced from 11 to 8 nodes.
✅ 2330_0_168: Reduced from 6 to 4 nodes.
✅ 2332_0_169: Reduced from 6 to 5 nodes.
✅ 2333_0_170: Reduced from 9 to 8 nodes.
✅ 2334_0_171: Reduced from 12 to 11 nodes.
✅ 2341_0_174: Reduced from 8 to 6 nodes.
✅ 2342_0_175: Reduced from 6 to 5 nodes.
✅ 2344_0_177: Reduced from 6 to 4 nodes.
✅ 2345_0_178: Reduced from 12 to 10 nodes.
✅ 2346_0_179: Reduced from 16 to 11 nodes.
✅ 2350_0_180: Reduced from 10 to 8 nodes.
✅ 2351_0_181: Reduced from 6 to 4 nodes.
✅ 2352_0_182: Reduced from 7 to 6 nodes.
✅ 2354_0_183: Reduced from 9 to 7 nodes.
✅ 2355_0_184: Reduced from 7 to 6 nodes.
✅ 2360_0_186: Reduced from 6 to 5 nodes.
✅ 2365_0_187: Reduced from 13 to 10 nodes.
✅ 2369_0_189: Reduced from 6 to 4 nodes.
✅ 2370_0_190: Reduced from 6 to 4 nodes.
✅ 2371_0_191: Reduced from 9 to 6 nodes.
✅ 2373_0_192: Reduced from 11 to 7 nodes.
✅ 2374_0_193: Reduced from 8 to 7 nodes.
✅ 2376_0_194: Reduced from 11 to 8 nodes.
✅ 2379_0_196: Reduced from 10 to 7 nodes.
✅ 2382_0_197: Reduced from 9 to 7 nodes.
✅ 2384_0_199: Reduced from 15 to 11 nodes.
✅ 2396_0_202: Reduced from 8 to 7 nodes.
✅ 2399_0_204: Reduced from 5 to 3 nodes.
✅ 2406_0_207: Reduced from 6 to 5 nodes.
✅ 2410_0_209: Reduced from 12 to 9 nodes.
✅ 2412_0_210: Reduced from 6 to 4 nodes.
✅ 2416_0_211: Reduced from 16 to 15 nodes.
✅ 2423_0_214: Reduced from 12 to 10 nodes.
✅ 2424_0_215: Reduced from 7 to 5 nodes.
✅ 2429_0_216: Reduced from 11 to 9 nodes.
✅ 2434_0_218: Reduced from 12 to 8 nodes.
✅ 2435_0_219: Reduced from 10 to 9 nodes.
✅ 2436_0_220: Reduced from 6 to 5 nodes.
✅ 2437_0_221: Reduced from 12 to 7 nodes.
✅ 2439_0_222: Reduced from 6 to 4 nodes.
✅ 2446_0_225: Reduced from 11 to 9 nodes.
✅ 2447_0_226: Reduced from 11 to 8 nodes.
✅ 2448_0_227: Reduced from 13 to 9 nodes.
✅ 2449_0_228: Reduced from 15 to 14 nodes.
✅ 2454_0_229: Reduced from 6 to 4 nodes.
✅ 2457_0_230: Reduced from 8 to 7 nodes.
✅ 2458_0_231: Reduced from 11 to 8 nodes.
✅ 2464_0_234: Reduced from 9 to 8 nodes.
✅ 2466_0_235: Reduced from 10 to 8 nodes.
✅ 2470_0_237: Reduced from 9 to 8 nodes.
✅ 2472_0_238: Reduced from 11 to 9 nodes.
✅ 2476_0_239: Reduced from 4 to 3 nodes.
✅ 2478_0_240: Reduced from 4 to 3 nodes.
✅ 2479_0_241: Reduced from 13 to 10 nodes.
✅ 2483_0_243: Reduced from 10 to 9 nodes.
✅ 2493_0_246: Reduced from 7 to 6 nodes.
✅ 2495_0_248: Reduced from 12 to 6 nodes.
✅ 2497_0_249: Reduced from 16 to 12 nodes.
✅ 2502_0_251: Reduced from 13 to 12 nodes.
✅ 2503_0_252: Reduced from 11 to 9 nodes.
✅ 2505_0_253: Reduced from 6 to 4 nodes.
✅ 2506_0_254: Reduced from 14 to 12 nodes.
✅ 2508_0_255: Reduced from 15 to 14 nodes.
✅ 2511_0_257: Reduced from 9 to 7 nodes.
✅ 2516_0_259: Reduced from 7 to 6 nodes.
✅ 2524_0_262: Reduced from 10 to 9 nodes.
✅ 2529_0_263: Reduced from 5 to 4 nodes.
✅ 2535_0_266: Reduced from 13 to 12 nodes.
✅ 2539_0_267: Reduced from 6 to 4 nodes.
✅ 2542_0_269: Reduced from 6 to 4 nodes.
✅ 2544_0_270: Reduced from 6 to 5 nodes.
✅ 2545_0_271: Reduced from 6 to 4 nodes.
✅ 2546_0_272: Reduced from 7 to 6 nodes.
✅ 2558_0_273: Reduced from 14 to 8 nodes.
✅ 2562_0_274: Reduced from 9 to 8 nodes.
✅ 2567_0_276: Reduced from 13 to 9 nodes.
✅ 2570_0_278: Reduced from 6 to 4 nodes.
✅ 2574_0_280: Reduced from 6 to 4 nodes.
✅ 2577_0_282: Reduced from 8 to 7 nodes.
✅ 2582_0_284: Reduced from 9 to 7 nodes.
✅ 2584_0_285: Reduced from 4 to 3 nodes.
✅ 2585_0_286: Reduced from 6 to 4 nodes.
✅ 2586_0_287: Reduced from 15 to 14 nodes.
✅ 2592_0_291: Reduced from 6 to 4 nodes.
✅ 2593_0_292: Reduced from 12 to 9 nodes.
✅ 2598_0_294: Reduced from 9 to 7 nodes.

INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)

✅ 2602_0_296: Reduced from 11 to 8 nodes.
✅ 2605_0_297: Reduced from 15 to 10 nodes.
✅ 2607_0_298: Reduced from 10 to 7 nodes.
✅ 2611_0_299: Reduced from 10 to 6 nodes.
✅ 2612_0_300: Reduced from 6 to 4 nodes.
✅ 2614_0_301: Reduced from 9 to 6 nodes.
✅ 2620_0_302: Reduced from 10 to 9 nodes.
✅ 2623_0_303: Reduced from 10 to 7 nodes.
✅ 2631_0_306: Reduced from 16 to 14 nodes.
✅ 2636_0_307: Reduced from 4 to 3 nodes.
✅ 2637_0_308: Reduced from 6 to 4 nodes.
✅ 2645_0_310: Reduced from 7 to 6 nodes.
✅ 2647_0_311: Reduced from 9 to 7 nodes.
✅ 2648_0_312: Reduced from 12 to 10 nodes.
✅ 2650_0_313: Reduced from 8 to 7 nodes.
✅ 2653_0_314: Reduced from 15 to 10 nodes.
✅ 2655_0_315: Reduced from 6 to 5 nodes.
✅ 2656_0_316: Reduced from 8 to 6 nodes.
✅ 2663_0_317: Reduced from 11 to 7 nodes.
✅ 2666_0_319: Reduced from 12 to 9 nodes.
✅ 2673_0_320: Reduced from 16 to 12 nodes.
✅ 2681_0_323: Reduced from 7 to 5 nodes.
✅ 2684_0_324: Reduced from 12 to 9 nodes.
✅ 2687_0_325: Reduced from 8 to 7 nodes.
✅ 2691_0_327: Reduced from 9 to 7 nodes.
✅ 2692_0_328: Reduced from 6 to 4 nodes.
✅ 2694_0_329: Reduced from 9 to 6 nodes.
✅ 2700_0_330: Reduced from 4 to 3 nodes.
✅ 2707_0_333: Reduced from 8 to 7 nodes.
✅ 2710_0_335: Reduced from 4 to 3 nodes.
✅ 2711_0_336: Reduced from 7 to 6 nodes.
✅ 2712_0_337: Reduced from 10 to 6 nodes.
✅ 2723_0_339: Reduced from 6 to 4 nodes.
✅ 2728_0_340: Reduced from 13 to 10 nodes.
✅ 2731_0_341: Reduced from 15 to 11 nodes.
✅ 2741_0_343: Reduced from 8 to 7 nodes.
✅ 2746_0_344: Reduced from 11 to 5 nodes.
✅ 2750_0_345: Reduced from 7 to 5 nodes.
✅ 2752_0_346: Reduced from 6 to 5 nodes.
✅ 2755_0_348: Reduced from 10 to 7 nodes.
✅ 2759_0_350: Reduced from 14 to 11 nodes.
✅ 2764_0_351: Reduced from 9 to 6 nodes.
✅ 2769_0_352: Reduced from 8 to 5 nodes.
✅ 2770_0_353: Reduced from 6 to 4 nodes.
✅ 2772_0_354: Reduced from 6 to 5 nodes.
✅ 2773_0_355: Reduced from 5 to 4 nodes.
✅ 2774_0_356: Reduced from 12 to 8 nodes.
✅ 2775_0_357: Reduced from 11 to 8 nodes.
✅ 2785_0_359: Reduced from 10 to 8 nodes.
✅ 2786_0_360: Reduced from 10 to 5 nodes.
✅ 2788_0_361: Reduced from 13 to 8 nodes.
✅ 2789_0_362: Reduced from 14 to 11 nodes.
✅ 2790_0_363: Reduced from 6 to 4 nodes.
✅ 2797_0_365: Reduced from 6 to 5 nodes.
✅ 2799_0_366: Reduced from 6 to 5 nodes.
✅ 2802_0_367: Reduced from 12 to 7 nodes.
✅ 2803_0_368: Reduced from 6 to 5 nodes.
✅ 2804_0_369: Reduced from 6 to 4 nodes.
✅ 2810_0_371: Reduced from 16 to 12 nodes.
✅ 2815_0_374: Reduced from 6 to 5 nodes.
✅ 2817_0_375: Reduced from 11 to 10 nodes.
✅ 2820_0_376: Reduced from 15 to 13 nodes.
✅ 2827_0_377: Reduced from 14 to 13 nodes.
✅ 2828_0_378: Reduced from 9 to 7 nodes.
✅ 2830_0_379: Reduced from 8 to 5 nodes.
✅ 2832_0_380: Reduced from 9 to 6 nodes.
✅ 2834_0_381: Reduced from 12 to 8 nodes.
✅ 2847_0_383: Reduced from 16 to 13 nodes.
✅ 2855_0_385: Reduced from 11 to 8 nodes.
✅ 2864_0_386: Reduced from 10 to 5 nodes.
✅ 2865_0_387: Reduced from 11 to 9 nodes.
✅ 2867_0_389: Reduced from 6 to 5 nodes.
✅ 2868_0_390: Reduced from 6 to 4 nodes.
✅ 2869_0_391: Reduced from 14 to 11 nodes.
✅ 2871_0_392: Reduced from 6 to 4 nodes.
✅ 2878_0_394: Reduced from 8 to 6 nodes.
✅ 2882_0_396: Reduced from 13 to 8 nodes.
✅ 2885_0_397: Reduced from 7 to 5 nodes.
✅ 2886_0_398: Reduced from 9 to 8 nodes.
✅ 2893_0_399: Reduced from 11 to 10 nodes.
✅ 2896_0_400: Reduced from 5 to 4 nodes.
✅ 2898_0_401: Reduced from 7 to 5 nodes.
✅ 2900_0_402: Reduced from 12 to 11 nodes.
✅ 2903_0_403: Reduced from 10 to 8 nodes.
✅ 2904_0_404: Reduced from 6 to 5 nodes.
✅ 2906_0_405: Reduced from 16 to 12 nodes.
✅ 2908_0_406: Reduced from 12 to 10 nodes.
✅ 2913_0_408: Reduced from 14 to 9 nodes.
✅ 2930_0_411: Reduced from 11 to 9 nodes.
✅ 2943_0_413: Reduced from 10 to 5 nodes.
✅ 2946_0_414: Reduced from 12 to 11 nodes.
✅ 2947_0_415: Reduced from 14 to 13 nodes.
✅ 2948_0_416: Reduced from 9 to 7 nodes.
✅ 2950_0_417: Reduced from 13 to 7 nodes.
✅ 2956_0_420: Reduced from 11 to 8 nodes.
✅ 2957_0_421: Reduced from 6 to 4 nodes.
✅ 2959_0_423: Reduced from 11 to 9 nodes.
✅ 2960_0_424: Reduced from 10 to 5 nodes.
✅ 2962_0_425: Reduced from 10 to 8 nodes.
✅ 2975_0_428: Reduced from 10 to 8 nodes.
✅ 2980_0_429: Reduced from 13 to 9 nodes.
✅ 2993_0_432: Reduced from 4 to 3 nodes.
✅ 3005_0_436: Reduced from 15 to 13 nodes.
✅ 3006_0_437: Reduced from 11 to 10 nodes.
✅ 3007_0_438: Reduced from 9 to 8 nodes.
✅ 3009_0_439: Reduced from 16 to 12 nodes.
✅ 3013_0_440: Reduced from 10 to 7 nodes.
✅ 3015_0_441: Reduced from 9 to 6 nodes.
✅ 3026_0_443: Reduced from 12 to 10 nodes.
✅ 3032_0_445: Reduced from 9 to 7 nodes.
✅ 3033_0_446: Reduced from 12 to 9 nodes.
✅ 3035_0_447: Reduced from 5 to 4 nodes.
✅ 3037_0_448: Reduced from 8 to 6 nodes.
✅ 3043_0_449: Reduced from 12 to 8 nodes.
✅ 3045_0_450: Reduced from 11 to 9 nodes.
✅ 3051_0_451: Reduced from 11 to 8 nodes.
✅ 3054_0_452: Reduced from 11 to 10 nodes.
✅ 3059_0_453: Reduced from 5 to 4 nodes.
✅ 3068_0_454: Reduced from 11 to 8 nodes.
✅ 3074_0_456: Reduced from 10 to 8 nodes.
✅ 3078_0_457: Reduced from 9 to 6 nodes.
✅ 3081_0_459: Reduced from 6 to 4 nodes.
✅ 3094_0_460: Reduced from 6 to 4 nodes.
✅ 3097_0_461: Reduced from 10 to 8 nodes.
✅ 3105_0_463: Reduced from 6 to 4 nodes.
✅ 3107_0_465: Reduced from 8 to 7 nodes.
✅ 3109_0_466: Reduced from 6 to 4 nodes.
✅ 3113_0_468: Reduced from 14 to 10 nodes.
✅ 3123_0_470: Reduced from 9 to 6 nodes.
✅ 3124_0_471: Reduced from 8 to 7 nodes.
✅ 3128_0_473: Reduced from 14 to 10 nodes.
✅ 3131_0_474: Reduced from 8 to 6 nodes.
✅ 3146_0_478: Reduced from 9 to 8 nodes.
✅ 3150_0_480: Reduced from 9 to 7 nodes.
✅ 3157_0_481: Reduced from 8 to 6 nodes.
✅ 3159_0_482: Reduced from 6 to 4 nodes.
✅ 3163_0_484: Reduced from 12 to 11 nodes.
✅ 3174_0_485: Reduced from 6 to 4 nodes.
✅ 3181_0_486: Reduced from 10 to 7 nodes.
✅ 3187_0_487: Reduced from 10 to 9 nodes.
✅ 3198_0_491: Reduced from 13 to 9 nodes.
✅ 3199_0_492: Reduced from 15 to 13 nodes.
✅ 3207_0_493: Reduced from 8 to 5 nodes.
✅ 3214_0_496: Reduced from 8 to 7 nodes.
✅ 3215_0_497: Reduced from 6 to 5 nodes.
✅ 3217_0_498: Reduced from 6 to 5 nodes.
✅ 3224_0_500: Reduced from 6 to 5 nodes.
✅ 3225_0_501: Reduced from 6 to 4 nodes.
✅ 3227_0_502: Reduced from 6 to 5 nodes.
✅ 3233_0_504: Reduced from 6 to 5 nodes.
✅ 3236_0_505: Reduced from 12 to 10 nodes.
✅ 3251_0_509: Reduced from 6 to 4 nodes.
✅ 3253_0_510: Reduced from 11 to 5 nodes.
✅ 3257_0_512: Reduced from 7 to 6 nodes.
✅ 3258_0_513: Reduced from 9 to 8 nodes.
✅ 3269_0_516: Reduced from 11 to 9 nodes.
✅ 3271_0_517: Reduced from 10 to 7 nodes.
✅ 3272_0_518: Reduced from 8 to 7 nodes.
✅ 3274_0_519: Reduced from 9 to 7 nodes.
✅ 3277_0_520: Reduced from 8 to 6 nodes.
✅ 3278_0_521: Reduced from 8 to 5 nodes.
✅ 3280_0_522: Reduced from 13 to 11 nodes.
✅ 3281_0_523: Reduced from 10 to 8 nodes.
✅ 3288_0_525: Reduced from 15 to 14 nodes.
✅ 3293_0_526: Reduced from 10 to 8 nodes.
✅ 3301_0_528: Reduced from 14 to 13 nodes.
✅ 3302_0_529: Reduced from 16 to 12 nodes.
✅ 3305_0_530: Reduced from 11 to 7 nodes.
✅ 3309_0_531: Reduced from 10 to 7 nodes.
✅ 3316_0_533: Reduced from 15 to 11 nodes.
✅ 3318_0_534: Reduced from 6 to 4 nodes.
✅ 3321_0_537: Reduced from 15 to 14 nodes.
✅ 3322_0_538: Reduced from 16 to 8 nodes.
✅ 3323_0_539: Reduced from 6 to 4 nodes.
✅ 3324_0_540: Reduced from 7 to 5 nodes.
✅ 3328_0_541: Reduced from 12 to 10 nodes.
✅ 3330_0_542: Reduced from 10 to 9 nodes.
✅ 3331_0_543: Reduced from 12 to 9 nodes.
✅ 3336_0_544: Reduced from 10 to 7 nodes.
✅ 3340_0_545: Reduced from 14 to 11 nodes.
✅ 3344_0_546: Reduced from 11 to 10 nodes.
✅ 3347_0_547: Reduced from 13 to 6 nodes.
✅ 3349_0_549: Reduced from 11 to 7 nodes.
✅ 3353_0_551: Reduced from 11 to 9 nodes.
✅ 3361_0_554: Reduced from 7 to 5 nodes.
✅ 3364_0_555: Reduced from 6 to 5 nodes.
✅ 3375_0_558: Reduced from 6 to 4 nodes.
✅ 3377_0_559: Reduced from 14 to 10 nodes.
✅ 3384_0_561: Reduced from 6 to 5 nodes.
✅ 3402_0_562: Reduced from 8 to 5 nodes.
✅ 34924_0_564: Reduced from 6 to 4 nodes.
✅ 34925_0_565: Reduced from 11 to 6 nodes.
✅ 34926_0_566: Reduced from 16 to 15 nodes.
✅ 34998_0_567: Reduced from 6 to 4 nodes.
✅ 35014_0_568: Reduced from 11 to 6 nodes.
✅ 35062_0_569: Reduced from 15 to 13 nodes.
✅ 35064_0_570: Reduced from 9 to 7 nodes.
✅ 35070_0_572: Reduced from 6 to 5 nodes.
✅ 35071_0_573: Reduced from 15 to 10 nodes.
✅ 35072_0_574: Reduced from 6 to 4 nodes.
✅ 35082_0_576: Reduced from 10 to 8 nodes.
✅ 35096_0_578: Reduced from 6 to 4 nodes.
✅ 35097_0_579: Reduced from 6 to 4 nodes.
✅ 35100_0_581: Reduced from 16 to 13 nodes.
✅ 35103_0_584: Reduced from 15 to 12 nodes.
✅ 35104_0_585: Reduced from 6 to 4 nodes.
✅ 35111_0_587: Reduced from 16 to 12 nodes.
✅ 35119_0_589: Reduced from 11 to 6 nodes.
✅ 35121_0_590: Reduced from 9 to 7 nodes.
✅ 35123_0_591: Reduced from 15 to 13 nodes.
✅ 35131_0_592: Reduced from 11 to 6 nodes.
✅ 35142_0_593: Reduced from 9 to 7 nodes.
✅ 35144_0_594: Reduced from 14 to 12 nodes.
✅ 35146_0_596: Reduced from 9 to 7 nodes.

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)

✅ 35153_0_597: Reduced from 11 to 6 nodes.
✅ 35178_0_598: Reduced from 11 to 6 nodes.
✅ 35180_0_599: Reduced from 12 to 11 nodes.
✅ 35184_0_600: Reduced from 12 to 10 nodes.
✅ 35186_0_602: Reduced from 15 to 10 nodes.
✅ 35189_0_604: Reduced from 11 to 6 nodes.
✅ 35197_0_607: Reduced from 15 to 13 nodes.
✅ 35200_0_608: Reduced from 6 to 4 nodes.
✅ 35201_0_609: Reduced from 15 to 8 nodes.
✅ 35203_0_610: Reduced from 15 to 13 nodes.
✅ 35204_0_611: Reduced from 6 to 4 nodes.
✅ 35205_0_612: Reduced from 9 to 7 nodes.
✅ 35213_0_613: Reduced from 15 to 13 nodes.
✅ 35222_0_615: Reduced from 6 to 4 nodes.
✅ 35223_0_616: Reduced from 16 to 12 nodes.
✅ 35233_0_617: Reduced from 16 to 12 nodes.
✅ 35234_0_618: Reduced from 6 to 5 nodes.
✅ 35236_0_620: Reduced from 6 to 4 nodes.
✅ 35238_0_621: Reduced from 6 to 4 nodes.
✅ 35245_0_623: Reduced from 11 to 6 nodes.
✅ 35270_0_625: Reduced from 16 to 14 nodes.
✅ 35273_0_626: Reduced from 6 to 5 nodes.
✅ 35274_0_627: Reduced from 9 to 7 nodes.
✅ 35319_0_629: Reduced from 15 to 6 nodes.
✅ 35326_0_630: Reduced from 8 to 7 nodes.
✅ 35331_0_631: Reduced from 14 to 12 nodes.
✅ 35333_0_632: Reduced from 16 to 13 nodes.
✅ 35376_0_633: Reduced from 11 to 6 nodes.
✅ 35392_0_634: Reduced from 11 to 6 nodes.
✅ 35393_0_635: Reduced from 12 to 7 nodes.
✅ 35396_0_636: Reduced from 12 to 7 nodes.
✅ 35401_0_637: Reduced from 10 to 8 nodes.
✅ 35407_0_638: Reduced from 11 to 6 nodes.
✅ 35423_0_639: Reduced from 11 to 6 nodes.
✅ 35424_0_640: Reduced from 6 to 4 nodes.
✅ 35439_0_641: Reduced from 10 to 7 nodes.
✅ 35440_0_642: Reduced from 11 to 6 nodes.
✅ 35441_0_643: Reduced from 15 to 13 nodes.
✅ 35445_0_644: Reduced from 15 to 13 nodes.
✅ 35447_0_645: Reduced from 9 to 7 nodes.
✅ 35448_0_646: Reduced from 10 to 8 nodes.
✅ 35455_0_647: Reduced from 9 to 7 nodes.
✅ 35464_0_648: Reduced from 15 to 13 nodes.
✅ 35471_0_649: Reduced from 11 to 9 nodes.
✅ 35477_0_650: Reduced from 11 to 6 nodes.
✅ 35481_0_651: Reduced from 9 to 7 nodes.
✅ 35482_0_652: Reduced from 10 to 8 nodes.
✅ 35486_0_653: Reduced from 6 to 4 nodes.
✅ 35498_0_655: Reduced from 6 to 4 nodes.
✅ 35499_0_656: Reduced from 16 to 14 nodes.
✅ 35500_0_657: Reduced from 6 to 5 nodes.
✅ 35505_0_658: Reduced from 15 to 13 nodes.
✅ 35507_0_659: Reduced from 15 to 8 nodes.
✅ 35511_0_662: Reduced from 10 to 9 nodes.
✅ 35515_0_664: Reduced from 6 to 4 nodes.
✅ 35516_0_665: Reduced from 15 to 12 nodes.
✅ 35517_0_666: Reduced from 6 to 4 nodes.
✅ 35519_0_668: Reduced from 6 to 4 nodes.
✅ 35525_0_670: Reduced from 15 to 12 nodes.
✅ 35526_0_671: Reduced from 8 to 6 nodes.
✅ 35527_0_672: Reduced from 9 to 7 nodes.
✅ 35531_0_674: Reduced from 6 to 4 nodes.
✅ 35532_0_675: Reduced from 15 to 11 nodes.
✅ 35533_0_676: Reduced from 6 to 5 nodes.
✅ 35549_0_677: Reduced from 15 to 8 nodes.
✅ 35551_0_678: Reduced from 6 to 5 nodes.
✅ 35553_0_679: Reduced from 6 to 5 nodes.
✅ 35554_0_680: Reduced from 6 to 4 nodes.
✅ 35561_0_682: Reduced from 11 to 8 nodes.
✅ 35580_0_684: Reduced from 9 to 7 nodes.
✅ 35583_0_685: Reduced from 15 to 12 nodes.
✅ 35584_0_686: Reduced from 15 to 13 nodes.
✅ 35589_0_689: Reduced from 9 to 7 nodes.
✅ 35596_0_690: Reduced from 8 to 7 nodes.
✅ 35606_0_692: Reduced from 14 to 12 nodes.
✅ 35607_0_693: Reduced from 16 to 13 nodes.
✅ 35608_0_694: Reduced from 6 to 4 nodes.
✅ 35609_0_695: Reduced from 11 to 5 nodes.
✅ 35617_0_696: Reduced from 15 to 8 nodes.
✅ 35621_0_697: Reduced from 9 to 7 nodes.
✅ 35624_0_698: Reduced from 7 to 5 nodes.
✅ 35633_0_699: Reduced from 6 to 5 nodes.
✅ 35635_0_700: Reduced from 15 to 7 nodes.
✅ 35642_0_702: Reduced from 6 to 4 nodes.
✅ 35650_0_704: Reduced from 11 to 10 nodes.
✅ 35665_0_707: Reduced from 15 to 12 nodes.
✅ 35670_0_708: Reduced from 6 to 4 nodes.
✅ 35672_0_709: Reduced from 14 to 12 nodes.
✅ 35731_0_711: Reduced from 9 to 6 nodes.
✅ 35738_0_713: Reduced from 13 to 12 nodes.
✅ 35755_0_717: Reduced from 12 to 7 nodes.
✅ 35759_0_718: Reduced from 8 to 5 nodes.
✅ 35761_0_719: Reduced from 8 to 5 nodes.
✅ 35765_0_720: Reduced from 14 to 12 nodes.
✅ 35766_0_721: Reduced from 12 to 10 nodes.
✅ 35772_0_722: Reduced from 14 to 12 nodes.
✅ 35776_0_723: Reduced from 11 to 10 nodes.
✅ 35780_0_725: Reduced from 11 to 10 nodes.
✅ 35785_0_726: Reduced from 11 to 9 nodes.
✅ 35786_0_727: Reduced from 9 to 7 nodes.
✅ 35788_0_728: Reduced from 6 to 4 nodes.
✅ 35793_0_729: Reduced from 15 to 7 nodes.
✅ 35795_0_731: Reduced from 6 to 4 nodes.
✅ 35802_0_732: Reduced from 6 to 5 nodes.
✅ 35803_0_733: Reduced from 6 to 4 nodes.
✅ 35804_0_734: Reduced from 6 to 5 nodes.
✅ 35806_0_735: Reduced from 11 to 10 nodes.
✅ 35809_0_736: Reduced from 10 to 7 nodes.
✅ 35811_0_737: Reduced from 8 to 7 nodes.
✅ 35813_0_738: Reduced from 9 to 7 nodes.
✅ 35814_0_739: Reduced from 14 to 12 nodes.
✅ 35816_0_740: Reduced from 6 to 5 nodes.
✅ 35820_0_741: Reduced from 8 to 7 nodes.
✅ 35822_0_742: Reduced from 13 to 10 nodes.
✅ 35837_0_744: Reduced from 8 to 6 nodes.
✅ 35858_0_748: Reduced from 15 to 8 nodes.
✅ 35861_0_749: Reduced from 8 to 6 nodes.
✅ 35871_0_752: Reduced from 13 to 12 nodes.
✅ 35875_0_753: Reduced from 14 to 11 nodes.
✅ 35876_0_754: Reduced from 12 to 7 nodes.
✅ 35881_0_757: Reduced from 11 to 6 nodes.
✅ 35883_0_758: Reduced from 8 to 5 nodes.
✅ 35894_0_761: Reduced from 12 to 7 nodes.
✅ 35902_0_762: Reduced from 11 to 10 nodes.
✅ 35905_0_763: Reduced from 15 to 12 nodes.
✅ 35909_0_764: Reduced from 9 to 6 nodes.
✅ 35910_0_765: Reduced from 14 to 11 nodes.
✅ 35911_0_766: Reduced from 12 to 10 nodes.
✅ 35916_0_768: Reduced from 12 to 7 nodes.
✅ 35919_0_769: Reduced from 8 to 7 nodes.
✅ 35923_0_771: Reduced from 6 to 4 nodes.
✅ 35925_0_772: Reduced from 8 to 7 nodes.
✅ 35926_0_773: Reduced from 12 to 7 nodes.
✅ 35932_0_774: Reduced from 6 to 5 nodes.
✅ 35939_0_775: Reduced from 10 to 9 nodes.
✅ 35946_0_776: Reduced from 6 to 4 nodes.
✅ 35959_0_778: Reduced from 10 to 7 nodes.
✅ 35960_0_779: Reduced from 12 to 10 nodes.
✅ 35962_0_780: Reduced from 6 to 4 nodes.
✅ 35966_0_781: Reduced from 12 to 7 nodes.
✅ 35969_0_782: Reduced from 6 to 4 nodes.
✅ 35970_0_783: Reduced from 10 to 9 nodes.
✅ 35979_0_784: Reduced from 11 to 6 nodes.
✅ 35996_0_787: Reduced from 9 to 6 nodes.
✅ 35997_0_788: Reduced from 12 to 7 nodes.
✅ 36002_0_789: Reduced from 8 to 7 nodes.
✅ 36006_0_790: Reduced from 12 to 7 nodes.
✅ 36008_0_792: Reduced from 11 to 6 nodes.
✅ 36009_0_793: Reduced from 6 to 5 nodes.
✅ 36015_0_795: Reduced from 13 to 11 nodes.
✅ 36027_0_796: Reduced from 11 to 6 nodes.
✅ 36032_0_797: Reduced from 8 to 6 nodes.
✅ 36034_0_798: Reduced from 16 to 13 nodes.
✅ 36042_0_801: Reduced from 14 to 12 nodes.
✅ 36043_0_802: Reduced from 13 to 10 nodes.
✅ 36055_0_804: Reduced from 15 to 13 nodes.
✅ 36063_0_807: Reduced from 12 to 7 nodes.
✅ 36066_0_808: Reduced from 9 to 8 nodes.
✅ 36069_0_809: Reduced from 6 to 4 nodes.
✅ 36070_0_810: Reduced from 6 to 5 nodes.
✅ 36071_0_811: Reduced from 7 to 6 nodes.
✅ 36078_0_812: Reduced from 10 to 7 nodes.
✅ 36081_0_813: Reduced from 10 to 8 nodes.
✅ 36083_0_814: Reduced from 15 to 8 nodes.
✅ 36092_0_815: Reduced from 10 to 7 nodes.
✅ 36098_0_816: Reduced from 9 to 8 nodes.
✅ 36110_0_818: Reduced from 6 to 4 nodes.
✅ 36113_0_819: Reduced from 15 to 13 nodes.
✅ 36114_0_820: Reduced from 10 to 7 nodes.
✅ 36115_0_821: Reduced from 6 to 4 nodes.
✅ 36116_0_822: Reduced from 6 to 5 nodes.
✅ 36117_0_823: Reduced from 11 to 6 nodes.
✅ 36119_0_824: Reduced from 6 to 5 nodes.
✅ 36129_0_825: Reduced from 15 to 6 nodes.
✅ 36130_0_826: Reduced from 9 to 8 nodes.
✅ 36131_0_827: Reduced from 6 to 5 nodes.
✅ 36132_0_828: Reduced from 6 to 5 nodes.
✅ 36136_0_829: Reduced from 8 to 5 nodes.
✅ 36138_0_830: Reduced from 7 to 5 nodes.
✅ 36142_0_832: Reduced from 11 to 6 nodes.
✅ 36144_0_833: Reduced from 10 to 7 nodes.
✅ 36145_0_834: Reduced from 11 to 5 nodes.
✅ 36146_0_835: Reduced from 15 to 11 nodes.
✅ 36162_0_839: Reduced from 12 to 7 nodes.
✅ 36166_0_840: Reduced from 11 to 6 nodes.
✅ 36175_0_842: Reduced from 6 to 4 nodes.
✅ 36177_0_843: Reduced from 15 to 13 nodes.
✅ 36179_0_844: Reduced from 6 to 5 nodes.
✅ 36188_0_847: Reduced from 6 to 5 nodes.
✅ 36196_0_849: Reduced from 6 to 4 nodes.
✅ 36199_0_850: Reduced from 6 to 5 nodes.
✅ 36201_0_852: Reduced from 15 to 7 nodes.
✅ 36202_0_853: Reduced from 6 to 4 nodes.
✅ 36203_0_854: Reduced from 14 to 13 nodes.
✅ 36209_0_855: Reduced from 11 to 5 nodes.
✅ 36212_0_857: Reduced from 10 to 7 nodes.
✅ 36213_0_858: Reduced from 11 to 10 nodes.
✅ 36217_0_859: Reduced from 6 to 5 nodes.
✅ 36220_0_861: Reduced from 8 to 6 nodes.
✅ 36225_0_862: Reduced from 9 to 8 nodes.
✅ 36228_0_863: Reduced from 10 to 9 nodes.
✅ 36229_0_864: Reduced from 10 to 8 nodes.

INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)

✅ 36236_0_867: Reduced from 11 to 6 nodes.
✅ 36239_0_868: Reduced from 6 to 4 nodes.
✅ 36245_0_870: Reduced from 14 to 9 nodes.
✅ 36248_0_872: Reduced from 10 to 7 nodes.
✅ 36249_0_873: Reduced from 6 to 5 nodes.
✅ 36251_0_874: Reduced from 9 to 8 nodes.
✅ 36255_0_875: Reduced from 7 to 5 nodes.
✅ 36256_0_876: Reduced from 10 to 8 nodes.
✅ 36258_0_878: Reduced from 12 to 10 nodes.
✅ 36267_0_879: Reduced from 14 to 12 nodes.
✅ 36269_0_880: Reduced from 8 to 5 nodes.
✅ 36277_0_882: Reduced from 15 to 11 nodes.
✅ 36284_0_884: Reduced from 12 to 10 nodes.
✅ 36291_0_885: Reduced from 6 to 5 nodes.
✅ 36292_0_886: Reduced from 9 to 8 nodes.
✅ 36293_0_887: Reduced from 11 to 9 nodes.
✅ 36308_0_892: Reduced from 6 to 5 nodes.
✅ 36309_0_893: Reduced from 9 to 6 nodes.
✅ 36310_0_894: Reduced from 15 to 10 nodes.
✅ 36315_0_897: Reduced from 6 to 4 nodes.
✅ 36316_0_898: Reduced from 6 to 5 nodes.
✅ 36323_0_900: Reduced from 6 to 5 nodes.
✅ 36325_0_901: Reduced from 10 to 8 nodes.
✅ 36328_0_902: Reduced from 15 to 8 nodes.
✅ 36332_0_904: Reduced from 6 to 4 nodes.
✅ 36336_0_906: Reduced from 10 to 9 nodes.
✅ 36342_0_907: Reduced from 12 to 7 nodes.
✅ 36343_0_908: Reduced from 16 to 12 nodes.
✅ 36347_0_909: Reduced from 11 to 5 nodes.
✅ 36353_0_912: Reduced from 15 to 13 nodes.
✅ 36374_0_915: Reduced from 10 to 8 nodes.
✅ 36379_0_916: Reduced from 11 to 5 nodes.
✅ 36381_0_917: Reduced from 9 to 6 nodes.
✅ 36385_0_918: Reduced from 11 to 5 nodes.
✅ 36402_0_921: Reduced from 11 to 5 nodes.
✅ 36407_0_923: Reduced from 11 to 5 nodes.
✅ 36410_0_924: Reduced from 11 to 5 nodes.
✅ 36414_0_925: Reduced from 6 to 4 nodes.
✅ 36420_0_927: Reduced from 14 to 13 nodes.
✅ 36428_0_928: Reduced from 14 to 11 nodes.
✅ 36431_0_929: Reduced from 8 to 6 nodes.
✅ 36432_0_930: Reduced from 11 to 9 nodes.
✅ 36433_0_931: Reduced from 8 to 6 nodes.
✅ 36438_0_934: Reduced from 12 to 7 nodes.
✅ 36439_0_935: Reduced from 9 to 7 nodes.
✅ 36440_0_936: Reduced from 11 to 9 nodes.
✅ 36442_0_937: Reduced from 10 to 8 nodes.
✅ 36444_0_938: Reduced from 11 to 8 nodes.
✅ 36455_0_939: Reduced from 10 to 8 nodes.
✅ 36462_0_941: Reduced from 6 to 4 nodes.
✅ 36466_0_942: Reduced from 10 to 7 nodes.
✅ 36468_0_943: Reduced from 6 to 4 nodes.
✅ 36481_0_947: Reduced from 8 to 7 nodes.
✅ 36491_0_948: Reduced from 5 to 4 nodes.
✅ 36495_0_951: Reduced from 11 to 5 nodes.
✅ 36496_0_952: Reduced from 5 to 4 nodes.
✅ 36499_0_953: Reduced from 15 to 11 nodes.
✅ 36502_0_954: Reduced from 12 to 10 nodes.
✅ 36514_0_956: Reduced from 15 to 7 nodes.
✅ 36520_0_959: Reduced from 8 to 6 nodes.
✅ 36522_0_960: Reduced from 6 to 4 nodes.
✅ 36525_0_961: Reduced from 16 to 13 nodes.
✅ 36530_0_963: Reduced from 8 to 6 nodes.
✅ 36535_0_965: Reduced from 6 to 5 nodes.
✅ 36537_0_966: Reduced from 4 to 3 nodes.
✅ 36538_0_967: Reduced from 12 to 10 nodes.
✅ 36540_0_968: Reduced from 10 to 5 nodes.
✅ 36545_0_969: Reduced from 6 to 4 nodes.
✅ 36547_0_970: Reduced from 8 to 6 nodes.
✅ 36554_0_972: Reduced from 6 to 5 nodes.
✅ 36556_0_973: Reduced from 12 to 11 nodes.
✅ 36557_0_974: Reduced from 12 to 11 nodes.
✅ 36560_0_975: Reduced from 6 to 4 nodes.
✅ 36561_0_976: Reduced from 16 to 12 nodes.
✅ 36564_0_977: Reduced from 11 to 5 nodes.
✅ 36576_0_980: Reduced from 15 to 12 nodes.
✅ 36584_0_981: Reduced from 16 to 12 nodes.
✅ 36606_0_987: Reduced from 6 to 4 nodes.
✅ 36611_0_989: Reduced from 10 to 7 nodes.
✅ 36612_0_990: Reduced from 11 to 10 nodes.
✅ 36613_0_991: Reduced from 16 to 15 nodes.
✅ 36621_0_993: Reduced from 10 to 9 nodes.
✅ 36627_0_994: Reduced from 6 to 5 nodes.
✅ 36630_0_995: Reduced from 6 to 4 nodes.
✅ 36632_0_996: Reduced from 15 to 12 nodes.
✅ 36638_0_997: Reduced from 6 to 4 nodes.
✅ 36641_0_998: Reduced from 11 to 6 nodes.
✅ 36645_0_1001: Reduced from 12 to 9 nodes.
✅ 36646_0_1002: Reduced from 10 to 6 nodes.
✅ 36653_0_1005: Reduced from 6 to 4 nodes.
✅ 36655_0_1006: Reduced from 10 to 8 nodes.
✅ 36656_0_1007: Reduced from 8 to 7 nodes.
✅ 36672_0_1013: Reduced from 6 to 5 nodes.
✅ 36676_0_1015: Reduced from 11 to 5 nodes.
✅ 36680_0_1016: Reduced from 10 to 9 nodes.
✅ 36686_0_1018: Reduced from 6 to 5 nodes.
✅ 36696_0_1022: Reduced from 16 to 10 nodes.
✅ 36697_0_1023: Reduced from 6 to 4 nodes.
✅ 36702_0_1024: Reduced from 10 to 6 nodes.
✅ 36703_0_1025: Reduced from 5 to 4 nodes.
✅ 36704_0_1026: Reduced from 15 to 11 nodes.
✅ 36714_0_1028: Reduced from 9 to 8 nodes.
✅ 36716_0_1029: Reduced from 6 to 4 nodes.
✅ 36720_0_1031: Reduced from 10 to 8 nodes.
✅ 36723_0_1033: Reduced from 11 to 8 nodes.
✅ 36734_0_1037: Reduced from 6 to 5 nodes.
✅ 36738_0_1038: Reduced from 15 to 8 nodes.
✅ 36739_0_1039: Reduced from 6 to 4 nodes.
✅ 36740_0_1040: Reduced from 9 to 7 nodes.
✅ 36743_0_1042: Reduced from 9 to 7 nodes.
✅ 36749_0_1043: Reduced from 8 to 6 nodes.
✅ 36750_0_1044: Reduced from 7 to 6 nodes.
✅ 36754_0_1046: Reduced from 11 to 9 nodes.
✅ 36760_0_1047: Reduced from 9 to 7 nodes.
✅ 36766_0_1048: Reduced from 14 to 12 nodes.
✅ 36768_0_1049: Reduced from 8 to 7 nodes.
✅ 36771_0_1050: Reduced from 14 to 12 nodes.
✅ 36772_0_1051: Reduced from 11 to 8 nodes.
✅ 36779_0_1054: Reduced from 13 to 10 nodes.
✅ 36782_0_1055: Reduced from 7 to 5 nodes.
✅ 36784_0_1057: Reduced from 11 to 8 nodes.
✅ 36787_0_1058: Reduced from 11 to 5 nodes.
✅ 36792_0_1059: Reduced from 7 to 6 nodes.
✅ 36795_0_1060: Reduced from 10 to 8 nodes.
✅ 36803_0_1061: Reduced from 12 to 11 nodes.
✅ 36804_0_1062: Reduced from 14 to 11 nodes.
✅ 36807_0_1063: Reduced from 12 to 10 nodes.
✅ 36809_0_1064: Reduced from 10 to 7 nodes.
✅ 36811_0_1065: Reduced from 6 to 4 nodes.
✅ 36812_0_1066: Reduced from 10 to 9 nodes.
✅ 36814_0_1068: Reduced from 8 to 6 nodes.
✅ 36815_0_1069: Reduced from 11 to 10 nodes.
✅ 36821_0_1070: Reduced from 8 to 6 nodes.
✅ 36824_0_1071: Reduced from 13 to 9 nodes.
✅ 36830_0_1073: Reduced from 8 to 7 nodes.
✅ 36837_0_1074: Reduced from 8 to 6 nodes.
✅ 36838_0_1075: Reduced from 9 to 7 nodes.
✅ 36842_0_1078: Reduced from 9 to 6 nodes.
✅ 36849_0_1080: Reduced from 10 to 7 nodes.
✅ 36854_0_1083: Reduced from 10 to 7 nodes.
✅ 36858_0_1084: Reduced from 6 to 4 nodes.
✅ 36869_0_1085: Reduced from 12 to 7 nodes.
✅ 36879_0_1088: Reduced from 12 to 7 nodes.
✅ 36881_0_1090: Reduced from 12 to 7 nodes.
✅ 36889_0_1092: Reduced from 10 to 9 nodes.
✅ 36897_0_1093: Reduced from 16 to 12 nodes.
✅ 36904_0_1095: Reduced from 6 to 4 nodes.
✅ 36913_0_1096: Reduced from 9 to 5 nodes.
✅ 36914_0_1097: Reduced from 8 to 6 nodes.
✅ 36919_0_1098: Reduced from 5 to 4 nodes.
✅ 36927_0_1099: Reduced from 6 to 4 nodes.

In [33]:
import pandas as pd
import copy
import logging

# Helper to turn the node tree into a string for the CSV
def dsl_to_string(node):
    if node is None:
        return ""
    # This assumes your DSL nodes have a __repr__ or __str__ 
    # If not, we can use: str(type(node).__name__)
    return str(node)

stats_list = []

for shape_id, data in shapes_l0.items():
    try:
        original_dsl = data.get("dsl")
        if original_dsl is None:
            logger.warning(f"SKIP: {shape_id} - No DSL found.")
            continue

        # 1. Run Optimization
        # We keep a copy of the original for the 'before' string
        original_copy = copy.deepcopy(original_dsl)
        optimized = optimizer.run(copy.deepcopy(original_dsl))
        
        # 2. Extract Metrics
        orig_count = len(optimizer.flatten_unions(original_copy))
        opt_count = len(optimizer.flatten_unions(optimized))
        reduction = orig_count - opt_count
        
        # 3. Logging (No emojis)
        logger.info(f"Shape: {shape_id} | Reduction: {reduction}")
        
        # 4. Append to list for DataFrame
        stats_list.append({
            "shape_id": shape_id,
            "status": "SUCCESS",
            "original_count": orig_count,
            "optimized_count": opt_count,
            "reduction": reduction,
            "original_dsl": dsl_to_string(original_copy),
            "optimized_dsl": dsl_to_string(optimized)
        })
            
    except Exception as e:
        logger.error(f"FAILURE: {shape_id} - {str(e)}")
        stats_list.append({
            "shape_id": shape_id,
            "status": f"ERROR: {str(e)}",
            "original_count": None,
            "optimized_count": None,
            "reduction": None,
            "original_dsl": None,
            "optimized_dsl": None
        })

# --- Pandas Processing ---
df = pd.DataFrame(stats_list)

# Calculate percentage
df['reduction_pct'] = (df['reduction'] / df['original_count'] * 100).round(2).fillna(0)

# Reorder columns for better readability in CSV
column_order = [
    "shape_id", "status", "original_count", "optimized_count", 
    "reduction", "reduction_pct", "original_dsl", "optimized_dsl"
]
df = df[column_order]

# Save to CSV
df.to_csv("shape_optimization_report.csv", index=False)

logger.info("CSV Report generated with 'original_dsl' and 'optimized_dsl' columns.")

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 172_0_0 | Reduction: 5
INFO: Shape: 173_0_1 | Reduction: 2
INFO: Shape: 178_0_2 | Reduction: 0
INFO: Shape: 180_0_3 | Reduction: 0
INFO: Shape: 182_0_4 | Reduction: 1
INFO: Shape: 186_0_5 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Shape: 187_0_6 | Reduction: 7
INFO: Shape: 197_0_7 | Reduction: 2
INFO: Shape: 257_0_8 | Reduction: 0
INFO: Shape: 272_0_9 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 278_0_10 | Reduction: 5
INFO: Shape: 280_0_11 | Reduction: 1
INFO: Shape: 285_0_12 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 286_0_13 | Reduction: 4
INFO: Shape: 308_0_14 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 314_0_15 | Reduction: 5
INFO: Shape: 315_0_16 | Reduction: 2
INFO: Shape: 328_0_17 | Reduction: 2
INFO: Shape: 331_0_18 | Reduction: 0
INFO: Shape: 340_0_19 | Reduction: 1
INFO: Shape: 341_0_20 | Reduction: 1
INFO: Shape: 347_0_21 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 349_0_22 | Reduction: 3
INFO: Shape: 456_0_23 | Reduction: 2
INFO: Shape: 470_0_24 | Reduction: 1
INFO: Shape: 497_0_25 | Reduction: 0
INFO: Shape: 499_0_26 | Reduction: 0
INFO: Shape: 515_0_27 | Reduction: 1
INFO: Shape: 516_0_28 | Reduction: 0
INFO: Shape: 518_0_29 | Reduction: 1
INFO: Shape: 523_0_30 | Reduction: 2
INFO: Shape: 526_0_31 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 539_0_32 | Reduction: 5
INFO: Shape: 543_0_33 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 545_0_34 | Reduction: 5
INFO: Shape: 547_0_35 | Reduction: 3
INFO: Shape: 550_0_36 | Reduction: 2
INFO: Shape: 552_0_37 | Reduction: 0
INFO: Rule: SymTrans detected (9 parts, axis AX)
INFO: Shape: 554_0_38 | Reduction: 8
INFO: Shape: 555_0_39 | Reduction: 1
INFO: Shape: 557_0_40 | Reduction: 1
INFO: Shape: 561_0_41 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 574_0_42 | Reduction: 6
INFO: Shape: 671_0_43 | Reduction: 2
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 682_0_44 | Reduction: 6
INFO: Shape: 686_0_45 | Reduction: 0
INFO: Shape: 698_0_46 | Reduction: 4
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 699_0_47 | Reduction: 5
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 701_0_48 | Reduction: 6
INFO: Shape: 716_0_49 | Reduction: 0
INFO: Shape: 724_0_50 | Reduction: 2
INFO: Shape: 725_0_51 | Reduction: 3
INFO: Shape: 732_0_52 | Reduction: 2
INFO: Shape: 737_0_53 | Reduction: 1
INFO: Shape: 739_0_54 | Reduction: 1
INFO: Shape: 740_0_55 | Reduction: 0
INFO: Shape: 746_0_56 | Reduction: 2
INFO: Shape: 748_0_57 | Reduction: 1
INFO: Shape: 750_0_58 | Reduction: 2
INFO: Shape: 752_0_59 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 754_0_60 | Reduction: 7
INFO: Shape: 756_0_61 | Reduction: 3
INFO: Shape: 760_0_62 | Reduction: 4
INFO: Shape: 763_0_63 | Reduction: 2
INFO: Shape: 768_0_64 | Reduction: 0
INFO: Shape: 772_0_65 | Reduction: 2
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Shape: 776_0_66 | Reduction: 7
INFO: Shape: 1277_0_67 | Reduction: 0
INFO: Shape: 1282_0_68 | Reduction: 2
INFO: Shape: 1287_0_69 | Reduction: 1
INFO: Shape: 1293_0_70 | Reduction: 3
INFO: Shape: 1295_0_71 | Reduction: 2
INFO: Shape: 1297_0_72 | Reduction: 0
INFO: Shape: 1299_0_73 | Reduction: 1
INFO: Shape: 1301_0_74 | Reduction: 2
INFO: Shape: 1305_0_75 | Reduction: 0
INFO: Shape: 1309_0_76 | Reduction: 0
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 1314_0_77 | Reduction: 5
INFO: Shape: 1316_0_78 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 1319_0_79 | Reduction: 4
INFO: Shape: 1329_0_80 | Reduction: 0
INFO: Shape: 1331_0_81 | Reduction: 3
INFO: Shape: 1333_0_82 | Reduction: 1
INFO: Shape: 1351_0_83 | Reduction: 0
INFO: Shape: 1355_0_84 | Reduction: 2
INFO: Shape: 1359_0_85 | Reduction: 2
INFO: Shape: 1366_0_86 | Reduction: 0
INFO: Shape: 1368_0_87 | Reduction: 4
INFO: Shape: 1373_0_88 | Reduction: 0
INFO: Shape: 1374_0_89 | Reduction: 2
INFO: Shape: 1377_0_90 | Reduction: 2
INFO: Shape: 1378_0_91 | Reduction: 0
INFO: Shape: 1382_0_92 | Reduction: 2
INFO: Shape: 1398_0_93 | Reduction: 0
INFO: Shape: 1400_0_94 | Reduction: 1
INFO: Shape: 1403_0_95 | Reduction: 1
INFO: Shape: 1409_0_96 | Reduction: 2
INFO: Shape: 1425_0_97 | Reduction: 1
INFO: Shape: 1438_0_98 | Reduction: 0
INFO: Shape: 1439_0_99 | Reduction: 0
INFO: Shape: 1441_0_100 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 1463_0_101 | Reduction: 3
INFO: Shape: 1472_0_102 | Reduction: 1
INFO: Shape: 1473_0_103 | Reduction: 0
INFO: Shape: 1746_0_104 | Reduction: 0
INFO: Shape: 1762_0_105 | Reduction: 0
INFO: Shape: 2121_0_106 | Reduction: 3
INFO: Shape: 2132_0_107 | Reduction: 1
INFO: Shape: 2136_0_108 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 2184_0_109 | Reduction: 5
INFO: Shape: 2194_0_110 | Reduction: 1
INFO: Shape: 2198_0_111 | Reduction: 2
INFO: Shape: 2203_0_112 | Reduction: 3
INFO: Shape: 2214_0_113 | Reduction: 4
INFO: Shape: 2217_0_114 | Reduction: 2
INFO: Shape: 2220_0_115 | Reduction: 0
INFO: Shape: 2221_0_116 | Reduction: 1
INFO: Shape: 2223_0_117 | Reduction: 4
INFO: Shape: 2225_0_118 | Reduction: 1
INFO: Shape: 2227_0_119 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2233_0_120 | Reduction: 4
INFO: Shape: 2234_0_121 | Reduction: 1
INFO: Shape: 2235_0_122 | Reduction: 0
INFO: Shape: 2236_0_123 | Reduction: 2
INFO: Shape: 2239_0_124 | Reduction: 5
INFO: Shape: 2240_0_125 | Reduction: 3
INFO: Shape: 2241_0_126 | Reduction: 2
INFO: Shape: 2242_0_127 | Reduction: 0
INFO: Shape: 2248_0_128 | Reduction: 1
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2249_0_129 | Reduction: 6
INFO: Shape: 2252_0_130 | Reduction: 4
INFO: Shape: 2253_0_131 | Reduction: 1
INFO: Shape: 2255_0_132 | Reduction: 2
INFO: Shape: 2260_0_133 | Reduction: 0
INFO: Shape: 2261_0_134 | Reduction: 0
INFO: Shape: 2262_0_135 | Reduction: 2
INFO: Shape: 2263_0_136 | Reduction: 3
INFO: Shape: 2266_0_137 | Reduction: 2
INFO: Shape: 2269_0_138 | Reduction: 2
INFO: Shape: 2270_0_139 | Reduction: 1
INFO: Shape: 2271_0_140 | Reduction: 1
INFO: Shape: 2276_0_141 | Reduction: 3
INFO: Shape: 2277_0_142 | Reduction: 1
INFO: Shape: 2280_0_143 | Reduction: 0
INFO: Shape: 2281_0_144 | Reduction: 3
INFO: Shape: 2283_0_145 | Reduction: 3
INFO: Shape: 2286_0_146 | Reduction: 0
INFO: Shape: 2287_0_147 | Reduction: 3
INFO: Shape: 2291_0_148 | Reduction: 1
INFO: Shape: 2293_0_149 | Reduction: 1
INFO: Shape: 2294_0_150 | Reduction: 2
INFO: Shape: 2295_0_151 | Reduction: 2
INFO: Shape: 2296_0_152 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2302_0_153 | Reduction: 4
INFO: Shape: 2304_0_154 | Reduction: 3
INFO: Shape: 2306_0_155 | Reduction: 3
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Shape: 2307_0_156 | Reduction: 8
INFO: Shape: 2308_0_157 | Reduction: 0
INFO: Shape: 2309_0_158 | Reduction: 2
INFO: Shape: 2311_0_159 | Reduction: 0
INFO: Shape: 2312_0_160 | Reduction: 0
INFO: Shape: 2315_0_161 | Reduction: 4
INFO: Shape: 2316_0_162 | Reduction: 1
INFO: Shape: 2318_0_163 | Reduction: 1
INFO: Shape: 2319_0_164 | Reduction: 0
INFO: Shape: 2323_0_165 | Reduction: 0
INFO: Shape: 2325_0_166 | Reduction: 0
INFO: Shape: 2328_0_167 | Reduction: 3
INFO: Shape: 2330_0_168 | Reduction: 2
INFO: Shape: 2332_0_169 | Reduction: 1
INFO: Shape: 2333_0_170 | Reduction: 1
INFO: Shape: 2334_0_171 | Reduction: 1
INFO: Shape: 2335_0_172 | Reduction: 0
INFO: Shape: 2338_0_173 | Reduction: 0
INFO: Shape: 2341_0_174 | Reduction: 2
INFO: Shape: 2342_0_175 | Reduction: 1
INFO: Shape: 2343_0_176 | Reduction: 0
INFO: Shape: 2344_0_177 | Reduction: 2
INFO: Shape: 2345_0_178 | Reduction: 2
INFO: Shape: 2346_0_179 | Reduction: 5
INFO: Shape: 2350_0_180 | Reduction: 2
INFO: Shape: 2351_0_181 | Reduction: 2
INFO: Shape: 2352_0_182 | Reduction: 1
INFO: Shape: 2354_0_183 | Reduction: 2
INFO: Shape: 2355_0_184 | Reduction: 1
INFO: Shape: 2359_0_185 | Reduction: 0
INFO: Shape: 2360_0_186 | Reduction: 1
INFO: Shape: 2365_0_187 | Reduction: 3
INFO: Shape: 2366_0_188 | Reduction: 0
INFO: Shape: 2369_0_189 | Reduction: 2
INFO: Shape: 2370_0_190 | Reduction: 2
INFO: Shape: 2371_0_191 | Reduction: 3
INFO: Shape: 2373_0_192 | Reduction: 4
INFO: Shape: 2374_0_193 | Reduction: 1
INFO: Shape: 2376_0_194 | Reduction: 3
INFO: Shape: 2377_0_195 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2379_0_196 | Reduction: 3
INFO: Shape: 2382_0_197 | Reduction: 2
INFO: Shape: 2383_0_198 | Reduction: 0
INFO: Shape: 2384_0_199 | Reduction: 4
INFO: Shape: 2391_0_200 | Reduction: 0
INFO: Shape: 2392_0_201 | Reduction: 0
INFO: Shape: 2396_0_202 | Reduction: 1
INFO: Shape: 2397_0_203 | Reduction: 0
INFO: Shape: 2399_0_204 | Reduction: 2
INFO: Shape: 2400_0_205 | Reduction: 0
INFO: Shape: 2405_0_206 | Reduction: 0
INFO: Shape: 2406_0_207 | Reduction: 1
INFO: Shape: 2408_0_208 | Reduction: 0
INFO: Shape: 2410_0_209 | Reduction: 3
INFO: Shape: 2412_0_210 | Reduction: 2
INFO: Shape: 2416_0_211 | Reduction: 1
INFO: Shape: 2420_0_212 | Reduction: 0
INFO: Shape: 2422_0_213 | Reduction: 0
INFO: Shape: 2423_0_214 | Reduction: 2
INFO: Shape: 2424_0_215 | Reduction: 2
INFO: Shape: 2429_0_216 | Reduction: 2
INFO: Shape: 2430_0_217 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2434_0_218 | Reduction: 4
INFO: Shape: 2435_0_219 | Reduction: 1
INFO: Shape: 2436_0_220 | Reduction: 1
INFO: Shape: 2437_0_221 | Reduction: 5
INFO: Shape: 2439_0_222 | Reduction: 2
INFO: Shape: 2441_0_223 | Reduction: 0
INFO: Shape: 2444_0_224 | Reduction: 0
INFO: Shape: 2446_0_225 | Reduction: 2
INFO: Shape: 2447_0_226 | Reduction: 3
INFO: Shape: 2448_0_227 | Reduction: 4
INFO: Shape: 2449_0_228 | Reduction: 1
INFO: Shape: 2454_0_229 | Reduction: 2
INFO: Shape: 2457_0_230 | Reduction: 1
INFO: Shape: 2458_0_231 | Reduction: 3
INFO: Shape: 2460_0_232 | Reduction: 0
INFO: Shape: 2461_0_233 | Reduction: 0
INFO: Shape: 2464_0_234 | Reduction: 1
INFO: Shape: 2466_0_235 | Reduction: 2
INFO: Shape: 2467_0_236 | Reduction: 0
INFO: Shape: 2470_0_237 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2472_0_238 | Reduction: 2
INFO: Shape: 2476_0_239 | Reduction: 1
INFO: Shape: 2478_0_240 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2479_0_241 | Reduction: 3
INFO: Shape: 2481_0_242 | Reduction: 0
INFO: Shape: 2483_0_243 | Reduction: 1
INFO: Shape: 2489_0_244 | Reduction: 0
INFO: Shape: 2491_0_245 | Reduction: 0
INFO: Shape: 2493_0_246 | Reduction: 1
INFO: Shape: 2494_0_247 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2495_0_248 | Reduction: 6
INFO: Shape: 2497_0_249 | Reduction: 4
INFO: Shape: 2498_0_250 | Reduction: 0
INFO: Shape: 2502_0_251 | Reduction: 1
INFO: Shape: 2503_0_252 | Reduction: 2
INFO: Shape: 2505_0_253 | Reduction: 2
INFO: Shape: 2506_0_254 | Reduction: 2
INFO: Shape: 2508_0_255 | Reduction: 1
INFO: Shape: 2510_0_256 | Reduction: 0
INFO: Shape: 2511_0_257 | Reduction: 2
INFO: Shape: 2513_0_258 | Reduction: 0
INFO: Shape: 2516_0_259 | Reduction: 1
INFO: Shape: 2522_0_260 | Reduction: 0
INFO: Shape: 2523_0_261 | Reduction: 0
INFO: Shape: 2524_0_262 | Reduction: 1
INFO: Shape: 2529_0_263 | Reduction: 1
INFO: Shape: 2533_0_264 | Reduction: 0
INFO: Shape: 2534_0_265 | Reduction: 0
INFO: Shape: 2535_0_266 | Reduction: 1
INFO: Shape: 2539_0_267 | Reduction: 2
INFO: Shape: 2540_0_268 | Reduction: 0
INFO: Shape: 2542_0_269 | Reduction: 2
INFO: Shape: 2544_0_270 | Reduction: 1
INFO: Shape: 2545_0_271 | Reduction: 2
INFO: Shape: 2546_0_272 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Shape: 2558_0_273 | Reduction: 6
INFO: Shape: 2562_0_274 | Reduction: 1
INFO: Shape: 2565_0_275 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2567_0_276 | Reduction: 4
INFO: Shape: 2569_0_277 | Reduction: 0
INFO: Shape: 2570_0_278 | Reduction: 2
INFO: Shape: 2571_0_279 | Reduction: 0
INFO: Shape: 2574_0_280 | Reduction: 2
INFO: Shape: 2575_0_281 | Reduction: 0
INFO: Shape: 2577_0_282 | Reduction: 1
INFO: Shape: 2578_0_283 | Reduction: 0
INFO: Shape: 2582_0_284 | Reduction: 2
INFO: Shape: 2584_0_285 | Reduction: 1
INFO: Shape: 2585_0_286 | Reduction: 2
INFO: Shape: 2586_0_287 | Reduction: 1
INFO: Shape: 2587_0_288 | Reduction: 0
INFO: Shape: 2588_0_289 | Reduction: 0
INFO: Shape: 2590_0_290 | Reduction: 0
INFO: Shape: 2592_0_291 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2593_0_292 | Reduction: 3
INFO: Shape: 2597_0_293 | Reduction: 0
INFO: Shape: 2598_0_294 | Reduction: 2
INFO: Shape: 2599_0_295 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2602_0_296 | Reduction: 3
INFO: Shape: 2605_0_297 | Reduction: 5
INFO: Shape: 2607_0_298 | Reduction: 3
INFO: Shape: 2611_0_299 | Reduction: 4
INFO: Shape: 2612_0_300 | Reduction: 2
INFO: Shape: 2614_0_301 | Reduction: 3
INFO: Shape: 2620_0_302 | Reduction: 1
INFO: Shape: 2623_0_303 | Reduction: 3
INFO: Shape: 2624_0_304 | Reduction: 0
INFO: Shape: 2626_0_305 | Reduction: 0
INFO: Shape: 2631_0_306 | Reduction: 2
INFO: Shape: 2636_0_307 | Reduction: 1
INFO: Shape: 2637_0_308 | Reduction: 2
INFO: Shape: 2641_0_309 | Reduction: 0
INFO: Shape: 2645_0_310 | Reduction: 1
INFO: Shape: 2647_0_311 | Reduction: 2
INFO: Shape: 2648_0_312 | Reduction: 2
INFO: Shape: 2650_0_313 | Reduction: 1
INFO: Shape: 2653_0_314 | Reduction: 5
INFO: Shape: 2655_0_315 | Reduction: 1
INFO: Shape: 2656_0_316 | Reduction: 2
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2663_0_317 | Reduction: 4
INFO: Shape: 2665_0_318 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2666_0_319 | Reduction: 3
INFO: Shape: 2673_0_320 | Reduction: 4
INFO: Shape: 2676_0_321 | Reduction: 0
INFO: Shape: 2680_0_322 | Reduction: 0
INFO: Shape: 2681_0_323 | Reduction: 2
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Shape: 2684_0_324 | Reduction: 3
INFO: Shape: 2687_0_325 | Reduction: 1
INFO: Shape: 2688_0_326 | Reduction: 0
INFO: Shape: 2691_0_327 | Reduction: 2
INFO: Shape: 2692_0_328 | Reduction: 2
INFO: Shape: 2694_0_329 | Reduction: 3
INFO: Shape: 2700_0_330 | Reduction: 1
INFO: Shape: 2701_0_331 | Reduction: 0
INFO: Shape: 2704_0_332 | Reduction: 0
INFO: Shape: 2707_0_333 | Reduction: 1
INFO: Shape: 2709_0_334 | Reduction: 0
INFO: Shape: 2710_0_335 | Reduction: 1
INFO: Shape: 2711_0_336 | Reduction: 1
INFO: Shape: 2712_0_337 | Reduction: 4
INFO: Shape: 2713_0_338 | Reduction: 0
INFO: Shape: 2723_0_339 | Reduction: 2
INFO: Shape: 2728_0_340 | Reduction: 3
INFO: Shape: 2731_0_341 | Reduction: 4
INFO: Shape: 2737_0_342 | Reduction: 0
INFO: Shape: 2741_0_343 | Reduction: 1
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2746_0_344 | Reduction: 6
INFO: Shape: 2750_0_345 | Reduction: 2
INFO: Shape: 2752_0_346 | Reduction: 1
INFO: Shape: 2753_0_347 | Reduction: 0
INFO: Shape: 2755_0_348 | Reduction: 3
INFO: Shape: 2757_0_349 | Reduction: 0
INFO: Shape: 2759_0_350 | Reduction: 3
INFO: Shape: 2764_0_351 | Reduction: 3
INFO: Shape: 2769_0_352 | Reduction: 3
INFO: Shape: 2770_0_353 | Reduction: 2
INFO: Shape: 2772_0_354 | Reduction: 1
INFO: Shape: 2773_0_355 | Reduction: 1
INFO: Shape: 2774_0_356 | Reduction: 4
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2775_0_357 | Reduction: 3
INFO: Shape: 2784_0_358 | Reduction: 0
INFO: Shape: 2785_0_359 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2786_0_360 | Reduction: 5
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 2788_0_361 | Reduction: 5
INFO: Shape: 2789_0_362 | Reduction: 3
INFO: Shape: 2790_0_363 | Reduction: 2
INFO: Shape: 2796_0_364 | Reduction: 0
INFO: Shape: 2797_0_365 | Reduction: 1
INFO: Shape: 2799_0_366 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2802_0_367 | Reduction: 5
INFO: Shape: 2803_0_368 | Reduction: 1
INFO: Shape: 2804_0_369 | Reduction: 2
INFO: Shape: 2807_0_370 | Reduction: 0
INFO: Shape: 2810_0_371 | Reduction: 4
INFO: Shape: 2811_0_372 | Reduction: 0
INFO: Shape: 2812_0_373 | Reduction: 0
INFO: Shape: 2815_0_374 | Reduction: 1
INFO: Shape: 2817_0_375 | Reduction: 1
INFO: Shape: 2820_0_376 | Reduction: 2
INFO: Shape: 2827_0_377 | Reduction: 1
INFO: Shape: 2828_0_378 | Reduction: 2
INFO: Shape: 2830_0_379 | Reduction: 3
INFO: Shape: 2832_0_380 | Reduction: 3
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2834_0_381 | Reduction: 4
INFO: Shape: 2841_0_382 | Reduction: 0
INFO: Shape: 2847_0_383 | Reduction: 3
INFO: Shape: 2850_0_384 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2855_0_385 | Reduction: 3
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2864_0_386 | Reduction: 5
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2865_0_387 | Reduction: 2
INFO: Shape: 2866_0_388 | Reduction: 0
INFO: Shape: 2867_0_389 | Reduction: 1
INFO: Shape: 2868_0_390 | Reduction: 2
INFO: Shape: 2869_0_391 | Reduction: 3
INFO: Shape: 2871_0_392 | Reduction: 2
INFO: Shape: 2876_0_393 | Reduction: 0
INFO: Shape: 2878_0_394 | Reduction: 2
INFO: Shape: 2880_0_395 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AY)
INFO: Shape: 2882_0_396 | Reduction: 5
INFO: Shape: 2885_0_397 | Reduction: 2
INFO: Shape: 2886_0_398 | Reduction: 1
INFO: Shape: 2893_0_399 | Reduction: 1
INFO: Shape: 2896_0_400 | Reduction: 1
INFO: Shape: 2898_0_401 | Reduction: 2
INFO: Shape: 2900_0_402 | Reduction: 1
INFO: Shape: 2903_0_403 | Reduction: 2
INFO: Shape: 2904_0_404 | Reduction: 1
INFO: Shape: 2906_0_405 | Reduction: 4
INFO: Shape: 2908_0_406 | Reduction: 2
INFO: Shape: 2909_0_407 | Reduction: 0
INFO: Shape: 2913_0_408 | Reduction: 5
INFO: Shape: 2916_0_409 | Reduction: 0
INFO: Shape: 2917_0_410 | Reduction: 0
INFO: Shape: 2930_0_411 | Reduction: 2
INFO: Shape: 2940_0_412 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2943_0_413 | Reduction: 5
INFO: Shape: 2946_0_414 | Reduction: 1
INFO: Shape: 2947_0_415 | Reduction: 1
INFO: Shape: 2948_0_416 | Reduction: 2
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Shape: 2950_0_417 | Reduction: 6
INFO: Shape: 2951_0_418 | Reduction: 0
INFO: Shape: 2955_0_419 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2956_0_420 | Reduction: 3
INFO: Shape: 2957_0_421 | Reduction: 2
INFO: Shape: 2958_0_422 | Reduction: 0
INFO: Shape: 2959_0_423 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2960_0_424 | Reduction: 5
INFO: Shape: 2962_0_425 | Reduction: 2
INFO: Shape: 2969_0_426 | Reduction: 0
INFO: Shape: 2972_0_427 | Reduction: 0
INFO: Shape: 2975_0_428 | Reduction: 2
INFO: Shape: 2980_0_429 | Reduction: 4
INFO: Shape: 2981_0_430 | Reduction: 0
INFO: Shape: 2989_0_431 | Reduction: 0
INFO: Shape: 2993_0_432 | Reduction: 1
INFO: Shape: 2995_0_433 | Reduction: 0
INFO: Shape: 3003_0_434 | Reduction: 0
INFO: Shape: 3004_0_435 | Reduction: 0
INFO: Shape: 3005_0_436 | Reduction: 2
INFO: Shape: 3006_0_437 | Reduction: 1
INFO: Shape: 3007_0_438 | Reduction: 1
INFO: Shape: 3009_0_439 | Reduction: 4
INFO: Shape: 3013_0_440 | Reduction: 3
INFO: Shape: 3015_0_441 | Reduction: 3
INFO: Shape: 3024_0_442 | Reduction: 0
INFO: Shape: 3026_0_443 | Reduction: 2
INFO: Shape: 3029_0_444 | Reduction: 0
INFO: Shape: 3032_0_445 | Reduction: 2
INFO: Shape: 3033_0_446 | Reduction: 3
INFO: Shape: 3035_0_447 | Reduction: 1
INFO: Shape: 3037_0_448 | Reduction: 2
INFO: Shape: 3043_0_449 | Reduction: 4
INFO: Shape: 3045_0_450 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 3051_0_451 | Reduction: 3

In [34]:
df

,shape_id,status,original_count,optimized_count,reduction,reduction_pct,original_dsl,optimized_dsl
0,172_0_0,SUCCESS,11,6,5,45.45,"Union(\n Translate(vec=[-0.000, -0.170, 0.0...","Union(\n Translate(vec=[-0.000, -0.170, 0.0..."
1,173_0_1,SUCCESS,6,4,2,33.33,"Union(\n Translate(vec=[-0.000, -0.160, -0....","Union(\n Translate(vec=[-0.000, -0.160, -0...."
2,178_0_2,SUCCESS,6,6,0,0.00,"Union(\n Translate(vec=[0.000, -0.180, 0.00...","Union(\n Translate(vec=[0.000, -0.180, 0.00..."
3,180_0_3,SUCCESS,16,16,0,0.00,"Union(\n Rotate(quat=[-0.1741, 0.0000, 0.00...","Union(\n Rotate(quat=[-0.1741, 0.0000, 0.00..."
4,182_0_4,SUCCESS,6,5,1,16.67,"Union(\n Translate(vec=[-0.000, 0.330, -0.4...","Union(\n Translate(vec=[-0.000, 0.330, -0.4..."
...,...,...,...,...,...,...,...,...
1095,36904_0_1095,SUCCESS,6,4,2,33.33,"Union(\n Translate(vec=[-0.000, -0.220, -0....","Union(\n Translate(vec=[-0.000, -0.220, -0...."
1096,36913_0_1096,SUCCESS,9,5,4,44.44,"Union(\n Translate(vec=[-0.000, -0.150, -0....","Union(\n Translate(vec=[-0.000, -0.150, -0...."
1097,36914_0_1097,SUCCESS,8,6,2,25.00,"Union(\n Translate(vec=[-0.000, -0.250, 0.0...","Union(\n Translate(vec=[-0.000, -0.250, 0.0..."
1098,36919_0_1098,SUCCESS,5,4,1,20.00,"Union(\n Translate(vec=[0.000, -0.480, 0.29...","Union(\n Translate(vec=[0.000, -0.480, 0.29..."
1099,36927_0_1099,SUCCESS,6,4,2,33.33,"Union(\n Translate(vec=[0.000, -0.230, 0.08...","Union(\n Translate(vec=[0.000, -0.230, 0.08..."

In [22]:
from abstractionsshapecoder.dsl_utils import collect_singleton_and_pair_data
from abstractionsshapecoder.debug_utils import debug_info, debug_success

# 1. Isolate the DSL objects from the dictionary
all_l0_dsl_trees = [data['dsl'] for data in shapes_l0.values()]

debug_info(f"Extracting parameters from {len(all_l0_dsl_trees)} L0 shapes...")

# 2. Run the collection utility
# s_data_l0: { 'NodeName': [ [params], [params], ... ] }
# p_data_l0: { 'Parent(Child)': [ [params], [params], ... ] }
s_data_l0, p_data_l0 = collect_singleton_and_pair_data(all_l0_dsl_trees)

debug_success(f"Extraction complete.")
debug_info(f"Unique Singletons found: {len(s_data_l0)}")
debug_info(f"Unique Parent-Child Pairs found: {len(p_data_l0)}")

[INFO] Extracting parameters from 1100 L0 shapes...
[SUCCESS] Extraction complete.
[INFO] Unique Singletons found: 3
[INFO] Unique Parent-Child Pairs found: 5

In [23]:
import pandas as pd

# Create a summary for Singletons
singleton_summary = []
for node_type, param_list in s_data_l0.items():
    singleton_summary.append({
        "Node Type": node_type,
        "Total Occurrences": len(param_list),
        "Param Dimension": len(param_list[0]) if param_list else 0,
        "Example Params": param_list[0] if param_list else []
    })

# Create a summary for Pairs
pair_summary = []
for pair_name, param_list in p_data_l0.items():
    pair_summary.append({
        "Relationship": pair_name,
        "Total Occurrences": len(param_list),
        "Combined Dimension": len(param_list[0]) if param_list else 0
    })

# Convert to DataFrames for easy viewing
df_singletons = pd.DataFrame(singleton_summary).sort_values("Total Occurrences", ascending=False)
df_pairs = pd.DataFrame(pair_summary).sort_values("Total Occurrences", ascending=False)

print("=== L0 SINGLETON CENSUS ===")
display(df_singletons)

print("\n=== L0 PAIR CENSUS ===")
display(df_pairs)

=== L0 SINGLETON CENSUS ===

,Node Type,Total Occurrences,Param Dimension,Example Params
0,Cuboid,10268,3,"[0.68, 0.09, 0.66]"
2,Translate,10268,3,"[-0.0, -0.17, 0.0]"
1,Rotate,3416,4,"[-0.17410813759359595, 0.0, 0.0, 0.98472653890..."

=== L0 PAIR CENSUS ===

        Relationship  Total Occurrences  Combined Dimension
2  Translate(Cuboid)              10268                   6
4   Union(Translate)               8656                   3
0     Rotate(Rotate)               1804                   8
1  Rotate(Translate)               1612                   7
3      Union(Rotate)               1612                   4

In [24]:
import torch

class FloatOperation:
    def __init__(self, func, unary: bool = False):
        self.func = func
        self.unary = unary

LANGUAGE = {
    "binary_ops": {
        "Add": FloatOperation(lambda a, b: a + b),
        "Sub": FloatOperation(lambda a, b: a - b),
        "Mul": FloatOperation(lambda a, b: a * b),
    },
    "unary_ops": {"Neg": FloatOperation(lambda a: -a, unary=True)}
}

def log_best_match(method_name, target_name, expr, diff, tol, min_match):
    """Utility to print how close the best candidate came to success."""
    mean_err = diff.mean().item()
    match_frac = (diff < tol).float().mean().item()
    status = "[SUCCESS]" if match_frac >= min_match else "[FAILED ]"
    
    print(f"    {status} {method_name:10} | Target: {target_name:4} | Best: {expr:20} | "
          f"AvgErr: {mean_err:.4f} | Match: {match_frac*100:5.1f}% (Req: {min_match*100}%)")

def compare_with_tolerance(predicted, target, max_error, min_fraction):
    if not isinstance(predicted, torch.Tensor):
        predicted = torch.tensor(predicted, device=target.device, dtype=target.dtype)
    if predicted.dim() == 0: 
        predicted = predicted.expand_as(target)
    
    diff = torch.abs(predicted - target)
    success = (diff < max_error).float().mean().item() >= min_fraction
    return success, diff

def search_direct_variable(inp, target_name):
    best_diff, best_name = None, None
    for name, values in inp["variables"].items():
        success, diff = compare_with_tolerance(values, inp["target"], inp["tol"], inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success:
            log_best_match("Direct", target_name, name, diff, inp["tol"], inp["min_match"])
            return name
            
    if best_name:
        log_best_match("Direct", target_name, best_name, best_diff, inp["tol"], inp["min_match"])
    return None

def search_constants(inp, target_name):
    best_diff, best_name = None, None
    for name, val in inp["simple_consts"].items():
        # Constants usually use 0.05 tol as per your original code
        success, diff = compare_with_tolerance(val, inp["target"], 0.05, inp["min_match"])
        if best_diff is None or diff.mean() < best_diff.mean():
            best_diff, best_name = diff, name
        if success:
            log_best_match("Const", target_name, name, diff, 0.05, inp["min_match"])
            return name
            
    if best_name:
        log_best_match("Const", target_name, best_name, best_diff, 0.05, inp["min_match"])
    return None

def search_binary_operations(inp, target_name):
    var_keys = list(inp["variables"].keys())
    const_keys = list(inp["extended_consts"].keys())
    all_keys = var_keys + const_keys
    
    value_stack = torch.stack(list(inp["variables"].values()) + 
                             [c.expand(len(inp["target"])) for c in inp["extended_consts"].values()])
    
    index_pairs = torch.cartesian_prod(torch.arange(len(inp["variables"])), torch.arange(len(all_keys)))
    
    global_best_fraction = -1.0
    global_best_expr = ""
    global_best_diff = None

    for op_name, op in LANGUAGE["binary_ops"].items():
        results = op.func(value_stack[index_pairs[:, 0]], value_stack[index_pairs[:, 1]])
        diffs = torch.abs(results - inp["target"].unsqueeze(0))
        fractions = (diffs < inp["tol"]).float().mean(dim=1)
        
        # Find best in this specific operation
        best_val, best_idx = torch.max(fractions, dim=0)
        idx = best_idx.item()
        expr = f"{op_name}({all_keys[index_pairs[idx][0]]}, {all_keys[index_pairs[idx][1]]})"
        
        if best_val.item() > global_best_fraction:
            global_best_fraction = best_val.item()
            global_best_expr = expr
            global_best_diff = diffs[idx]

        if best_val.item() >= inp["min_match"]:
            log_best_match("Binary", target_name, expr, diffs[idx], inp["tol"], inp["min_match"])
            return expr

    if global_best_expr:
        log_best_match("Binary", target_name, global_best_expr, global_best_diff, inp["tol"], inp["min_match"])
    return None

def discover_symbolic_rules(df, custom_tol=0.08, custom_min_match=0.85, custom_constants=None):
    rules = {}
    const_dict = {str(round(c, 2)): torch.tensor(c, dtype=torch.float32) for c in (custom_constants or [0.5, 1.0])}

    for target_col in df.columns:
        print(f"--- Searching for target: {target_col} ---")
        input_cols = [p for p in df.columns if p != target_col]
        target_tensor = torch.tensor(df[target_col].values, dtype=torch.float32)
        
        search_space = {
            "target": target_tensor,
            "variables": {inp: torch.tensor(df[inp].values, dtype=torch.float32) for inp in input_cols},
            "simple_consts": const_dict, "extended_consts": const_dict,
            "tol": custom_tol, "min_match": custom_min_match
        }

        found_for_col = False
        for search_fn, name in [(search_direct_variable, "Direct"), 
                                (search_constants, "Const"), 
                                (search_binary_operations, "Binary")]:
            found = search_fn(search_space, target_col)
            if found:
                rules[target_col] = found
                found_for_col = True
                break
        
        if not found_for_col:
            print(f"    [FAILED ] No rule discovered for {target_col}")
            
    return rules

In [25]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY
# ==========================================
raw_cuboids = s_data_l0.get("Cuboid", [])
df_l0 = pd.DataFrame(raw_cuboids, columns=['sw', 'sh', 'sd'])

# Group cuboids into 4 functional types (e.g., Legs, Seats, Backs, Joints)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0['cluster'] = kmeans.fit_predict(df_l0)

cluster_grammars = {}
s_data_l1 = {"Cuboid": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0[df_l0['cluster'] == c_id].drop(columns=['cluster'])
    
    # Auto-harvest potential constants (modes) for this specific cluster
    modes = [float(stats.mode(np.round(subset[col].values, 2), keepdims=True)[0][0]) for col in subset.columns]
    
    # Discover Symbolic Rules (Symmetry or Constants)
    # Using your optimized thresholds: 5% tolerance and 40% minimum match
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=list(set(modes + [0.0, 1.0])), 
        custom_tol=0.05, 
        custom_min_match=0.40
    )
    cluster_grammars[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (COMPRESSION TO L1)
# ==========================================
for _, row in df_l0.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars[c_id]
    
    # Compress: Keep only dimensions that ARE NOT explained by a rule
    latent = [row[v] for v in ['sw', 'sh', 'sd'] if v not in rules]
    
    # Fallback: preserve at least one dimension to keep the instance unique
    if not latent: 
        latent = [row['sw']] 
    
    s_data_l1["Cuboid"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (DECOMPRESSION TO L0)
# ==========================================
reconstructed_rows = []

for node in s_data_l1["Cuboid"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars[c_id]
    
    # Identify which variables are "Free" (Latent)
    latent_vars = [v for v in ['sw', 'sh', 'sd'] if v not in rules]
    if not latent_vars: 
        latent_vars = ['sw']
    
    # Map latent values back to their variable names
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    # Apply rules to fill in the missing/fixed dimensions
    for target, expr in rules.items():
        if expr in recon: 
            # Alias/Symmetry rule (e.g., sd = sw)
            recon[target] = recon[expr]
        else: 
            # Constant rule (e.g., sh = 0.05)
            try:
                recon[target] = float(expr)
            except ValueError:
                recon[target] = 0.05 # Default safety fallback
                
    reconstructed_rows.append([recon.get('sw', 0), recon.get('sh', 0), recon.get('sd', 0)])

# ==========================================
# 4. FINAL PERFORMANCE METRICS
# ==========================================
df_recon = pd.DataFrame(reconstructed_rows, columns=['sw_r', 'sh_r', 'sd_r'])

# Parameter Savings
total_l0_params = len(df_l0) * 3
total_l1_params = sum(len(node["l"]) for node in s_data_l1["Cuboid"])
reduction = (1 - total_l1_params / total_l0_params) * 100

# Error Metric
mse = ((df_l0[['sw', 'sh', 'sd']].values - df_recon.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_params}")
print(f"L1 Parameters: {total_l1_params}")
print(f"Compression:   {reduction:.2f}%")
print(f"Reconstruction MSE: {mse:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: sw ---
    [SUCCESS] Direct     | Target: sw   | Best: sd                   | AvgErr: 0.0378 | Match:  83.9% (Req: 40.0%)
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sd                   | AvgErr: 0.5196 | Match:   0.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.6                  | AvgErr: 0.1200 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Add(sw, 0.6)         | AvgErr: 0.1425 | Match:  19.1% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [SUCCESS] Direct     | Target: sd   | Best: sw                   | AvgErr: 0.0378 | Match:  83.9% (Req: 40.0%)
0        | {'sw': 'sd', 'sd': 'sw'}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sd                   | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sw   | Best: 0.74                 | AvgErr: 0.2384 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: sw   | Best: Add(sd, 0.0)         | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] No rule discovered for sw
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.5935 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.09                 | AvgErr: 0.1886 | Match:  36.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Mul(sd, 0.09)        | AvgErr: 0.1945 | Match:  30.7% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sw                   | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sd   | Best: 0.86                 | AvgErr: 0.1619 | Match:  21.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: sd   | Best: Add(sw, 0.0)         | AvgErr: 0.2762 | Match:  30.6% (Req: 40.0%)
    [FAILED ] No rule discovered for sd
1        | {}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sh                   | AvgErr: 0.3320 | Match:  13.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sw   | Best: 0.88                 | AvgErr: 0.1651 | Match:  19.5% (Req: 40.0%)
    [FAILED ] Binary     | Target: sw   | Best: Mul(sh, 0.88)        | AvgErr: 0.3433 | Match:  14.8% (Req: 40.0%)
    [FAILED ] No rule discovered for sw
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.3320 | Match:  13.6% (Req: 40.0%)
    [FAILED ] Const      | Target: sh   | Best: 0.77                 | AvgErr: 0.2378 | Match:  17.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: sh   | Best: Add(sw, 0.11)        | AvgErr: 0.3737 | Match:  13.9% (Req: 40.0%)
    [FAILED ] No rule discovered for sh
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sh                   | AvgErr: 0.5019 | Match:   8.1% (Req: 40.0%)
    [FAILED ] Const      | Target: sd   | Best: 0.11                 | AvgErr: 0.1196 | Match:  37.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: sd   | Best: Mul(sw, 0.11)        | AvgErr: 0.1259 | Match:  35.0% (Req: 40.0%)
    [FAILED ] No rule discovered for sd
2        | {}
--- Searching for target: sw ---
    [FAILED ] Direct     | Target: sw   | Best: sh                   | AvgErr: 0.2047 | Match:  39.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: sw   | Best: 0.06                 | AvgErr: 0.1847 | Match:  47.4% (Req: 40.0%)
--- Searching for target: sh ---
    [FAILED ] Direct     | Target: sh   | Best: sw                   | AvgErr: 0.2047 | Match:  39.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: sh   | Best: 0.06                 | AvgErr: 0.0750 | Match:  61.8% (Req: 40.0%)
--- Searching for target: sd ---
    [FAILED ] Direct     | Target: sd   | Best: sh                   | AvgErr: 0.2324 | Match:  26.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: sd   | Best: 0.06                 | AvgErr: 0.2327 | Match:  46.4% (Req: 40.0%)
3        | {'sw': '0.06', 'sh': '0.06', 'sd': '0.06'}
-----------------------------------------------------------------
L0 Parameters: 30804
L1 Parameters: 16568
Compression:   46.21%
Reconstruction MSE: 0.020697

In [26]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY (TRANSLATE)
# ==========================================
raw_translates = s_data_l0.get("Translate", [])
# Translation nodes use tx, ty, tz (X, Y, Z coordinates)
df_l0_t = pd.DataFrame(raw_translates, columns=['tx', 'ty', 'tz'])

# Cluster positions (helps group parts like "Left Legs" vs "Right Legs")
kmeans_t = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0_t['cluster'] = kmeans_t.fit_predict(df_l0_t)

cluster_grammars_t = {}
s_data_l1_t = {"Translate": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0_t[df_l0_t['cluster'] == c_id].drop(columns=['cluster'])
    
    # --- ENHANCED CONSTANT HARVESTING ---
    # We take top 5 frequent positions (tx, ty, or tz) to catch standard offsets
    dynamic_consts = [0.0] # 0 is a critical constant for center-alignment
    for col in subset.columns:
        top_vals = subset[col].round(2).value_counts().head(5).index.tolist()
        dynamic_consts.extend(top_vals)
    dynamic_consts = list(set([x for x in dynamic_consts if not np.isnan(x)]))
    
    # Discover Rules with slightly relaxed tolerance (0.06) to catch near-misses
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=dynamic_consts, 
        custom_tol=0.06, 
        custom_min_match=0.40
    )
    cluster_grammars_t[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (L0 -> L1)
# ==========================================
for _, row in df_l0_t.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars_t[c_id]
    
    # Compress: tx, ty, tz are only latent if they aren't ruled
    latent = [row[v] for v in ['tx', 'ty', 'tz'] if v not in rules]
    
    if not latent: 
        latent = [row['ty']] # Default to vertical position if everything else is fixed
    
    s_data_l1_t["Translate"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (L1 -> L0)
# ==========================================
reconstructed_t = []

for node in s_data_l1_t["Translate"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars_t[c_id]
    
    latent_vars = [v for v in ['tx', 'ty', 'tz'] if v not in rules]
    if not latent_vars: latent_vars = ['ty']
    
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    for target, expr in rules.items():
        if expr in recon: # Alias/Symmetry (e.g. tz = tx)
            recon[target] = recon[expr]
        else: # Constant (e.g. ty = 0.45)
            try:
                recon[target] = float(expr)
            except:
                recon[target] = 0.0
                
    reconstructed_t.append([recon.get('tx', 0), recon.get('ty', 0), recon.get('tz', 0)])

# ==========================================
# 4. METRICS
# ==========================================
df_recon_t = pd.DataFrame(reconstructed_t, columns=['tx_r', 'ty_r', 'tz_r'])

total_l0_t = len(df_l0_t) * 3
total_l1_t = sum(len(node["l"]) for node in s_data_l1_t["Translate"])
reduction_t = (1 - total_l1_t / total_l0_t) * 100
mse_t = ((df_l0_t[['tx', 'ty', 'tz']].values - df_recon_t.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_t}")
print(f"L1 Parameters: {total_l1_t}")
print(f"Compression:   {reduction_t:.2f}%")
print(f"Reconstruction MSE: {mse_t:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.3347 | Match:   8.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: tx   | Best: 0.0                  | AvgErr: 0.1396 | Match:  51.8% (Req: 40.0%)
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tx                   | AvgErr: 0.3775 | Match:   8.0% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: 0.3                  | AvgErr: 0.1419 | Match:  32.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Sub(tx, -0.36)       | AvgErr: 0.2296 | Match:  20.1% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: tx                   | AvgErr: 0.3347 | Match:   8.6% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: -0.27                | AvgErr: 0.1031 | Match:  31.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Add(tx, -0.32)       | AvgErr: 0.1913 | Match:  29.0% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
0        | {'tx': '0.0'}
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: ty                   | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: tx   | Best: -0.4                 | AvgErr: 0.0878 | Match:  33.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tx   | Best: Add(tz, -0.57)       | AvgErr: 0.1799 | Match:  22.8% (Req: 40.0%)
    [FAILED ] No rule discovered for tx
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tx                   | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: -0.44                | AvgErr: 0.2091 | Match:  16.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Add(tx, 0.0)         | AvgErr: 0.2641 | Match:  12.3% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: ty                   | AvgErr: 0.6268 | Match:   7.9% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: 0.34                 | AvgErr: 0.1428 | Match:  27.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Mul(ty, -0.57)       | AvgErr: 0.1599 | Match:  29.2% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
1        | {}
--- Searching for target: tx ---
    [SUCCESS] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.1422 | Match:  45.5% (Req: 40.0%)
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tz                   | AvgErr: 0.4461 | Match:   9.3% (Req: 40.0%)
    [FAILED ] Const      | Target: ty   | Best: -0.17                | AvgErr: 0.2001 | Match:  16.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: ty   | Best: Add(tz, -0.16)       | AvgErr: 0.3384 | Match:  20.1% (Req: 40.0%)
    [FAILED ] No rule discovered for ty
--- Searching for target: tz ---
    [SUCCESS] Direct     | Target: tz   | Best: tx                   | AvgErr: 0.1422 | Match:  45.5% (Req: 40.0%)
2        | {'tx': 'tz', 'tz': 'tx'}
--- Searching for target: tx ---
    [FAILED ] Direct     | Target: tx   | Best: tz                   | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] Const      | Target: tx   | Best: 0.0                  | AvgErr: 0.2996 | Match:  14.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: tx   | Best: Add(tz, 0.0)         | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] No rule discovered for tx
--- Searching for target: ty ---
    [FAILED ] Direct     | Target: ty   | Best: tz                   | AvgErr: 0.2181 | Match:  14.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: ty   | Best: -0.5                 | AvgErr: 0.0885 | Match:  40.5% (Req: 40.0%)
--- Searching for target: tz ---
    [FAILED ] Direct     | Target: tz   | Best: ty                   | AvgErr: 0.2181 | Match:  14.1% (Req: 40.0%)
    [FAILED ] Const      | Target: tz   | Best: -0.31                | AvgErr: 0.1005 | Match:  32.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: tz   | Best: Add(tx, 0.0)         | AvgErr: 0.3459 | Match:  29.3% (Req: 40.0%)
    [FAILED ] No rule discovered for tz
3        | {'ty': '-0.5'}
-----------------------------------------------------------------
L0 Parameters: 30804
L1 Parameters: 19002
Compression:   38.31%
Reconstruction MSE: 0.023101

In [27]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# ==========================================
# 1. CLUSTERING & RULE DISCOVERY (ROTATE)
# ==========================================
raw_rotates = s_data_l0.get("Rotate", [])
# Assuming Rotate has 4 parameters: qx, qy, qz, qw
df_l0_r = pd.DataFrame(raw_rotates, columns=['qx', 'qy', 'qz', 'qw'])

# Cluster rotations (groups parts with similar orientations)
kmeans_r = KMeans(n_clusters=4, random_state=42, n_init=10)
df_l0_r['cluster'] = kmeans_r.fit_predict(df_l0_r)

cluster_grammars_r = {}
s_data_l1_r = {"Rotate": []}

print(f"{'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 65)

for c_id in range(4):
    subset = df_l0_r[df_l0_r['cluster'] == c_id].drop(columns=['cluster'])
    
    # --- ROTATION SPECIFIC CONSTANTS ---
    # Common rotation values: 0, 1, 0.707 (45/90 deg in quaternions), -1
    dynamic_consts = [0.0, 1.0, -1.0, 0.707, -0.707] 
    for col in subset.columns:
        top_vals = subset[col].round(3).value_counts().head(5).index.tolist()
        dynamic_consts.extend(top_vals)
    dynamic_consts = list(set([x for x in dynamic_consts if not np.isnan(x)]))
    
    # Discover Rules
    # Using 0.06 tol to account for floating point precision in rotations
    rules = discover_symbolic_rules(
        subset, 
        custom_constants=dynamic_consts, 
        custom_tol=0.06, 
        custom_min_match=0.40
    )
    cluster_grammars_r[c_id] = rules
    print(f"{c_id:<8} | {rules}")

# ==========================================
# 2. ABSTRACTION (L0 -> L1)
# ==========================================
for _, row in df_l0_r.iterrows():
    c_id = int(row['cluster'])
    rules = cluster_grammars_r[c_id]
    
    # Compress: keep only the components that aren't fixed or aliased
    latent = [row[v] for v in ['qx', 'qy', 'qz', 'qw'] if v not in rules]
    
    # Fallback: if it's a perfect constant rotation, keep qw to represent the instance
    if not latent: 
        latent = [row['qw']] 
    
    s_data_l1_r["Rotate"].append({"c": c_id, "l": [round(x, 4) for x in latent]})

# ==========================================
# 3. RECONSTRUCTION (L1 -> L0)
# ==========================================
reconstructed_r = []

for node in s_data_l1_r["Rotate"]:
    c_id = node["c"]
    latent = node["l"]
    rules = cluster_grammars_r[c_id]
    
    latent_vars = [v for v in ['qx', 'qy', 'qz', 'qw'] if v not in rules]
    if not latent_vars: latent_vars = ['qw']
    
    recon = {var: val for var, val in zip(latent_vars, latent)}
    
    for target, expr in rules.items():
        if expr in recon:
            recon[target] = recon[expr]
        else:
            try:
                recon[target] = float(expr)
            except:
                # Default for Quaternions is usually (0,0,0,1)
                recon[target] = 1.0 if target == 'qw' else 0.0
                
    reconstructed_r.append([recon.get('qx', 0), recon.get('qy', 0), recon.get('qz', 0), recon.get('qw', 1)])

# ==========================================
# 4. METRICS
# ==========================================
df_recon_r = pd.DataFrame(reconstructed_r, columns=['qx_r', 'qy_r', 'qz_r', 'qw_r'])

total_l0_r = len(df_l0_r) * 4
total_l1_r = sum(len(node["l"]) for node in s_data_l1_r["Rotate"])
reduction_r = (1 - total_l1_r / total_l0_r) * 100
mse_r = ((df_l0_r[['qx', 'qy', 'qz', 'qw']].values - df_recon_r.values)**2).mean()

print("-" * 65)
print(f"L0 Parameters: {total_l0_r}")
print(f"L1 Parameters: {total_l1_r}")
print(f"Compression:   {reduction_r:.2f}%")
print(f"Reconstruction MSE: {mse_r:.6f}")

CLUSTER  | RULES FOUND
-----------------------------------------------------------------
--- Searching for target: qx ---
    [SUCCESS] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.0160 | Match:  94.2% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qx                   | AvgErr: 0.0160 | Match:  94.2% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qx                   | AvgErr: 0.0253 | Match:  88.3% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qx                   | AvgErr: 0.9958 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0034 | Match:  99.6% (Req: 40.0%)
0        | {'qx': 'qy', 'qy': 'qx', 'qz': 'qx', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.0995 | Match:  19.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: -0.09                | AvgErr: 0.0302 | Match:  83.9% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qy                   | AvgErr: 0.9944 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0033 | Match: 100.0% (Req: 40.0%)
1        | {'qx': '-0.09', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.1876 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: 0.14                 | AvgErr: 0.0651 | Match:  64.3% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qx                   | AvgErr: 0.7909 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0214 | Match:  88.8% (Req: 40.0%)
2        | {'qx': '0.14', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
--- Searching for target: qx ---
    [FAILED ] Direct     | Target: qx   | Best: qy                   | AvgErr: 0.2616 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qx   | Best: -0.19                | AvgErr: 0.0730 | Match:  42.2% (Req: 40.0%)
--- Searching for target: qy ---
    [SUCCESS] Direct     | Target: qy   | Best: qz                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qz ---
    [SUCCESS] Direct     | Target: qz   | Best: qy                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: qw ---
    [FAILED ] Direct     | Target: qw   | Best: qy                   | AvgErr: 0.9634 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: qw   | Best: 1.0                  | AvgErr: 0.0366 | Match:  76.0% (Req: 40.0%)
3        | {'qx': '-0.19', 'qy': 'qz', 'qz': 'qy', 'qw': '1.0'}
-----------------------------------------------------------------
L0 Parameters: 13664
L1 Parameters: 3416
Compression:   75.00%
Reconstruction MSE: 0.000971

In [28]:
import pandas as pd
import numpy as np

# ==========================================
# 1. AGGREGATE ACTUAL DATA
# ==========================================
def get_report_data(type_name, df_orig, s_data_l1_list, recon_list):
    # Calculate row-wise MSE
    orig_vals = df_orig.drop(columns=['cluster'], errors='ignore').values
    recon_vals = np.array(recon_list)
    row_mse = ((orig_vals - recon_vals)**2).mean(axis=1)
    
    # Prepare strings for display
    return pd.DataFrame({
        'Type': type_name,
        'Original L0': [list(np.round(x, 3)) for x in orig_vals],
        'Latent L1': [node['l'] for node in s_data_l1_list],
        'Reconstructed': [list(np.round(x, 3)) for x in recon_vals],
        'MSE Error': row_mse
    })

# Combine all results
report_cuboid = get_report_data("Cuboid", df_l0, s_data_l1["Cuboid"], reconstructed_rows)
report_trans = get_report_data("Translate", df_l0_t, s_data_l1_t["Translate"], reconstructed_t)
report_rotate = get_report_data("Rotate", df_l0_r, s_data_l1_r["Rotate"], reconstructed_r)

full_report_df = pd.concat([report_cuboid, report_trans, report_rotate]).reset_index(drop=True)

# ==========================================
# 2. FORMATTED REPORT & HEATMAP
# ==========================================
print("=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT ===")

# Summary Statistics Table
summary_stats = pd.DataFrame({
    'Metric': ['Total L0 Params', 'Total L1 Params', 'Compression %', 'Global MSE'],
    'Value': [
        total_l0_params + total_l0_t + total_l0_r,
        total_l1_params + total_l1_t + total_l1_r,
        f"{((1 - (total_l1_params + total_l1_t + total_l1_r) / (total_l0_params + total_l0_t + total_l0_r)) * 100):.2f}%",
        f"{(mse + mse_t + mse_r) / 3:.6f}"
    ]
})
display(summary_stats)

# Styling Function for Error Highlighting
def error_heatmap(val):
    # Normalizing color: 0 error is white, high error is red
    # Adjust 'max_val' based on your typical error range (e.g., 0.1)
    color_intensity = min(int(255 * (val / 0.1)), 255) 
    inv_intensity = 255 - color_intensity
    return f'background-color: rgb(255, {inv_intensity}, {inv_intensity})'

# Display top 20 rows with the most interesting errors
print("\n--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---")
styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)

display(styled_report)

=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT ===

            Metric     Value
0  Total L0 Params     75272
1  Total L1 Params     38986
2    Compression %    48.21%
3       Global MSE  0.014923

--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_131964\1884652687.py:56: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [29]:
import pandas as pd
import numpy as np

# ==========================================
# 1. CLEAN AGGREGATION FUNCTION
# ==========================================
def get_report_data_clean(type_name, df_orig, s_data_l1_list, recon_list):
    # Calculate row-wise MSE
    orig_vals = df_orig.drop(columns=['cluster'], errors='ignore').values
    recon_vals = np.array(recon_list)
    row_mse = ((orig_vals - recon_vals)**2).mean(axis=1)
    
    # helper to force python floats and 2 decimal rounding
    def clean_list(arr):
        return [round(float(x), 2) for x in arr]

    # Prepare strings for display
    return pd.DataFrame({
        'Type': type_name,
        'Original L0': [clean_list(x) for x in orig_vals],
        'Latent L1': [clean_list(node['l']) for node in s_data_l1_list],
        'Reconstructed': [clean_list(x) for x in recon_vals],
        'MSE Error': row_mse
    })

# Combine results with rounding
report_cuboid = get_report_data_clean("Cuboid", df_l0, s_data_l1["Cuboid"], reconstructed_rows)
report_trans = get_report_data_clean("Translate", df_l0_t, s_data_l1_t["Translate"], reconstructed_t)
report_rotate = get_report_data_clean("Rotate", df_l0_r, s_data_l1_r["Rotate"], reconstructed_r)

full_report_df = pd.concat([report_cuboid, report_trans, report_rotate]).reset_index(drop=True)

# Display with Heatmap
print("=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT (ROUNDED) ===")
styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)
display(styled_report)

=== SYMBOLIC ABSTRACTION PERFORMANCE REPORT (ROUNDED) ===

C:\Users\Amogh\AppData\Local\Temp\ipykernel_131964\3563489100.py:35: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [30]:
# Display top 20 rows with the most interesting errors
print("\n--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---")
styled_report = full_report_df.sort_values("MSE Error", ascending=True).head(25).style.applymap(
    error_heatmap, subset=['MSE Error']
)

styled_report

--- TOP ERROR SAMPLES (MANUAL INSPECTION) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_131964\2999429750.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_report = full_report_df.sort_values("MSE Error", ascending=True).head(25).style.applymap(

In [31]:
full_report_df

,Type,Original L0,Latent L1,Reconstructed,MSE Error
0,Cuboid,"[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]",0.000000
1,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
2,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
3,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
4,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
...,...,...,...,...,...
23947,Rotate,"[0.0, -0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23948,Rotate,"[0.0, 0.0, -0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100
23949,Rotate,"[0.26, 0.0, 0.0, 0.97]",[0.97],"[0.14, 0.0, 0.0, 1.0]",0.004020
23950,Rotate,"[0.0, 0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23951,Rotate,"[0.0, 0.0, 0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100

In [32]:
p_data_l0.keys()

dict_keys(['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)'])

In [38]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# The relationships found in your p_data_l0
pair_keys = ['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)']

pair_grammars = {}
s_data_l1_pairs = {}

print(f"{'RELATIONSHIP':<20} | {'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 85)

for p_key in pair_keys:
    raw_data = p_data_l0.get(p_key, [])
    if not raw_data:
        continue
        
    # Create column names based on the pair (e.g., p_qx, p_qy... c_tx, c_ty...)
    # We dynamically detect dimension based on the first entry
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    child_dim = len(raw_data[0]) - parent_dim
    
    p_cols = [f'p{i}' for i in range(parent_dim)]
    c_cols = [f'c{i}' for i in range(child_dim)]
    all_cols = p_cols + c_cols
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    
    # 1. Cluster the relationships
    n_clusters = min(3, len(df_pair)) 
    kmeans_p = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    df_pair['cluster'] = kmeans_p.fit_predict(df_pair)
    
    cluster_rules = {}
    s_data_l1_pairs[p_key] = []
    
    for c_id in range(n_clusters):
        subset = df_pair[df_pair['cluster'] == c_id].drop(columns=['cluster'])
        
        # 2. Harvest constants from both parent and child values
        dynamic_consts = [0.0, 0.5, 1.0, -1.0]
        for col in subset.columns:
            top_vals = subset[col].round(2).value_counts().head(3).index.tolist()
            dynamic_consts.extend(top_vals)
        dynamic_consts = list(set(dynamic_consts))
        
        # 3. Discover Rules (Cross-parameter relationships)
        rules = discover_symbolic_rules(
            subset, 
            custom_constants=dynamic_consts, 
            custom_tol=0.07, 
            custom_min_match=0.40
        )
        cluster_rules[c_id] = rules
        print(f"{p_key[:20]:<20} | {c_id:<8} | {rules}")
        
    pair_grammars[p_key] = cluster_rules

RELATIONSHIP         | CLUSTER  | RULES FOUND
-------------------------------------------------------------------------------------
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0311 | Match:  87.1% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.0148 | Match:  97.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0174 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
Rotate(Rotate)       | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': 'p0', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0026 | Match:  99.4% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.1506 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: -0.08                | AvgErr: 0.0707 | Match:  55.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
Rotate(Rotate)       | 1        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '-0.08', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0047 | Match:  97.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.1830 | Match:   1.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.13                 | AvgErr: 0.0660 | Match:  64.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
Rotate(Rotate)       | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '0.13', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1072 | Match:  47.7% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c0                   | AvgErr: 0.5745 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0104 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3664 | Match:  18.7% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.44                 | AvgErr: 0.0875 | Match:  40.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3063 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.26                | AvgErr: 0.2905 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(p1, -0.37)       | AvgErr: 0.3073 | Match:  23.3% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2450 | Match:  15.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.12                 | AvgErr: 0.2308 | Match:  14.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, 0.12)        | AvgErr: 0.2849 | Match:  23.5% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': '0.44'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1078 | Match:  31.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.08                | AvgErr: 0.0664 | Match:  53.8% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c1                   | AvgErr: 0.6753 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0083 | Match:  97.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.1093 | Match:  63.9% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3229 | Match:   9.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.29                 | AvgErr: 0.1464 | Match:  22.9% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c1   | Best: Sub(p2, -0.34)       | AvgErr: 0.1448 | Match:  42.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2652 | Match:   4.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: -0.35                | AvgErr: 0.0878 | Match:  42.3% (Req: 40.0%)
Rotate(Translate)    | 1        | {'p0': '-0.08', 'p1': 'p2', 'p2': 'p1', 'p3': '1.0', 'c0': 'p1', 'c1': 'Sub(p2, -0.34)', 'c2': '-0.35'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1081 | Match:  48.0% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c2                   | AvgErr: 0.9299 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0108 | Match:  94.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c1                   | AvgErr: 0.3280 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: -0.37                | AvgErr: 0.1385 | Match:  28.4% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c0   | Best: Add(p2, -0.44)       | AvgErr: 0.1489 | Match:  46.3% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2769 | Match:  14.9% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.12                | AvgErr: 0.2573 | Match:  10.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, 0.07)        | AvgErr: 0.3493 | Match:  23.4% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2300 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.07                 | AvgErr: 0.2194 | Match:  14.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Sub(p2, -0.12)       | AvgErr: 0.2225 | Match:  22.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': 'Add(p2, -0.44)'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.3687 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.3531 | Match:   4.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p0   | Best: Mul(p2, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p0
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.5051 | Match:   9.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1118 | Match:  41.6% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c0                   | AvgErr: 0.3450 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.11                 | AvgErr: 0.3338 | Match:   1.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Mul(p0, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: c2                   | AvgErr: 0.4043 | Match:  12.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.52                 | AvgErr: 0.1872 | Match:  20.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, -0.51)       | AvgErr: 0.2281 | Match:  31.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
Translate(Cuboid)    | 0        | {'p1': '-0.51', 'c0': 'c2', 'c2': 'c0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.2426 | Match:  33.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1848 | Match:  58.4% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.2411 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: -0.05                | AvgErr: 0.1813 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c0, -0.16)       | AvgErr: 0.1641 | Match:  35.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c1                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.0964 | Match:  45.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: 0.69                 | AvgErr: 0.3358 | Match:  11.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c0   | Best: Sub(c2, p0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c0
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: c1   | Best: 0.08                 | AvgErr: 0.1801 | Match:  42.2% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.83                 | AvgErr: 0.1851 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, c0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Translate(Cuboid)    | 1        | {'p0': '0.0', 'p2': '0.0', 'c1': '0.08'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1203 | Match:  54.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: c2                   | AvgErr: 0.2518 | Match:  13.7% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: 0.28                 | AvgErr: 0.1516 | Match:  29.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c1, 0.5)         | AvgErr: 0.2172 | Match:  32.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3348 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: -0.27                | AvgErr: 0.0893 | Match:  34.2% (Req: 40.0%)
    [SUCCESS] Binary     | Target: p2   | Best: Add(c2, -0.36)       | AvgErr: 0.1245 | Match:  41.3% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.3254 | Match:  11.5% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.06                 | AvgErr: 0.3942 | Match:  41.0% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.4567 | Match:   5.5% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.7                  | AvgErr: 0.2715 | Match:  15.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(c2, 0.7)         | AvgErr: 0.3114 | Match:  27.7% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: 0.06                 | AvgErr: 0.0858 | Match:  57.4% (Req: 40.0%)
Translate(Cuboid)    | 2        | {'p0': '0.0', 'p2': 'Add(c2, -0.36)', 'c0': '0.06', 'c2': '0.06'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0419 | Match:  83.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.9953 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0022 | Match:  99.4% (Req: 40.0%)
Union(Rotate)        | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1654 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.12                | AvgErr: 0.0563 | Match:  67.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.9832 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0168 | Match:  90.9% (Req: 40.0%)
Union(Rotate)        | 1        | {'p0': '-0.12', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1875 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.14                 | AvgErr: 0.0622 | Match:  62.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.7915 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0210 | Match:  90.4% (Req: 40.0%)
Union(Rotate)        | 2        | {'p0': '0.14', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.34                 | AvgErr: 0.0852 | Match:  42.2% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.4912 | Match:  10.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1380 | Match:  40.4% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.3071 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Add(p0, 0.0)         | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
Union(Translate)     | 0        | {'p0': '0.34', 'p1': '-0.51'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3215 | Match:  11.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1339 | Match:  51.7% (Req: 40.0%)

In [39]:
pair_reports = []

for p_key, clusters in pair_grammars.items():
    raw_data = p_data_l0[p_key]
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    p_cols = [f'p{i}' for i in range(parent_dim)]
    c_cols = [f'c{i}' for i in range(len(raw_data[0]) - parent_dim)]
    all_cols = p_cols + c_cols
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    df_pair['cluster'] = KMeans(n_clusters=len(clusters), random_state=42, n_init=10).fit_predict(df_pair)
    
    recon_rows = []
    
    for i, row in df_pair.iterrows():
        c_id = int(row['cluster'])
        rules = clusters[c_id]
        
        # Compression: Only keep columns not ruled
        latent = [row[v] for v in all_cols if v not in rules]
        if not latent: latent = [row[all_cols[0]]]
        
        # Reconstruction logic
        recon = {v: row[v] if v not in rules else None for v in all_cols}
        # (Simplified recon for report mapping)
        for target, expr in rules.items():
            if expr in all_cols: recon[target] = row[expr]
            else: 
                try: recon[target] = float(expr)
                except: recon[target] = 0.0
        
        recon_rows.append([recon[v] for v in all_cols])
        
    # Calculate MSE for this relationship type
    orig_np = df_pair[all_cols].values
    recon_np = np.array(recon_rows)
    mse_p = ((orig_np - recon_np)**2).mean()
    
    pair_reports.append({
        'Relationship': p_key,
        'L0 Params': len(df_pair) * len(all_cols),
        'L1 Params': sum([len([v for v in all_cols if v not in clusters[int(df_pair.iloc[j]['cluster'])]]) for j in range(len(df_pair))]),
        'MSE': mse_p
    })

df_pair_report = pd.DataFrame(pair_reports)

In [40]:
df_pair_report

        Relationship  L0 Params  L1 Params       MSE
0     Rotate(Rotate)      14432          0  0.001285
1  Rotate(Translate)      11284       1934  0.024150
2  Translate(Cuboid)      61608      27816  0.037602
3      Union(Rotate)       6448          0  0.001513
4   Union(Translate)      25968      11240  0.034966

In [41]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.cluster import KMeans

# 1. Initialization
pair_keys = ['Rotate(Rotate)', 'Rotate(Translate)', 'Translate(Cuboid)', 'Union(Rotate)', 'Union(Translate)']
pair_grammars = {}
s_data_l1_pairs = {}
pair_reconstructions = {} # This fixes your NameError

print(f"{'RELATIONSHIP':<20} | {'CLUSTER':<8} | {'RULES FOUND'}")
print("-" * 85)

# 2. Discovery & Reconstruction Loop
for p_key in pair_keys:
    raw_data = p_data_l0.get(p_key, [])
    if not raw_data: continue
    
    # Setup dimensions
    parent_dim = 4 if "Rotate" in p_key.split('(')[0] else 3
    child_dim = len(raw_data[0]) - parent_dim
    all_cols = [f'p{i}' for i in range(parent_dim)] + [f'c{i}' for i in range(child_dim)]
    
    df_pair = pd.DataFrame(raw_data, columns=all_cols)
    n_clusters = min(3, len(df_pair)) 
    df_pair['cluster'] = KMeans(n_clusters=n_clusters, random_state=42, n_init=10).fit_predict(df_pair)
    
    cluster_rules = {}
    s_data_l1_pairs[p_key] = []
    recons_for_this_key = []
    
    for c_id in range(n_clusters):
        subset = df_pair[df_pair['cluster'] == c_id].drop(columns=['cluster'])
        
        # Harvest top constants
        dynamic_consts = [0.0, 0.5, 1.0, -1.0]
        for col in subset.columns:
            dynamic_consts.extend(subset[col].round(2).value_counts().head(3).index.tolist())
        
        # Discover Rules
        rules = discover_symbolic_rules(subset, custom_constants=list(set(dynamic_consts)), custom_tol=0.07, custom_min_match=0.40)
        cluster_rules[c_id] = rules
        print(f"{p_key[:20]:<20} | {c_id:<8} | {rules}")

    # 3. Apply Compression and Generate Reconstructions
    for _, row in df_pair.iterrows():
        c_id = int(row['cluster'])
        rules = cluster_rules[c_id]
        
        # L1 Latent
        latent = [row[v] for v in all_cols if v not in rules]
        if not latent: latent = [row[all_cols[0]]]
        s_data_l1_pairs[p_key].append({"c": c_id, "l": [round(x, 4) for x in latent]})
        
        # Reconstruct (Logic for the Report)
        latent_vars = [v for v in all_cols if v not in rules]
        if not latent_vars: latent_vars = [all_cols[0]]
        recon_dict = {var: val for var, val in zip(latent_vars, latent)}
        
        for target, expr in rules.items():
            if expr in recon_dict: recon_dict[target] = recon_dict[expr]
            else:
                try: recon_dict[target] = float(expr)
                except: recon_dict[target] = 0.0
        
        recons_for_this_key.append([recon_dict.get(v, 0.0) for v in all_cols])
    
    pair_reconstructions[p_key] = recons_for_this_key
    pair_grammars[p_key] = cluster_rules

# ==========================================
# 4. FINAL DETAILED REPORT
# ==========================================
pair_report_list = []
for p_key in pair_keys:
    if p_key not in pair_reconstructions: continue
    orig_np = np.array(p_data_l0[p_key])
    recon_np = np.array(pair_reconstructions[p_key])
    row_mse = ((orig_np - recon_np)**2).mean(axis=1)
    
    pair_report_list.append(pd.DataFrame({
        'Relationship': p_key,
        'Original L0': [list(np.round(x, 3)) for x in orig_np],
        'Latent L1': [node['l'] for node in s_data_l1_pairs[p_key]],
        'Reconstructed': [list(np.round(x, 3)) for x in recon_np],
        'MSE Error': row_mse
    }))

full_pair_report_df = pd.concat(pair_report_list).reset_index(drop=True)

def pair_error_heatmap(val):
    intensity = min(int(255 * (val / 0.1)), 255)
    return f'background-color: rgb(255, {255-intensity}, {255-intensity})'

display(full_pair_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    pair_error_heatmap, subset=['MSE Error']
))

RELATIONSHIP         | CLUSTER  | RULES FOUND
-------------------------------------------------------------------------------------
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0080 | Match:  97.7% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0311 | Match:  87.1% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.0148 | Match:  97.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0174 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0026 | Match:  99.9% (Req: 40.0%)
Rotate(Rotate)       | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': 'p0', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0204 | Match:  93.9% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0026 | Match:  99.4% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.1506 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: -0.08                | AvgErr: 0.0707 | Match:  55.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0136 | Match:  99.4% (Req: 40.0%)
Rotate(Rotate)       | 1        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '-0.08', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0250 | Match:  93.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0047 | Match:  97.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [SUCCESS] Direct     | Target: p3   | Best: c3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.1830 | Match:   1.1% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.13                 | AvgErr: 0.0660 | Match:  64.1% (Req: 40.0%)
--- Searching for target: c1 ---
    [SUCCESS] Direct     | Target: c1   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c3 ---
    [SUCCESS] Direct     | Target: c3   | Best: p3                   | AvgErr: 0.0194 | Match:  96.7% (Req: 40.0%)
Rotate(Rotate)       | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': 'c3', 'c0': '0.13', 'c1': 'p0', 'c2': 'p0', 'c3': 'p3'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1046 | Match:  49.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1072 | Match:  47.7% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c0                   | AvgErr: 0.5745 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0104 | Match:  95.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3664 | Match:  18.7% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.44                 | AvgErr: 0.0875 | Match:  40.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3063 | Match:  12.3% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.26                | AvgErr: 0.2905 | Match:   4.1% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(p1, -0.37)       | AvgErr: 0.3073 | Match:  23.3% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2450 | Match:  15.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.12                 | AvgErr: 0.2308 | Match:  14.6% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, 0.12)        | AvgErr: 0.2849 | Match:  23.5% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': '0.44'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1078 | Match:  31.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.08                | AvgErr: 0.0664 | Match:  53.8% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0004 | Match:  99.8% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c1                   | AvgErr: 0.6753 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0083 | Match:  97.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.1093 | Match:  63.9% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.3229 | Match:   9.1% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.29                 | AvgErr: 0.1464 | Match:  22.9% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c1   | Best: Sub(p2, -0.34)       | AvgErr: 0.1448 | Match:  42.0% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2652 | Match:   4.8% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: -0.35                | AvgErr: 0.0878 | Match:  42.3% (Req: 40.0%)
Rotate(Translate)    | 1        | {'p0': '-0.08', 'p1': 'p2', 'p2': 'p1', 'p3': '1.0', 'c0': 'p1', 'c1': 'Sub(p2, -0.34)', 'c2': '-0.35'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.1056 | Match:  49.5% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.1081 | Match:  48.0% (Req: 40.0%)
--- Searching for target: p3 ---
    [FAILED ] Direct     | Target: p3   | Best: c2                   | AvgErr: 0.9299 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p3   | Best: 1.0                  | AvgErr: 0.0108 | Match:  94.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c1                   | AvgErr: 0.3280 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: -0.37                | AvgErr: 0.1385 | Match:  28.4% (Req: 40.0%)
    [SUCCESS] Binary     | Target: c0   | Best: Add(p2, -0.44)       | AvgErr: 0.1489 | Match:  46.3% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2769 | Match:  14.9% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: -0.12                | AvgErr: 0.2573 | Match:  10.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, 0.07)        | AvgErr: 0.3493 | Match:  23.4% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p1                   | AvgErr: 0.2300 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.07                 | AvgErr: 0.2194 | Match:  14.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Sub(p2, -0.12)       | AvgErr: 0.2225 | Match:  22.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Rotate(Translate)    | 2        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'p3': '1.0', 'c0': 'Add(p2, -0.44)'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.3687 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.3531 | Match:   4.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p0   | Best: Mul(p2, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p0
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.5051 | Match:   9.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1118 | Match:  41.6% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c0                   | AvgErr: 0.3450 | Match:   3.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.11                 | AvgErr: 0.3338 | Match:   1.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Mul(p0, -1.0)        | AvgErr: 0.3876 | Match:  31.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
--- Searching for target: c0 ---
    [SUCCESS] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: c2                   | AvgErr: 0.4043 | Match:  12.0% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.52                 | AvgErr: 0.1872 | Match:  20.4% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Sub(c0, -0.51)       | AvgErr: 0.2281 | Match:  31.9% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [SUCCESS] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.0651 | Match:  83.6% (Req: 40.0%)
Translate(Cuboid)    | 0        | {'p1': '-0.51', 'c0': 'c2', 'c2': 'c0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.2426 | Match:  33.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1848 | Match:  58.4% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.2411 | Match:  18.0% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: -0.05                | AvgErr: 0.1813 | Match:  18.2% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c0, -0.16)       | AvgErr: 0.1641 | Match:  35.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: c1                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.0964 | Match:  45.5% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: c2                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c0   | Best: 0.69                 | AvgErr: 0.3358 | Match:  11.7% (Req: 40.0%)
    [FAILED ] Binary     | Target: c0   | Best: Sub(c2, p0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c0
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p2                   | AvgErr: 0.2345 | Match:  28.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: c1   | Best: 0.08                 | AvgErr: 0.1801 | Match:  42.2% (Req: 40.0%)
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: c0                   | AvgErr: 0.3709 | Match:  26.6% (Req: 40.0%)
    [FAILED ] Const      | Target: c2   | Best: 0.83                 | AvgErr: 0.1851 | Match:  19.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: c2   | Best: Add(p0, c0)          | AvgErr: 0.3799 | Match:  29.1% (Req: 40.0%)
    [FAILED ] No rule discovered for c2
Translate(Cuboid)    | 1        | {'p0': '0.0', 'p2': '0.0', 'c1': '0.08'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: c2                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1203 | Match:  54.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: c2                   | AvgErr: 0.2518 | Match:  13.7% (Req: 40.0%)
    [FAILED ] Const      | Target: p1   | Best: 0.28                 | AvgErr: 0.1516 | Match:  29.8% (Req: 40.0%)
    [FAILED ] Binary     | Target: p1   | Best: Mul(c1, 0.5)         | AvgErr: 0.2172 | Match:  32.8% (Req: 40.0%)
    [FAILED ] No rule discovered for p1
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3348 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: -0.27                | AvgErr: 0.0893 | Match:  34.2% (Req: 40.0%)
    [SUCCESS] Binary     | Target: p2   | Best: Add(c2, -0.36)       | AvgErr: 0.1245 | Match:  41.3% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.3254 | Match:  11.5% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 0.06                 | AvgErr: 0.3942 | Match:  41.0% (Req: 40.0%)
--- Searching for target: c1 ---
    [FAILED ] Direct     | Target: c1   | Best: p1                   | AvgErr: 0.4567 | Match:   5.5% (Req: 40.0%)
    [FAILED ] Const      | Target: c1   | Best: 0.7                  | AvgErr: 0.2715 | Match:  15.0% (Req: 40.0%)
    [FAILED ] Binary     | Target: c1   | Best: Add(c2, 0.7)         | AvgErr: 0.3114 | Match:  27.7% (Req: 40.0%)
    [FAILED ] No rule discovered for c1
--- Searching for target: c2 ---
    [FAILED ] Direct     | Target: c2   | Best: p0                   | AvgErr: 0.2114 | Match:  14.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c2   | Best: 0.06                 | AvgErr: 0.0858 | Match:  57.4% (Req: 40.0%)
Translate(Cuboid)    | 2        | {'p0': '0.0', 'p2': 'Add(c2, -0.36)', 'c0': '0.06', 'c2': '0.06'}
--- Searching for target: p0 ---
    [SUCCESS] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p0                   | AvgErr: 0.0084 | Match:  97.1% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.0419 | Match:  83.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p2                   | AvgErr: 0.9953 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0022 | Match:  99.4% (Req: 40.0%)
Union(Rotate)        | 0        | {'p0': 'p1', 'p1': 'p0', 'p2': 'p0', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1654 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: -0.12                | AvgErr: 0.0563 | Match:  67.1% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p1                   | AvgErr: 0.9832 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0168 | Match:  90.9% (Req: 40.0%)
Union(Rotate)        | 1        | {'p0': '-0.12', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p1                   | AvgErr: 0.1875 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.14                 | AvgErr: 0.0622 | Match:  62.7% (Req: 40.0%)
--- Searching for target: p1 ---
    [SUCCESS] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: p2 ---
    [SUCCESS] Direct     | Target: p2   | Best: p1                   | AvgErr: 0.0000 | Match: 100.0% (Req: 40.0%)
--- Searching for target: c0 ---
    [FAILED ] Direct     | Target: c0   | Best: p0                   | AvgErr: 0.7915 | Match:   0.0% (Req: 40.0%)
    [SUCCESS] Const      | Target: c0   | Best: 1.0                  | AvgErr: 0.0210 | Match:  90.4% (Req: 40.0%)
Union(Rotate)        | 2        | {'p0': '0.14', 'p1': 'p2', 'p2': 'p1', 'c0': '1.0'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.34                 | AvgErr: 0.0852 | Match:  42.2% (Req: 40.0%)
--- Searching for target: p1 ---
    [FAILED ] Direct     | Target: p1   | Best: p2                   | AvgErr: 0.4912 | Match:  10.6% (Req: 40.0%)
    [SUCCESS] Const      | Target: p1   | Best: -0.51                | AvgErr: 0.1380 | Match:  40.4% (Req: 40.0%)
--- Searching for target: p2 ---
    [FAILED ] Direct     | Target: p2   | Best: p0                   | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] Const      | Target: p2   | Best: 0.0                  | AvgErr: 0.3071 | Match:   8.9% (Req: 40.0%)
    [FAILED ] Binary     | Target: p2   | Best: Add(p0, 0.0)         | AvgErr: 0.3549 | Match:  32.3% (Req: 40.0%)
    [FAILED ] No rule discovered for p2
Union(Translate)     | 0        | {'p0': '0.34', 'p1': '-0.51'}
--- Searching for target: p0 ---
    [FAILED ] Direct     | Target: p0   | Best: p2                   | AvgErr: 0.3215 | Match:  11.2% (Req: 40.0%)
    [SUCCESS] Const      | Target: p0   | Best: 0.0                  | AvgErr: 0.1339 | Match:  51.7% (Req: 40.0%)

C:\Users\Amogh\AppData\Local\Temp\ipykernel_131964\2689885488.py:96: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  display(full_pair_report_df.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [42]:
# ==========================================
# 2. CLEAN AGGREGATION FOR PAIRS
# ==========================================
pair_report_list_clean = []

def clean_list(arr):
    return [round(float(x), 2) for x in arr]

for p_key in pair_keys:
    if p_key not in pair_reconstructions: continue
    
    orig_np = np.array(p_data_l0[p_key])
    recon_np = np.array(pair_reconstructions[p_key])
    row_mse = ((orig_np - recon_np)**2).mean(axis=1)
    
    pair_report_list_clean.append(pd.DataFrame({
        'Relationship': p_key,
        'Original L0': [clean_list(x) for x in orig_np],
        'Latent L1': [clean_list(node['l']) for node in s_data_l1_pairs[p_key]],
        'Reconstructed': [clean_list(x) for x in recon_np],
        'MSE Error': row_mse
    }))

full_pair_report_clean = pd.concat(pair_report_list_clean).reset_index(drop=True)

print("\n--- TOP PAIR ERROR SAMPLES (ROUNDED) ---")
styled_pair_report = full_pair_report_clean.sort_values("MSE Error", ascending=False).head(25).style.applymap(
    pair_error_heatmap, subset=['MSE Error']
)
display(styled_pair_report)

--- TOP PAIR ERROR SAMPLES (ROUNDED) ---

C:\Users\Amogh\AppData\Local\Temp\ipykernel_131964\2830648964.py:27: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_pair_report = full_pair_report_clean.sort_values("MSE Error", ascending=False).head(25).style.applymap(

In [43]:
full_report_df

,Type,Original L0,Latent L1,Reconstructed,MSE Error
0,Cuboid,"[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]","[0.68, 0.09, 0.66]",0.000000
1,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
2,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
3,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
4,Cuboid,"[0.06, 0.6, 0.06]",[0.6],"[0.05, 0.6, 0.05]",0.000067
...,...,...,...,...,...
23947,Rotate,"[0.0, -0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23948,Rotate,"[0.0, 0.0, -0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100
23949,Rotate,"[0.26, 0.0, 0.0, 0.97]",[0.97],"[0.14, 0.0, 0.0, 1.0]",0.004020
23950,Rotate,"[0.0, 0.01, 0.0, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000056
23951,Rotate,"[0.0, 0.0, 0.02, 1.0]",[1.0],"[0.0, 0.0, 0.0, 1.0]",0.000100

In [44]:
full_pair_report_clean

,Relationship,Original L0,Latent L1,Reconstructed,MSE Error
0,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
1,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]",[0.0],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.250000
2,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
3,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]",[0.0],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.250000
4,Rotate(Rotate),"[0.0, 0.0, 0.0, 1.0, -0.12, 0.0, 0.0, 0.99]",[0.0],"[0.0, 0.0, 0.0, 0.0, -0.08, 0.0, 0.0, 0.0]",0.248307
...,...,...,...,...,...
23947,Union(Translate),"[0.28, -0.61, 0.3]",[0.3],"[0.34, -0.51, 0.3]",0.004533
23948,Union(Translate),"[-0.28, -0.61, 0.3]",[-0.61],"[0.0, -0.61, 0.0]",0.056133
23949,Union(Translate),"[-0.29, -0.6, -0.28]",[-0.6],"[0.0, -0.6, 0.0]",0.054167
23950,Union(Translate),"[-0.0, 0.28, -0.28]","[0.28, -0.28]","[0.0, 0.28, -0.28]",0.000000
23951,Union(Translate),"[0.0, -0.23, 0.08]",[-0.23],"[0.0, -0.23, 0.0]",0.002133

In [ ]:
"""
CUBOID_REWRITES:
Standardizes box dimensions by enforcing symmetry and snapping small parts.

- cuboid_sym_0: Forces width and depth to be identical if they are within 0.05 units.
  Useful for turning near-square footprints into perfect squares.
- cuboid_snap_3: Snaps all three dimensions of small parts to exactly 0.06. 
  Targets the 'standard joint' cluster where components should be uniform cubes.
"""

CUBOID_REWRITES = [
    # Cluster 0: Symmetry discovered (sw == sd)
    ["cuboid_sym_0", "(Cuboid ?sw ?sh ?sd)", "(Cuboid ?sw ?sh ?sw)", "abs:0.05:?sd=new|?sw|0"],
    
    # Cluster 3: Standard small component (snapping all to 0.06)
    ["cuboid_snap_3", "(Cuboid ?sw ?sh ?sd)", "(Cuboid 0.06 0.06 0.06)", "abs:0.05:?sw=new|0.06|0,?sh=new|0.06|0,?sd=new|0.06|0"]
]

"""
TRANSLATE_REWRITES:
Aligns part positions to the global grid and standardizes vertical offsets.

- trans_center_x: Snaps the X-offset to 0.0 if it's already close to the center.
- trans_sym_xz: Forces the Z-translation to match the X-translation. 
  Used for parts that should be equidistantly offset from the origin (like legs).
- trans_height_snap: Locks vertical position (ty) to -0.5. 
  Standardizes the 'ground level' for objects within the -0.5 height cluster.
"""

TRANSLATE_REWRITES = [
    # Cluster 0: Centering on X-axis
    ["trans_center_x", "(Translate ?tx ?ty ?tz)", "(Translate 0.0 ?ty ?tz)", "abs:0.05:?tx=new|0.0|0"],
    
    # Cluster 2: Lateral Symmetry (tx == tz)
    ["trans_sym_xz", "(Translate ?tx ?ty ?tz)", "(Translate ?tx ?ty ?tx)", "abs:0.05:?tz=new|?tx|0"],
    
    # Cluster 3: Standard height snap (ty == -0.5)
    ["trans_height_snap", "(Translate ?tx ?ty ?tz)", "(Translate ?tx -0.5 ?tz)", "abs:0.05:?ty=new|-0.5|0"]
]

"""
ROTATE_REWRITES:
Fixes noisy rotation data by snapping quaternions to canonical orientations.

- rot_clean_0: Forces qy and qz to match qx while resetting qw to 1.0. 
  Cleans up axis-aligned rotations that have floating-point drift.
- rot_snap_1: Sets a fixed tilt of -0.09 on the X-axis and synchronizes YZ. 
  Standardizes a specific recurring tilt found in Cluster 1.
- rot_snap_2: Sets a fixed tilt of 0.14 on the X-axis and synchronizes YZ. 
  Standardizes the recurring 'forward lean' found in Cluster 2.
"""

ROTATE_REWRITES = [
    # Cluster 0 & 3: Axis alignment + Identity Check
    ["rot_clean_0", "(Rotate ?qx ?qy ?qz ?qw)", "(Rotate ?qx ?qx ?qx 1.0)", "abs:0.03:?qy=new|?qx|0,?qz=new|?qx|0,?qw=new|1.0|0"],
    
    # Cluster 1: Specific Offset + YZ Symmetry
    ["rot_snap_1", "(Rotate ?qx ?qy ?qz ?qw)", "(Rotate -0.09 ?qz ?qz 1.0)", "abs:0.03:?qx=new|-0.09|0,?qy=new|?qz|0,?qw=new|1.0|0"],
    
    # Cluster 2: Positive Offset
    ["rot_snap_2", "(Rotate ?qx ?qy ?qz ?qw)", "(Rotate 0.14 ?qz ?qz 1.0)", "abs:0.03:?qx=new|0.14|0,?qy=new|?qz|0,?qw=new|1.0|0"]
]

"""
PAIR_REWRITES:
Parametric rules for parent-child dependencies discovered in the scene graph.

- pair_rot_sync: Inherits the parent's rotation for the child. 
  Collapses redundant nested rotations into a single shared orientation.
- pair_rot_trans_dep: A complex dependency where child position is derived 
  from parent rotation. Sets a fixed tilt (-0.08) and functional Y-offset.
- pair_trans_cub_sym: Forces a cuboid to be square (c2 = c0) if it is placed 
  at a standard height (-0.51) relative to its parent.
- pair_union_spacing: Discovers parametric spacing. Shifts the child 
  by a fixed 0.04 offset relative to the parent's starting position.
"""

PAIR_REWRITES = [
    # Rotate(Rotate) Cluster 0: Total Synchronization
    # Parent and Child rotations are effectively identical
    ["pair_rot_sync", 
     "(Rotate ?p0 ?p1 ?p2 ?p3 (Rotate ?c0 ?c1 ?c2 ?c3 ?s))", 
     "(Rotate ?p0 ?p0 ?p0 ?p3 (Rotate ?p0 ?p0 ?p0 ?p3 ?s))", 
     "abs:0.05:?p1=new|?p0|0,?c0=new|?p0|0"],

    # Rotate(Translate) Cluster 1: Child Y-offset depends on Parent Y-rotation
    ["pair_rot_trans_dep",
     "(Rotate ?p0 ?p1 ?p2 ?p3 (Translate ?c0 ?c1 ?c2 ?s))",
     "(Rotate -0.08 ?p1 ?p1 1.0 (Translate ?p1 (Sub ?p2 -0.34) -0.35 ?s))",
     "abs:0.05:?p0=new|-0.08|0,?p3=new|1.0|0"],

    # Translate(Cuboid) Cluster 0: Centered Cuboid width depends on depth
    ["pair_trans_cub_sym",
     "(Translate ?p0 ?p1 ?p2 (Cuboid ?c0 ?c1 ?c2))",
     "(Translate ?p0 -0.51 ?p2 (Cuboid ?c2 ?c1 ?c2))",
     "abs:0.05:?p1=new|-0.51|0"],
     
    # Union(Translate) Cluster 2: Parametric spacing discovered
    # Child position (p2) is offset from p0 by 0.04
    ["pair_union_spacing",
     "(Union (Translate ?p0 ?p1 ?p2 ?s))",
     "(Union (Translate 0.0 ?p1 (Add ?p0 0.04) ?s))",
     "abs:0.05:?p0=new|0.0|0"]
]