In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
## 1. Setup Paths & Configuration

import sys
import os
from pathlib import Path

# Add source directory to path
current_path = Path.cwd()
base_project_dir = current_path.parent
src_dir = base_project_dir / "src"

if str(src_dir) not in sys.path:
    sys.path.append(str(src_dir))

# Define key directories
dataset_directory = src_dir / "abstractionsshapecoder" / "dataset"
saved_directory = src_dir / "abstractionsshapecoder" / "saved"

In [4]:
import pickle
import os
from tqdm import tqdm
from abstractionsshapecoder.shape_parser import ShapeParser
from abstractionsshapecoder.dsl_utils import collect_singleton_and_pair_data

# --- Configuration ---
INPUT_FILE = src_dir / "abstractionsshapecoder" / "prog_data" / "PN_chair.txt"
PICKLE_FILE = saved_directory / "all_dsl_shapes.pkl"
CHAIR_LIMIT = None  # Set to an integer for testing, or None for all

def load_dsl_dataset():
    full_dsl_shapes = {}

    # FIX: Ensure the parent directory exists
    PICKLE_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Check for cached Pickle
    if PICKLE_FILE.exists():
        print(f"[INFO] Loading cached dataset from {PICKLE_FILE}...")
        with open(PICKLE_FILE, "rb") as f:
            full_dsl_shapes = pickle.load(f)
    else:
        print(f"[INFO] Cache not found. Parsing from {INPUT_FILE}...")
        if not INPUT_FILE.exists():
            print(f"[ERROR] Input file not found: {INPUT_FILE}")
            return {}

        parser = ShapeParser()
        with open(INPUT_FILE, 'r') as f:
            lines = f.readlines()

        for line in tqdm(lines, desc="Parsing Shapes"):
            line = line.strip()
            if not line: continue
            try:
                shape_id, prog_text = line.split(':', 1)
                dsl_obj = parser.parse(prog_text)
                if dsl_obj:
                    # Calculate Params immediately
                    s_data, p_data = collect_singleton_and_pair_data([dsl_obj])
                    full_dsl_shapes[shape_id.strip()] = {
                        "dsl": dsl_obj,
                        "singleton_params": s_data,
                        "pair_params": p_data
                    }
            except Exception:
                pass

        # Save to Pickle
        with open(PICKLE_FILE, "wb") as f:
            pickle.dump(full_dsl_shapes, f)

    # Apply Limit
    if CHAIR_LIMIT is not None and len(full_dsl_shapes) > CHAIR_LIMIT:
        print(f"[INFO] Limiting to {CHAIR_LIMIT} shapes.")
        return dict(list(full_dsl_shapes.items())[:CHAIR_LIMIT])
    
    return full_dsl_shapes

shapes_l0 = load_dsl_dataset()
print(f"[RESULT] Loaded {len(shapes_l0)} L0 shapes.")

[INFO] Loading cached dataset from c:\Users\Amogh\abstraction-discovery\src\abstractionsshapecoder\saved\all_dsl_shapes.pkl...
[RESULT] Loaded 1100 L0 shapes.

In [5]:
shapes_l0["172_0_0"]

{'dsl': <abstractionsshapecoder.dsl_nodes.Union at 0x158af28eb70>,
 'singleton_params': {'Cuboid': [[0.68, 0.09, 0.66],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.06, 0.6, 0.06],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.68, 0.14, 0.24],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08],
   [0.08, 0.79, 0.08]],
  'Translate': [[-0.0, -0.17, 0.0],
   [-0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [0.31, -0.51, 0.3],
   [-0.26, 0.27, -0.18],
   [-0.14, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.0, 0.27, -0.25],
   [0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25]]},
 'pair_params': {'Translate(Cuboid)': [[-0.0, -0.17, 0.0, 0.68, 0.09, 0.66],
   [-0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [-0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [0.31, -0.51, -0.17, 0.06, 0.6, 0.06],
   [0.31, -0.51, 0.3, 0.06, 0.6, 0.06],
   [-0.26, 0.27, -0.18, 0.08, 0.79, 0.08],
   [-0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.0, 0.74, -0.22, 0.68, 0.14, 0.24],
   [-0.0, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.14, 0.27, -0.25, 0.08, 0.79, 0.08],
   [0.28, 0.27, -0.25, 0.08, 0.79, 0.08]],
  'Union(Translate)': [[0.14, 0.27, -0.25],
   [0.28, 0.27, -0.25],
   [-0.0, 0.27, -0.25],
   [0.0, 0.74, -0.22],
   [-0.14, 0.27, -0.25],
   [-0.26, 0.27, -0.18],
   [0.31, -0.51, 0.3],
   [0.31, -0.51, -0.17],
   [-0.31, -0.51, 0.3],
   [-0.31, -0.51, -0.17],
   [-0.0, -0.17, 0.0]]}}

In [6]:
shapes_l0["172_0_0"]["dsl"]

In [7]:
print(shapes_l0["172_0_0"]["dsl"])

Union(
    Translate(vec=[-0.000, -0.170, 0.000])
        Cuboid(size=[0.680, 0.090, 0.660]),
    Union(
        Translate(vec=[-0.310, -0.510, -0.170])
            Cuboid(size=[0.060, 0.600, 0.060]),
        Union(
            Translate(vec=[-0.310, -0.510, 0.300])
                Cuboid(size=[0.060, 0.600, 0.060]),
            Union(
                Translate(vec=[0.310, -0.510, -0.170])
                    Cuboid(size=[0.060, 0.600, 0.060]),
                Union(
                    Translate(vec=[0.310, -0.510, 0.300])
                        Cuboid(size=[0.060, 0.600, 0.060]),
                    Union(
                        Translate(vec=[-0.260, 0.270, -0.180])
                            Cuboid(size=[0.080, 0.790, 0.080]),
                        Union(
                            Translate(vec=[-0.140, 0.270, -0.250])
                                Cuboid(size=[0.080, 0.790, 0.080]),
                            Union(
                                Translate(vec=[0.000, 0.740, -0.220])
                                    Cuboid(size=[0.680, 0.140, 0.240]),
                                Union(
                                    Translate(vec=[-0.000, 0.270, -0.250])
                                        Cuboid(size=[0.080, 0.790, 0.080]),
                                    Union(
                                        Translate(vec=[0.140, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080]),
                                        Translate(vec=[0.280, 0.270, -0.250])
                                            Cuboid(size=[0.080, 0.790, 0.080])
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)

In [8]:
class SymRef:
    """Mirror symmetry (Reflection) across an axis."""
    def __init__(self, child, axis='AX'):
        self.child = child
        self.axis = axis  # 'AX', 'AY', or 'AZ'

class SymTrans:
    """Translational symmetry (Repetition)."""
    def __init__(self, child, axis, count, distance):
        self.child = child
        self.axis = axis      # 'AX', 'AY', or 'AZ'
        self.count = count    # Integer: number of repetitions
        self.distance = distance  # Float: spacing between repetitions

In [9]:
import numpy as np
import copy
import logging
from abstractionsshapecoder.dsl_nodes import Union, Translate, Cuboid, Rotate

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger("ShapeOptimizer")

class ShapeOptimizer:
    def __init__(self, threshold=0.01):
        self.threshold = threshold

    def is_near(self, a, b):
        """Helper for scalar comparison (abs:0.01)."""
        return abs(float(a) - float(b)) <= self.threshold

    def is_near_vec(self, v1, v2):
        """Helper for vector comparison."""
        return np.all(np.abs(np.array(v1) - np.array(v2)) <= self.threshold)

    def is_zero(self, val):
        """Rule: zero_add or zero_mov check."""
        if isinstance(val, (list, np.ndarray)):
            return np.all(np.abs(np.array(val)) <= self.threshold)
        return abs(float(val)) <= self.threshold

    def apply_optimization_rules(self, node):
        """
        Implements SEM_3DL_REWRITES logic at the individual node level.
        """
        if node is None: return None

        # --- RULE: s3dl_move_comb & s3dl_zero_mov ---
        if isinstance(node, Translate):
            node.child = self.optimize_node(node.child)
            
            # Combine Move(Move) -> Move(Add(a,x))
            if isinstance(node.child, Translate):
                logger.debug("Rule: s3dl_move_comb applied.")
                new_vec = (np.array(node.vector) + np.array(node.child.vector)).tolist()
                return Translate(node.child.child, new_vec)
            
            # Remove No-op Move
            if self.is_zero(node.vector):
                logger.debug("Rule: s3dl_zero_mov applied.")
                return node.child

        # --- RULE: s3dl_rot_comb & s3dl_zero_rot ---
        if isinstance(node, Rotate):
            node.child = self.optimize_node(node.child)
            
            # Combine Rotate(Rotate) if axis is same
            if isinstance(node.child, Rotate) and node.axis == node.child.axis:
                logger.debug("Rule: s3dl_rot_comb applied.")
                return Rotate(node.child.child, node.axis, node.angle + node.child.angle)
            
            # Remove No-op Rotate
            if self.is_zero(node.angle):
                logger.debug("Rule: s3dl_zero_rot applied.")
                return node.child

        # --- RULE: s3dl_rot_over_move ---
        # (Move (Rotate X A v) a b c) -> (Rotate (Move X a b c) A v)
        if isinstance(node, Translate) and isinstance(node.child, Rotate):
            logger.debug("Rule: s3dl_rot_over_move applied.")
            rot_node = node.child
            inner_move = Translate(rot_node.child, node.vector)
            return Rotate(inner_move, rot_node.axis, rot_node.angle)

        # --- RULE: s3dl_union_over_sym ---
        # (SymRef (Union X Y) A) -> (Union (SymRef X A) (SymRef Y A))
        if isinstance(node, SymRef) and isinstance(node.child, Union):
            logger.debug("Rule: s3dl_union_over_sym applied.")
            left_sym = SymRef(node.child.left, node.axis)
            right_sym = SymRef(node.child.right, node.axis)
            return Union(left_sym, right_sym)

        return node

    def find_symmetries(self, parts):
        optimized = []
        used_indices = set()

        for i in range(len(parts)):
            if i in used_indices: continue
            p1 = parts[i]
            
            # --- 1. Translational Symmetry (SymTrans) ---
            # Look for 3+ items with equal spacing along an axis
            for axis_idx, axis_name in enumerate(['AX', 'AY', 'AZ']):
                sequence = [i]
                if not isinstance(p1, Translate): continue
                
                # Find all potential matches in this axis
                for j in range(i + 1, len(parts)):
                    if j in used_indices: continue
                    p2 = parts[j]
                    if isinstance(p2, Translate) and self.is_near_node_geometry(p1.child, p2.child):
                        # Check if it aligns on the current axis but matches others
                        diff = np.array(p1.vector) - np.array(p2.vector)
                        other_axes = [0, 1, 2]
                        other_axes.remove(axis_idx)
                        
                        # Must be aligned on other axes
                        if all(abs(diff[ax]) < self.threshold for ax in other_axes):
                            sequence.append(j)
                
                if len(sequence) >= 3:
                    # Sort by the active axis to find consistent distance
                    sequence.sort(key=lambda idx: parts[idx].vector[axis_idx])
                    vecs = [np.array(parts[idx].vector)[axis_idx] for idx in sequence]
                    dist = vecs[1] - vecs[0]
                    
                    # Verify spacing is consistent
                    is_consistent = all(self.is_near(vecs[k+1] - vecs[k], dist) for k in range(len(vecs)-1))
                    
                    if is_consistent:
                        logger.info(f"Rule: SymTrans detected ({len(sequence)} parts, axis {axis_name})")
                        # Representative is the first item
                        optimized.append(SymTrans(parts[sequence[0]], axis_name, len(sequence), dist))
                        used_indices.update(sequence)
                        break

            if i in used_indices: continue

            # --- 2. Mirror Symmetry (SymRef) ---
            found_mirror = False
            for j in range(i + 1, len(parts)):
                if j in used_indices: continue
                p2 = parts[j]
                
                if isinstance(p1, Translate) and isinstance(p2, Translate):
                    v1, v2 = np.array(p1.vector), np.array(p2.vector)
                    for axis_name, idx in [('AX', 0), ('AY', 1), ('AZ', 2)]:
                        mirrored_v2 = v2.copy()
                        mirrored_v2[idx] = -mirrored_v2[idx]
                        
                        if self.is_near_vec(v1, mirrored_v2) and self.is_near_node_geometry(p1.child, p2.child):
                            optimized.append(SymRef(p1, axis_name))
                            used_indices.add(i); used_indices.add(j)
                            found_mirror = True
                            break
                    if found_mirror: break
            
            if not found_mirror:
                optimized.append(p1)
                used_indices.add(i)
                
        return optimized

    def is_near_node_geometry(self, n1, n2):
        """Checks if two nodes are identical in shape/size (for symmetry)."""
        if type(n1) != type(n2): return False
        if isinstance(n1, Cuboid):
            return self.is_near_vec(n1.size, n2.size)
        # Add more geometry checks (Sphere, Cylinder) here
        return False

    def flatten_unions(self, node):
        if isinstance(node, Union):
            return self.flatten_unions(node.left) + self.flatten_unions(node.right)
        return [node] if node is not None else []

    def rebuild_union(self, nodes):
        if not nodes: return None
        if len(nodes) == 1: return nodes[0]
        # s3dl_union_over ensures we build a consistent tree
        return Union(nodes[0], self.rebuild_union(nodes[1:]))

    def optimize_node(self, node):
        return self.apply_optimization_rules(node)

    def run(self, root_node):
        if root_node is None: return None

        # 1. Deep apply local rules (combining moves, rotations, etc.)
        root_node = self.optimize_node(root_node)
        
        # 2. Flatten for global structural rules
        parts = self.flatten_unions(root_node)
        
        # 3. Apply Symmetry and Factoring
        parts = self.find_symmetries(parts)
        
        # 4. Final rebuild
        return self.rebuild_union(parts)

# --- EXECUTION ---
optimizer = ShapeOptimizer()
results = {}

# Example loop with improved error handling
for shape_id, data in shapes_l0.items():
    try:
        original_dsl = data.get("dsl")
        if original_dsl is None:
            continue

        optimized = optimizer.run(copy.deepcopy(original_dsl))
        results[shape_id] = optimized
        
        orig_count = len(optimizer.flatten_unions(original_dsl))
        opt_count = len(optimizer.flatten_unions(optimized))
        
        if opt_count < orig_count:
            print(f"✅ {shape_id}: Reduced from {orig_count} to {opt_count} nodes.")
            
    except Exception as e:
        logger.error(f"Critical failure on {shape_id}: {e}", exc_info=True)

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)

INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (9 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)

✅ 172_0_0: Reduced from 11 to 6 nodes.
✅ 173_0_1: Reduced from 6 to 4 nodes.
✅ 182_0_4: Reduced from 6 to 5 nodes.
✅ 186_0_5: Reduced from 9 to 7 nodes.
✅ 187_0_6: Reduced from 15 to 8 nodes.
✅ 197_0_7: Reduced from 16 to 14 nodes.
✅ 272_0_9: Reduced from 6 to 5 nodes.
✅ 278_0_10: Reduced from 11 to 6 nodes.
✅ 280_0_11: Reduced from 16 to 15 nodes.
✅ 285_0_12: Reduced from 9 to 7 nodes.
✅ 286_0_13: Reduced from 15 to 11 nodes.
✅ 314_0_15: Reduced from 11 to 6 nodes.
✅ 315_0_16: Reduced from 6 to 4 nodes.
✅ 328_0_17: Reduced from 16 to 14 nodes.
✅ 340_0_19: Reduced from 6 to 5 nodes.
✅ 341_0_20: Reduced from 6 to 5 nodes.
✅ 347_0_21: Reduced from 9 to 7 nodes.
✅ 349_0_22: Reduced from 15 to 12 nodes.
✅ 456_0_23: Reduced from 8 to 6 nodes.
✅ 470_0_24: Reduced from 7 to 6 nodes.
✅ 515_0_27: Reduced from 10 to 9 nodes.
✅ 518_0_29: Reduced from 8 to 7 nodes.
✅ 523_0_30: Reduced from 7 to 5 nodes.
✅ 526_0_31: Reduced from 14 to 12 nodes.
✅ 539_0_32: Reduced from 12 to 7 nodes.
✅ 543_0_33: Reduced from 6 to 4 nodes.
✅ 545_0_34: Reduced from 11 to 6 nodes.
✅ 547_0_35: Reduced from 10 to 7 nodes.
✅ 550_0_36: Reduced from 16 to 14 nodes.
✅ 554_0_38: Reduced from 15 to 7 nodes.
✅ 555_0_39: Reduced from 6 to 5 nodes.
✅ 557_0_40: Reduced from 10 to 9 nodes.
✅ 561_0_41: Reduced from 6 to 5 nodes.
✅ 574_0_42: Reduced from 15 to 9 nodes.
✅ 671_0_43: Reduced from 6 to 4 nodes.
✅ 682_0_44: Reduced from 11 to 5 nodes.
✅ 698_0_46: Reduced from 10 to 6 nodes.
✅ 699_0_47: Reduced from 11 to 6 nodes.
✅ 701_0_48: Reduced from 11 to 5 nodes.
✅ 724_0_50: Reduced from 6 to 4 nodes.
✅ 725_0_51: Reduced from 9 to 6 nodes.
✅ 732_0_52: Reduced from 6 to 4 nodes.
✅ 737_0_53: Reduced from 16 to 15 nodes.
✅ 739_0_54: Reduced from 13 to 12 nodes.
✅ 746_0_56: Reduced from 8 to 6 nodes.
✅ 748_0_57: Reduced from 12 to 11 nodes.
✅ 750_0_58: Reduced from 7 to 5 nodes.
✅ 752_0_59: Reduced from 6 to 5 nodes.
✅ 754_0_60: Reduced from 16 to 9 nodes.
✅ 756_0_61: Reduced from 9 to 6 nodes.
✅ 760_0_62: Reduced from 11 to 7 nodes.
✅ 763_0_63: Reduced from 11 to 9 nodes.
✅ 772_0_65: Reduced from 9 to 7 nodes.
✅ 776_0_66: Reduced from 15 to 8 nodes.
✅ 1282_0_68: Reduced from 8 to 6 nodes.
✅ 1287_0_69: Reduced from 10 to 9 nodes.
✅ 1293_0_70: Reduced from 9 to 6 nodes.
✅ 1295_0_71: Reduced from 6 to 4 nodes.
✅ 1299_0_73: Reduced from 8 to 7 nodes.
✅ 1301_0_74: Reduced from 6 to 4 nodes.
✅ 1314_0_77: Reduced from 12 to 7 nodes.
✅ 1316_0_78: Reduced from 6 to 4 nodes.
✅ 1319_0_79: Reduced from 15 to 11 nodes.
✅ 1331_0_81: Reduced from 12 to 9 nodes.
✅ 1333_0_82: Reduced from 8 to 7 nodes.
✅ 1355_0_84: Reduced from 8 to 6 nodes.
✅ 1359_0_85: Reduced from 6 to 4 nodes.
✅ 1368_0_87: Reduced from 14 to 10 nodes.
✅ 1374_0_89: Reduced from 9 to 7 nodes.
✅ 1377_0_90: Reduced from 12 to 10 nodes.
✅ 1382_0_92: Reduced from 9 to 7 nodes.
✅ 1400_0_94: Reduced from 10 to 9 nodes.
✅ 1403_0_95: Reduced from 15 to 14 nodes.
✅ 1409_0_96: Reduced from 6 to 4 nodes.
✅ 1425_0_97: Reduced from 16 to 15 nodes.
✅ 1441_0_100: Reduced from 6 to 4 nodes.
✅ 1463_0_101: Reduced from 10 to 7 nodes.
✅ 1472_0_102: Reduced from 10 to 9 nodes.
✅ 2121_0_106: Reduced from 11 to 8 nodes.
✅ 2132_0_107: Reduced from 8 to 7 nodes.
✅ 2136_0_108: Reduced from 14 to 12 nodes.
✅ 2184_0_109: Reduced from 12 to 7 nodes.
✅ 2194_0_110: Reduced from 9 to 8 nodes.
✅ 2198_0_111: Reduced from 6 to 4 nodes.
✅ 2203_0_112: Reduced from 9 to 6 nodes.
✅ 2214_0_113: Reduced from 12 to 8 nodes.
✅ 2217_0_114: Reduced from 6 to 4 nodes.
✅ 2221_0_116: Reduced from 6 to 5 nodes.
✅ 2223_0_117: Reduced from 10 to 6 nodes.
✅ 2225_0_118: Reduced from 6 to 5 nodes.
✅ 2227_0_119: Reduced from 5 to 4 nodes.
✅ 2233_0_120: Reduced from 13 to 9 nodes.
✅ 2234_0_121: Reduced from 14 to 13 nodes.
✅ 2236_0_123: Reduced from 7 to 5 nodes.
✅ 2239_0_124: Reduced from 12 to 7 nodes.
✅ 2240_0_125: Reduced from 14 to 11 nodes.
✅ 2241_0_126: Reduced from 6 to 4 nodes.
✅ 2248_0_128: Reduced from 10 to 9 nodes.
✅ 2249_0_129: Reduced from 11 to 5 nodes.
✅ 2252_0_130: Reduced from 11 to 7 nodes.
✅ 2253_0_131: Reduced from 5 to 4 nodes.
✅ 2255_0_132: Reduced from 16 to 14 nodes.
✅ 2262_0_135: Reduced from 8 to 6 nodes.
✅ 2263_0_136: Reduced from 10 to 7 nodes.
✅ 2266_0_137: Reduced from 6 to 4 nodes.
✅ 2269_0_138: Reduced from 7 to 5 nodes.
✅ 2270_0_139: Reduced from 6 to 5 nodes.
✅ 2271_0_140: Reduced from 6 to 5 nodes.
✅ 2276_0_141: Reduced from 9 to 6 nodes.
✅ 2277_0_142: Reduced from 16 to 15 nodes.
✅ 2281_0_144: Reduced from 9 to 6 nodes.
✅ 2283_0_145: Reduced from 9 to 6 nodes.
✅ 2287_0_147: Reduced from 12 to 9 nodes.
✅ 2291_0_148: Reduced from 6 to 5 nodes.
✅ 2293_0_149: Reduced from 12 to 11 nodes.
✅ 2294_0_150: Reduced from 9 to 7 nodes.
✅ 2295_0_151: Reduced from 7 to 5 nodes.
✅ 2302_0_153: Reduced from 9 to 5 nodes.
✅ 2304_0_154: Reduced from 14 to 11 nodes.
✅ 2306_0_155: Reduced from 9 to 6 nodes.
✅ 2307_0_156: Reduced from 13 to 5 nodes.
✅ 2309_0_158: Reduced from 6 to 4 nodes.
✅ 2315_0_161: Reduced from 14 to 10 nodes.
✅ 2316_0_162: Reduced from 4 to 3 nodes.
✅ 2318_0_163: Reduced from 12 to 11 nodes.
✅ 2328_0_167: Reduced from 11 to 8 nodes.
✅ 2330_0_168: Reduced from 6 to 4 nodes.
✅ 2332_0_169: Reduced from 6 to 5 nodes.
✅ 2333_0_170: Reduced from 9 to 8 nodes.
✅ 2334_0_171: Reduced from 12 to 11 nodes.
✅ 2341_0_174: Reduced from 8 to 6 nodes.
✅ 2342_0_175: Reduced from 6 to 5 nodes.
✅ 2344_0_177: Reduced from 6 to 4 nodes.
✅ 2345_0_178: Reduced from 12 to 10 nodes.
✅ 2346_0_179: Reduced from 16 to 11 nodes.
✅ 2350_0_180: Reduced from 10 to 8 nodes.
✅ 2351_0_181: Reduced from 6 to 4 nodes.
✅ 2352_0_182: Reduced from 7 to 6 nodes.
✅ 2354_0_183: Reduced from 9 to 7 nodes.
✅ 2355_0_184: Reduced from 7 to 6 nodes.
✅ 2360_0_186: Reduced from 6 to 5 nodes.
✅ 2365_0_187: Reduced from 13 to 10 nodes.
✅ 2369_0_189: Reduced from 6 to 4 nodes.
✅ 2370_0_190: Reduced from 6 to 4 nodes.
✅ 2371_0_191: Reduced from 9 to 6 nodes.
✅ 2373_0_192: Reduced from 11 to 7 nodes.
✅ 2374_0_193: Reduced from 8 to 7 nodes.
✅ 2376_0_194: Reduced from 11 to 8 nodes.
✅ 2379_0_196: Reduced from 10 to 7 nodes.
✅ 2382_0_197: Reduced from 9 to 7 nodes.
✅ 2384_0_199: Reduced from 15 to 11 nodes.
✅ 2396_0_202: Reduced from 8 to 7 nodes.
✅ 2399_0_204: Reduced from 5 to 3 nodes.
✅ 2406_0_207: Reduced from 6 to 5 nodes.
✅ 2410_0_209: Reduced from 12 to 9 nodes.
✅ 2412_0_210: Reduced from 6 to 4 nodes.
✅ 2416_0_211: Reduced from 16 to 15 nodes.
✅ 2423_0_214: Reduced from 12 to 10 nodes.
✅ 2424_0_215: Reduced from 7 to 5 nodes.
✅ 2429_0_216: Reduced from 11 to 9 nodes.
✅ 2434_0_218: Reduced from 12 to 8 nodes.
✅ 2435_0_219: Reduced from 10 to 9 nodes.
✅ 2436_0_220: Reduced from 6 to 5 nodes.
✅ 2437_0_221: Reduced from 12 to 7 nodes.
✅ 2439_0_222: Reduced from 6 to 4 nodes.
✅ 2446_0_225: Reduced from 11 to 9 nodes.
✅ 2447_0_226: Reduced from 11 to 8 nodes.
✅ 2448_0_227: Reduced from 13 to 9 nodes.
✅ 2449_0_228: Reduced from 15 to 14 nodes.
✅ 2454_0_229: Reduced from 6 to 4 nodes.
✅ 2457_0_230: Reduced from 8 to 7 nodes.
✅ 2458_0_231: Reduced from 11 to 8 nodes.
✅ 2464_0_234: Reduced from 9 to 8 nodes.
✅ 2466_0_235: Reduced from 10 to 8 nodes.
✅ 2470_0_237: Reduced from 9 to 8 nodes.
✅ 2472_0_238: Reduced from 11 to 9 nodes.
✅ 2476_0_239: Reduced from 4 to 3 nodes.
✅ 2478_0_240: Reduced from 4 to 3 nodes.
✅ 2479_0_241: Reduced from 13 to 10 nodes.
✅ 2483_0_243: Reduced from 10 to 9 nodes.
✅ 2493_0_246: Reduced from 7 to 6 nodes.
✅ 2495_0_248: Reduced from 12 to 6 nodes.
✅ 2497_0_249: Reduced from 16 to 12 nodes.
✅ 2502_0_251: Reduced from 13 to 12 nodes.
✅ 2503_0_252: Reduced from 11 to 9 nodes.
✅ 2505_0_253: Reduced from 6 to 4 nodes.
✅ 2506_0_254: Reduced from 14 to 12 nodes.
✅ 2508_0_255: Reduced from 15 to 14 nodes.
✅ 2511_0_257: Reduced from 9 to 7 nodes.
✅ 2516_0_259: Reduced from 7 to 6 nodes.
✅ 2524_0_262: Reduced from 10 to 9 nodes.
✅ 2529_0_263: Reduced from 5 to 4 nodes.
✅ 2535_0_266: Reduced from 13 to 12 nodes.
✅ 2539_0_267: Reduced from 6 to 4 nodes.
✅ 2542_0_269: Reduced from 6 to 4 nodes.
✅ 2544_0_270: Reduced from 6 to 5 nodes.
✅ 2545_0_271: Reduced from 6 to 4 nodes.
✅ 2546_0_272: Reduced from 7 to 6 nodes.
✅ 2558_0_273: Reduced from 14 to 8 nodes.
✅ 2562_0_274: Reduced from 9 to 8 nodes.
✅ 2567_0_276: Reduced from 13 to 9 nodes.
✅ 2570_0_278: Reduced from 6 to 4 nodes.
✅ 2574_0_280: Reduced from 6 to 4 nodes.
✅ 2577_0_282: Reduced from 8 to 7 nodes.
✅ 2582_0_284: Reduced from 9 to 7 nodes.
✅ 2584_0_285: Reduced from 4 to 3 nodes.
✅ 2585_0_286: Reduced from 6 to 4 nodes.
✅ 2586_0_287: Reduced from 15 to 14 nodes.
✅ 2592_0_291: Reduced from 6 to 4 nodes.

INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)

✅ 2593_0_292: Reduced from 12 to 9 nodes.
✅ 2598_0_294: Reduced from 9 to 7 nodes.
✅ 2602_0_296: Reduced from 11 to 8 nodes.
✅ 2605_0_297: Reduced from 15 to 10 nodes.
✅ 2607_0_298: Reduced from 10 to 7 nodes.
✅ 2611_0_299: Reduced from 10 to 6 nodes.
✅ 2612_0_300: Reduced from 6 to 4 nodes.
✅ 2614_0_301: Reduced from 9 to 6 nodes.
✅ 2620_0_302: Reduced from 10 to 9 nodes.
✅ 2623_0_303: Reduced from 10 to 7 nodes.
✅ 2631_0_306: Reduced from 16 to 14 nodes.
✅ 2636_0_307: Reduced from 4 to 3 nodes.
✅ 2637_0_308: Reduced from 6 to 4 nodes.
✅ 2645_0_310: Reduced from 7 to 6 nodes.
✅ 2647_0_311: Reduced from 9 to 7 nodes.
✅ 2648_0_312: Reduced from 12 to 10 nodes.
✅ 2650_0_313: Reduced from 8 to 7 nodes.
✅ 2653_0_314: Reduced from 15 to 10 nodes.
✅ 2655_0_315: Reduced from 6 to 5 nodes.
✅ 2656_0_316: Reduced from 8 to 6 nodes.
✅ 2663_0_317: Reduced from 11 to 7 nodes.
✅ 2666_0_319: Reduced from 12 to 9 nodes.
✅ 2673_0_320: Reduced from 16 to 12 nodes.
✅ 2681_0_323: Reduced from 7 to 5 nodes.
✅ 2684_0_324: Reduced from 12 to 9 nodes.
✅ 2687_0_325: Reduced from 8 to 7 nodes.
✅ 2691_0_327: Reduced from 9 to 7 nodes.
✅ 2692_0_328: Reduced from 6 to 4 nodes.
✅ 2694_0_329: Reduced from 9 to 6 nodes.
✅ 2700_0_330: Reduced from 4 to 3 nodes.
✅ 2707_0_333: Reduced from 8 to 7 nodes.
✅ 2710_0_335: Reduced from 4 to 3 nodes.
✅ 2711_0_336: Reduced from 7 to 6 nodes.
✅ 2712_0_337: Reduced from 10 to 6 nodes.
✅ 2723_0_339: Reduced from 6 to 4 nodes.
✅ 2728_0_340: Reduced from 13 to 10 nodes.
✅ 2731_0_341: Reduced from 15 to 11 nodes.
✅ 2741_0_343: Reduced from 8 to 7 nodes.
✅ 2746_0_344: Reduced from 11 to 5 nodes.
✅ 2750_0_345: Reduced from 7 to 5 nodes.
✅ 2752_0_346: Reduced from 6 to 5 nodes.
✅ 2755_0_348: Reduced from 10 to 7 nodes.
✅ 2759_0_350: Reduced from 14 to 11 nodes.
✅ 2764_0_351: Reduced from 9 to 6 nodes.
✅ 2769_0_352: Reduced from 8 to 5 nodes.
✅ 2770_0_353: Reduced from 6 to 4 nodes.
✅ 2772_0_354: Reduced from 6 to 5 nodes.
✅ 2773_0_355: Reduced from 5 to 4 nodes.
✅ 2774_0_356: Reduced from 12 to 8 nodes.
✅ 2775_0_357: Reduced from 11 to 8 nodes.
✅ 2785_0_359: Reduced from 10 to 8 nodes.
✅ 2786_0_360: Reduced from 10 to 5 nodes.
✅ 2788_0_361: Reduced from 13 to 8 nodes.
✅ 2789_0_362: Reduced from 14 to 11 nodes.
✅ 2790_0_363: Reduced from 6 to 4 nodes.
✅ 2797_0_365: Reduced from 6 to 5 nodes.
✅ 2799_0_366: Reduced from 6 to 5 nodes.
✅ 2802_0_367: Reduced from 12 to 7 nodes.
✅ 2803_0_368: Reduced from 6 to 5 nodes.
✅ 2804_0_369: Reduced from 6 to 4 nodes.
✅ 2810_0_371: Reduced from 16 to 12 nodes.
✅ 2815_0_374: Reduced from 6 to 5 nodes.
✅ 2817_0_375: Reduced from 11 to 10 nodes.
✅ 2820_0_376: Reduced from 15 to 13 nodes.
✅ 2827_0_377: Reduced from 14 to 13 nodes.
✅ 2828_0_378: Reduced from 9 to 7 nodes.
✅ 2830_0_379: Reduced from 8 to 5 nodes.
✅ 2832_0_380: Reduced from 9 to 6 nodes.
✅ 2834_0_381: Reduced from 12 to 8 nodes.
✅ 2847_0_383: Reduced from 16 to 13 nodes.
✅ 2855_0_385: Reduced from 11 to 8 nodes.
✅ 2864_0_386: Reduced from 10 to 5 nodes.
✅ 2865_0_387: Reduced from 11 to 9 nodes.
✅ 2867_0_389: Reduced from 6 to 5 nodes.
✅ 2868_0_390: Reduced from 6 to 4 nodes.
✅ 2869_0_391: Reduced from 14 to 11 nodes.
✅ 2871_0_392: Reduced from 6 to 4 nodes.
✅ 2878_0_394: Reduced from 8 to 6 nodes.
✅ 2882_0_396: Reduced from 13 to 8 nodes.
✅ 2885_0_397: Reduced from 7 to 5 nodes.
✅ 2886_0_398: Reduced from 9 to 8 nodes.
✅ 2893_0_399: Reduced from 11 to 10 nodes.
✅ 2896_0_400: Reduced from 5 to 4 nodes.
✅ 2898_0_401: Reduced from 7 to 5 nodes.
✅ 2900_0_402: Reduced from 12 to 11 nodes.
✅ 2903_0_403: Reduced from 10 to 8 nodes.
✅ 2904_0_404: Reduced from 6 to 5 nodes.
✅ 2906_0_405: Reduced from 16 to 12 nodes.
✅ 2908_0_406: Reduced from 12 to 10 nodes.
✅ 2913_0_408: Reduced from 14 to 9 nodes.
✅ 2930_0_411: Reduced from 11 to 9 nodes.
✅ 2943_0_413: Reduced from 10 to 5 nodes.
✅ 2946_0_414: Reduced from 12 to 11 nodes.
✅ 2947_0_415: Reduced from 14 to 13 nodes.
✅ 2948_0_416: Reduced from 9 to 7 nodes.
✅ 2950_0_417: Reduced from 13 to 7 nodes.
✅ 2956_0_420: Reduced from 11 to 8 nodes.
✅ 2957_0_421: Reduced from 6 to 4 nodes.
✅ 2959_0_423: Reduced from 11 to 9 nodes.
✅ 2960_0_424: Reduced from 10 to 5 nodes.
✅ 2962_0_425: Reduced from 10 to 8 nodes.
✅ 2975_0_428: Reduced from 10 to 8 nodes.
✅ 2980_0_429: Reduced from 13 to 9 nodes.
✅ 2993_0_432: Reduced from 4 to 3 nodes.
✅ 3005_0_436: Reduced from 15 to 13 nodes.
✅ 3006_0_437: Reduced from 11 to 10 nodes.
✅ 3007_0_438: Reduced from 9 to 8 nodes.
✅ 3009_0_439: Reduced from 16 to 12 nodes.
✅ 3013_0_440: Reduced from 10 to 7 nodes.
✅ 3015_0_441: Reduced from 9 to 6 nodes.
✅ 3026_0_443: Reduced from 12 to 10 nodes.
✅ 3032_0_445: Reduced from 9 to 7 nodes.
✅ 3033_0_446: Reduced from 12 to 9 nodes.
✅ 3035_0_447: Reduced from 5 to 4 nodes.
✅ 3037_0_448: Reduced from 8 to 6 nodes.
✅ 3043_0_449: Reduced from 12 to 8 nodes.
✅ 3045_0_450: Reduced from 11 to 9 nodes.
✅ 3051_0_451: Reduced from 11 to 8 nodes.
✅ 3054_0_452: Reduced from 11 to 10 nodes.
✅ 3059_0_453: Reduced from 5 to 4 nodes.
✅ 3068_0_454: Reduced from 11 to 8 nodes.
✅ 3074_0_456: Reduced from 10 to 8 nodes.
✅ 3078_0_457: Reduced from 9 to 6 nodes.
✅ 3081_0_459: Reduced from 6 to 4 nodes.
✅ 3094_0_460: Reduced from 6 to 4 nodes.
✅ 3097_0_461: Reduced from 10 to 8 nodes.
✅ 3105_0_463: Reduced from 6 to 4 nodes.
✅ 3107_0_465: Reduced from 8 to 7 nodes.
✅ 3109_0_466: Reduced from 6 to 4 nodes.
✅ 3113_0_468: Reduced from 14 to 10 nodes.
✅ 3123_0_470: Reduced from 9 to 6 nodes.
✅ 3124_0_471: Reduced from 8 to 7 nodes.
✅ 3128_0_473: Reduced from 14 to 10 nodes.
✅ 3131_0_474: Reduced from 8 to 6 nodes.
✅ 3146_0_478: Reduced from 9 to 8 nodes.
✅ 3150_0_480: Reduced from 9 to 7 nodes.
✅ 3157_0_481: Reduced from 8 to 6 nodes.
✅ 3159_0_482: Reduced from 6 to 4 nodes.
✅ 3163_0_484: Reduced from 12 to 11 nodes.
✅ 3174_0_485: Reduced from 6 to 4 nodes.
✅ 3181_0_486: Reduced from 10 to 7 nodes.
✅ 3187_0_487: Reduced from 10 to 9 nodes.
✅ 3198_0_491: Reduced from 13 to 9 nodes.
✅ 3199_0_492: Reduced from 15 to 13 nodes.
✅ 3207_0_493: Reduced from 8 to 5 nodes.
✅ 3214_0_496: Reduced from 8 to 7 nodes.
✅ 3215_0_497: Reduced from 6 to 5 nodes.
✅ 3217_0_498: Reduced from 6 to 5 nodes.
✅ 3224_0_500: Reduced from 6 to 5 nodes.
✅ 3225_0_501: Reduced from 6 to 4 nodes.
✅ 3227_0_502: Reduced from 6 to 5 nodes.
✅ 3233_0_504: Reduced from 6 to 5 nodes.
✅ 3236_0_505: Reduced from 12 to 10 nodes.
✅ 3251_0_509: Reduced from 6 to 4 nodes.
✅ 3253_0_510: Reduced from 11 to 5 nodes.
✅ 3257_0_512: Reduced from 7 to 6 nodes.
✅ 3258_0_513: Reduced from 9 to 8 nodes.
✅ 3269_0_516: Reduced from 11 to 9 nodes.
✅ 3271_0_517: Reduced from 10 to 7 nodes.
✅ 3272_0_518: Reduced from 8 to 7 nodes.
✅ 3274_0_519: Reduced from 9 to 7 nodes.
✅ 3277_0_520: Reduced from 8 to 6 nodes.
✅ 3278_0_521: Reduced from 8 to 5 nodes.
✅ 3280_0_522: Reduced from 13 to 11 nodes.
✅ 3281_0_523: Reduced from 10 to 8 nodes.
✅ 3288_0_525: Reduced from 15 to 14 nodes.
✅ 3293_0_526: Reduced from 10 to 8 nodes.
✅ 3301_0_528: Reduced from 14 to 13 nodes.
✅ 3302_0_529: Reduced from 16 to 12 nodes.
✅ 3305_0_530: Reduced from 11 to 7 nodes.
✅ 3309_0_531: Reduced from 10 to 7 nodes.
✅ 3316_0_533: Reduced from 15 to 11 nodes.
✅ 3318_0_534: Reduced from 6 to 4 nodes.
✅ 3321_0_537: Reduced from 15 to 14 nodes.
✅ 3322_0_538: Reduced from 16 to 8 nodes.
✅ 3323_0_539: Reduced from 6 to 4 nodes.
✅ 3324_0_540: Reduced from 7 to 5 nodes.
✅ 3328_0_541: Reduced from 12 to 10 nodes.
✅ 3330_0_542: Reduced from 10 to 9 nodes.
✅ 3331_0_543: Reduced from 12 to 9 nodes.
✅ 3336_0_544: Reduced from 10 to 7 nodes.
✅ 3340_0_545: Reduced from 14 to 11 nodes.
✅ 3344_0_546: Reduced from 11 to 10 nodes.
✅ 3347_0_547: Reduced from 13 to 6 nodes.
✅ 3349_0_549: Reduced from 11 to 7 nodes.
✅ 3353_0_551: Reduced from 11 to 9 nodes.
✅ 3361_0_554: Reduced from 7 to 5 nodes.
✅ 3364_0_555: Reduced from 6 to 5 nodes.
✅ 3375_0_558: Reduced from 6 to 4 nodes.
✅ 3377_0_559: Reduced from 14 to 10 nodes.
✅ 3384_0_561: Reduced from 6 to 5 nodes.
✅ 3402_0_562: Reduced from 8 to 5 nodes.
✅ 34924_0_564: Reduced from 6 to 4 nodes.
✅ 34925_0_565: Reduced from 11 to 6 nodes.
✅ 34926_0_566: Reduced from 16 to 15 nodes.
✅ 34998_0_567: Reduced from 6 to 4 nodes.
✅ 35014_0_568: Reduced from 11 to 6 nodes.
✅ 35062_0_569: Reduced from 15 to 13 nodes.
✅ 35064_0_570: Reduced from 9 to 7 nodes.
✅ 35070_0_572: Reduced from 6 to 5 nodes.
✅ 35071_0_573: Reduced from 15 to 10 nodes.
✅ 35072_0_574: Reduced from 6 to 4 nodes.
✅ 35082_0_576: Reduced from 10 to 8 nodes.
✅ 35096_0_578: Reduced from 6 to 4 nodes.
✅ 35097_0_579: Reduced from 6 to 4 nodes.
✅ 35100_0_581: Reduced from 16 to 13 nodes.

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)

✅ 35103_0_584: Reduced from 15 to 12 nodes.
✅ 35104_0_585: Reduced from 6 to 4 nodes.
✅ 35111_0_587: Reduced from 16 to 12 nodes.
✅ 35119_0_589: Reduced from 11 to 6 nodes.
✅ 35121_0_590: Reduced from 9 to 7 nodes.
✅ 35123_0_591: Reduced from 15 to 13 nodes.
✅ 35131_0_592: Reduced from 11 to 6 nodes.
✅ 35142_0_593: Reduced from 9 to 7 nodes.
✅ 35144_0_594: Reduced from 14 to 12 nodes.
✅ 35146_0_596: Reduced from 9 to 7 nodes.
✅ 35153_0_597: Reduced from 11 to 6 nodes.
✅ 35178_0_598: Reduced from 11 to 6 nodes.
✅ 35180_0_599: Reduced from 12 to 11 nodes.
✅ 35184_0_600: Reduced from 12 to 10 nodes.
✅ 35186_0_602: Reduced from 15 to 10 nodes.
✅ 35189_0_604: Reduced from 11 to 6 nodes.
✅ 35197_0_607: Reduced from 15 to 13 nodes.
✅ 35200_0_608: Reduced from 6 to 4 nodes.
✅ 35201_0_609: Reduced from 15 to 8 nodes.
✅ 35203_0_610: Reduced from 15 to 13 nodes.
✅ 35204_0_611: Reduced from 6 to 4 nodes.
✅ 35205_0_612: Reduced from 9 to 7 nodes.
✅ 35213_0_613: Reduced from 15 to 13 nodes.
✅ 35222_0_615: Reduced from 6 to 4 nodes.
✅ 35223_0_616: Reduced from 16 to 12 nodes.
✅ 35233_0_617: Reduced from 16 to 12 nodes.
✅ 35234_0_618: Reduced from 6 to 5 nodes.
✅ 35236_0_620: Reduced from 6 to 4 nodes.
✅ 35238_0_621: Reduced from 6 to 4 nodes.
✅ 35245_0_623: Reduced from 11 to 6 nodes.
✅ 35270_0_625: Reduced from 16 to 14 nodes.
✅ 35273_0_626: Reduced from 6 to 5 nodes.
✅ 35274_0_627: Reduced from 9 to 7 nodes.
✅ 35319_0_629: Reduced from 15 to 6 nodes.
✅ 35326_0_630: Reduced from 8 to 7 nodes.
✅ 35331_0_631: Reduced from 14 to 12 nodes.
✅ 35333_0_632: Reduced from 16 to 13 nodes.
✅ 35376_0_633: Reduced from 11 to 6 nodes.
✅ 35392_0_634: Reduced from 11 to 6 nodes.
✅ 35393_0_635: Reduced from 12 to 7 nodes.
✅ 35396_0_636: Reduced from 12 to 7 nodes.
✅ 35401_0_637: Reduced from 10 to 8 nodes.
✅ 35407_0_638: Reduced from 11 to 6 nodes.
✅ 35423_0_639: Reduced from 11 to 6 nodes.
✅ 35424_0_640: Reduced from 6 to 4 nodes.
✅ 35439_0_641: Reduced from 10 to 7 nodes.
✅ 35440_0_642: Reduced from 11 to 6 nodes.
✅ 35441_0_643: Reduced from 15 to 13 nodes.
✅ 35445_0_644: Reduced from 15 to 13 nodes.
✅ 35447_0_645: Reduced from 9 to 7 nodes.
✅ 35448_0_646: Reduced from 10 to 8 nodes.
✅ 35455_0_647: Reduced from 9 to 7 nodes.
✅ 35464_0_648: Reduced from 15 to 13 nodes.
✅ 35471_0_649: Reduced from 11 to 9 nodes.
✅ 35477_0_650: Reduced from 11 to 6 nodes.
✅ 35481_0_651: Reduced from 9 to 7 nodes.
✅ 35482_0_652: Reduced from 10 to 8 nodes.
✅ 35486_0_653: Reduced from 6 to 4 nodes.
✅ 35498_0_655: Reduced from 6 to 4 nodes.
✅ 35499_0_656: Reduced from 16 to 14 nodes.
✅ 35500_0_657: Reduced from 6 to 5 nodes.
✅ 35505_0_658: Reduced from 15 to 13 nodes.
✅ 35507_0_659: Reduced from 15 to 8 nodes.
✅ 35511_0_662: Reduced from 10 to 9 nodes.
✅ 35515_0_664: Reduced from 6 to 4 nodes.
✅ 35516_0_665: Reduced from 15 to 12 nodes.
✅ 35517_0_666: Reduced from 6 to 4 nodes.
✅ 35519_0_668: Reduced from 6 to 4 nodes.
✅ 35525_0_670: Reduced from 15 to 12 nodes.
✅ 35526_0_671: Reduced from 8 to 6 nodes.
✅ 35527_0_672: Reduced from 9 to 7 nodes.
✅ 35531_0_674: Reduced from 6 to 4 nodes.
✅ 35532_0_675: Reduced from 15 to 11 nodes.
✅ 35533_0_676: Reduced from 6 to 5 nodes.
✅ 35549_0_677: Reduced from 15 to 8 nodes.
✅ 35551_0_678: Reduced from 6 to 5 nodes.
✅ 35553_0_679: Reduced from 6 to 5 nodes.
✅ 35554_0_680: Reduced from 6 to 4 nodes.
✅ 35561_0_682: Reduced from 11 to 8 nodes.
✅ 35580_0_684: Reduced from 9 to 7 nodes.
✅ 35583_0_685: Reduced from 15 to 12 nodes.
✅ 35584_0_686: Reduced from 15 to 13 nodes.
✅ 35589_0_689: Reduced from 9 to 7 nodes.
✅ 35596_0_690: Reduced from 8 to 7 nodes.
✅ 35606_0_692: Reduced from 14 to 12 nodes.
✅ 35607_0_693: Reduced from 16 to 13 nodes.
✅ 35608_0_694: Reduced from 6 to 4 nodes.
✅ 35609_0_695: Reduced from 11 to 5 nodes.
✅ 35617_0_696: Reduced from 15 to 8 nodes.
✅ 35621_0_697: Reduced from 9 to 7 nodes.
✅ 35624_0_698: Reduced from 7 to 5 nodes.
✅ 35633_0_699: Reduced from 6 to 5 nodes.
✅ 35635_0_700: Reduced from 15 to 7 nodes.
✅ 35642_0_702: Reduced from 6 to 4 nodes.
✅ 35650_0_704: Reduced from 11 to 10 nodes.
✅ 35665_0_707: Reduced from 15 to 12 nodes.
✅ 35670_0_708: Reduced from 6 to 4 nodes.
✅ 35672_0_709: Reduced from 14 to 12 nodes.
✅ 35731_0_711: Reduced from 9 to 6 nodes.
✅ 35738_0_713: Reduced from 13 to 12 nodes.
✅ 35755_0_717: Reduced from 12 to 7 nodes.
✅ 35759_0_718: Reduced from 8 to 5 nodes.
✅ 35761_0_719: Reduced from 8 to 5 nodes.
✅ 35765_0_720: Reduced from 14 to 12 nodes.
✅ 35766_0_721: Reduced from 12 to 10 nodes.
✅ 35772_0_722: Reduced from 14 to 12 nodes.
✅ 35776_0_723: Reduced from 11 to 10 nodes.
✅ 35780_0_725: Reduced from 11 to 10 nodes.
✅ 35785_0_726: Reduced from 11 to 9 nodes.
✅ 35786_0_727: Reduced from 9 to 7 nodes.
✅ 35788_0_728: Reduced from 6 to 4 nodes.
✅ 35793_0_729: Reduced from 15 to 7 nodes.
✅ 35795_0_731: Reduced from 6 to 4 nodes.
✅ 35802_0_732: Reduced from 6 to 5 nodes.
✅ 35803_0_733: Reduced from 6 to 4 nodes.
✅ 35804_0_734: Reduced from 6 to 5 nodes.
✅ 35806_0_735: Reduced from 11 to 10 nodes.
✅ 35809_0_736: Reduced from 10 to 7 nodes.
✅ 35811_0_737: Reduced from 8 to 7 nodes.
✅ 35813_0_738: Reduced from 9 to 7 nodes.
✅ 35814_0_739: Reduced from 14 to 12 nodes.
✅ 35816_0_740: Reduced from 6 to 5 nodes.
✅ 35820_0_741: Reduced from 8 to 7 nodes.
✅ 35822_0_742: Reduced from 13 to 10 nodes.
✅ 35837_0_744: Reduced from 8 to 6 nodes.
✅ 35858_0_748: Reduced from 15 to 8 nodes.
✅ 35861_0_749: Reduced from 8 to 6 nodes.
✅ 35871_0_752: Reduced from 13 to 12 nodes.
✅ 35875_0_753: Reduced from 14 to 11 nodes.
✅ 35876_0_754: Reduced from 12 to 7 nodes.
✅ 35881_0_757: Reduced from 11 to 6 nodes.
✅ 35883_0_758: Reduced from 8 to 5 nodes.
✅ 35894_0_761: Reduced from 12 to 7 nodes.
✅ 35902_0_762: Reduced from 11 to 10 nodes.
✅ 35905_0_763: Reduced from 15 to 12 nodes.
✅ 35909_0_764: Reduced from 9 to 6 nodes.
✅ 35910_0_765: Reduced from 14 to 11 nodes.
✅ 35911_0_766: Reduced from 12 to 10 nodes.
✅ 35916_0_768: Reduced from 12 to 7 nodes.
✅ 35919_0_769: Reduced from 8 to 7 nodes.
✅ 35923_0_771: Reduced from 6 to 4 nodes.
✅ 35925_0_772: Reduced from 8 to 7 nodes.
✅ 35926_0_773: Reduced from 12 to 7 nodes.
✅ 35932_0_774: Reduced from 6 to 5 nodes.
✅ 35939_0_775: Reduced from 10 to 9 nodes.
✅ 35946_0_776: Reduced from 6 to 4 nodes.
✅ 35959_0_778: Reduced from 10 to 7 nodes.
✅ 35960_0_779: Reduced from 12 to 10 nodes.
✅ 35962_0_780: Reduced from 6 to 4 nodes.
✅ 35966_0_781: Reduced from 12 to 7 nodes.
✅ 35969_0_782: Reduced from 6 to 4 nodes.
✅ 35970_0_783: Reduced from 10 to 9 nodes.
✅ 35979_0_784: Reduced from 11 to 6 nodes.
✅ 35996_0_787: Reduced from 9 to 6 nodes.
✅ 35997_0_788: Reduced from 12 to 7 nodes.
✅ 36002_0_789: Reduced from 8 to 7 nodes.
✅ 36006_0_790: Reduced from 12 to 7 nodes.
✅ 36008_0_792: Reduced from 11 to 6 nodes.
✅ 36009_0_793: Reduced from 6 to 5 nodes.
✅ 36015_0_795: Reduced from 13 to 11 nodes.
✅ 36027_0_796: Reduced from 11 to 6 nodes.
✅ 36032_0_797: Reduced from 8 to 6 nodes.
✅ 36034_0_798: Reduced from 16 to 13 nodes.
✅ 36042_0_801: Reduced from 14 to 12 nodes.
✅ 36043_0_802: Reduced from 13 to 10 nodes.
✅ 36055_0_804: Reduced from 15 to 13 nodes.
✅ 36063_0_807: Reduced from 12 to 7 nodes.
✅ 36066_0_808: Reduced from 9 to 8 nodes.
✅ 36069_0_809: Reduced from 6 to 4 nodes.
✅ 36070_0_810: Reduced from 6 to 5 nodes.
✅ 36071_0_811: Reduced from 7 to 6 nodes.
✅ 36078_0_812: Reduced from 10 to 7 nodes.
✅ 36081_0_813: Reduced from 10 to 8 nodes.
✅ 36083_0_814: Reduced from 15 to 8 nodes.
✅ 36092_0_815: Reduced from 10 to 7 nodes.
✅ 36098_0_816: Reduced from 9 to 8 nodes.
✅ 36110_0_818: Reduced from 6 to 4 nodes.
✅ 36113_0_819: Reduced from 15 to 13 nodes.
✅ 36114_0_820: Reduced from 10 to 7 nodes.
✅ 36115_0_821: Reduced from 6 to 4 nodes.
✅ 36116_0_822: Reduced from 6 to 5 nodes.
✅ 36117_0_823: Reduced from 11 to 6 nodes.
✅ 36119_0_824: Reduced from 6 to 5 nodes.
✅ 36129_0_825: Reduced from 15 to 6 nodes.
✅ 36130_0_826: Reduced from 9 to 8 nodes.
✅ 36131_0_827: Reduced from 6 to 5 nodes.
✅ 36132_0_828: Reduced from 6 to 5 nodes.
✅ 36136_0_829: Reduced from 8 to 5 nodes.
✅ 36138_0_830: Reduced from 7 to 5 nodes.
✅ 36142_0_832: Reduced from 11 to 6 nodes.
✅ 36144_0_833: Reduced from 10 to 7 nodes.
✅ 36145_0_834: Reduced from 11 to 5 nodes.
✅ 36146_0_835: Reduced from 15 to 11 nodes.
✅ 36162_0_839: Reduced from 12 to 7 nodes.
✅ 36166_0_840: Reduced from 11 to 6 nodes.
✅ 36175_0_842: Reduced from 6 to 4 nodes.
✅ 36177_0_843: Reduced from 15 to 13 nodes.
✅ 36179_0_844: Reduced from 6 to 5 nodes.
✅ 36188_0_847: Reduced from 6 to 5 nodes.
✅ 36196_0_849: Reduced from 6 to 4 nodes.
✅ 36199_0_850: Reduced from 6 to 5 nodes.

INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)

✅ 36201_0_852: Reduced from 15 to 7 nodes.
✅ 36202_0_853: Reduced from 6 to 4 nodes.
✅ 36203_0_854: Reduced from 14 to 13 nodes.
✅ 36209_0_855: Reduced from 11 to 5 nodes.
✅ 36212_0_857: Reduced from 10 to 7 nodes.
✅ 36213_0_858: Reduced from 11 to 10 nodes.
✅ 36217_0_859: Reduced from 6 to 5 nodes.
✅ 36220_0_861: Reduced from 8 to 6 nodes.
✅ 36225_0_862: Reduced from 9 to 8 nodes.
✅ 36228_0_863: Reduced from 10 to 9 nodes.
✅ 36229_0_864: Reduced from 10 to 8 nodes.
✅ 36236_0_867: Reduced from 11 to 6 nodes.
✅ 36239_0_868: Reduced from 6 to 4 nodes.
✅ 36245_0_870: Reduced from 14 to 9 nodes.
✅ 36248_0_872: Reduced from 10 to 7 nodes.
✅ 36249_0_873: Reduced from 6 to 5 nodes.
✅ 36251_0_874: Reduced from 9 to 8 nodes.
✅ 36255_0_875: Reduced from 7 to 5 nodes.
✅ 36256_0_876: Reduced from 10 to 8 nodes.
✅ 36258_0_878: Reduced from 12 to 10 nodes.
✅ 36267_0_879: Reduced from 14 to 12 nodes.
✅ 36269_0_880: Reduced from 8 to 5 nodes.
✅ 36277_0_882: Reduced from 15 to 11 nodes.
✅ 36284_0_884: Reduced from 12 to 10 nodes.
✅ 36291_0_885: Reduced from 6 to 5 nodes.
✅ 36292_0_886: Reduced from 9 to 8 nodes.
✅ 36293_0_887: Reduced from 11 to 9 nodes.
✅ 36308_0_892: Reduced from 6 to 5 nodes.
✅ 36309_0_893: Reduced from 9 to 6 nodes.
✅ 36310_0_894: Reduced from 15 to 10 nodes.
✅ 36315_0_897: Reduced from 6 to 4 nodes.
✅ 36316_0_898: Reduced from 6 to 5 nodes.
✅ 36323_0_900: Reduced from 6 to 5 nodes.
✅ 36325_0_901: Reduced from 10 to 8 nodes.
✅ 36328_0_902: Reduced from 15 to 8 nodes.
✅ 36332_0_904: Reduced from 6 to 4 nodes.
✅ 36336_0_906: Reduced from 10 to 9 nodes.
✅ 36342_0_907: Reduced from 12 to 7 nodes.
✅ 36343_0_908: Reduced from 16 to 12 nodes.
✅ 36347_0_909: Reduced from 11 to 5 nodes.
✅ 36353_0_912: Reduced from 15 to 13 nodes.
✅ 36374_0_915: Reduced from 10 to 8 nodes.
✅ 36379_0_916: Reduced from 11 to 5 nodes.
✅ 36381_0_917: Reduced from 9 to 6 nodes.
✅ 36385_0_918: Reduced from 11 to 5 nodes.
✅ 36402_0_921: Reduced from 11 to 5 nodes.
✅ 36407_0_923: Reduced from 11 to 5 nodes.
✅ 36410_0_924: Reduced from 11 to 5 nodes.
✅ 36414_0_925: Reduced from 6 to 4 nodes.
✅ 36420_0_927: Reduced from 14 to 13 nodes.
✅ 36428_0_928: Reduced from 14 to 11 nodes.
✅ 36431_0_929: Reduced from 8 to 6 nodes.
✅ 36432_0_930: Reduced from 11 to 9 nodes.
✅ 36433_0_931: Reduced from 8 to 6 nodes.
✅ 36438_0_934: Reduced from 12 to 7 nodes.
✅ 36439_0_935: Reduced from 9 to 7 nodes.
✅ 36440_0_936: Reduced from 11 to 9 nodes.
✅ 36442_0_937: Reduced from 10 to 8 nodes.
✅ 36444_0_938: Reduced from 11 to 8 nodes.
✅ 36455_0_939: Reduced from 10 to 8 nodes.
✅ 36462_0_941: Reduced from 6 to 4 nodes.
✅ 36466_0_942: Reduced from 10 to 7 nodes.
✅ 36468_0_943: Reduced from 6 to 4 nodes.
✅ 36481_0_947: Reduced from 8 to 7 nodes.
✅ 36491_0_948: Reduced from 5 to 4 nodes.
✅ 36495_0_951: Reduced from 11 to 5 nodes.
✅ 36496_0_952: Reduced from 5 to 4 nodes.
✅ 36499_0_953: Reduced from 15 to 11 nodes.
✅ 36502_0_954: Reduced from 12 to 10 nodes.
✅ 36514_0_956: Reduced from 15 to 7 nodes.
✅ 36520_0_959: Reduced from 8 to 6 nodes.
✅ 36522_0_960: Reduced from 6 to 4 nodes.
✅ 36525_0_961: Reduced from 16 to 13 nodes.
✅ 36530_0_963: Reduced from 8 to 6 nodes.
✅ 36535_0_965: Reduced from 6 to 5 nodes.
✅ 36537_0_966: Reduced from 4 to 3 nodes.
✅ 36538_0_967: Reduced from 12 to 10 nodes.
✅ 36540_0_968: Reduced from 10 to 5 nodes.
✅ 36545_0_969: Reduced from 6 to 4 nodes.
✅ 36547_0_970: Reduced from 8 to 6 nodes.
✅ 36554_0_972: Reduced from 6 to 5 nodes.
✅ 36556_0_973: Reduced from 12 to 11 nodes.
✅ 36557_0_974: Reduced from 12 to 11 nodes.
✅ 36560_0_975: Reduced from 6 to 4 nodes.
✅ 36561_0_976: Reduced from 16 to 12 nodes.
✅ 36564_0_977: Reduced from 11 to 5 nodes.
✅ 36576_0_980: Reduced from 15 to 12 nodes.
✅ 36584_0_981: Reduced from 16 to 12 nodes.
✅ 36606_0_987: Reduced from 6 to 4 nodes.
✅ 36611_0_989: Reduced from 10 to 7 nodes.
✅ 36612_0_990: Reduced from 11 to 10 nodes.
✅ 36613_0_991: Reduced from 16 to 15 nodes.
✅ 36621_0_993: Reduced from 10 to 9 nodes.
✅ 36627_0_994: Reduced from 6 to 5 nodes.
✅ 36630_0_995: Reduced from 6 to 4 nodes.
✅ 36632_0_996: Reduced from 15 to 12 nodes.
✅ 36638_0_997: Reduced from 6 to 4 nodes.
✅ 36641_0_998: Reduced from 11 to 6 nodes.
✅ 36645_0_1001: Reduced from 12 to 9 nodes.
✅ 36646_0_1002: Reduced from 10 to 6 nodes.
✅ 36653_0_1005: Reduced from 6 to 4 nodes.
✅ 36655_0_1006: Reduced from 10 to 8 nodes.
✅ 36656_0_1007: Reduced from 8 to 7 nodes.
✅ 36672_0_1013: Reduced from 6 to 5 nodes.
✅ 36676_0_1015: Reduced from 11 to 5 nodes.
✅ 36680_0_1016: Reduced from 10 to 9 nodes.
✅ 36686_0_1018: Reduced from 6 to 5 nodes.
✅ 36696_0_1022: Reduced from 16 to 10 nodes.
✅ 36697_0_1023: Reduced from 6 to 4 nodes.
✅ 36702_0_1024: Reduced from 10 to 6 nodes.
✅ 36703_0_1025: Reduced from 5 to 4 nodes.
✅ 36704_0_1026: Reduced from 15 to 11 nodes.
✅ 36714_0_1028: Reduced from 9 to 8 nodes.
✅ 36716_0_1029: Reduced from 6 to 4 nodes.
✅ 36720_0_1031: Reduced from 10 to 8 nodes.
✅ 36723_0_1033: Reduced from 11 to 8 nodes.
✅ 36734_0_1037: Reduced from 6 to 5 nodes.
✅ 36738_0_1038: Reduced from 15 to 8 nodes.
✅ 36739_0_1039: Reduced from 6 to 4 nodes.
✅ 36740_0_1040: Reduced from 9 to 7 nodes.
✅ 36743_0_1042: Reduced from 9 to 7 nodes.
✅ 36749_0_1043: Reduced from 8 to 6 nodes.
✅ 36750_0_1044: Reduced from 7 to 6 nodes.
✅ 36754_0_1046: Reduced from 11 to 9 nodes.
✅ 36760_0_1047: Reduced from 9 to 7 nodes.
✅ 36766_0_1048: Reduced from 14 to 12 nodes.
✅ 36768_0_1049: Reduced from 8 to 7 nodes.
✅ 36771_0_1050: Reduced from 14 to 12 nodes.
✅ 36772_0_1051: Reduced from 11 to 8 nodes.
✅ 36779_0_1054: Reduced from 13 to 10 nodes.
✅ 36782_0_1055: Reduced from 7 to 5 nodes.
✅ 36784_0_1057: Reduced from 11 to 8 nodes.
✅ 36787_0_1058: Reduced from 11 to 5 nodes.
✅ 36792_0_1059: Reduced from 7 to 6 nodes.
✅ 36795_0_1060: Reduced from 10 to 8 nodes.
✅ 36803_0_1061: Reduced from 12 to 11 nodes.
✅ 36804_0_1062: Reduced from 14 to 11 nodes.
✅ 36807_0_1063: Reduced from 12 to 10 nodes.
✅ 36809_0_1064: Reduced from 10 to 7 nodes.
✅ 36811_0_1065: Reduced from 6 to 4 nodes.
✅ 36812_0_1066: Reduced from 10 to 9 nodes.
✅ 36814_0_1068: Reduced from 8 to 6 nodes.
✅ 36815_0_1069: Reduced from 11 to 10 nodes.
✅ 36821_0_1070: Reduced from 8 to 6 nodes.
✅ 36824_0_1071: Reduced from 13 to 9 nodes.
✅ 36830_0_1073: Reduced from 8 to 7 nodes.
✅ 36837_0_1074: Reduced from 8 to 6 nodes.
✅ 36838_0_1075: Reduced from 9 to 7 nodes.
✅ 36842_0_1078: Reduced from 9 to 6 nodes.
✅ 36849_0_1080: Reduced from 10 to 7 nodes.
✅ 36854_0_1083: Reduced from 10 to 7 nodes.
✅ 36858_0_1084: Reduced from 6 to 4 nodes.
✅ 36869_0_1085: Reduced from 12 to 7 nodes.
✅ 36879_0_1088: Reduced from 12 to 7 nodes.
✅ 36881_0_1090: Reduced from 12 to 7 nodes.
✅ 36889_0_1092: Reduced from 10 to 9 nodes.
✅ 36897_0_1093: Reduced from 16 to 12 nodes.
✅ 36904_0_1095: Reduced from 6 to 4 nodes.
✅ 36913_0_1096: Reduced from 9 to 5 nodes.
✅ 36914_0_1097: Reduced from 8 to 6 nodes.
✅ 36919_0_1098: Reduced from 5 to 4 nodes.
✅ 36927_0_1099: Reduced from 6 to 4 nodes.

In [10]:
import pandas as pd
import copy
import logging

# Helper to turn the node tree into a string for the CSV
def dsl_to_string(node):
    if node is None:
        return ""
    # This assumes your DSL nodes have a __repr__ or __str__ 
    # If not, we can use: str(type(node).__name__)
    return str(node)

stats_list = []

for shape_id, data in shapes_l0.items():
    try:
        original_dsl = data.get("dsl")
        if original_dsl is None:
            logger.warning(f"SKIP: {shape_id} - No DSL found.")
            continue

        # 1. Run Optimization
        # We keep a copy of the original for the 'before' string
        original_copy = copy.deepcopy(original_dsl)
        optimized = optimizer.run(copy.deepcopy(original_dsl))
        
        # 2. Extract Metrics
        orig_count = len(optimizer.flatten_unions(original_copy))
        opt_count = len(optimizer.flatten_unions(optimized))
        reduction = orig_count - opt_count
        
        # 3. Logging (No emojis)
        logger.info(f"Shape: {shape_id} | Reduction: {reduction}")
        
        # 4. Append to list for DataFrame
        stats_list.append({
            "shape_id": shape_id,
            "status": "SUCCESS",
            "original_count": orig_count,
            "optimized_count": opt_count,
            "reduction": reduction,
            "original_dsl": dsl_to_string(original_copy),
            "optimized_dsl": dsl_to_string(optimized)
        })
            
    except Exception as e:
        logger.error(f"FAILURE: {shape_id} - {str(e)}")
        stats_list.append({
            "shape_id": shape_id,
            "status": f"ERROR: {str(e)}",
            "original_count": None,
            "optimized_count": None,
            "reduction": None,
            "original_dsl": None,
            "optimized_dsl": None
        })

# --- Pandas Processing ---
df = pd.DataFrame(stats_list)

# Calculate percentage
df['reduction_pct'] = (df['reduction'] / df['original_count'] * 100).round(2).fillna(0)

# Reorder columns for better readability in CSV
# column_order = [
#     "shape_id", "status", "original_count", "optimized_count", 
#     "reduction", "reduction_pct", "original_dsl", "optimized_dsl"
# ]
# df = df[column_order]

# Save to CSV
# df.to_csv("shape_optimization_report.csv", index=False)

logger.info("CSV Report generated with 'original_dsl' and 'optimized_dsl' columns.")

INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 172_0_0 | Reduction: 5
INFO: Shape: 173_0_1 | Reduction: 2
INFO: Shape: 178_0_2 | Reduction: 0
INFO: Shape: 180_0_3 | Reduction: 0
INFO: Shape: 182_0_4 | Reduction: 1
INFO: Shape: 186_0_5 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AY)
INFO: Shape: 187_0_6 | Reduction: 7
INFO: Shape: 197_0_7 | Reduction: 2
INFO: Shape: 257_0_8 | Reduction: 0
INFO: Shape: 272_0_9 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 278_0_10 | Reduction: 5
INFO: Shape: 280_0_11 | Reduction: 1
INFO: Shape: 285_0_12 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 286_0_13 | Reduction: 4
INFO: Shape: 308_0_14 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 314_0_15 | Reduction: 5
INFO: Shape: 315_0_16 | Reduction: 2
INFO: Shape: 328_0_17 | Reduction: 2
INFO: Shape: 331_0_18 | Reduction: 0
INFO: Shape: 340_0_19 | Reduction: 1
INFO: Shape: 341_0_20 | Reduction: 1
INFO: Shape: 347_0_21 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 349_0_22 | Reduction: 3
INFO: Shape: 456_0_23 | Reduction: 2
INFO: Shape: 470_0_24 | Reduction: 1
INFO: Shape: 497_0_25 | Reduction: 0
INFO: Shape: 499_0_26 | Reduction: 0
INFO: Shape: 515_0_27 | Reduction: 1
INFO: Shape: 516_0_28 | Reduction: 0
INFO: Shape: 518_0_29 | Reduction: 1
INFO: Shape: 523_0_30 | Reduction: 2
INFO: Shape: 526_0_31 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 539_0_32 | Reduction: 5
INFO: Shape: 543_0_33 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 545_0_34 | Reduction: 5
INFO: Shape: 547_0_35 | Reduction: 3
INFO: Shape: 550_0_36 | Reduction: 2
INFO: Shape: 552_0_37 | Reduction: 0
INFO: Rule: SymTrans detected (9 parts, axis AX)
INFO: Shape: 554_0_38 | Reduction: 8
INFO: Shape: 555_0_39 | Reduction: 1
INFO: Shape: 557_0_40 | Reduction: 1
INFO: Shape: 561_0_41 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 574_0_42 | Reduction: 6
INFO: Shape: 671_0_43 | Reduction: 2
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 682_0_44 | Reduction: 6
INFO: Shape: 686_0_45 | Reduction: 0
INFO: Shape: 698_0_46 | Reduction: 4
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 699_0_47 | Reduction: 5
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 701_0_48 | Reduction: 6
INFO: Shape: 716_0_49 | Reduction: 0
INFO: Shape: 724_0_50 | Reduction: 2
INFO: Shape: 725_0_51 | Reduction: 3
INFO: Shape: 732_0_52 | Reduction: 2
INFO: Shape: 737_0_53 | Reduction: 1
INFO: Shape: 739_0_54 | Reduction: 1
INFO: Shape: 740_0_55 | Reduction: 0
INFO: Shape: 746_0_56 | Reduction: 2
INFO: Shape: 748_0_57 | Reduction: 1
INFO: Shape: 750_0_58 | Reduction: 2
INFO: Shape: 752_0_59 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 754_0_60 | Reduction: 7
INFO: Shape: 756_0_61 | Reduction: 3
INFO: Shape: 760_0_62 | Reduction: 4
INFO: Shape: 763_0_63 | Reduction: 2
INFO: Shape: 768_0_64 | Reduction: 0
INFO: Shape: 772_0_65 | Reduction: 2
INFO: Rule: SymTrans detected (8 parts, axis AY)
INFO: Shape: 776_0_66 | Reduction: 7
INFO: Shape: 1277_0_67 | Reduction: 0
INFO: Shape: 1282_0_68 | Reduction: 2
INFO: Shape: 1287_0_69 | Reduction: 1
INFO: Shape: 1293_0_70 | Reduction: 3
INFO: Shape: 1295_0_71 | Reduction: 2
INFO: Shape: 1297_0_72 | Reduction: 0
INFO: Shape: 1299_0_73 | Reduction: 1
INFO: Shape: 1301_0_74 | Reduction: 2
INFO: Shape: 1305_0_75 | Reduction: 0
INFO: Shape: 1309_0_76 | Reduction: 0
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 1314_0_77 | Reduction: 5
INFO: Shape: 1316_0_78 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AY)
INFO: Shape: 1319_0_79 | Reduction: 4
INFO: Shape: 1329_0_80 | Reduction: 0
INFO: Shape: 1331_0_81 | Reduction: 3
INFO: Shape: 1333_0_82 | Reduction: 1
INFO: Shape: 1351_0_83 | Reduction: 0
INFO: Shape: 1355_0_84 | Reduction: 2
INFO: Shape: 1359_0_85 | Reduction: 2
INFO: Shape: 1366_0_86 | Reduction: 0
INFO: Shape: 1368_0_87 | Reduction: 4
INFO: Shape: 1373_0_88 | Reduction: 0
INFO: Shape: 1374_0_89 | Reduction: 2
INFO: Shape: 1377_0_90 | Reduction: 2
INFO: Shape: 1378_0_91 | Reduction: 0
INFO: Shape: 1382_0_92 | Reduction: 2
INFO: Shape: 1398_0_93 | Reduction: 0
INFO: Shape: 1400_0_94 | Reduction: 1
INFO: Shape: 1403_0_95 | Reduction: 1
INFO: Shape: 1409_0_96 | Reduction: 2
INFO: Shape: 1425_0_97 | Reduction: 1
INFO: Shape: 1438_0_98 | Reduction: 0
INFO: Shape: 1439_0_99 | Reduction: 0
INFO: Shape: 1441_0_100 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 1463_0_101 | Reduction: 3
INFO: Shape: 1472_0_102 | Reduction: 1
INFO: Shape: 1473_0_103 | Reduction: 0
INFO: Shape: 1746_0_104 | Reduction: 0
INFO: Shape: 1762_0_105 | Reduction: 0
INFO: Shape: 2121_0_106 | Reduction: 3
INFO: Shape: 2132_0_107 | Reduction: 1
INFO: Shape: 2136_0_108 | Reduction: 2
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 2184_0_109 | Reduction: 5
INFO: Shape: 2194_0_110 | Reduction: 1
INFO: Shape: 2198_0_111 | Reduction: 2
INFO: Shape: 2203_0_112 | Reduction: 3
INFO: Shape: 2214_0_113 | Reduction: 4
INFO: Shape: 2217_0_114 | Reduction: 2
INFO: Shape: 2220_0_115 | Reduction: 0
INFO: Shape: 2221_0_116 | Reduction: 1
INFO: Shape: 2223_0_117 | Reduction: 4
INFO: Shape: 2225_0_118 | Reduction: 1
INFO: Shape: 2227_0_119 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2233_0_120 | Reduction: 4
INFO: Shape: 2234_0_121 | Reduction: 1
INFO: Shape: 2235_0_122 | Reduction: 0
INFO: Shape: 2236_0_123 | Reduction: 2
INFO: Shape: 2239_0_124 | Reduction: 5
INFO: Shape: 2240_0_125 | Reduction: 3
INFO: Shape: 2241_0_126 | Reduction: 2
INFO: Shape: 2242_0_127 | Reduction: 0
INFO: Shape: 2248_0_128 | Reduction: 1
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2249_0_129 | Reduction: 6
INFO: Shape: 2252_0_130 | Reduction: 4
INFO: Shape: 2253_0_131 | Reduction: 1
INFO: Shape: 2255_0_132 | Reduction: 2
INFO: Shape: 2260_0_133 | Reduction: 0
INFO: Shape: 2261_0_134 | Reduction: 0
INFO: Shape: 2262_0_135 | Reduction: 2
INFO: Shape: 2263_0_136 | Reduction: 3
INFO: Shape: 2266_0_137 | Reduction: 2
INFO: Shape: 2269_0_138 | Reduction: 2
INFO: Shape: 2270_0_139 | Reduction: 1
INFO: Shape: 2271_0_140 | Reduction: 1
INFO: Shape: 2276_0_141 | Reduction: 3
INFO: Shape: 2277_0_142 | Reduction: 1
INFO: Shape: 2280_0_143 | Reduction: 0
INFO: Shape: 2281_0_144 | Reduction: 3
INFO: Shape: 2283_0_145 | Reduction: 3
INFO: Shape: 2286_0_146 | Reduction: 0
INFO: Shape: 2287_0_147 | Reduction: 3
INFO: Shape: 2291_0_148 | Reduction: 1
INFO: Shape: 2293_0_149 | Reduction: 1
INFO: Shape: 2294_0_150 | Reduction: 2
INFO: Shape: 2295_0_151 | Reduction: 2
INFO: Shape: 2296_0_152 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2302_0_153 | Reduction: 4
INFO: Shape: 2304_0_154 | Reduction: 3
INFO: Shape: 2306_0_155 | Reduction: 3
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Shape: 2307_0_156 | Reduction: 8
INFO: Shape: 2308_0_157 | Reduction: 0
INFO: Shape: 2309_0_158 | Reduction: 2
INFO: Shape: 2311_0_159 | Reduction: 0
INFO: Shape: 2312_0_160 | Reduction: 0
INFO: Shape: 2315_0_161 | Reduction: 4
INFO: Shape: 2316_0_162 | Reduction: 1
INFO: Shape: 2318_0_163 | Reduction: 1
INFO: Shape: 2319_0_164 | Reduction: 0
INFO: Shape: 2323_0_165 | Reduction: 0
INFO: Shape: 2325_0_166 | Reduction: 0
INFO: Shape: 2328_0_167 | Reduction: 3
INFO: Shape: 2330_0_168 | Reduction: 2
INFO: Shape: 2332_0_169 | Reduction: 1
INFO: Shape: 2333_0_170 | Reduction: 1
INFO: Shape: 2334_0_171 | Reduction: 1
INFO: Shape: 2335_0_172 | Reduction: 0
INFO: Shape: 2338_0_173 | Reduction: 0
INFO: Shape: 2341_0_174 | Reduction: 2
INFO: Shape: 2342_0_175 | Reduction: 1
INFO: Shape: 2343_0_176 | Reduction: 0
INFO: Shape: 2344_0_177 | Reduction: 2
INFO: Shape: 2345_0_178 | Reduction: 2
INFO: Shape: 2346_0_179 | Reduction: 5
INFO: Shape: 2350_0_180 | Reduction: 2
INFO: Shape: 2351_0_181 | Reduction: 2
INFO: Shape: 2352_0_182 | Reduction: 1
INFO: Shape: 2354_0_183 | Reduction: 2
INFO: Shape: 2355_0_184 | Reduction: 1
INFO: Shape: 2359_0_185 | Reduction: 0
INFO: Shape: 2360_0_186 | Reduction: 1
INFO: Shape: 2365_0_187 | Reduction: 3
INFO: Shape: 2366_0_188 | Reduction: 0
INFO: Shape: 2369_0_189 | Reduction: 2
INFO: Shape: 2370_0_190 | Reduction: 2
INFO: Shape: 2371_0_191 | Reduction: 3
INFO: Shape: 2373_0_192 | Reduction: 4
INFO: Shape: 2374_0_193 | Reduction: 1
INFO: Shape: 2376_0_194 | Reduction: 3
INFO: Shape: 2377_0_195 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2379_0_196 | Reduction: 3
INFO: Shape: 2382_0_197 | Reduction: 2
INFO: Shape: 2383_0_198 | Reduction: 0
INFO: Shape: 2384_0_199 | Reduction: 4
INFO: Shape: 2391_0_200 | Reduction: 0
INFO: Shape: 2392_0_201 | Reduction: 0
INFO: Shape: 2396_0_202 | Reduction: 1
INFO: Shape: 2397_0_203 | Reduction: 0
INFO: Shape: 2399_0_204 | Reduction: 2
INFO: Shape: 2400_0_205 | Reduction: 0
INFO: Shape: 2405_0_206 | Reduction: 0
INFO: Shape: 2406_0_207 | Reduction: 1
INFO: Shape: 2408_0_208 | Reduction: 0
INFO: Shape: 2410_0_209 | Reduction: 3
INFO: Shape: 2412_0_210 | Reduction: 2
INFO: Shape: 2416_0_211 | Reduction: 1
INFO: Shape: 2420_0_212 | Reduction: 0
INFO: Shape: 2422_0_213 | Reduction: 0
INFO: Shape: 2423_0_214 | Reduction: 2
INFO: Shape: 2424_0_215 | Reduction: 2
INFO: Shape: 2429_0_216 | Reduction: 2
INFO: Shape: 2430_0_217 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2434_0_218 | Reduction: 4
INFO: Shape: 2435_0_219 | Reduction: 1
INFO: Shape: 2436_0_220 | Reduction: 1
INFO: Shape: 2437_0_221 | Reduction: 5
INFO: Shape: 2439_0_222 | Reduction: 2
INFO: Shape: 2441_0_223 | Reduction: 0
INFO: Shape: 2444_0_224 | Reduction: 0
INFO: Shape: 2446_0_225 | Reduction: 2
INFO: Shape: 2447_0_226 | Reduction: 3
INFO: Shape: 2448_0_227 | Reduction: 4
INFO: Shape: 2449_0_228 | Reduction: 1
INFO: Shape: 2454_0_229 | Reduction: 2
INFO: Shape: 2457_0_230 | Reduction: 1
INFO: Shape: 2458_0_231 | Reduction: 3
INFO: Shape: 2460_0_232 | Reduction: 0
INFO: Shape: 2461_0_233 | Reduction: 0
INFO: Shape: 2464_0_234 | Reduction: 1
INFO: Shape: 2466_0_235 | Reduction: 2
INFO: Shape: 2467_0_236 | Reduction: 0
INFO: Shape: 2470_0_237 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2472_0_238 | Reduction: 2
INFO: Shape: 2476_0_239 | Reduction: 1
INFO: Shape: 2478_0_240 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2479_0_241 | Reduction: 3
INFO: Shape: 2481_0_242 | Reduction: 0
INFO: Shape: 2483_0_243 | Reduction: 1
INFO: Shape: 2489_0_244 | Reduction: 0
INFO: Shape: 2491_0_245 | Reduction: 0
INFO: Shape: 2493_0_246 | Reduction: 1
INFO: Shape: 2494_0_247 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2495_0_248 | Reduction: 6
INFO: Shape: 2497_0_249 | Reduction: 4
INFO: Shape: 2498_0_250 | Reduction: 0
INFO: Shape: 2502_0_251 | Reduction: 1
INFO: Shape: 2503_0_252 | Reduction: 2
INFO: Shape: 2505_0_253 | Reduction: 2
INFO: Shape: 2506_0_254 | Reduction: 2
INFO: Shape: 2508_0_255 | Reduction: 1
INFO: Shape: 2510_0_256 | Reduction: 0
INFO: Shape: 2511_0_257 | Reduction: 2
INFO: Shape: 2513_0_258 | Reduction: 0
INFO: Shape: 2516_0_259 | Reduction: 1
INFO: Shape: 2522_0_260 | Reduction: 0
INFO: Shape: 2523_0_261 | Reduction: 0
INFO: Shape: 2524_0_262 | Reduction: 1
INFO: Shape: 2529_0_263 | Reduction: 1
INFO: Shape: 2533_0_264 | Reduction: 0
INFO: Shape: 2534_0_265 | Reduction: 0
INFO: Shape: 2535_0_266 | Reduction: 1
INFO: Shape: 2539_0_267 | Reduction: 2
INFO: Shape: 2540_0_268 | Reduction: 0
INFO: Shape: 2542_0_269 | Reduction: 2
INFO: Shape: 2544_0_270 | Reduction: 1
INFO: Shape: 2545_0_271 | Reduction: 2
INFO: Shape: 2546_0_272 | Reduction: 1
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Shape: 2558_0_273 | Reduction: 6
INFO: Shape: 2562_0_274 | Reduction: 1
INFO: Shape: 2565_0_275 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2567_0_276 | Reduction: 4
INFO: Shape: 2569_0_277 | Reduction: 0
INFO: Shape: 2570_0_278 | Reduction: 2
INFO: Shape: 2571_0_279 | Reduction: 0
INFO: Shape: 2574_0_280 | Reduction: 2
INFO: Shape: 2575_0_281 | Reduction: 0
INFO: Shape: 2577_0_282 | Reduction: 1
INFO: Shape: 2578_0_283 | Reduction: 0
INFO: Shape: 2582_0_284 | Reduction: 2
INFO: Shape: 2584_0_285 | Reduction: 1
INFO: Shape: 2585_0_286 | Reduction: 2
INFO: Shape: 2586_0_287 | Reduction: 1
INFO: Shape: 2587_0_288 | Reduction: 0
INFO: Shape: 2588_0_289 | Reduction: 0
INFO: Shape: 2590_0_290 | Reduction: 0
INFO: Shape: 2592_0_291 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2593_0_292 | Reduction: 3
INFO: Shape: 2597_0_293 | Reduction: 0
INFO: Shape: 2598_0_294 | Reduction: 2
INFO: Shape: 2599_0_295 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2602_0_296 | Reduction: 3
INFO: Shape: 2605_0_297 | Reduction: 5
INFO: Shape: 2607_0_298 | Reduction: 3
INFO: Shape: 2611_0_299 | Reduction: 4
INFO: Shape: 2612_0_300 | Reduction: 2
INFO: Shape: 2614_0_301 | Reduction: 3
INFO: Shape: 2620_0_302 | Reduction: 1
INFO: Shape: 2623_0_303 | Reduction: 3
INFO: Shape: 2624_0_304 | Reduction: 0
INFO: Shape: 2626_0_305 | Reduction: 0
INFO: Shape: 2631_0_306 | Reduction: 2
INFO: Shape: 2636_0_307 | Reduction: 1
INFO: Shape: 2637_0_308 | Reduction: 2
INFO: Shape: 2641_0_309 | Reduction: 0
INFO: Shape: 2645_0_310 | Reduction: 1
INFO: Shape: 2647_0_311 | Reduction: 2
INFO: Shape: 2648_0_312 | Reduction: 2
INFO: Shape: 2650_0_313 | Reduction: 1
INFO: Shape: 2653_0_314 | Reduction: 5
INFO: Shape: 2655_0_315 | Reduction: 1
INFO: Shape: 2656_0_316 | Reduction: 2
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2663_0_317 | Reduction: 4
INFO: Shape: 2665_0_318 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2666_0_319 | Reduction: 3
INFO: Shape: 2673_0_320 | Reduction: 4
INFO: Shape: 2676_0_321 | Reduction: 0
INFO: Shape: 2680_0_322 | Reduction: 0
INFO: Shape: 2681_0_323 | Reduction: 2
INFO: Rule: SymTrans detected (3 parts, axis AY)
INFO: Shape: 2684_0_324 | Reduction: 3
INFO: Shape: 2687_0_325 | Reduction: 1
INFO: Shape: 2688_0_326 | Reduction: 0
INFO: Shape: 2691_0_327 | Reduction: 2
INFO: Shape: 2692_0_328 | Reduction: 2
INFO: Shape: 2694_0_329 | Reduction: 3
INFO: Shape: 2700_0_330 | Reduction: 1
INFO: Shape: 2701_0_331 | Reduction: 0
INFO: Shape: 2704_0_332 | Reduction: 0
INFO: Shape: 2707_0_333 | Reduction: 1
INFO: Shape: 2709_0_334 | Reduction: 0
INFO: Shape: 2710_0_335 | Reduction: 1
INFO: Shape: 2711_0_336 | Reduction: 1
INFO: Shape: 2712_0_337 | Reduction: 4
INFO: Shape: 2713_0_338 | Reduction: 0
INFO: Shape: 2723_0_339 | Reduction: 2
INFO: Shape: 2728_0_340 | Reduction: 3
INFO: Shape: 2731_0_341 | Reduction: 4
INFO: Shape: 2737_0_342 | Reduction: 0
INFO: Shape: 2741_0_343 | Reduction: 1
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2746_0_344 | Reduction: 6
INFO: Shape: 2750_0_345 | Reduction: 2
INFO: Shape: 2752_0_346 | Reduction: 1
INFO: Shape: 2753_0_347 | Reduction: 0
INFO: Shape: 2755_0_348 | Reduction: 3
INFO: Shape: 2757_0_349 | Reduction: 0
INFO: Shape: 2759_0_350 | Reduction: 3
INFO: Shape: 2764_0_351 | Reduction: 3
INFO: Shape: 2769_0_352 | Reduction: 3
INFO: Shape: 2770_0_353 | Reduction: 2
INFO: Shape: 2772_0_354 | Reduction: 1
INFO: Shape: 2773_0_355 | Reduction: 1
INFO: Shape: 2774_0_356 | Reduction: 4
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2775_0_357 | Reduction: 3
INFO: Shape: 2784_0_358 | Reduction: 0
INFO: Shape: 2785_0_359 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2786_0_360 | Reduction: 5
INFO: Rule: SymTrans detected (6 parts, axis AX)
INFO: Shape: 2788_0_361 | Reduction: 5
INFO: Shape: 2789_0_362 | Reduction: 3
INFO: Shape: 2790_0_363 | Reduction: 2
INFO: Shape: 2796_0_364 | Reduction: 0
INFO: Shape: 2797_0_365 | Reduction: 1
INFO: Shape: 2799_0_366 | Reduction: 1
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2802_0_367 | Reduction: 5
INFO: Shape: 2803_0_368 | Reduction: 1
INFO: Shape: 2804_0_369 | Reduction: 2
INFO: Shape: 2807_0_370 | Reduction: 0
INFO: Shape: 2810_0_371 | Reduction: 4
INFO: Shape: 2811_0_372 | Reduction: 0
INFO: Shape: 2812_0_373 | Reduction: 0
INFO: Shape: 2815_0_374 | Reduction: 1
INFO: Shape: 2817_0_375 | Reduction: 1
INFO: Shape: 2820_0_376 | Reduction: 2
INFO: Shape: 2827_0_377 | Reduction: 1
INFO: Shape: 2828_0_378 | Reduction: 2
INFO: Shape: 2830_0_379 | Reduction: 3
INFO: Shape: 2832_0_380 | Reduction: 3
INFO: Rule: SymTrans detected (5 parts, axis AX)
INFO: Shape: 2834_0_381 | Reduction: 4
INFO: Shape: 2841_0_382 | Reduction: 0
INFO: Shape: 2847_0_383 | Reduction: 3
INFO: Shape: 2850_0_384 | Reduction: 0
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2855_0_385 | Reduction: 3
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2864_0_386 | Reduction: 5
INFO: Rule: SymTrans detected (3 parts, axis AX)
INFO: Shape: 2865_0_387 | Reduction: 2
INFO: Shape: 2866_0_388 | Reduction: 0
INFO: Shape: 2867_0_389 | Reduction: 1
INFO: Shape: 2868_0_390 | Reduction: 2
INFO: Shape: 2869_0_391 | Reduction: 3
INFO: Shape: 2871_0_392 | Reduction: 2
INFO: Shape: 2876_0_393 | Reduction: 0
INFO: Shape: 2878_0_394 | Reduction: 2
INFO: Shape: 2880_0_395 | Reduction: 0
INFO: Rule: SymTrans detected (5 parts, axis AY)
INFO: Shape: 2882_0_396 | Reduction: 5
INFO: Shape: 2885_0_397 | Reduction: 2
INFO: Shape: 2886_0_398 | Reduction: 1
INFO: Shape: 2893_0_399 | Reduction: 1
INFO: Shape: 2896_0_400 | Reduction: 1
INFO: Shape: 2898_0_401 | Reduction: 2
INFO: Shape: 2900_0_402 | Reduction: 1
INFO: Shape: 2903_0_403 | Reduction: 2
INFO: Shape: 2904_0_404 | Reduction: 1
INFO: Shape: 2906_0_405 | Reduction: 4
INFO: Shape: 2908_0_406 | Reduction: 2
INFO: Shape: 2909_0_407 | Reduction: 0
INFO: Shape: 2913_0_408 | Reduction: 5
INFO: Shape: 2916_0_409 | Reduction: 0
INFO: Shape: 2917_0_410 | Reduction: 0
INFO: Shape: 2930_0_411 | Reduction: 2
INFO: Shape: 2940_0_412 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2943_0_413 | Reduction: 5
INFO: Shape: 2946_0_414 | Reduction: 1
INFO: Shape: 2947_0_415 | Reduction: 1
INFO: Shape: 2948_0_416 | Reduction: 2
INFO: Rule: SymTrans detected (7 parts, axis AX)
INFO: Shape: 2950_0_417 | Reduction: 6
INFO: Shape: 2951_0_418 | Reduction: 0
INFO: Shape: 2955_0_419 | Reduction: 0
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2956_0_420 | Reduction: 3
INFO: Shape: 2957_0_421 | Reduction: 2
INFO: Shape: 2958_0_422 | Reduction: 0
INFO: Shape: 2959_0_423 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 2960_0_424 | Reduction: 5
INFO: Shape: 2962_0_425 | Reduction: 2
INFO: Shape: 2969_0_426 | Reduction: 0
INFO: Shape: 2972_0_427 | Reduction: 0
INFO: Shape: 2975_0_428 | Reduction: 2
INFO: Shape: 2980_0_429 | Reduction: 4
INFO: Shape: 2981_0_430 | Reduction: 0
INFO: Shape: 2989_0_431 | Reduction: 0
INFO: Shape: 2993_0_432 | Reduction: 1
INFO: Shape: 2995_0_433 | Reduction: 0
INFO: Shape: 3003_0_434 | Reduction: 0
INFO: Shape: 3004_0_435 | Reduction: 0
INFO: Shape: 3005_0_436 | Reduction: 2
INFO: Shape: 3006_0_437 | Reduction: 1
INFO: Shape: 3007_0_438 | Reduction: 1
INFO: Shape: 3009_0_439 | Reduction: 4
INFO: Shape: 3013_0_440 | Reduction: 3
INFO: Shape: 3015_0_441 | Reduction: 3
INFO: Shape: 3024_0_442 | Reduction: 0
INFO: Shape: 3026_0_443 | Reduction: 2
INFO: Shape: 3029_0_444 | Reduction: 0
INFO: Shape: 3032_0_445 | Reduction: 2
INFO: Shape: 3033_0_446 | Reduction: 3
INFO: Shape: 3035_0_447 | Reduction: 1
INFO: Shape: 3037_0_448 | Reduction: 2
INFO: Shape: 3043_0_449 | Reduction: 4
INFO: Shape: 3045_0_450 | Reduction: 2
INFO: Rule: SymTrans detected (4 parts, axis AX)
INFO: Shape: 3051_0_451 | Reduction: 3

In [11]:
from abstractionsshapecoder.dsl_utils import collect_singleton_and_pair_data
from abstractionsshapecoder.debug_utils import debug_info, debug_success

# 1. Isolate the DSL objects from the dictionary
all_l0_dsl_trees = [data['dsl'] for data in shapes_l0.values()]

debug_info(f"Extracting parameters from {len(all_l0_dsl_trees)} L0 shapes...")

# 2. Run the collection utility
# s_data_l0: { 'NodeName': [ [params], [params], ... ] }
# p_data_l0: { 'Parent(Child)': [ [params], [params], ... ] }
s_data_l0, p_data_l0 = collect_singleton_and_pair_data(all_l0_dsl_trees)

debug_success(f"Extraction complete.")
debug_info(f"Unique Singletons found: {len(s_data_l0)}")
debug_info(f"Unique Parent-Child Pairs found: {len(p_data_l0)}")

[INFO] Extracting parameters from 1100 L0 shapes...
[SUCCESS] Extraction complete.
[INFO] Unique Singletons found: 3
[INFO] Unique Parent-Child Pairs found: 5

In [12]:
import pandas as pd

# Create a summary for Singletons
singleton_summary = []
for node_type, param_list in s_data_l0.items():
    singleton_summary.append({
        "Node Type": node_type,
        "Total Occurrences": len(param_list),
        "Param Dimension": len(param_list[0]) if param_list else 0,
        "Example Params": param_list[0] if param_list else []
    })

# Create a summary for Pairs
pair_summary = []
for pair_name, param_list in p_data_l0.items():
    pair_summary.append({
        "Relationship": pair_name,
        "Total Occurrences": len(param_list),
        "Combined Dimension": len(param_list[0]) if param_list else 0
    })

# Convert to DataFrames for easy viewing
df_singletons = pd.DataFrame(singleton_summary).sort_values("Total Occurrences", ascending=False)
df_pairs = pd.DataFrame(pair_summary).sort_values("Total Occurrences", ascending=False)

print("=== L0 SINGLETON CENSUS ===")
display(df_singletons)

print("\n=== L0 PAIR CENSUS ===")
display(df_pairs)

=== L0 SINGLETON CENSUS ===

,Node Type,Total Occurrences,Param Dimension,Example Params
0,Cuboid,10268,3,"[0.68, 0.09, 0.66]"
2,Translate,10268,3,"[-0.0, -0.17, 0.0]"
1,Rotate,3416,4,"[-0.17410813759359595, 0.0, 0.0, 0.98472653890..."

=== L0 PAIR CENSUS ===

        Relationship  Total Occurrences  Combined Dimension
2  Translate(Cuboid)              10268                   6
4   Union(Translate)               8656                   3
0     Rotate(Rotate)               1804                   8
1  Rotate(Translate)               1612                   7
3      Union(Rotate)               1612                   4

In [13]:
results

{'172_0_0': <abstractionsshapecoder.dsl_nodes.Union at 0x1588f8b26f0>,
 '173_0_1': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615af0>,
 '178_0_2': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd614b90>,
 '180_0_3': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6163c0>,
 '182_0_4': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd614770>,
 '186_0_5': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd617b60>,
 '187_0_6': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd616c00>,
 '197_0_7': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5eb1d0>,
 '257_0_8': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd616180>,
 '272_0_9': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5e9d30>,
 '278_0_10': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5ea840>,
 '280_0_11': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6344d0>,
 '285_0_12': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5eb500>,
 '286_0_13': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd635c40>,
 '308_0_14': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd634a40>,
 '314_0_15': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615d30>,
 '315_0_16': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd636ea0>,
 '328_0_17': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65a4e0>,
 '331_0_18': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658aa0>,
 '340_0_19': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658290>,
 '341_0_20': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658e60>,
 '347_0_21': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658b30>,
 '349_0_22': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65ade0>,
 '456_0_23': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65be60>,
 '470_0_24': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615310>,
 '497_0_25': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd678f80>,
 '499_0_26': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd679d90>,
 '515_0_27': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd679ee0>,
 '516_0_28': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67ad50>,
 '518_0_29': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67bb30>,
 '523_0_30': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67bec0>,
 '526_0_31': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a1460>,
 '539_0_32': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5e90a0>,
 '543_0_33': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a07a0>,
 '545_0_34': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3320>,
 '547_0_35': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3050>,
 '550_0_36': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3fe0>,
 '552_0_37': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8bf0>,
 '554_0_38': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3200>,
 '555_0_39': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca2a0>,
 '557_0_40': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8350>,
 '561_0_41': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca6f0>,
 '574_0_42': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8080>,
 '671_0_43': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbec0>,
 '682_0_44': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca3c0>,
 '686_0_45': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbb00>,
 '698_0_46': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbfb0>,
 '699_0_47': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ec620>,
 '701_0_48': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6eccb0>,
 '716_0_49': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ed220>,
 '724_0_50': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ef0b0>,
 '725_0_51': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6eeb40>,
 '732_0_52': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6efa10>,
 '737_0_53': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70c2c0>,
 '739_0_54': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70cfe0>,
 '740_0_55': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70df70>,
 '746_0_56': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70da00>,
 '748_0_57': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70cda0>,
 '750_0_58': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70f6e0>,
 '752_0_59': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70e240>,
 '754_0_60': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd730b90>,
 '756_0_61': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ee240>,
 '760_0_62': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732330>,
 '763_0_63': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731940>,
 '768_0_64': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732420>,
 '772_0_65': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732360>,
 '776_0_66': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd733500>,
 '1277_0_67': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d490>,
 '1282_0_68': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd733e90>,
 '1287_0_69': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d8b0>,
 '1293_0_70': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d0d0>,
 '1295_0_71': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d100>,
 '1297_0_72': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75dc70>,
 '1299_0_73': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75fb90>,
 '1301_0_74': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75e960>,
 '1305_0_75': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77cec0>,
 '1309_0_76': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75fa70>,
 '1314_0_77': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731400>,
 '1316_0_78': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77ea80>,
 '1319_0_79': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77e3f0>,
 '1329_0_80': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731250>,
 '1331_0_81': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77ffb0>,
 '1333_0_82': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77fad0>,
 '1351_0_83': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77eb70>,
 '1355_0_84': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a0e90>,
 '1359_0_85': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a08f0>,
 '1366_0_86': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a0680>,
 '1368_0_87': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a1eb0>,
 '1373_0_88': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a3170>,
 '1374_0_89': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a3c20>,
 '1377_0_90': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bc740>,
 '1378_0_91': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bd670>,
 '1382_0_92': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bd490>,
 '1398_0_93': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7be7e0>,
 '1400_0_94': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7be3f0>,
 '1403_0_95': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e4c20>,
 '1409_0_96': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bff20>,
 '1425_0_97': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e50a0>,
 '1438_0_98': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e55b0>,
 '1439_0_99': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e70e0>,
 '1441_0_100': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e5fa0>,
 '1463_0_101': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e6540>,
 '1472_0_102': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7590>,
 '1473_0_103': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7620>,
 '1746_0_104': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd808bf0>,
 '1762_0_105': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7dd0>,
 '2121_0_106': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd809550>,
 '2132_0_107': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd808c50>,
 '2136_0_108': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80aea0>,
 '2184_0_109': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80b1a0>,
 '2194_0_110': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80ade0>,
 '2198_0_111': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd4546b0>,
 '2203_0_112': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80b710>,
 '2214_0_113': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82c710>,
 '2217_0_114': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82d3a0>,
 '2220_0_115': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e3c0>,
 '2221_0_116': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e8d0>,
 '2223_0_117': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e5d0>,
 '2225_0_118': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e4b0>,
 '2227_0_119': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82fe60>,
 '2233_0_120': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854950>,
 '2234_0_121': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8550a0>,
 '2235_0_122': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854fb0>,
 '2236_0_123': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8553d0>,
 '2239_0_124': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd856ba0>,
 '2240_0_125': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd857cb0>,
 '2241_0_126': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd857b90>,
 '2242_0_127': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8579e0>,
 '2248_0_128': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8747a0>,
 '2249_0_129': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd855100>,
 '2252_0_130': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd855d30>,
 '2253_0_131': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8760c0>,
 '2255_0_132': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd875f10>,
 '2260_0_133': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8764e0>,
 '2261_0_134': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8773b0>,
 '2262_0_135': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd877b00>,
 '2263_0_136': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd877ce0>,
 '2266_0_137': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a07d0>,
 '2269_0_138': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a1970>,
 '2270_0_139': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2270>,
 '2271_0_140': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a27e0>,
 '2276_0_141': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a1940>,
 '2277_0_142': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2120>,
 '2280_0_143': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2b40>,
 '2281_0_144': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a3e30>,
 '2283_0_145': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a3f20>,
 '2286_0_146': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c0c80>,
 '2287_0_147': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c0f80>,
 '2291_0_148': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2180>,
 '2293_0_149': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2420>,
 '2294_0_150': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2ab0>,
 '2295_0_151': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c38f0>,
 '2296_0_152': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2870>,
 '2302_0_153': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9040>,
 '2304_0_154': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9fa0>,
 '2306_0_155': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9820>,
 '2307_0_156': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9f70>,
 '2308_0_157': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8eb650>,
 '2309_0_158': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8ebfe0>,
 '2311_0_159': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ca40>,
 '2312_0_160': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ccb0>,
 '2315_0_161': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e900>,
 '2316_0_162': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e960>,
 '2318_0_163': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90fb30>,
 '2319_0_164': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e990>,
 '2323_0_165': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ef90>,
 '2325_0_166': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd930ad0>,
 '2328_0_167': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9312e0>,
 '2330_0_168': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd931580>,
 '2332_0_169': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932420>,
 '2333_0_170': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932540>,
 '2334_0_171': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932780>,
 '2335_0_172': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd933bf0>,
 '2338_0_173': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932bd0>,
 '2341_0_174': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932db0>,
 '2342_0_175': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd959550>,
 '2343_0_176': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd959e80>,
 '2344_0_177': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9586e0>,
 '2345_0_178': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9597f0>,
 '2346_0_179': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd95b950>,
 '2350_0_180': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd95bc20>,
 '2351_0_181': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd974560>,
 '2352_0_182': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9749e0>,
 '2354_0_183': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9748f0>,
 '2355_0_184': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd975910>,
 '2359_0_185': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd975310>,
 '2360_0_186': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9771d0>,
 '2365_0_187': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977b30>,
 '2366_0_188': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd976150>,
 '2369_0_189': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977f80>,
 '2370_0_190': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977fb0>,
 '2371_0_191': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd976de0>,
 '2373_0_192': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99cb60>,
 '2374_0_193': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854e00>,
 '2376_0_194': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99e390>,
 '2377_0_195': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99ef30>,
 '2379_0_196': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99e8a0>,
 '2382_0_197': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8ebcb0>,
 '2383_0_198': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bc950>,
 '2384_0_199': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bce60>,
 '2391_0_200': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9be0c0>,
 '2392_0_201': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bd6a0>,
 '2396_0_202': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9beab0>,
 '2397_0_203': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bddf0>,
 '2399_0_204': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bf3b0>,
 '2400_0_205': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bfce0>,
 '2405_0_206': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bfd10>,
 '2406_0_207': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e4380>,
 '2408_0_208': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e4b90>,
 '2410_0_209': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e45f0>,
 '2412_0_210': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e5460>,
 '2416_0_211': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e6600>,
 '2420_0_212': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e72f0>,
 '2422_0_213': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e79e0>,
 '2423_0_214': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda04260>,
 '2424_0_215': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda04da0>,
 '2429_0_216': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda06810>,
 '2430_0_217': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda06990>,
 '2434_0_218': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda079b0>,
 '2435_0_219': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2c8f0>,
 '2436_0_220': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2ca70>,
 '2437_0_221': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2c530>,
 '2439_0_222': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2cd40>,
 '2441_0_223': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2df70>,
 '2444_0_224': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2f410>,
 '2446_0_225': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2fa40>,
 '2447_0_226': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda50f50>,
 '2448_0_227': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda51490>,
 '2449_0_228': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda50500>,
 '2454_0_229': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda51eb0>,
 '2457_0_230': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda52de0>,
 '2458_0_231': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda52600>,
 '2460_0_232': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda53320>,
 '2461_0_233': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78c50>,
 '2464_0_234': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78920>,
 '2466_0_235': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78410>,
 '2467_0_236': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda79af0>,
 '2470_0_237': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7a630>,
 '2472_0_238': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7abd0>,
 '2476_0_239': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7ad80>,
 '2478_0_240': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7bd40>,
 '2479_0_241': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9cad0>,
 '2481_0_242': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d8b0>,
 '2483_0_243': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d070>,
 '2489_0_244': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9e8a0>,
 '2491_0_245': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9e9f0>,
 '2493_0_246': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9fa70>,
 '2494_0_247': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9ea20>,
 '2495_0_248': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9f710>,
 '2497_0_249': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabcfb0>,
 '2498_0_250': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabd5e0>,
 '2502_0_251': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe2d0>,
 '2503_0_252': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe420>,
 '2505_0_253': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabda00>,
 '2506_0_254': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe960>,
 '2508_0_255': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae4440>,
 '2510_0_256': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae4b00>,
 '2511_0_257': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae62a0>,
 '2513_0_258': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae6930>,
 '2516_0_259': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7320>,
 '2522_0_260': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7440>,
 '2523_0_261': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7f50>,
 '2524_0_262': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb01610>,
 '2529_0_263': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb00500>,
 '2533_0_264': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb004a0>,
 '2534_0_265': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb01f10>,
 '2535_0_266': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb037a0>,
 '2539_0_267': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d910>,
 '2540_0_268': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb03f50>,
 '2542_0_269': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb03320>,
 '2544_0_270': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb2d2e0>,
 '2545_0_271': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb2cf20>,

In [14]:
results

{'172_0_0': <abstractionsshapecoder.dsl_nodes.Union at 0x1588f8b26f0>,
 '173_0_1': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615af0>,
 '178_0_2': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd614b90>,
 '180_0_3': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6163c0>,
 '182_0_4': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd614770>,
 '186_0_5': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd617b60>,
 '187_0_6': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd616c00>,
 '197_0_7': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5eb1d0>,
 '257_0_8': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd616180>,
 '272_0_9': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5e9d30>,
 '278_0_10': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5ea840>,
 '280_0_11': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6344d0>,
 '285_0_12': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5eb500>,
 '286_0_13': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd635c40>,
 '308_0_14': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd634a40>,
 '314_0_15': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615d30>,
 '315_0_16': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd636ea0>,
 '328_0_17': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65a4e0>,
 '331_0_18': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658aa0>,
 '340_0_19': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658290>,
 '341_0_20': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658e60>,
 '347_0_21': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd658b30>,
 '349_0_22': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65ade0>,
 '456_0_23': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd65be60>,
 '470_0_24': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd615310>,
 '497_0_25': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd678f80>,
 '499_0_26': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd679d90>,
 '515_0_27': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd679ee0>,
 '516_0_28': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67ad50>,
 '518_0_29': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67bb30>,
 '523_0_30': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd67bec0>,
 '526_0_31': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a1460>,
 '539_0_32': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd5e90a0>,
 '543_0_33': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a07a0>,
 '545_0_34': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3320>,
 '547_0_35': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3050>,
 '550_0_36': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3fe0>,
 '552_0_37': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8bf0>,
 '554_0_38': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6a3200>,
 '555_0_39': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca2a0>,
 '557_0_40': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8350>,
 '561_0_41': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca6f0>,
 '574_0_42': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6c8080>,
 '671_0_43': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbec0>,
 '682_0_44': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ca3c0>,
 '686_0_45': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbb00>,
 '698_0_46': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6cbfb0>,
 '699_0_47': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ec620>,
 '701_0_48': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6eccb0>,
 '716_0_49': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ed220>,
 '724_0_50': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ef0b0>,
 '725_0_51': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6eeb40>,
 '732_0_52': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6efa10>,
 '737_0_53': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70c2c0>,
 '739_0_54': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70cfe0>,
 '740_0_55': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70df70>,
 '746_0_56': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70da00>,
 '748_0_57': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70cda0>,
 '750_0_58': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70f6e0>,
 '752_0_59': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd70e240>,
 '754_0_60': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd730b90>,
 '756_0_61': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd6ee240>,
 '760_0_62': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732330>,
 '763_0_63': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731940>,
 '768_0_64': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732420>,
 '772_0_65': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd732360>,
 '776_0_66': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd733500>,
 '1277_0_67': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d490>,
 '1282_0_68': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd733e90>,
 '1287_0_69': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d8b0>,
 '1293_0_70': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d0d0>,
 '1295_0_71': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75d100>,
 '1297_0_72': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75dc70>,
 '1299_0_73': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75fb90>,
 '1301_0_74': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75e960>,
 '1305_0_75': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77cec0>,
 '1309_0_76': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd75fa70>,
 '1314_0_77': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731400>,
 '1316_0_78': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77ea80>,
 '1319_0_79': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77e3f0>,
 '1329_0_80': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd731250>,
 '1331_0_81': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77ffb0>,
 '1333_0_82': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77fad0>,
 '1351_0_83': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd77eb70>,
 '1355_0_84': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a0e90>,
 '1359_0_85': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a08f0>,
 '1366_0_86': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a0680>,
 '1368_0_87': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a1eb0>,
 '1373_0_88': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a3170>,
 '1374_0_89': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7a3c20>,
 '1377_0_90': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bc740>,
 '1378_0_91': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bd670>,
 '1382_0_92': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bd490>,
 '1398_0_93': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7be7e0>,
 '1400_0_94': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7be3f0>,
 '1403_0_95': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e4c20>,
 '1409_0_96': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7bff20>,
 '1425_0_97': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e50a0>,
 '1438_0_98': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e55b0>,
 '1439_0_99': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e70e0>,
 '1441_0_100': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e5fa0>,
 '1463_0_101': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e6540>,
 '1472_0_102': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7590>,
 '1473_0_103': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7620>,
 '1746_0_104': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd808bf0>,
 '1762_0_105': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd7e7dd0>,
 '2121_0_106': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd809550>,
 '2132_0_107': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd808c50>,
 '2136_0_108': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80aea0>,
 '2184_0_109': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80b1a0>,
 '2194_0_110': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80ade0>,
 '2198_0_111': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd4546b0>,
 '2203_0_112': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd80b710>,
 '2214_0_113': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82c710>,
 '2217_0_114': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82d3a0>,
 '2220_0_115': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e3c0>,
 '2221_0_116': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e8d0>,
 '2223_0_117': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e5d0>,
 '2225_0_118': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82e4b0>,
 '2227_0_119': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd82fe60>,
 '2233_0_120': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854950>,
 '2234_0_121': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8550a0>,
 '2235_0_122': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854fb0>,
 '2236_0_123': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8553d0>,
 '2239_0_124': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd856ba0>,
 '2240_0_125': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd857cb0>,
 '2241_0_126': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd857b90>,
 '2242_0_127': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8579e0>,
 '2248_0_128': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8747a0>,
 '2249_0_129': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd855100>,
 '2252_0_130': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd855d30>,
 '2253_0_131': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8760c0>,
 '2255_0_132': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd875f10>,
 '2260_0_133': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8764e0>,
 '2261_0_134': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8773b0>,
 '2262_0_135': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd877b00>,
 '2263_0_136': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd877ce0>,
 '2266_0_137': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a07d0>,
 '2269_0_138': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a1970>,
 '2270_0_139': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2270>,
 '2271_0_140': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a27e0>,
 '2276_0_141': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a1940>,
 '2277_0_142': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2120>,
 '2280_0_143': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a2b40>,
 '2281_0_144': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a3e30>,
 '2283_0_145': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8a3f20>,
 '2286_0_146': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c0c80>,
 '2287_0_147': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c0f80>,
 '2291_0_148': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2180>,
 '2293_0_149': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2420>,
 '2294_0_150': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2ab0>,
 '2295_0_151': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c38f0>,
 '2296_0_152': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8c2870>,
 '2302_0_153': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9040>,
 '2304_0_154': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9fa0>,
 '2306_0_155': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9820>,
 '2307_0_156': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8e9f70>,
 '2308_0_157': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8eb650>,
 '2309_0_158': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8ebfe0>,
 '2311_0_159': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ca40>,
 '2312_0_160': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ccb0>,
 '2315_0_161': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e900>,
 '2316_0_162': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e960>,
 '2318_0_163': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90fb30>,
 '2319_0_164': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90e990>,
 '2323_0_165': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd90ef90>,
 '2325_0_166': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd930ad0>,
 '2328_0_167': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9312e0>,
 '2330_0_168': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd931580>,
 '2332_0_169': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932420>,
 '2333_0_170': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932540>,
 '2334_0_171': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932780>,
 '2335_0_172': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd933bf0>,
 '2338_0_173': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932bd0>,
 '2341_0_174': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd932db0>,
 '2342_0_175': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd959550>,
 '2343_0_176': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd959e80>,
 '2344_0_177': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9586e0>,
 '2345_0_178': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9597f0>,
 '2346_0_179': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd95b950>,
 '2350_0_180': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd95bc20>,
 '2351_0_181': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd974560>,
 '2352_0_182': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9749e0>,
 '2354_0_183': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9748f0>,
 '2355_0_184': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd975910>,
 '2359_0_185': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd975310>,
 '2360_0_186': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9771d0>,
 '2365_0_187': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977b30>,
 '2366_0_188': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd976150>,
 '2369_0_189': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977f80>,
 '2370_0_190': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd977fb0>,
 '2371_0_191': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd976de0>,
 '2373_0_192': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99cb60>,
 '2374_0_193': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd854e00>,
 '2376_0_194': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99e390>,
 '2377_0_195': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99ef30>,
 '2379_0_196': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd99e8a0>,
 '2382_0_197': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd8ebcb0>,
 '2383_0_198': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bc950>,
 '2384_0_199': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bce60>,
 '2391_0_200': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9be0c0>,
 '2392_0_201': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bd6a0>,
 '2396_0_202': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9beab0>,
 '2397_0_203': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bddf0>,
 '2399_0_204': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bf3b0>,
 '2400_0_205': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bfce0>,
 '2405_0_206': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9bfd10>,
 '2406_0_207': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e4380>,
 '2408_0_208': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e4b90>,
 '2410_0_209': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e45f0>,
 '2412_0_210': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e5460>,
 '2416_0_211': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e6600>,
 '2420_0_212': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e72f0>,
 '2422_0_213': <abstractionsshapecoder.dsl_nodes.Union at 0x158cd9e79e0>,
 '2423_0_214': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda04260>,
 '2424_0_215': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda04da0>,
 '2429_0_216': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda06810>,
 '2430_0_217': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda06990>,
 '2434_0_218': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda079b0>,
 '2435_0_219': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2c8f0>,
 '2436_0_220': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2ca70>,
 '2437_0_221': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2c530>,
 '2439_0_222': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2cd40>,
 '2441_0_223': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2df70>,
 '2444_0_224': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2f410>,
 '2446_0_225': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda2fa40>,
 '2447_0_226': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda50f50>,
 '2448_0_227': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda51490>,
 '2449_0_228': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda50500>,
 '2454_0_229': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda51eb0>,
 '2457_0_230': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda52de0>,
 '2458_0_231': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda52600>,
 '2460_0_232': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda53320>,
 '2461_0_233': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78c50>,
 '2464_0_234': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78920>,
 '2466_0_235': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda78410>,
 '2467_0_236': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda79af0>,
 '2470_0_237': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7a630>,
 '2472_0_238': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7abd0>,
 '2476_0_239': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7ad80>,
 '2478_0_240': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda7bd40>,
 '2479_0_241': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9cad0>,
 '2481_0_242': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d8b0>,
 '2483_0_243': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d070>,
 '2489_0_244': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9e8a0>,
 '2491_0_245': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9e9f0>,
 '2493_0_246': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9fa70>,
 '2494_0_247': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9ea20>,
 '2495_0_248': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9f710>,
 '2497_0_249': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabcfb0>,
 '2498_0_250': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabd5e0>,
 '2502_0_251': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe2d0>,
 '2503_0_252': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe420>,
 '2505_0_253': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabda00>,
 '2506_0_254': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdabe960>,
 '2508_0_255': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae4440>,
 '2510_0_256': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae4b00>,
 '2511_0_257': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae62a0>,
 '2513_0_258': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae6930>,
 '2516_0_259': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7320>,
 '2522_0_260': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7440>,
 '2523_0_261': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdae7f50>,
 '2524_0_262': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb01610>,
 '2529_0_263': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb00500>,
 '2533_0_264': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb004a0>,
 '2534_0_265': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb01f10>,
 '2535_0_266': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb037a0>,
 '2539_0_267': <abstractionsshapecoder.dsl_nodes.Union at 0x158cda9d910>,
 '2540_0_268': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb03f50>,
 '2542_0_269': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb03320>,
 '2544_0_270': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb2d2e0>,
 '2545_0_271': <abstractionsshapecoder.dsl_nodes.Union at 0x158cdb2cf20>,